### ISSUE TITLE
System.ArgumentOutOfRangeException Error with null child in Stack Panel

### ISSUE THREAD

**Issue by MarshMello0** [AvaloniaUI/Avalonia#10041]
**Describe the bug**
If a StackPanel has a null child in `.Children` the next addition will cause a `System.ArgumentOutOfRangeException` error.

**To Reproduce**

1. Programmly create a new stack panel
2. Add a null item to the children
3. Try to add another item to the children

**Expected behavior**
Not throw an exception or at least a custom one mentioning Children can't be null

**Desktop (please complete the following information):**

- OS: Windows 
- Version Tested in 0.10.13 & 0.10.18

**Additional context**
Here is the small sample I took out of my code. I accidentally had a null in my logic and got super lost by this. 

```cs
var stackPanel = new StackPanel();            
stackPanel.Children.Add(null);
stackPanel.Children.Add(new TextBlock
{
    Text = "Error!"
});
```

Stack Trace of the error in my test
```
System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Avalonia.Collections.AvaloniaList`1.InsertRange(Int32 index, IEnumerable`1 items) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 360
   at Avalonia.Controls.Panel.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls/Panel.cs:line 121
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 687
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia_Bug_Test.MainWindow.CreateBug() in B:\Code\Avalonia Bug Test\Avalonia Bug Test\MainWindow.axaml.cs:line 28
   at Avalonia_Bug_Test.MainWindow..ctor() in B:\Code\Avalonia Bug Test\Avalonia Bug Test\MainWindow.axaml.cs:line 11
   at Avalonia_Bug_Test.App.OnFrameworkInitializationCompleted() in B:\Code\Avalonia Bug Test\Avalonia Bug Test\App.axaml.cs:line 18
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Avalonia_Bug_Test.Program.Main(String[] args) in B:\Code\Avalonia Bug Test\Avalonia Bug Test\Program.cs:line 14
```

**Comment by maxkatz6** [comment]
I believe some kind of validation needs to be added to this method
https://github.com/AvaloniaUI/Avalonia/blob/d2bfd61dfcf04ea1436a87452c83ba5ea04e2041/src/Avalonia.Controls/Panel.cs#L118
