### ISSUE TITLE
ObservableCollection with ItemsControl -> An item with the same key has already been added

### ISSUE THREAD

**Issue by mail2mhossain** [AvaloniaUI/Avalonia#10043]
public ObservableCollection<VideoViewModel>? VideoViewModels { get; set; } 

try
{
    VideoViewModels.Add(r);
}
catch (Exception ex)
{
    Log.Information(ex.Message);
}

I am using ObservableCollection with ItemsControl. We are adding, removing items checking item's id and also using try-catch in adding method. But getting following errors and app is crashing though there is a try-catch

System.ArgumentException: An item with the same key has already been added. Key: [1, Avalonia.Controls.Generators.ItemContainerInfo]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Materialize(Int32 index, Object item) in /_/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs:line 58
   at Avalonia.Controls.Presenters.ItemContainerSync.AddContainers(ItemsPresenterBase owner, Int32 index, IEnumerable items) in /_/src/Avalonia.Controls/Presenters/ItemContainerSync.cs:line 91
   at Avalonia.Controls.Presenters.ItemContainerSync.<ItemsChanged>g__Add|0_0(<>c__DisplayClass0_0& ) in /_/src/Avalonia.Controls/Presenters/ItemContainerSync.cs:line 32
   at Avalonia.Controls.Presenters.ItemContainerSync.ItemsChanged(ItemsPresenterBase owner, IEnumerable items, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls/Presenters/ItemContainerSync.cs:line 43
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls/Presenters/ItemVirtualizerNone.cs:line 59
   at Avalonia.Controls.Presenters.ItemsPresenterBase.Avalonia.Controls.Presenters.IItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls/Presenters/ItemsPresenterBase.cs:line 159
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakEventSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged incc, NotifyCollectionChangedEventArgs args, List`1 listeners) in /_/src/Avalonia.Controls/Utils/CollectionChangedEventManager.cs:line 132
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 258
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 96
   at Comm.Net.Program.Main(String[] args) in D:\source\csharp-janus-client\CSharpJanusClient\Comm.Net\Program.cs:line 25

**Comment by DmitryZhelnin** [comment]
Are you adding objects on main UI thread?
Try to wrap it with `Dispatcher.UIThread.Post(() => {VideoViewModels.Add(r)});`

**Comment by timunie** [comment]
@mail2mhossain can you provide a minimal sample to reproduce your issue?

**Comment by maxkatz6** [comment]
It is likely to be fixed in 11.0.

**Comment by mail2mhossain** [comment]
Current Latest stable version is  0.10.18. When 0.11.0 is going to be released?
