### ISSUE TITLE
DBus exceptions on mouse click in trimmed linux builds

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#10069]
**Describe the bug**
Clicking anywhere on a basic Avalonia app published for linux with trimming enabled causes the app to exit with this exception

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder' threw an exception.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Tmds.DBus.CodeGen.TypeExtensions.GetConstructor(Type, BindingFlags, Type[])
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder..cctor()
   --- End of inner exception stack trace ---
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type)
   at Tmds.DBus.Connection.CreateProxy(Type, String, ObjectPath)
   at Tmds.DBus.Connection.CreateProxy[T](String, ObjectPath)
   at Avalonia.FreeDesktop.DBusPlatformSettings..ctor() in /_/src/Avalonia.FreeDesktop/DBusPlatformSettings.cs:line 15
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass5_0`1.<ToSingleton>b__0() in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 76
   at Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass3_0`1.<ToFunc>b__0() in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 52
   at Avalonia.AvaloniaLocator.GetService(Type t) in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 32
   at Avalonia.LocatorExtensions.GetRequiredService[T](IAvaloniaDependencyResolver resolver) in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 136
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, IInputElement hitTest) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 128
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 74
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 31
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 590
   at Avalonia.X11.X11Window.DispatchInput(RawInputEventArgs args) in /_/src/Avalonia.X11/X11Window.cs:line 733
   at Avalonia.RawEventGrouper.DispatchFromQueue() in /_/src/Shared/RawEventGrouping.cs:line 52
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Threading.Dispatcher.RunJobs() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 69
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 212
   at AvaloniaDbusTrim.Program.Main(String[]) in C:\Users\alan\OneDrive\scratch\AvaloniaDbusTrim\AvaloniaDbusTrim\Program.cs:line 14
Aborted

```
if a roots.xml is used with

```
<linker> 		
	<assembly fullname="Tmds.DBus" preserve="all" />
	<assembly fullname="Avalonia.FreeDesktop" preserve="all" />
	<assembly fullname="Avalonia.X11" preserve="all" />
</linker>
```

the exception changes to

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Access is denied: 'Tmds.DBus.CodeGen.DBusObjectProxy'.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfoImpl()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type)
   at Tmds.DBus.Connection.CreateProxy(Type, String, ObjectPath)
   at Tmds.DBus.Connection.CreateProxy[T](String, ObjectPath)
   at Avalonia.FreeDesktop.DBusPlatformSettings..ctor() in /_/src/Avalonia.FreeDesktop/DBusPlatformSettings.cs:line 15
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass5_0`1.<ToSingleton>b__0() in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 76
   at Avalonia.AvaloniaLocator.RegistrationHelper`1.<>c__DisplayClass3_0`1.<ToFunc>b__0() in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 52
   at Avalonia.AvaloniaLocator.GetService(Type t) in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 32
   at Avalonia.LocatorExtensions.GetRequiredService[T](IAvaloniaDependencyResolver resolver) in /_/src/Avalonia.Base/AvaloniaLocator.cs:line 136
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, IInputElement hitTest) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 128
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 74
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 31
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 590
   at Avalonia.X11.X11Window.DispatchInput(RawInputEventArgs args) in /_/src/Avalonia.X11/X11Window.cs:line 733
   at Avalonia.RawEventGrouper.DispatchFromQueue() in /_/src/Shared/RawEventGrouping.cs:line 52
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 212
   at AvaloniaDbusTrim.Program.Main(String[]) in C:\Users\alan\OneDrive\scratch\AvaloniaDbusTrim\AvaloniaDbusTrim\Program.cs:line 14
Aborted


```

changing the link mode does not seem to have an effect.

**To Reproduce**

Publish an app straight from the template for linux with trimming, run and click anywhere.

**Expected behavior**
No crash

**Desktop (please complete the following information):**

- Version 11.0.999-cibuild0028980-beta

**Comment by maxkatz6** [comment]
DBus is still not trimmable.
There is a PR expected to fix that https://github.com/AvaloniaUI/Avalonia/pull/9810

**Comment by ahopper** [comment]
some previous 11.0 nightly builds have worked with trimming so I can't help thinking it ought to be possible to find what to put in roots.xml to make it work again.

**Comment by maxkatz6** [comment]
I suppose that's because all other usages of DBus were optional or by request before (like, file pickers). While DBusPlatformSettings is always used right away now.

Not sure what's the problem with "System.TypeLoadException: Access is denied: 'Tmds.DBus.CodeGen.DBusObjectProxy'." exception though.

**Comment by ahopper** [comment]
#9810 does indeed fix this, If anyone needs a quick fix, build 11.0.999-cibuild0029117-beta appears stable, I have released a test version of my app using it and have had no bad reports.

I gave up trying to make it work with roots.xml so the 'Access is denied' can stay a mystery.

**Comment by mysteryx93** [comment]
Can this also be solved for now by exluding `Tmds.DBus` from trimming?

```
<ItemGroup>
  <TrimmerRootAssembly Include="Tmds.DBus" />
</ItemGroup>
```

This gives me 

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Type 'Avalonia.FreeDesktop.IDBusSettingsProxy' from assembly 'Tmds.DBus.Emit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9abd76e9812c1bca' is attempting to implement an inaccessible interface.

**Comment by maxkatz6** [comment]
@mysteryx93 it doesn't seem to have an easy workaround. You either need to disable trimming, or use nightly builds in the target app.

**Comment by mysteryx93** [comment]
The beta build doesn't seem compatible with FluentAvalonia.

**Comment by mysteryx93** [comment]
FluentAvalonia preview5.1 is built on the beta build so that should work.

Only issue I have now with that beta build is `EventTriggerBehavior` not found anymore in `Avalonia.Xaml.Interactions.Core`

    GC.KeepAlive(typeof(EventTriggerBehavior));
