### ISSUE TITLE
Running Avalonia apps in Windows 11 ARM64 running in Parallels Desktop on Mac M1 gives AccessViolationException

### ISSUE THREAD

**Issue by martin-honnen** [AvaloniaUI/Avalonia#10272]
**Describe the bug**
Using dotnet 7 command line runner under a Windows 11 ARM64 running in Parallels Desktop on a Mac M1 to run .NET 6 or .NET 7 Avalonia dlls fails with an AccessViolationException. That seems to happen with any kind of Avalonia desktop app, I have tried MVVM and non MVVM apps.
Detailed stack trace is e.g.
```
 dotnet \\Mac\Home\Library\CloudStorage\OneDrive-Persönlich\Documents\AvaloniaNet7MVVMApp2\AvaloniaNet7MVVMApp2.dll
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositionGraphicsDeviceProxy.CreateDrawingSurface(SIZE, Avalonia.Win32.WinRT.DirectXPixelFormat, Avalonia.Win32.WinRT.DirectXAlphaMode)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection.CreateWindow(IntPtr)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateGlRenderTarget()
   at Avalonia.Skia.GlRenderTarget..ctor(SkiaSharp.GRContext, Avalonia.OpenGL.Surfaces.IGlPlatformSurface)
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(System.Collections.Generic.IEnumerable`1<System.Object>)
   at Avalonia.Skia.PlatformRenderInterface.CreateRenderTarget(System.Collections.Generic.IEnumerable`1<System.Object>)
   at Avalonia.Controls.TopLevel.CreateRenderTarget()
   at Avalonia.Controls.TopLevel.Avalonia.Rendering.IRenderRoot.CreateRenderTarget()
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(Avalonia.Platform.IDrawingContextImpl ByRef)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Avalonia.Platform.IDrawingContextImpl ByRef, Boolean)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean)
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render()
   at Avalonia.Rendering.RenderLoop.TimerTick(System.TimeSpan)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection+RunLoopHandler.Invoke(Avalonia.Win32.WinRT.IAsyncAction, Avalonia.Win32.WinRT.AsyncStatus)
   at Avalonia.Win32.WinRT.Impl.__MicroComIAsyncActionCompletedHandlerVTable.Invoke(Void*, Void*, Avalonia.Win32.WinRT.AsyncStatus)
   at Avalonia.Win32.Interop.UnmanagedMethods.GetMessage(MSG ByRef, IntPtr, UInt32, UInt32)
   at Avalonia.Win32.Interop.UnmanagedMethods.GetMessage(MSG ByRef, IntPtr, UInt32, UInt32)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection.RunLoop()
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection+<>c__DisplayClass16_0.<TryCreateAndRegisterCore>b__0()
```

Output of `dotnet --info` is
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet\x64]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**To Reproduce**

1. compile  and publish Avalonia desktop app with settings any platform , framework dependent into folder with dlls
2. try to run it with `dotnet app.dll` under Windows 11 ARM64 running in Parallels Desktop on Apple M1 
3. see error as shown above: it appears the app window comes up shortly but then (on drawing in the window?) the crash occurs

**Expected behavior**
I expect the app to run i.e. the app window to appear and its content to be drawn.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]
Windows 11 Home ARM64 Version 10.0.22621 Build 22621 running in Parallels 18.1.1 ARM Virtual Machine under Apple M1 Ventura 13.2
Avalonia:
```
        <PackageReference Include="Avalonia" Version="0.10.18"/>
        <PackageReference Include="Avalonia.Desktop" Version="0.10.18"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.18"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.18"/>
        <PackageReference Include="XamlNameReferenceGenerator" Version="1.5.1"/>
```

**Additional context**
The same app/dll run directly with dotnet of the MacOS runs fine e.g. `dotnet /Users/martin/OneDrive/Documents/AvaloniaNet7MVVMApp2/AvaloniaNet7MVVMApp2.dll` brings up the app window and its content fine.
That dotnet is also the ARM64 version:
```
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/
```
The app also runs fine, however, with the Windows x64 dotnet e.g. `'C:\Program Files\dotnet\x64\dotnet.exe' \\Mac\Home\Library\CloudStorage\OneDrive-Persönlich\Documents\AvaloniaNet7MVVMApp2\AvaloniaNet7MVVMApp2.dll`.

The crash seems to occur with any app I tried, the stack above is one where I did nothing but change the view model of the created template to e.g.
```
public class MainWindowViewModel : ViewModelBase
{
    public string Greeting => $"Welcome to Avalonia! {Environment.Version} {Environment.OSVersion} {Environment.ProcessPath}";
}
```

**Comment by martin-honnen** [comment]
Also now tried installing Ubuntu 22 ARM64 into a Parallels Desktops virtual machine and running Avalonia desktop apps with the Ubuntu dotnet, apps (so far only .NET 6 as that seems to be the one that is part of Ubuntu's packages) come up and run fine although the terminal window shows some error (`libGL error: pci id for fd 79: 1ab8:0010, driver (null)`), but at least it is not a complete crash like with Windows. And that probably shows that it is not my app creation/compilation/publishing that is somehow wrong and responsible for the crash in the Windows ARM dotnet, the dlls run fine on the ARM64 MacOS dotnet and the Linux one, only with the Windows one, at least inside of the VM, they crash.

**Comment by martin-honnen** [comment]
I have now simply used the dotnet ARM windows tool to create and run an app with e.g.
```
dotnet new avalonia.app -o AvaloniaARM64WinApp1
cd AvaloniaARM64WinApp1
dotnet run
```
the app window frame appears, then the app window disappears, the terminal window is not showing any error message. If I use `dotnet .\bin\Debug\net6.0\AvaloniaARM64WinApp1.dll` instead I get the crash stack trace
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositionGraphicsDeviceProxy.CreateDrawingSurface(SIZE, Avalonia.Win32.WinRT.DirectXPixelFormat, Avalonia.Win32.WinRT.DirectXAlphaMode)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection.CreateWindow(IntPtr)
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateGlRenderTarget()
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(System.Collections.Generic.IEnumerable`1<System.Object>)
   at Avalonia.Skia.PlatformRenderInterface.CreateRenderTarget(System.Collections.Generic.IEnumerable`1<System.Object>)
   at Avalonia.Controls.TopLevel.CreateRenderTarget()
   at Avalonia.Controls.TopLevel.Avalonia.Rendering.IRenderRoot.CreateRenderTarget()
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(Avalonia.Platform.IDrawingContextImpl ByRef)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Avalonia.Platform.IDrawingContextImpl ByRef, Boolean)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean)
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render()
   at Avalonia.Rendering.RenderLoop.TimerTick(System.TimeSpan)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection+RunLoopHandler.Invoke(Avalonia.Win32.WinRT.IAsyncAction, Avalonia.Win32.WinRT.AsyncStatus)
   at Avalonia.Win32.WinRT.Impl.__MicroComIAsyncActionCompletedHandlerVTable.Invoke(Void*, Void*, Avalonia.Win32.WinRT.AsyncStatus)
   at Avalonia.Win32.Interop.UnmanagedMethods.GetMessage(MSG ByRef, IntPtr, UInt32, UInt32)
   at Avalonia.Win32.Interop.UnmanagedMethods.GetMessage(MSG ByRef, IntPtr, UInt32, UInt32)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection.RunLoop()
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection+<>c__DisplayClass16_0.<TryCreateAndRegisterCore>b__0()
   at System.Threading.Thread.StartCallback()
```

**Comment by maxkatz6** [comment]
Same exception was fixed in the 11 preview https://github.com/AvaloniaUI/Avalonia/issues/8776

**Comment by snickler** [comment]
> Same exception was fixed in the 11 preview #8776


Hi, 

This isn't resolved in Windows Insider Dev Channel builds 25295 and 25300. Same issue on both my Surface Pro X and Volterra.

![image](https://user-images.githubusercontent.com/4016293/219990868-5461508f-3cec-4b5c-99ff-aee703afe291.png)

**Comment by maxkatz6** [comment]
@snickler is it the latest preview build? It seems you are not using the latest one.
CreateDrawingSurface(SIZE) isn't used anymore, which hints your stack trace is out of dated.
This issue was solved by using CreateDrawingSurface(SIZE_F) instead.

**Comment by snickler** [comment]
> @snickler is it the latest preview build? It seems you are not using the latest one. CreateDrawingSurface(SIZE) isn't used anymore, which hints your stack trace is out of dated. This issue was solved by using CreateDrawingSurface(SIZE_F) instead.

After upgrading to 11.00-preview5
![image](https://user-images.githubusercontent.com/4016293/220013539-7c865b7e-2a9b-4a12-9214-0acf530b208c.png)

**Comment by snickler** [comment]
Actually, the build didn't work properly because it errored out with changes needed to FluentTheme? I took the style out and now it just simply shows the transparent window without errors.

![image](https://user-images.githubusercontent.com/4016293/220014250-0f48f354-6e52-4e7c-bc0e-5c61794b4e5c.png)

**Comment by maxkatz6** [comment]
@snickler can you open a new issue for the transparent window?

But first, do you build app with "win7-x64" runtime identifier?
Like: "dotnet publish -c Release -r win7-x64" and then check bin/Release/win7-x64/publish folder.
Or try latest master nightly.

**Comment by snickler** [comment]
> @snickler can you open a new issue for the transparent window?
> 
> But first, do you build app with "win7-x64" runtime identifier? Like: "dotnet publish -c Release -r win7-x64" and then check bin/Release/win7-x64/publish folder. Or try latest master nightly.

I'm publishing using win10-arm64

**Comment by maxkatz6** [comment]
Ah, right, important part was to include win10 or win7. Regardless of the arch.

**Comment by snickler** [comment]
> Ah, right, important part was to include win10 or win7. Regardless of the arch.

https://github.com/AvaloniaUI/Avalonia/issues/10405 Created a new issue to track this. Thanks!
