### ISSUE TITLE
Cannot Start Web App on Linux

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10297]
I created a blank Avalonia template for cross-platform app. I open it in Jetbrains Rider.

I try to debug the Web project in FireFox. It requests to install `Microsoft.AspNetCore.Components.WebAssembly.DevServer` so I do.

If I try to debug, now I get this error

> class com.intellij.ide.browsers.firefox.FirefoxSettings cannot be cast to class com.intellij.ide.browsers.chrome.ChromeSettings (com.intellij.ide.browsers.firefox.FirefoxSettings and com.intellij.ide.browsers.chrome.ChromeSettings are in unnamed module of loader com.intellij.util.lang.PathClassLoader @769c9116)

If I run the app without debugging, I get a blank page in my browser.

I have a separate Blazor project that runs fine.

OS: Garuda Linux (Arch-based)
Avalonia v11 preview 4 and 5

**Comment by maxkatz6** [comment]
Make sure you have latest templates. They don't use `Avalonia.Browser.Blazor` backend.
It's recommended to use `Avalonia.Browser` (which doesn't depend on the blazor at all).

In the preview5 there is known issue that Blazor backend is missing "avalonia.js", but in your case it doesn't seems so.

**Comment by maxkatz6** [comment]
Not sure if there is any bug in the framework here. Aside from well-known issue with "avalonia.js" I mentioned.

**Comment by mysteryx93** [comment]
Cannot start Web project from template in Windows either.

Nothing useful in the Output log, but it says

> Verbose logs are written to: C:\Users\Hanuman\AppData\Local\Temp\visualstudio-js-debugger.txt

```
{"timestamp":1676089609471,"tag":"runtime.welcome","level":1,"message":"js-debug v1.71.0 started","metadata":{"os":"win32 x64","nodeVersion":"v16.14.0","adapterVersion":"1.71.0"}}
{"tag":"dap.receive","timestamp":1676089609420,"metadata":{"connectionId":0,"message":{"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"pwa-msedge","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"SupportsMessageBox":true,"supportsHandshakeRequest":true,"supportsVsAdditionalBreakpointBinds":true,"supportsHitCountsChange":true,"supportsVsCustomMessages":true,"supportsVariableEnumerators":true,"supportsMapURLToFilePathRequest":true,"supportsLaunchUnelevatedProcessRequest":true,"supportsAccessingSourcesThorughClient":true},"seq":1}},"level":0}
{"tag":"dap.send","timestamp":1676089609421,"metadata":{"connectionId":0,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"supportsReadMemoryRequest":true,"supportsWriteMemoryRequest":true,"exceptionBreakpointFilters":[{"filter":"all","label":"Caught Exceptions","default":false,"supportsCondition":true,"description":"Breaks on all throw errors, even if they're caught later.","conditionDescription":"error.name == \"MyError\""},{"filter":"uncaught","label":"Uncaught Exceptions","default":false,"supportsCondition":true,"description":"Breaks only on errors or promise rejections that are not handled.","conditionDescription":"error.name == \"MyError\""}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":true,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":true,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true,"supportsClipboardContext":true,"supportsExceptionFilterOptions":true,"supportsDebuggerProperties":true}}},"level":0}
{"tag":"dap.send","timestamp":1676089609423,"metadata":{"connectionId":0,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1676089609455,"metadata":{"connectionId":0,"message":{"type":"request","command":"launch","arguments":{"webRoot":"H:\\Downloads\\Avalonia11\\Avalonia11.Web","rootPath":"H:\\Downloads\\Avalonia11\\Avalonia11.Web","__workspaceFolder":"H:\\Downloads\\Avalonia11\\Avalonia11.Web","runtimeExecutable":"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","runtimeArgs":[],"sourceMaps":true,"url":"https://localhost:5001/","trace":{"logFile":"C:\\Users\\Hanuman\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt"},"launchUnelevated":false,"projectGuid":"1c1a049e-235c-4cd0-b6fa-d53ac418f4da","userDataDir":"C:\\Users\\Hanuman\\AppData\\Local\\Microsoft\\VisualStudio\\17.0_06ba489f\\WebTools\\90107F59_61B99BF3","breakOnLoad":true,"smartStep":true,"continueOnAttach":false,"skipFiles":[],"showAsyncStacks":true,"timeout":60000,"inspectUri":"{wsProtocol}://{url.hostname}:{url.port}/debug?browser={browserInspectUri}","__webAssemblyDebugServerPath":"C:\\Users\\Hanuman\\.nuget\\packages\\microsoft.aspnetcore.components.webassembly.devserver\\7.0.2\\Tools\\BlazorDebugProxy\\BrowserDebugHost.dll","__startWebAssemblyDebugServer":false,"cleanUp":"wholeBrowser","name":"Launch the JavaScript PWA Debugger from Visual Studio","type":"pwa-msedge","request":"launch","continueOnDisconnect":true},"seq":2}},"level":0}
{"tag":"dap.send","timestamp":1676089609457,"metadata":{"connectionId":0,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-msedge","request":"launch","os":"win32 x64","nodeVersion":"v16.14.0","adapterVersion":"1.71.0","parameters":"{\"type\":\"pwa-msedge\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":{\"logFile\":\"<string>\"},\"outputCapture\":\"console\",\"timeout\":60000,\"timeouts\":{},\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"sourceMapRenames\":true,\"pauseForSourceMap\":true,\"resolveSourceMapLocations\":null,\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack:///./~/*\":\"<string>\",\"webpack:////*\":\"<string>\",\"webpack://@?:*/?:*/*\":\"<string>\",\"webpack://?:*/*\":\"<string>\",\"webpack:///([a-z]):/(.+)\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"enableContentValidation\":true,\"cascadeTerminateToConfigurations\":[],\"__workspaceFolder\":\"<string>\",\"__breakOnConditionalError\":false,\"address\":\"localhost\",\"port\":0,\"disableNetworkCache\":true,\"pathMapping\":{},\"url\":\"<string>\",\"restart\":false,\"urlFilter\":\"*\",\"webRoot\":\"<string>\",\"server\":null,\"browserAttachLocation\":\"workspace\",\"targetSelection\":\"automatic\",\"vueComponentPaths\":[\"<string>\",\"<string>\"],\"perScriptSourcemaps\":\"auto\",\"cwd\":null,\"file\":null,\"env\":{},\"includeDefaultArgs\":true,\"runtimeArgs\":[],\"runtimeExecutable\":\"<string>\",\"userDataDir\":\"<string>\",\"browserLaunchLocation\":\"workspace\",\"profileStartup\":false,\"cleanUp\":\"wholeBrowser\",\"useWebView\":false,\"launchUnelevated\":false,\"projectGuid\":\"<string>\",\"breakOnLoad\":true,\"continueOnAttach\":false,\"inspectUri\":\"<string>\",\"__webAssemblyDebugServerPath\":\"<string>\",\"__startWebAssemblyDebugServer\":false,\"continueOnDisconnect\":true}"}}}},"level":0}
{"tag":"dap.send","timestamp":1676089609459,"metadata":{"connectionId":0,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\nC:\\Users\\Hanuman\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1676089609472,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":3}},"level":0}
{"tag":"dap.receive","timestamp":1676089609472,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":4}},"level":0}
{"tag":"dap.receive","timestamp":1676089609473,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":5}},"level":0}
{"tag":"dap.receive","timestamp":1676089609473,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":6}},"level":0}
{"tag":"dap.receive","timestamp":1676089609473,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":7}},"level":0}
{"tag":"dap.receive","timestamp":1676089609473,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"Native.LoadExports":0},"seq":8}},"level":0}
{"tag":"dap.receive","timestamp":1676089609473,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}},"level":0}
{"tag":"dap.receive","timestamp":1676089609474,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":0},"seq":10}},"level":0}
{"tag":"dap.receive","timestamp":1676089609474,"metadata":{"connectionId":0,"message":{"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":11}},"level":0}
{"tag":"runtime.launch","timestamp":1676089609476,"message":"Launching Chrome from C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","level":1}
{"tag":"runtime.exception","timestamp":1676089609819,"message":"Error running taskkill.exe","metadata":{"message":"Command failed: C:\\Windows\\System32\\taskkill.exe /F /T /PID 12416\nERROR: The process \"12416\" not found.\r\n","stack":"Error: Command failed: C:\\Windows\\System32\\taskkill.exe /F /T /PID 12416\nERROR: The process \"12416\" not found.\r\n\n    at checkExecSyncError (node:child_process:828:11)\n    at execSync (node:child_process:902:15)\n    at killTree (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\node\\killTree.js:22:33)\n    at t.ChildProcessBrowserProcess.kill (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\spawn\\browserProcess.js:114:24)\n    at exitListener (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\launcher.js:97:28)\n    at Object.t.launch (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\launcher.js:124:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at P.launched (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:91:9)\n    at P.target [as prepareLaunch] (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:119:13)\n    at P.launch (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:187:15)"},"level":3}
{"tag":"runtime.launch","timestamp":1676089610304,"message":"Launch returned error","metadata":{"error":{"message":"Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\"","stack":"Error: Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\"\n    at P.prepareLaunch (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:122:19)\n    at process.target (node:internal/process/task_queues:96:5)\n    at P.result (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:187:15)\n    at t.Binder.captureLaunch (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:251:13)\n    at t.Binder._launch (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:227:9)\n    at async Promise.all (index 6)\n    at t.Binder.result [as _boot] (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:175:9)\n    at t.default._onMessage (c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\dap\\connection.js:145:27)"},"wasCancelled":false,"name":"P"},"level":2}
{"tag":"dap.send","timestamp":1676089610305,"metadata":{"connectionId":0,"message":{"seq":5,"type":"response","request_seq":2,"command":"launch","success":false,"body":{"error":{"id":9240,"format":"Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\"","showUser":true}}}},"level":0}
{"tag":"dap.send","timestamp":1676089612327,"metadata":{"connectionId":0,"message":{"seq":6,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/error","data":{"!error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"}},"error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"}},"exceptionType":"uncaughtException"}}}},"level":0}
{"tag":"dap.send","timestamp":1676089612327,"message":"Message not sent. Connection was closed.","level":2}
{"tag":"runtime.exception","timestamp":1676089612327,"message":"Unhandled error in debug adapter","metadata":{"message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"},"level":3}
{"tag":"dap.send","timestamp":1676089614434,"metadata":{"connectionId":0,"message":{"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"errors":[],"initialize":{"operation":"initialize","totalTime":2.7,"max":2.7,"avg":2.7,"stddev":null,"count":1,"failed":0},"!initialize.errors":[],"initialize.errors":[],"setDebuggerProperty":{"operation":"setDebuggerProperty","totalTime":11.8,"max":2.2,"avg":1.3,"stddev":0.6,"count":9,"failed":0},"!setDebuggerProperty.errors":[],"setDebuggerProperty.errors":[],"launch":{"operation":"launch","totalTime":850,"max":850,"avg":850,"stddev":null,"count":1,"failed":1},"!launch.errors":[{"error":{"message":"Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\"","name":"Error","stack":"Error: Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: httptroubleshooting.md\n\"\n    at P.prepareLaunch (c:browserLauncher.js:122:19)\n    at process.target (node:internaltask_queues:96:5)\n    at P.result (browserLauncher.js:187:15)\n    at t.Binder.captureLaunch (binder.js:251:13)\n    at t.Binder._launch (binder.js:227:9)\n    at async Promise.all (index 6)\n    at t.Binder.result [as _boot] (binder.js:175:9)\n    at t.default._onMessage (connection.js:145:27)"}}],"launch.errors":[{"error":{"message":"Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\"","name":"Error","stack":"Error: Unable to launch browser: \"Failed to launch browser!\n\n\nTROUBLESHOOTING: httptroubleshooting.md\n\"\n    at P.prepareLaunch (c:browserLauncher.js:122:19)\n    at process.target (node:internaltask_queues:96:5)\n    at P.result (browserLauncher.js:187:15)\n    at t.Binder.captureLaunch (binder.js:251:13)\n    at t.Binder._launch (binder.js:227:9)\n    at async Promise.all (index 6)\n    at t.Binder.result [as _boot] (binder.js:175:9)\n    at t.default._onMessage (connection.js:145:27)"}}]}}}},"level":0}
{"tag":"dap.send","timestamp":1676089614434,"message":"Message not sent. Connection was closed.","level":2}
```

**Comment by maxkatz6** [comment]
Does "dotnet run" work?

Also, double check that you have the latest VS/Rider/.NET SDK and workloads (both wasm-tools and wasm-experimental). Doesn't look like anything related to avalonia.

**Comment by mysteryx93** [comment]
On Windows, Visual Studio is up-to-date.

Ran in the terminal for the project: dotnet workload restore

Anything else to update?

How would I do dotnet run on a web project

**Comment by maxkatz6** [comment]
> How would I do dotnet run on a web project? It does open up in the console window; with no notable error.

Simply running "dotnet run" from the web project directory should be enough. After the build it prompts in the console links to open the website locally.

**Comment by mysteryx93** [comment]
Nothing unusual; but can't open in browser.

```
dotnet run
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: H:\Downloads\Avalonia11\Avalonia11.Web\bin\Debug\net7.0\browser-wasm\AppBundle
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
PS H:\Downloads\Avalonia11\Avalonia11.Web> dotnet run
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: H:\Downloads\Avalonia11\Avalonia11.Web\bin\Debug\net7.0\browser-wasm\AppBundle
```

**Comment by maxkatz6** [comment]
What do you mean "can't open in browser"? Is there any error when you open https://localhost:5001 or http://localhost:5000 ? You also can check console log in the browser dev tools (F12 in the browser).

**Comment by mysteryx93** [comment]
It just gives `ERR_CONNECTION_CLOSED`

**Comment by mysteryx93** [comment]
I tried again on Linux; now I get something different. It throws this error:

> WasmApp.Native.targets(292, 5): Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.

**Comment by maxkatz6** [comment]
> I tried again on Linux; now I get something different. It throws this error:

Well, that's another problem indeed. You are referencing some dependencies non compatible with WASM .NET compiler. Specifically, Avalonia.Native backend for macos.
By any chance, have you referenced Avalonia.Desktop by mistake?

**Comment by mysteryx93** [comment]
Ah the problem is `FluentAvalonia.UI.Windowing`.

Now I'm back to the previous error.

So this brings an additional consideration: if I want to use TaskDialogs on Desktop and ContentDialogs on Web/Mobile...

The reference to `FluentAvalonia.UI.Windowing` must be conditional, and `<StyleInclude Source="avares://FluentAvalonia.UI.Windowing/Styles/FAWindowingStyles.axaml" />` also should be included only on desktop. Is there a good solution to this?

**Comment by maxkatz6** [comment]
> how can I define the StyleInclude in the .Desktop project

I assume it's an app and not dialogs library. In this case, if your .Desktop project has BuildAvaloniaApp, you can add ".AfterSetup()" there and add style from C# code directly to the Application.Current.

Ideally, FluentAvalonia.UI.Windowing shouldn't reference Avalonia.Desktop project. But IIRC there was some specific reason for that on their side.

**Comment by timunie** [comment]
I think @amwx is working on a new solution for the Windowing stuff which will remove this limitation. See also https://github.com/amwx/FluentAvalonia/pull/307
