### ISSUE TITLE
Setting_Validated_Direct_Property_Calls_UpdateDataValidation test fails intermittently 

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#1033]
```
Message: Assert.Equal() Failure
Expected: BindingNotification[] [{Value: 6}, {Error: System.Exception: Exception of type 'System.Exception' was thrown.}, {DataValidationError: System.Exception: Exception of type 'System.Exception' was thrown.}, {Value: 7}]
Actual:   List<BindingNotification> [{Value: (unset)}, {Error: System.Exception: Exception of type 'System.Exception' was thrown.}, {DataValidationError: System.Exception: Exception of type 'System.Exception' was thrown.}, {Value: 7}]
```

**Comment by grokys** [comment]
Related: `Produces_Range_BindingNotificationsx` (not sure why there's an `x` on the end there!) also occasionall fails with:

```
Message: Assert.Equal() Failure
Expected: BindingNotification[] [{Value: 5}, {DataValidationError: System.ComponentModel.DataAnnotations.ValidationException: The field Between5And10 must be between 5 and 10., Fallback: 3}, {Value: 7}, {DataValidationError: System.ComponentModel.DataAnnotations.ValidationException: The field Between5And10 must be between 5 and 10., Fallback: 11}]
Actual:   List<Object> [{Value: (unset)}, {DataValidationError: System.ComponentModel.DataAnnotations.ValidationException: The field Between5And10 must be between 5 and 10., Fallback: 3}, {Value: 7}, {DataValidationError: System.ComponentModel.DataAnnotations.ValidationException: The field Between5And10 must be between 5 and 10., Fallback: 11}]
```

**Comment by grokys** [comment]
These are very difficult to diagnose as they don't happen when running under the debugger.

**Comment by grokys** [comment]
Also:

```
Test Name:	Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Handle_DataValidation
Test FullName:	Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Handle_DataValidation (c1d0b79aa7e2418d8fd3e3259fd38203d7be95bc)
Test Source:	D:\projects\Avalonia\tests\Avalonia.Markup.UnitTests\Data\BindingExpressionTests.cs : line 332
Test Outcome:	Failed
Test Duration:	0:00:00.003

Result StackTrace:	at Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Handle_DataValidation() in D:\projects\Avalonia\tests\Avalonia.Markup.UnitTests\Data\BindingExpressionTests.cs:line 349
Result Message:	
Assert.Equal() Failure
Expected: BindingNotification[] [{Value: 5.6}, {Value: 1.2}, {Value: 3.4}, {Error: System.InvalidCastException: 'bar' is not a valid number.}]
Actual:   List<Object> [{Value: (unset)}, {Value: 1.2}, {Value: 3.4}, {Error: System.InvalidCastException: 'bar' is not a valid number.}]
```

**Comment by grokys** [comment]
Looks like this may be the cause:

https://github.com/AvaloniaUI/Avalonia/blob/cfcdeff5470a4d8a99fc0687f24d39a7a0601c0f/src/Avalonia.Base/Data/BindingNotification.cs#L112

**Comment by grokys** [comment]
Created #1034 to try and fix this problem but in testing that just came upon:

```
[xUnit.net 00:00:01.7303705]     Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert [FAIL]
[xUnit.net 00:00:01.7311746]       Moq.MockException : 
Expected invocation on the mock at least once, but was never performed: x => x.Convert(5.6, System.String, "foo", )
[xUnit.net 00:00:01.7312449]       No setups configured.
[xUnit.net 00:00:01.7312949]       
[xUnit.net 00:00:01.7313409]       Performed invocations:
[xUnit.net 00:00:01.7313837]       IValueConverter.Convert((unset), System.String, "foo", )
[xUnit.net 00:00:01.7321045]       Stack Trace:
[xUnit.net 00:00:01.7390099]            at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
[xUnit.net 00:00:01.7392750]            at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
[xUnit.net 00:00:01.7393365]            at Moq.Mock.Verify[T,TResult](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
[xUnit.net 00:00:01.7393822]            at Moq.Mock`1.Verify[TResult](Expression`1 expression)
[xUnit.net 00:00:01.7394304]            at Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert()
Failed   Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert
Error Message:
 Moq.MockException : 
Expected invocation on the mock at least once, but was never performed: x => x.Convert(5.6, System.String, "foo", )
No setups configured.
Performed invocations:
IValueConverter.Convert((unset), System.String, "foo", )
Stack Trace:
   at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
   at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
   at Moq.Mock.Verify[T,TResult](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   at Moq.Mock`1.Verify[TResult](Expression`1 expression)
   at Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert()
```

This seems to have a slightly different cause, though likely still due to weak references.

**Comment by grokys** [comment]
Also:

```
[xUnit.net 00:00:03.0842205]     Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Return_BindingNotification_With_FallbackValue_For_NonConvertibe_Target_Value [FAIL]
[xUnit.net 00:00:03.0850214]       Assert.Equal() Failure
[xUnit.net 00:00:03.0850953]       Expected: {Error: System.InvalidCastException: 'foo' is not a valid number., Fallback: 42}
[xUnit.net 00:00:03.0851400]       Actual:   {Value: 42}
[xUnit.net 00:00:03.0857905]       Stack Trace:
[xUnit.net 00:00:03.0890356]            at Avalonia.Markup.UnitTests.Data.BindingExpressionTests.<Should_Return_BindingNotification_With_FallbackValue_For_NonConvertibe_Target_Value>d__9.MoveNext()
[xUnit.net 00:00:03.0891501]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:03.0892148]            at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
[xUnit.net 00:00:03.0933157]     Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert [SKIP]
[xUnit.net 00:00:03.0934412]       Moq.MockException
Failed   Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Return_BindingNotification_With_FallbackValue_For_NonConvertibe_Target_Value
Error Message:
 Assert.Equal() Failure
Expected: {Error: System.InvalidCastException: 'foo' is not a valid number., Fallback: 42}
Actual:   {Value: 42}
Stack Trace:
   at Avalonia.Markup.UnitTests.Data.BindingExpressionTests.<Should_Return_BindingNotification_With_FallbackValue_For_NonConvertibe_Target_Value>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
Skipped  Avalonia.Markup.UnitTests.Data.BindingExpressionTests.Should_Pass_ConverterParameter_To_Convert
```
