### ISSUE TITLE
Headless CreateGlyphRun Null Reference Exception

### ISSUE THREAD

**Issue by pixsperdavid** [AvaloniaUI/Avalonia#10332]
Headless (with UseHeadlessDrawing = false) platform crashes with a null reference exception when calling CreateGlyphRun whilst creating the application view. This seems to be due to HeadlessGlyphTypefaceImpl not being derived from GlyphTypefaceImpl, as the function assumes that the IGlyphTypeface instance passed in will be convertable to GlyphTypefaceImpl.

Tested on nightly 11.0.999-cibuild0029921-beta, Windows 10.

**Comment by pixsperdavid** [comment]
Stack trace:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Avalonia.Skia
  StackTrace:
   at Avalonia.Skia.PlatformRenderInterface.CreateGlyphRun(IGlyphTypeface glyphTypeface, Double fontRenderingEmSize, IReadOnlyList`1 glyphInfos, Point baselineOrigin) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 227
   at Avalonia.Media.GlyphRun.CreateGlyphRunImpl() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 822
   at Avalonia.Media.GlyphRun.get_PlatformImpl() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 218
   at Avalonia.Media.GlyphRun.get_Size() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 156
   at Avalonia.Media.TextFormatting.ShapedTextRun.get_Size() in /_/src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs:line 41
   at Avalonia.Media.TextFormatting.TextLineImpl.CreateLineMetrics() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1449
   at Avalonia.Media.TextFormatting.TextLineImpl.FinalizeLine() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1116
   at Avalonia.Media.TextFormatting.TextFormatterImpl.PerformTextWrapping(List`1 textRuns, Boolean canReuseTextRunList, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, FlowDirection resolvedFlowDirection, TextLineBreak currentLineBreak, FormattingObjectPool objectPool) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 847
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 72
   at Avalonia.Media.TextFormatting.TextLayout.CreateTextLines() in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 478
   at Avalonia.Media.TextFormatting.TextLayout..ctor(ITextSource textSource, TextParagraphProperties paragraphProperties, TextTrimming textTrimming, Double maxWidth, Double maxHeight, Double lineHeight, Double letterSpacing, Int32 maxLines) in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 112
   at Avalonia.Controls.TextBlock.CreateTextLayout(String text) in /_/src/Avalonia.Controls/TextBlock.cs:line 636
   at Avalonia.Controls.TextBlock.get_TextLayout() in /_/src/Avalonia.Controls/TextBlock.cs:line 176
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/TextBlock.cs:line 707
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Controls.Viewbox.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Viewbox.cs:line 121
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Viseal.UI.Controls.KeyGrid.MeasureOverride(Size availableSize) in C:\LocalDev\viseal\src\ui\Viseal.UI\Controls\KeyGrid.cs:line 95
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 596
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 361
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 294
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 254
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 236
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 148
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 108
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Headless.HeadlessPlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Headless/HeadlessPlatformThreadingInterface.cs:line 32
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at App.Run() in C:\LocalDev\App\AppBuilder.cs:line 72
   at Program.Main(String[] args) in C:\LocalDev\App\Program.cs:line 79

**Comment by Gillibald** [comment]
The stacktrace includes a reference to the Skia backend and that should not the case with the headless backend. There is probably a wrong platform render interface registered.

**Comment by pixsperdavid** [comment]
Would that be registered by calling a method on the AppBuilder? I'm only calling UsePlatformDetect.

**Comment by Gillibald** [comment]
> Would that be registered by calling a method on the AppBuilder? I'm only calling UsePlatformDetect.

Yes that uses Skia by default

**Comment by maxkatz6** [comment]
@Gillibald headless backend can be registered with skia renderer, if you want to render it into a bitmap.

@pixsperdavid UsePlatformDetect is used if you want to apply non-headless desktop backends. So, even aside from Skia, it can add some implementations that you don't really need.

UseHeadless by itself should be more than enough.

**Comment by pixsperdavid** [comment]
@maxkatz6 For this app I do need to render to a bitmap (which is then passed to a hardware device for display). I'm now testing with UseSkia and UseHeadless, and still getting the same error. I would also note that this worked in preview 4 so seems to be a regression.

**Comment by Gillibald** [comment]
The current FontManager needs to be compatible with the current platform render interface. If there is a mismatch it doesn't work.

**Comment by pixsperdavid** [comment]
So just to be clear, have I misconfigured something or is this actually a bug?

**Comment by Gillibald** [comment]
Please share your AppBuilder setup

**Comment by timunie** [comment]
> So just to be clear, have I misconfigured something or is this actually a bug?

easiest way to figure it out is imo to create a simple sample to reproduce the issue. If this also fails,  load it up to GitHub and share the link with us. If it's a bug, we can test against your issue. If it's something on your side, we may point you in the right direction.

**Comment by pixsperdavid** [comment]
https://github.com/pixsperdavid/avalonia_headless_bug

Minimal example above demonstrating the error.

**Comment by Gillibald** [comment]
Thanks for the info. I could identify the issue and introduce a fix in the linked PR.

**Comment by pixsperdavid** [comment]
Many thanks!
