### ISSUE TITLE
OnPlatform causes Unhandled exception. System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#10422]
**Describe the bug**

When doing the following:
```XAML
TextElement.FontFamily="{OnPlatform {StaticResource RobotoMonoFont}, Windows='Consolas'}"
```
when running app I get:
```C#
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
   at HexView.MainWindow.DynamicSetters_2.DynamicSetter_1(TextElement, Object)
   at HexView.MainWindow.!XamlIlPopulate(IServiceProvider, MainWindow) in C:\Users\Administrator\Documents\GitHub\HexView\HexView\MainWindow.axaml:line 16
   at HexView.MainWindow.!XamlIlPopulateTrampoline(MainWindow)
   at HexView.MainWindow.InitializeComponent(Boolean loadXaml, Boolean attachDevTools) in C:\Users\Administrator\Documents\GitHub\HexView\HexView\Avalonia.NameGenerator\Avalonia.NameGenerator.AvaloniaNameSourceGenerator\HexView.Main
Window.g.cs:line 23
   at HexView.MainWindow..ctor() in C:\Users\Administrator\Documents\GitHub\HexView\HexView\MainWindow.axaml.cs:line 13
   at HexView.App.OnFrameworkInitializationCompleted() in C:\Users\Administrator\Documents\GitHub\HexView\HexView\App.axaml.cs:line 18
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 250
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 160
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplic
ationLifetime.cs:line 211
   at HexView.Program.Main(String[] args) in C:\Users\Administrator\Documents\GitHub\HexView\HexView\Program.cs:line 12

```

generated code:
```C#
      OnPlatformExtension platformExtension = new OnPlatformExtension();
      object obj;
      if (OnPlatformExtension.ShouldProvideOption("WINDOWS"))
      {
        obj = (object) "Consolas";
      }
      else
      {
        StaticResourceExtension resourceExtension = new StaticResourceExtension((object) "RobotoMonoFont");
        XamlIlContext.Context<MainWindow> context2 = context1;
        context1.ProvideTargetProperty = (object) TextElement.FontFamilyProperty;
        obj = resourceExtension.ProvideValue((IServiceProvider) context2);
        context1.ProvideTargetProperty = (object) null;
      }
      MainWindow.DynamicSetters_2.DynamicSetter_1((TextElement) target, obj);
```

**To Reproduce**

**Expected behavior**
No exception.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview5

**Additional context**

Workaround I use for now: 
```XAML
TextElement.FontFamily="{OnPlatform Default={StaticResource RobotoMonoFont}, Windows={StaticResource ConsolasFont}}"
```

**Comment by maxkatz6** [comment]
As an alternative, you can use "x:TypeArguments" inside of the OnPlatform extension.
`TextElement.FontFamily="{OnPlatform {StaticResource RobotoMonoFont}, Windows='Consolas', x:TypeArguments=FontFamily}"`
