### ISSUE TITLE
Some unicode strings throw System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

### ISSUE THREAD

**Issue by d2phap** [AvaloniaUI/Avalonia#10550]
**Describe the bug**
Some unicode strings throw System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

**To Reproduce**

1. Create new Avalonia project
2. Select v11.0.0-preview5
3. Replace `Welcome to Avalonia!` with this string:
```
สวัสดีครับ ผมมาที่นี่เพื่อต้องการ
คำแนะนำจากคุณ
```
5. See error

Demo project:
[AvaloniaApplication3.zip](https://github.com/AvaloniaUI/Avalonia/files/10888401/AvaloniaApplication3.zip)

**Expected behavior**
The string is displayed without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3154213/222903349-21177734-a4db-4975-98ea-cdc9efa14063.png)

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version: 11 preview 5

**Additional context**
This bug does not happen in v11.0.0-preview4

Exception details:
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at System.ReadOnlySpan`1.get_Item(Int32 index)
   at Avalonia.Skia.TextShaperImpl.ShapeText(ReadOnlyMemory`1 text, TextShaperOptions options)
   at Avalonia.Media.TextFormatting.TextShaper.ShapeText(ReadOnlyMemory`1 text, TextShaperOptions options)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.ShapeTogether(IReadOnlyList`1 textRuns, ReadOnlyMemory`1 text, TextShaperOptions options, TextShaper textShaper, RentedList`1 results)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.ShapeTextRuns(IReadOnlyList`1 textRuns, TextParagraphProperties paragraphProperties, FormattingObjectPool objectPool, FontManager fontManager, FlowDirection& resolvedFlowDirection)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.CreateTextLines()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(ITextSource textSource, TextParagraphProperties paragraphProperties, TextTrimming textTrimming, Double maxWidth, Double maxHeight, Double lineHeight, Double letterSpacing, Int32 maxLines)
   at Avalonia.Controls.TextBlock.CreateTextLayout(String text)
   at Avalonia.Controls.TextBlock.get_TextLayout()
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.Window.ShowCore(Window owner)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaApplication3.Program.Main(String[] args) in D:\DEV\Avalonia\AvaloniaApplication3\AvaloniaApplication3\Program.cs:line 12

```

**Comment by d2phap** [comment]
The issue is somehow fixed in v11 preview 6
