### ISSUE TITLE
macOS: Crash when creating a window when UseGpu is false

### ISSUE THREAD

**Issue by SourMesen** [AvaloniaUI/Avalonia#10591]
**Describe the bug**
On macOS, when `UseGpu` in `AvaloniaNativePlatformOptions` is set to false, a crash occurs when creating any window.  This crash also occurs when `UseGpu` is true if running in an environment where GPU acceleration can't be initialized properly.

Crash:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowImpl..ctor(IAvaloniaNativeFactory factory, AvaloniaNativePlatformOptions opts, AvaloniaNativeGlPlatformGraphics glFeature) in /_/src/Avalonia.Native/WindowImpl.cs:line 32
   at Avalonia.Native.AvaloniaNativePlatform.CreateWindow() in /_/src/Avalonia.Native/AvaloniaNativePlatform.cs:line 153
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 31
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 219
   at [...]
```

The WindowImpl constructor appears to be called with glFeature set to null when UseGpu is false (or when gpu acceleration isn't available). This causes a crash on this line: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Native/WindowImpl.cs#L34

In `AvaloniaNativePlatform`, `_platformGl` appears to only be initialized here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Native/AvaloniaNativePlatform.cs#L132
So if UseGpu is false or an exception occurs during initialization, `_platformGl` is null, which causes the crash.

This crash seems to be new to 11.0.0-preview5

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.0.0-preview5

**Comment by kekekeks** [comment]
Should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/11914
