### ISSUE TITLE
NRE in TooltipService

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#10598]
**Describe the bug**
Trying to set a tooltip for a TextBlock that is being destroyed/recycled ends up throwing a NRE.

**To Reproduce**
It's not easy to reproduce but maybe it's easier to go through the implementation and protect the NRE exception. To reproduce, it needs to set a tooltip while the `TextBlock` is being destroyed/recycled in a virtualized list.

**Expected behavior**
No NRE exception is thrown.

**CallStack**
```
Object reference not set to an instance of an object.
   at Avalonia.Controls.ToolTipService.TipChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/ToolTipService.cs:line 25
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 149
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 807
   at Avalonia.AvaloniaObject.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 564
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 365
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 265
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 99
   at Avalonia.Controls.ToolTip.SetTip(Control element, Object value) in /_/src/Avalonia.Controls/ToolTip.cs:line 99
   at AppUiFramework.Controls.TextBlockAutoTooltip.SetupTooltipVisibility(TextLayout layout)
   at AppUiFramework.Controls.TextBlockAutoTooltip.CreateTextLayout(String text)
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/TextBlock.cs:line 709
```
**Desktop (please complete the following information):**

- OS: Windows/Mac/Linux
- Version: preview4.

**Comment by timunie** [comment]
There were many fixes since preview4. Can you try it with latest nightly again, please?

**Comment by danipen** [comment]
Still there in `11.0.999-cibuild0030125-beta` (preview5-based, but not the latest build). Sorry, I can't try the latest build because it requires some (several) code changes in our codebase.

**Comment by timunie** [comment]
Virtualization was changed after preview5 iirc. So it'd be good to have a sample to reproduce. I know time is limited, so appreciate your effort. 

On the other hand, if you think you know where to fix it, go ahead and file a PR.

**Comment by danipen** [comment]
Still reproduced in `11.0.999-cibuild0031655-beta` (the latest build I found, from 17 hours ago).

**Comment by timunie** [comment]
Then we need to dig deeper into it. Any chance you can share a short sample or file a PR if you have an idea where the NRE happens?

**Comment by danipen** [comment]
I created a minimal example but it doesn't repro :-(. I'll try to connect our app in debug...

**Comment by danipen** [comment]
Ok, I catched the NRE.

At [this point](https://github.com/AvaloniaUI/Avalonia/blob/ef129ec0bc401d28916f5d4900c3c8cf36673da4/src/Avalonia.Controls/ToolTipService.cs#L49) tip is null:
![image](https://user-images.githubusercontent.com/501613/223716033-78594309-a494-4265-89f2-4d8786f398b6.png)

Please can you create the the PR to fix it?

**Comment by timunie** [comment]
Adding a null-check would be easy I guess. But I'm not sure if it is the correct fix. I'll open a PR with the null-check and see what others think. You're welcome to this this PR.

**Comment by danipen** [comment]
I was finally able to repro in a [minimal example](https://gist.github.com/danipen/d2f5c19a66a7f24048f510f080db1c9f).

Making the window quite small, and waiting some milliseconds between mouse wheel scrolls causes the app to crash.

**Comment by danipen** [comment]
I paste here a video, so you can better figure out how to repro:

https://user-images.githubusercontent.com/501613/223725055-d0d49254-356b-4562-a224-02d4422b3aa7.mp4
