### ISSUE TITLE
macOS application doesn't work in VM environment (or without a GPU)

### ISSUE THREAD

**Issue by Mbucari** [AvaloniaUI/Avalonia#10770]
**Describe the bug**
Avalonia cannot launch a desktop window on macOS 10.15. When creating the main window, the call to `IAvaloniaDependencyResolver.GetRequiredService<IWindowingPlatform>()` returns an `AvaloniaNativePlatform`, but `AvaloniaNativePlatform._platformGl` is null. This causes `WindowImpl` constructor to throw an exception here:

https://github.com/AvaloniaUI/Avalonia/blob/532e89c837d61d37d7fb2273f852d51bdc0f1999/src/Avalonia.Native/WindowImpl.cs#L34

**To Reproduce**
Create a barebones macOS desktop application using 11.0.0-preview6 and platform detection. Run it on macOS version 10.15.

**Desktop (please complete the following information):**

- macOS 10.15
- v11.0.0-preview6

**More Detail
The call to new `AvaloniaNativeGlPlatformGraphics` throws an exception,  and it's just ignored.
https://github.com/AvaloniaUI/Avalonia/blob/532e89c837d61d37d7fb2273f852d51bdc0f1999/src/Avalonia.Native/AvaloniaNativePlatform.cs#L130-L136

The exception is thrown by `display.CreateContext(null);` here:

https://github.com/AvaloniaUI/Avalonia/blob/532e89c837d61d37d7fb2273f852d51bdc0f1999/src/Avalonia.Native/AvaloniaNativeGlPlatformGraphics.cs#L19

And here's the exception

```Stacktrace
System.Runtime.InteropServices.COMException (0x80004005): CreateContext failed
   at Avalonia.Native.Interop.Impl.__MicroComIAvnGlDisplayProxy.CreateContext(IAvnGlContext share) in /_/src/Avalonia.Native/Interop.Generated.cs:line 6224
   at Avalonia.Native.AvaloniaNativeGlPlatformGraphics..ctor(IAvnGlDisplay display) in /_/src/Avalonia.Native/AvaloniaNativeGlPlatformGraphics.cs:line 19
   at Avalonia.Native.AvaloniaNativePlatform.DoInitialize(AvaloniaNativePlatformOptions options) in /_/src/Avalonia.Native/AvaloniaNativePlatform.cs:line 132
```

**Comment by kekekeks** [comment]
Are you using a virtual machine?

**Comment by Mbucari** [comment]
> Are you using a virtual machine?

yes. VMWare 16 on a win10 host.

**Comment by Mbucari** [comment]
@kekekeks Is there any documentation that might explain what changed between preview4 and preview6 to break Avalonia on a macos VM?

**Comment by mysteryx93** [comment]
What's the issue with running in a VM, is it a requirement for hardware acceleration?

**Comment by mysteryx93** [comment]
Having some issues with the published app on MacOS tested by a friend on his Mac. I don't have a Mac to debug it myself so I can't what causes it but I'll just mention it

app crashes on startup without saying anything

```
% /Applications/[YangDownloader.app/Contents/MacOS/YangDownloader](http://yangdownloader.app/Contents/MacOS/YangDownloader?fbclid=IwAR3iP36uo05Nx6wx1W_0n5SWWfRXAZEiBDadWIvbXLFxW7sUneYo5cnDZRg) ; exit;

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by Coloryr** [comment]
https://github.com/AvaloniaUI/Avalonia/discussions/10761
the problem start in `v11p5` version.

**Comment by mysteryx93** [comment]
Published my 432Hz Player app for Linux and Windows. Solved some final issues with loading DLLs and stuff, now it's stable.

Here's the MacOS version if someone wants to test it. Not working from the last client reports.
https://mega.nz/file/vBoSFIpA#JzE-x0o_JsTdMis1-uI85kYrcS8JrRjTGJZL5ecZT1g

**Comment by mysteryx93** [comment]
My friend tested the latest version; actually the app now works in MacOS :)

Curious that there's an About Avalonia page that is only available in MacOS

**Comment by mysteryx93** [comment]
and........... the other app crashes on MacOS

```
System.ArgumentNullException: Value cannot be null. (Parameter 'chars')
   at System.Text.UTF8Encoding.GetByteCount(String chars)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnTextInputMethodProxy.SetSurroundingText(String text, Int32 anchorOffset, Int32 cursorOffset)
   at Avalonia.Native.AvaloniaNativeTextInputMethod.OnSurroundingTextChanged(Object sender, EventArgs e)
   at Avalonia.Native.AvaloniaNativeTextInputMethod.SetClient(ITextInputMethodClient client)
   at Avalonia.Input.TextInput.TextInputMethodManager.set_Client(ITextInputMethodClient value)
   at Avalonia.Input.TextInput.TextInputMethodManager.TryFindAndApplyClient()
   at Avalonia.Input.TextInput.TextInputMethodManager.SetFocusedElement(IInputElement element)
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers)
   at Avalonia.Input.FocusManager.SetFocusedElement(IFocusScope scope, IInputElement element, NavigationMethod method, KeyModifiers keyModifiers)
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers)
   at Avalonia.Input.InputElement.Focus()
   at HanumanInstitute.Common.Avalonia.FocusExtensions.<>c__DisplayClass12_0.<OnFocusOnLoadedChanged>b__0(Object , VisualTreeAttachmentEventArgs)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.SetVisualParent(Visual value)
```

FocusExtensions are here
https://github.com/mysteryx93/HanumanInstituteApps/blob/master/Common.Avalonia/Extensions/FocusExtension.cs

**Comment by timunie** [comment]
@mysteryx93 the most recent comment you posted sounds like a complete different issue to me. In that case please do us a favor: 

1. open a new issue for this. 
2. Create a very minimal sample to reproduce the issue. The easier to reproduce the issue for us, the higher the chance for a fix.
