### ISSUE TITLE
ListBox Index out of range exception

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#10815]
**Describe the bug**
On showing a view containing a ListBox the following exception is thrown. The index requested is -12 , there are 69 items in the collection and approx 16 should fit the space.  So far I have failed to make this happen in a simple repro.  The view is shown in a ContentControl that slides out from the side of the window, the error only happens when the ContentControl has previously hosted a different view. An animation controls a translate transform and visibility. The error does not happen when using a StackPanel instead of the virtualizing one.

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.Private.CoreLib
Void ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.Generic.List`1.get_Item(Int32)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32)
   at SparkSDR.Utils.WrappedObservableCollection`2.System.Collections.IList.get_Item(Int32) in /home/pi/Documents/sparksdr/src/SparkSDR/shared/Utils/WrappedObservableCollection.cs:line 92
   at Avalonia.Controls.ItemsSourceView.get_Item(Int32) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 57
   at Avalonia.Controls.VirtualizingStackPanel.GetItemIsOwnContainer(IReadOnlyList`1 , Int32) in /_/src/Avalonia.Controls/VirtualizingStackPanel.cs:line 525
   at Avalonia.Controls.VirtualizingStackPanel.GenerateElements(Size, MeasureViewport&) in /_/src/Avalonia.Controls/VirtualizingStackPanel.cs:line 492
   at Avalonia.Controls.VirtualizingStackPanel.MeasureOverride(Size) in /_/src/Avalonia.Controls/VirtualizingStackPanel.cs:line 166
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size) in /_/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs:line 342
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32, Boolean) in /_/src/Avalonia.Controls/Grid.cs:line 1098
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32, Size, Boolean, Boolean, Boolean& ) in /_/src/Avalonia.Controls/Grid.cs:line 1053
   at Avalonia.Controls.Grid.MeasureOverride(Size) in /_/src/Avalonia.Controls/Grid.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Border.MeasureOverride(Size) in /_/src/Avalonia.Controls/Border.cs:line 241
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32, Boolean) in /_/src/Avalonia.Controls/Grid.cs:line 1098
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32, Size, Boolean, Boolean, Boolean& ) in /_/src/Avalonia.Controls/Grid.cs:line 1053
   at Avalonia.Controls.Grid.MeasureOverride(Size) in /_/src/Avalonia.Controls/Grid.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 591
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 591
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32, Boolean) in /_/src/Avalonia.Controls/Grid.cs:line 1098
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32, Size, Boolean, Boolean, Boolean& ) in /_/src/Avalonia.Controls/Grid.cs:line 1053
   at Avalonia.Controls.Grid.MeasureOverride(Size) in /_/src/Avalonia.Controls/Grid.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 605
   at Avalonia.Layout.Layoutable.MeasureCore(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 519
   at Avalonia.Layout.Layoutable.Measure(Size) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(Layoutable) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 297
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 257
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 244
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 175
   at Avalonia.Threading.DispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 183
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 157
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 111
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 166
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 119
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 119
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 192
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 119
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at SparkSDR.Program.Main(String[]) in /home/pi/Documents/sparksdr/src/SparkSDR/Program.cs:line 100

```

**Desktop (please complete the following information):**

- OS: reproduces on windows 10 and rpi arm32, not tested on others
- Version 11.0.999-cibuild0032372-beta

**Comment by timunie** [comment]
@ahopper do you have minimal repo to reproduce the issue?

**Comment by ahopper** [comment]
I have just discovered that removing the visibility from the animation prevents the exception, hopefully I can now make a minimal repro, I couldn't before.
Maybe it is related to https://github.com/AvaloniaUI/Avalonia/issues/10814

**Comment by ahopper** [comment]
here is a repro 
[AvaloniaListBoxRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/11087221/AvaloniaListBoxRepro.zip) it also repros something similar to #10814 click button B then C (list should appear here but does not) then click B again for the exception.
