### ISSUE TITLE
DataGrid CTRL+C Default Behaviour Crashes Host Application

### ISSUE THREAD

**Issue by jamsoft** [AvaloniaUI/Avalonia#10841]
**Describe the bug**
On a default DataGrid out the box, selecting a row / cell and pressing CTRL+C bombs the application

**To Reproduce**

1. Create project
2. Add a datagrid
3. Bind some rows
4. Run application and select a row or cell
5. Press CTRL+C

**Expected behavior**
It would be nice if it copied the row item to the clipboard but it definitely shouldn't bomb the host application as a default.

Setting `ClipboardCopyMode="None"` prevents the crash.

I've also tried implementing `OnCopyingRowClipboardContent` But this event handler never fires.

How do you handle CTRL+C?

- OS: Win10
- Version 11preview-5

```
System.NotSupportedException: Two way bindings are not supported with a string format
   at Avalonia.Data.Converters.StringFormatValueConverter.ConvertBack(Object value, Type targetType, Object parameter, CultureInfo culture) in /_/src/Avalonia.Base/Data/Converters/StringFormatValueConverter.cs:line 44
   at Avalonia.Data.Core.BindingExpression.OnNext(Object value) in /_/src/Avalonia.Base/Data/Core/BindingExpression.cs:line 131
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.Subscribed(IObserver`1 observer, Boolean first) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 45
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 66
   at Avalonia.Data.BindingOperations.Apply(AvaloniaObject target, AvaloniaProperty property, InstancedBinding binding, Object anchor) in /_/src/Avalonia.Base/Data/BindingOperations.cs:line 49
   at Avalonia.AvaloniaObjectExtensions.Bind(AvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 212
   at Avalonia.Controls.DataGridColumn.GetCellValue(Object item, IBinding binding) in /_/src/Avalonia.Controls.DataGrid/DataGridColumn.cs:line 635
   at Avalonia.Controls.DataGrid.ProcessCopyKey(KeyModifiers modifiers) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 6115
   at Avalonia.Controls.DataGrid.ProcessDataGridKey(KeyEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 4715
   at Avalonia.Controls.DataGrid.DataGrid_KeyDown(Object sender, KeyEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 3935
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 64
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 70
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 164
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 125
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/KeyboardDevice.cs:line 232
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 632
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 750
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 204
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 212
```

**Comment by jamsoft** [comment]
@timunie that'll teach me for raising bugs in the wee hours of the morning eh ... thank you.
