### ISSUE TITLE
DataGridTextColumn causes application crash when editing on macOS

### ISSUE THREAD

**Issue by Mbucari** [AvaloniaUI/Avalonia#10843]
**Describe the bug**
[One of our users reported a bug](https://github.com/rmcrackan/Libation/issues/552#issuecomment-1486070852) that causes his application crashed when double-clicking into a `DataGridTextColumn` cell to begin editing its contents. I am unable to investigate this in detail due to #10770, but I was able to prevent a crash by changing `DataGridTextColumn` to a `DataGridTemplateColumn` with a `TextBox`.

**To Reproduce**
1. Create a `DataGrid` control and bind it to an `AvaloniaList<T>`, where `T` is a custom type containing a string property with public get and set;
2. Add a `DataGridTextColumn` bound to said string property, with `BindingMode.TwoWay`.
3. Add an instance of `T` to the bound list, and set its string property to `null`.
4. Run this application on macOS, and double-click the empty cell in the `DataGridTextColumn` to initiate an edit.

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.0.0-preview6

**Comment by Mbucari** [comment]
I've reproduced the error on macOS Monterey running on an M1 chip. It happend whether the bound string property is null or has a value.

https://github.com/Mbucari/AvaloniaApplication2

Here's the exception and stack trace:
```C#
System.ArgumentNullException: Value cannot be null. (Parameter 'chars')
   at System.Text.UTF8Encoding.GetByteCount(String chars)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnTextInputMethodProxy.SetSurroundingText(String text, Int32 anchorOffset, Int32 cursorOffset) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4646
   at Avalonia.Native.AvaloniaNativeTextInputMethod.OnSurroundingTextChanged(Object sender, EventArgs e) in /_/src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs:line 86
   at Avalonia.Native.AvaloniaNativeTextInputMethod.SetClient(ITextInputMethodClient client) in /_/src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs:line 46
   at Avalonia.Input.TextInput.TextInputMethodManager.set_Client(ITextInputMethodClient value) in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 60
   at Avalonia.Input.TextInput.TextInputMethodManager.TryFindAndApplyClient() in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 129
   at Avalonia.Input.TextInput.TextInputMethodManager.SetFocusedElement(IInputElement element) in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 110
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/KeyboardDevice.cs:line 163
   at Avalonia.Input.FocusManager.SetFocusedElement(IFocusScope scope, IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 142
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 70
   at Avalonia.Input.InputElement.Focus() in /_/src/Avalonia.Base/Input/InputElement.cs:line 500
   at Avalonia.Controls.DataGridColumn.PrepareCellForEditInternal(Control editingElement, RoutedEventArgs editingEventArgs) in /_/src/Avalonia.Controls.DataGrid/DataGridColumn.cs:line 933
   at Avalonia.Controls.DataGrid.PreparingCellForEditPrivate(Control editingElement) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 4643
   at Avalonia.Controls.DataGrid.PopulateCellContent(Boolean isCellEdited, DataGridColumn dataGridColumn, DataGridRow dataGridRow, DataGridCell dataGridCell) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 4603
   at Avalonia.Controls.DataGrid.BeginCellEdit(RoutedEventArgs editingEventArgs) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 3367
   at Avalonia.Controls.DataGrid.UpdateStateOnMouseLeftButtonDown(PointerPressedEventArgs pointerPressedEventArgs, Int32 columnIndex, Int32 slot, Boolean allowEdit, Boolean shift, Boolean ctrl) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 5937
   at Avalonia.Controls.DataGrid.UpdateStateOnMouseLeftButtonDown(PointerPressedEventArgs pointerPressedEventArgs, Int32 columnIndex, Int32 slot, Boolean allowEdit) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 3137
   at Avalonia.Controls.DataGridCell.DataGridCell_PointerPressed(PointerPressedEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGridCell.cs:line 179
   at Avalonia.Controls.DataGridCell.<>c.<.cctor>b__5_0(DataGridCell x, PointerPressedEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGridCell.cs:line 35
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass1_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/RoutedEvent.cs:line 125
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Base/Interactivity/RoutedEvent.cs:line 92
   at Avalonia.Reactive.AnonymousObserver`1.OnNext(T value) in /_/src/Avalonia.Base/Reactive/AnonymousObserver.cs:line 65
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 143
   at Avalonia.Reactive.LightweightSubject`1.OnNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightSubject.cs:line 24
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/RoutedEvent.cs:line 99
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 146
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 125
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, IInputElement hitTest) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 144
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 75
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 32
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 651
   at Avalonia.Native.WindowBaseImpl.RawMouseEvent(AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta) in /_/src/Avalonia.Native/WindowImplBase.cs:line 356
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.RawMouseEvent(AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta) in /_/src/Avalonia.Native/WindowImplBase.cs:line 224
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.RawMouseEvent(Void* this, AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4152
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at AvaloniaApplication2.Program.Main(String[] args) in /Users/mbucari/RiderProjects/AvaloniaApplication2/AvaloniaApplication2/Program.cs:line 14

```

**Comment by maxkatz6** [comment]
@Mbucari thanks for the stacktrace!
It seems this bug was already fixed in this PR - https://github.com/AvaloniaUI/Avalonia/pull/10820
