### ISSUE TITLE
StyleInclude resources can not be found when used inside Behaviors

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1088]
StyleInclude seems to be broken when using inside UserControl it worked before.

It works only first time when control is loaded and after that style resources are not available.
```XAML
<UserControl x:Class="BehaviorsTestApplication.Controls.ChangePropertyActionControl"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:vm="clr-namespace:BehaviorsTestApplication.ViewModels;assembly=BehaviorsTestApplication"
             xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
             xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions"
             xmlns:iac="clr-namespace:Avalonia.Xaml.Interactions.Custom;assembly=Avalonia.Xaml.Interactions.Custom">
    <UserControl.Styles>
        <StyleInclude Source="resm:BehaviorsTestApplication.Styles.Brushes.xaml?assembly=BehaviorsTestApplication"/>
    </UserControl.Styles>
    <Grid RowDefinitions="5*,*" ColumnDefinitions="50*,5,50*">
        <Rectangle Name="ChangePropertyRectangle" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" Margin="5" Fill="{StyleResource PinkBrush}" Stroke="{StyleResource GrayBrush}" StrokeThickness="5"/>
        <Button Name="pinkButton" Content="Pink" Grid.Row="1" Grid.Column="0" Margin="5,0,0,5" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
            <i:Interaction.Behaviors>
                <ia:EventTriggerBehavior EventName="Click" SourceObject="{Binding #pinkButton}">
                    <ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource PinkBrush}"/>
                </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
        </Button>
        <Button Name="yellowButton" Content="Yellow" Grid.Row="1" Grid.Column="2" Margin="0,0,5,5" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
            <i:Interaction.Behaviors>
                <ia:EventTriggerBehavior EventName="Click" SourceObject="{Binding #yellowButton}">
                    <ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource YellowBrush}"/>
                </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
        </Button>
    </Grid>
</UserControl>
```
this line does not work:
```XAML
<ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource PinkBrush}"/>
```

when I include style resources directly it all works as expected.

Version: 0.5.1-build3595-alpha

**Comment by grokys** [comment]
Do you think you could upload the solution? When I try to create a new project with `Avalonia.Xaml.Behaviors` I get:

```
System.Reflection.TargetInvocationException occurred
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Portable.Xaml.Schema.XamlMemberInvoker.GetValueReflectionAttachable(Object instance)
   at Portable.Xaml.Schema.XamlMemberInvoker.GetValue(Object instance)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteGetObject()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Type type, Object rootInstance)
   at AvaloniaCoreApplication2.MainWindow.InitializeComponent() in d:\temp\AvaloniaCoreApplication2\AvaloniaCoreApplication2\MainWindow.xaml.cs:line 17
   at AvaloniaCoreApplication2.MainWindow..ctor() in d:\temp\AvaloniaCoreApplication2\AvaloniaCoreApplication2\MainWindow.xaml.cs:line 11

Inner Exception 1:
TypeInitializationException: The type initializer for 'Avalonia.Xaml.Interactivity.Interaction' threw an exception.

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Reactive.Core, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by wieslawsoltes** [comment]
@grokys Did you update `Rx` to `3.1.0` ? https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/master/build/Rx.props

**Comment by wieslawsoltes** [comment]
@grokys And you need to use nightly NuGet feed https://github.com/wieslawsoltes/AvaloniaBehaviors#nuget

**Comment by wieslawsoltes** [comment]
@grokys Sample app with repro https://files.gitter.im/AvaloniaUI/Avalonia/rMvQ/AvaloniaBehaviorsSamples-v1.zip
