### ISSUE TITLE
TabItem not passing its DataContext to its child view

### ISSUE THREAD

**Issue by oli-g-sk** [AvaloniaUI/Avalonia#10958]
**Describe the bug**
When we set a `DataContext` to a `TabItem`, its logical child (set in `TabItem.Content`) doesn't inherit it. The `DataContext` of the logical child remains that of `TabItem`'s parent.

**To Reproduce**
Consider the following trivial ViewModels:
```csharp
public class MainViewModel
{
    public ChildViewModel ChildViewModel { get; } = new();
}
```
```csharp
public class ChildViewModel
{
    public string Foo => "Hello World!";
}
```
Let's try and bind to `Foo` from `TabItem`'s child:
```xaml
<Window>
    <Window.DataContext>
        <core:MainViewModel/>
    </Window.DataContext>
    <TabControl>
        <TabItem Header="Broken tab item"
                 DataContext="{Binding ChildViewModel}">
            <!-- this binding does not work -->
            <TextBlock Text="{Binding Foo}" />
        </TabItem>
        <TabItem Header="Working tab item">
            <!-- this binding works -->
            <TextBlock Text="{Binding ChildViewModel.Foo}" />
        </TabItem>
    </TabControl>
</Window>
```

**Expected behavior**
When a `DataContext` is set to a `TabItem` , the element set in `TabItem.Content` inherits the `DataContext`.

**Screenshots**

![avalonia20230408_01](https://user-images.githubusercontent.com/1889369/230732348-4d30845d-33ce-43ef-a9f1-32ea3518bd48.gif)

![image](https://user-images.githubusercontent.com/1889369/230733002-d28311f5-eb8b-46eb-9947-17add2256d08.png)

![image](https://user-images.githubusercontent.com/1889369/230733017-3849ee2a-2134-4559-ae20-409657385c59.png)

**Desktop**
- OS: Windows 11 (but presumably every other?)
- Avalonia version: **0.10.19** (first spotted in 0.10.14)

**Additional context**
- There are no warnings in Avalonia's log-to-trace output.
- Copy-pasting the above XAML into a WPF project works out of the box; both tab items display the text.

**Comment by oli-g-sk** [comment]
I've just discovered #10242 and I believe this might be a duplicate; with a bit simpler repro steps at least

**Comment by derekantrican** [comment]
Seeing the same thing - I was wondering if this was a design choice for TabItem (for the DataContext prop to apply to only the TabItem but not to contents).

Right now, the workaround is to set the DataContext for the contents (usually a Grid):

```xml
<TabItem Header="My tab item">
    <Grid DataContext="{Binding ChildViewModel}">
        <TextBlock Text="{Binding Foo}" />
    </Grid>
</TabItem>
```

or in both places if you also need it for header binding:

```xml
<TabItem Header="{Binding Header}" DataContext="{Binding ChildViewModel}">
    <Grid DataContext="{Binding ChildViewModel}">
        <TextBlock Text="{Binding Foo}" />
    </Grid>
</TabItem>
```

```csharp
public class ChildViewModel
{
    public string Header => "My tab item";
    public string Foo => "Hello World!";
}
```

**Comment by timunie** [comment]
@derekantrican no, I don't think it is by design. Seems to be an actual bug.

**Comment by lcocea** [comment]
Same here

**Comment by SkytAsul** [comment]
That's pretty annoying because the workaround cannot be used for tabitems defined in their own xaml file. Has someone figured out why this bug is happening?

**Comment by toomasz** [comment]
Hitting same bug in 2025

**Comment by ptasev** [comment]
The error is not helpful when this happens which can make it difficult for a new user of the framework. I get this with compiled bindings enabled during the call `BuildAvaloniaApp().StartWithClassicDesktopLifetime(args)`.
```csharp
System.InvalidCastException: Unable to cast object of type 'App.ViewModels.MainViewModel' to type 'App.ViewModels.ResourcesWorkspaceViewModel'.
   at CompiledAvaloniaXaml.XamlIlHelpers.App.ViewModels.ResourcesWorkspaceViewModel,App.Resources!Getter(Object)
   at Avalonia.Data.Core.ClrPropertyInfo.Get(Object target)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.get_Value()
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.SendCurrentValue()
```
```xml
<TabControl>
    <TabItem Header="{Binding DisplayName}" DataContext="{Binding Path=ResourcesWorkspace}">
        ...
```

When you try the workaround by putting the datacontext on the tab item's content you then get a compiler error.
```bash
1>MainWindow.axaml(87,28): Error AVLN2000 Avalonia: Unable to resolve property or method of name 'ResourcesWorkspace' on type 'App.ViewModels.ResourcesWorkspaceViewModel'. Line 87, position 28.
```
```xml
<TabControl>
    <TabItem Header="{Binding DisplayName}" DataContext="{Binding Path=ResourcesWorkspace}">
        <DockPanel DataContext="{Binding Path=ResourcesWorkspace}">
            ...
```

With compiled bindings the only choice is to remove the DataContext from the `TabItem` and put it on the content only. (Version 11.3.11)
```xml
<TabControl>
    <TabItem Header="{Binding ResourcesWorkspace.DisplayName}">
        <DockPanel DataContext="{Binding Path=ResourcesWorkspace}">
            ...
```
