### ISSUE TITLE
App crashes when closing while menu is showing

### ISSUE THREAD

**Issue by Zhou-Pixel** [AvaloniaUI/Avalonia#10980]
Env: `macOS12.6.4`  `avalonia11-preview6`

**Comment by maxkatz6** [comment]
Can you test it with latest nightly?
Should have been fixed recently.

Otherwise, please post full stacktrace and error message.

**Comment by Zhou-Pixel** [comment]
> Can you test it with latest nightly? Should have been fixed recently.
> 
> Otherwise, please post full stacktrace and error message.

```c#
/Users/zhou/Documents/Code/CSharp/AvaloniaApp/AvaloniaApp/bin/Debug/net6.0/AvaloniaApp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Styling.ThemeVariant.op_Explicit(ThemeVariant themeVariant) in /_/src/Avalonia.Base/Styling/ThemeVariant.cs:line 113
   at Avalonia.Controls.TopLevel.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Controls/TopLevel.cs:line 459
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/Animation/Animatable.cs:line 185
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 708
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 227
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 217
   at Avalonia.PropertyStore.LocalValueBindingObserverBase`1.<OnNext>g__Execute|15_0(LocalValueBindingObserverBase`1 instance, BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs:line 100
   at Avalonia.PropertyStore.LocalValueBindingObserverBase`1.OnNext(BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs:line 110
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyBindingObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyBindingObservable.cs:line 59
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 708
   at Avalonia.PropertyStore.EffectiveValue`1.RaiseInheritedValueChanged(AvaloniaObject owner, AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 106
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 759
   at Avalonia.PropertyStore.ValueStore.SetInheritanceParent(AvaloniaObject newParent) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 374
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Base/StyledElement.cs:line 471
   at Avalonia.Controls.ContextMenu.ControlDetachedFromVisualTree(Object sender, VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/ContextMenu.cs:line 438
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 538
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 758
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 505
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 384
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 548
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 758
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 505
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 384
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 548
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 758
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 505
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 384
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 548
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 758
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 505
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 384
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 548
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 758
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 505
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 384
   at Avalonia.Controls.TopLevel.HandleClosed() in /_/src/Avalonia.Controls/TopLevel.cs:line 506
   at Avalonia.Controls.WindowBase.HandleClosed() in /_/src/Avalonia.Controls/WindowBase.cs:line 202
   at Avalonia.Controls.Window.HandleClosed() in /_/src/Avalonia.Controls/Window.cs:line 986
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Closed() in /_/src/Avalonia.Native/WindowImplBase.cs:line 186
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Closed(Void* this) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4042
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at AvaloniaApp.Program.Main(String[] args) in /Users/zhou/Documents/Code/CSharp/AvaloniaApp/AvaloniaApp/Program.cs:line 13

Process finished with exit code 134.

```

**Comment by maxkatz6** [comment]
Thanks!
This bug was fixed in the master. Will be available in preview7.
