### ISSUE TITLE
Preview7: Telemetry on build throws an exception

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaUI/Avalonia#11145]
**Describe the bug**
If I try to build, I get a weird exception stacktrace about telemetry that I am not sure what it means or why it happens, but it doesn't sound normal.

**To Reproduce**
I build my project and I get this in the build log:
```
CONSOLE: Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
CONSOLE:    at System.Environment.FailFast(System.String)
CONSOLE:    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
CONSOLE:    at System.Globalization.GlobalizationMode..cctor()
CONSOLE:    at System.Globalization.CultureData.CreateCultureWithInvariantData()
CONSOLE:    at System.Globalization.CultureData.get_Invariant()
CONSOLE:    at System.Globalization.CultureInfo..cctor()
CONSOLE:    at System.String.ToUpperInvariant()
CONSOLE:    at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
CONSOLE:    at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
CONSOLE:    at System.Diagnostics.Tracing.EventSource..ctor()
CONSOLE:    at System.Net.NetEventSource..cctor()
CONSOLE:    at System.Net.Http.HttpClientHandler..ctor(Boolean)
CONSOLE:    at System.Net.Http.HttpClient..ctor()
CONSOLE:    at Avalonia.Telemetry.Collector..ctor()
CONSOLE:    at Avalonia.Telemetry.Program+<Main>d__0.MoveNext()
CONSOLE:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Avalonia.Telemetry.Program+<Main>d__0, Avalonia.BuildServices, Version=0.0.12.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
CONSOLE:    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Avalonia.Telemetry.Program+<Main>d__0, Avalonia.BuildServices, Version=0.0.12.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
CONSOLE:    at Avalonia.Telemetry.Program.Main(System.String[])
CONSOLE:    at Avalonia.Telemetry.Program.<Main>(System.String[])
```

**Expected behavior**
To not see this exception

**Desktop (please complete the following information):**

- OS: Arch Linux kernel 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC
- Version 11.0.0-preview7

**Comment by Gillibald** [comment]
https://archlinux.org/packages/core/x86_64/icu/

**Comment by aldelaro5** [comment]
> https://archlinux.org/packages/core/x86_64/icu/

Oh it seems I already had it installed:
```
warning: icu-72.1-2 is up to date -- reinstalling
```

So I am not sure whose problem it is then...

**Comment by kekekeks** [comment]
I think the collector runs on the oldest installed runtime that's >=3.0. I guess you have some old runtime installed that doesn't support the new state of your fancy distro that was updating itself in the meantime

**Comment by danwalmsley** [comment]
that wont cause a build issue any more.
