### ISSUE TITLE
Exception in Avalonia.Controls.Utils.RealizedStackElements.ItemsInserted

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#11153]
**Describe the bug**
A user has reported this exception
```
Specified argument was out of the range of valid values. (Parameter 'index')
Avalonia.Controls
Void ItemsInserted(Int32, Int32, System.Action`3[Avalonia.Controls.Control,System.Int32,System.Int32])
   at Avalonia.Controls.Utils.RealizedStackElements.ItemsInserted(Int32, Int32, Action`3) in /_/src/Avalonia.Controls/Utils/RealizedStackElements.cs:line 270
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakEventSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged, NotifyCollectionChangedEventArgs, WeakReference`1[]) in /_/src/Avalonia.Controls/Utils/CollectionChangedEventManager.cs:line 133
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object , TEventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 114
   at radio.PI4ModDemod.<>c__DisplayClass28_0.<sendSpot>b__0()
   at Avalonia.Threading.DispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 294
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 268
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 121
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 176
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 129
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr, UInt32, IntPtr, IntPtr) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 231
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken) in /_/src/Windows/Avalonia.Win32/Win32DispatcherImpl.cs:line 111
   at Avalonia.Threading.DispatcherFrame.RunCore(IControlledDispatcherImpl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 110
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 97
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at SparkSDR.Program.Main(String[])
```

The sendSpot method runs in a non ui thread and calls Dispatcher.UIThread.Post to update a collection that a ListBox is bound to.  This happened once in a 24 hour run with this method working the rest of the time.

So far I have failed to reproduce it, I'm working on a stress test to try to do so.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0 preview 7

**Additional context**

**Comment by ahopper** [comment]
This turned out to be an issue with my ObservableCircularCollection sending NotifyCollectionChangedAction.Add when an item was added to the start of the collection, using NotifyCollectionChangedAction.Reset (which makes more sense) fixed it. Odd that it had worked so well up to now.
