### ISSUE TITLE
Playing Animations from code produces various exceptions

### ISSUE THREAD

**Issue by DmitriyYukhanov** [AvaloniaUI/Avalonia#11156]
**Describe the bug**
When animating `IsVisible` and `Opacity` properties from the `AttachedProperty.Changed` `IObservable`, different exceptions occur while navigating through the application (navigation is done through the `RoutingState`).

**To Reproduce**
It does reproduce occasionally and requires a few minutes navigating through the app until it happens, but it doesn't reproduce when animations are disabled.

**Expected behavior**
No exceptions occur.

**Screenshots**
No screenshots, since it's just an exception, but here is a code I use to animate properties:
[FadeBehavior.zip](https://github.com/AvaloniaUI/Avalonia/files/11342647/FadeBehavior.zip)

And here are the stacktraces for the exceptions:

**If not observing on UI thread**
`IsVisibleProperty.Changed.Subscribe(x => HandleIsVisibleFadeChanged(x.Sender, x.NewValue.GetValueOrDefault<bool>()));
`

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)

Exception details:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)
 ---> System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.VerifyAccess() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 111
   at Avalonia.AvaloniaObject.GetValue[T](StyledProperty`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 226
   at Avalonia.Animation.Animatable.get_Transitions() in /_/src/Avalonia.Base/Animation/Animatable.cs:line 50
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/Animation/Animatable.cs:line 144
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 700
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 219
   at Avalonia.PropertyStore.EffectiveValue`1.RemoveAnimationAndRaise(ValueStore owner, AvaloniaProperty property) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 120
   at Avalonia.PropertyStore.ValueStore.ReevaluateEffectiveValue(AvaloniaProperty property, EffectiveValue current, IValueEntry changedValueEntry, Boolean ignoreLocalValue) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 850
   at Avalonia.PropertyStore.ValueStore.OnValueEntryRemoved(ValueFrame frame, AvaloniaProperty property) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 575
   at Avalonia.PropertyStore.ValueFrame.OnBindingCompleted(IValueEntry binding) in /_/src/Avalonia.Base/PropertyStore/ValueFrame.cs:line 64
   at Avalonia.PropertyStore.BindingEntryBase`2.BindingCompleted() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 186
   at Avalonia.PropertyStore.BindingEntryBase`2.Dispose() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 70
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.Dispose() in /_/src/Avalonia.Base/Animation/DisposeAnimationInstanceSubject.cs:line 30
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Animation.Animation.<>c__DisplayClass52_0.<RunAsync>b__0() in /_/src/Avalonia.Base/Animation/Animation.cs:line 382
   at Avalonia.Animation.Animation.<>c.<Apply>b__50_0(Task _, Object state) in /_/src/Avalonia.Base/Animation/Animation.cs:line 352
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)

Exception details:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)
 ---> System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.VerifyAccess() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 111
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 324
   at Avalonia.StyledProperty`1.RouteSetValue(AvaloniaObject target, Object value, BindingPriority priority) in /_/src/Avalonia.Base/StyledProperty.cs:line 199
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 305
   at Avalonia.Animation.AnimationInstance`1.ApplyFinalFill() in /_/src/Avalonia.Base/Animation/AnimationInstance`1.cs:line 114
   at Avalonia.Animation.AnimationInstance`1.Unsubscribed() in /_/src/Avalonia.Base/Animation/AnimationInstance`1.cs:line 81
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.Dispose() in /_/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 41
   at Avalonia.PropertyStore.BindingEntryBase`2.Unsubscribe() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 104
   at Avalonia.PropertyStore.BindingEntryBase`2.Dispose() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 69
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.Dispose() in /_/src/Avalonia.Base/Animation/DisposeAnimationInstanceSubject.cs:line 30
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Animation.Animation.<>c__DisplayClass52_0.<RunAsync>b__0() in /_/src/Avalonia.Base/Animation/Animation.cs:line 382
   at Avalonia.Animation.Animation.<>c.<Apply>b__50_0(Task _, Object state) in /_/src/Avalonia.Base/Animation/Animation.cs:line 352
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

**If observing on main thread**
`IsVisibleProperty.Changed.ObserveOn(RxApp.MainThreadScheduler).Subscribe(x => HandleIsVisibleFadeChanged(x.Sender, x.NewValue.GetValueOrDefault<bool>()));`

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)

Exception details:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Avalonia.Utilities.AvaloniaPropertyDictionary`1.RemoveAt(Int32 index) in /_/src/Avalonia.Base/Utilities/AvaloniaPropertyDictionary.cs:line 203
   at Avalonia.Utilities.AvaloniaPropertyDictionary`1.Remove(AvaloniaProperty property) in /_/src/Avalonia.Base/Utilities/AvaloniaPropertyDictionary.cs:line 162
   at Avalonia.PropertyStore.ValueFrame.Remove(AvaloniaProperty property) in /_/src/Avalonia.Base/PropertyStore/ValueFrame.cs:line 112
   at Avalonia.PropertyStore.ValueFrame.OnBindingCompleted(IValueEntry binding) in /_/src/Avalonia.Base/PropertyStore/ValueFrame.cs:line 62
   at Avalonia.PropertyStore.BindingEntryBase`2.BindingCompleted() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 186
   at Avalonia.PropertyStore.BindingEntryBase`2.Dispose() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 70
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.Dispose() in /_/src/Avalonia.Base/Animation/DisposeAnimationInstanceSubject.cs:line 30
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Animation.Animation.<>c__DisplayClass52_0.<RunAsync>b__0() in /_/src/Avalonia.Base/Animation/Animation.cs:line 382
   at Avalonia.Animation.Animation.<>c.<Apply>b__50_0(Task _, Object state) in /_/src/Avalonia.Base/Animation/Animation.cs:line 352
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))

Exception details:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Avalonia.PropertyStore.ValueStore.OnValueEntryRemoved(ValueFrame frame, AvaloniaProperty property) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 570
   at Avalonia.PropertyStore.ValueFrame.OnBindingCompleted(IValueEntry binding) in /_/src/Avalonia.Base/PropertyStore/ValueFrame.cs:line 64
   at Avalonia.PropertyStore.BindingEntryBase`2.BindingCompleted() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 186
   at Avalonia.PropertyStore.BindingEntryBase`2.Dispose() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 70
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.Dispose() in /_/src/Avalonia.Base/Animation/DisposeAnimationInstanceSubject.cs:line 30
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Animation.Animation.<>c__DisplayClass52_0.<RunAsync>b__0() in /_/src/Avalonia.Base/Animation/Animation.cs:line 382
   at Avalonia.Animation.Animation.<>c.<Apply>b__50_0(Task _, Object state) in /_/src/Avalonia.Base/Animation/Animation.cs:line 352
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

Tried to combine `IsVisibleProperty.Changed.ObserveOn(RxApp.MainThreadScheduler)` and `Dispatcher.UIThread.Post(() => { StartFadeAnimation(); });` but still getting this exception:

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)

Exception details:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)
 ---> System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.VerifyAccess() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 111
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 324
   at Avalonia.StyledProperty`1.RouteSetValue(AvaloniaObject target, Object value, BindingPriority priority) in /_/src/Avalonia.Base/StyledProperty.cs:line 199
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 305
   at Avalonia.Animation.AnimationInstance`1.ApplyFinalFill() in /_/src/Avalonia.Base/Animation/AnimationInstance`1.cs:line 114
   at Avalonia.Animation.AnimationInstance`1.Unsubscribed() in /_/src/Avalonia.Base/Animation/AnimationInstance`1.cs:line 81
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.Dispose() in /_/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 41
   at Avalonia.PropertyStore.BindingEntryBase`2.Unsubscribe() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 104
   at Avalonia.PropertyStore.BindingEntryBase`2.Dispose() in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 69
   at Avalonia.Animation.DisposeAnimationInstanceSubject`1.Dispose() in /_/src/Avalonia.Base/Animation/DisposeAnimationInstanceSubject.cs:line 30
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Reactive.CompositeDisposable.Dispose() in /_/src/Avalonia.Base/Reactive/CompositeDisposable.cs:line 227
   at Avalonia.Animation.Animation.<>c__DisplayClass52_0.<RunAsync>b__0() in /_/src/Avalonia.Base/Animation/Animation.cs:line 382
   at Avalonia.Animation.Animation.<>c.<Apply>b__50_0(Task _, Object state) in /_/src/Avalonia.Base/Animation/Animation.cs:line 352
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

**Desktop**

- OS: Windows 11 latest
- Version 11 preview 4, preview 6 and preview 7

**Additional context**
Can show issue on video call with Avalonia maintainer but can't share a project due to nda, unfortunately.

P.S. the problem I'm trying to solve is have an easy-to-use generic tool for any Visuals fading, so they show and hide smoothly and nicely with such code:
```
<TextBlock Text="Test"
           behaviors:FadeBehavior.IsVisible="{Binding IsTextVisible}"/>
```

**Comment by maxkatz6** [comment]
Seems like this callback is not dispatched to the UI thread. Should be an easy fix, preferably with simple test.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Animation/Animation.cs#L352
