### ISSUE TITLE
[CompiledBinding] ExpressionParseException: Internal compiler error while transforming node XamlX.Ast.XamlAstObjectNode

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11224]
**Describe the bug**
Considering following code

```xaml
<Button Command="{Binding ((vm:ProjectViewModel)($parent[v:ProjectView].DataContext)).GoTo}"
        CommandParameter="{Binding .}"
        HorizontalAlignment="Stretch"
        HorizontalContentAlignment="Stretch"
        >
  <StackPanel>
    <TextBlock Text="{Binding Title}"
               FontWeight="Bold"/>
    <TextBlock Text="{Binding Subtitle}"
              />
  </StackPanel>
</Button>
```

when compile throw:

```bash
Error		Internal compiler error while transforming node XamlX.Ast.XamlAstObjectNode:
Avalonia.Data.Core.ExpressionParseException: Expected ')'.
   at Avalonia.Markup.Parsers.BindingExpressionGrammar.ParseTypeCast(CharacterReader& r, List`1 nodes) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs:line 249
   at Avalonia.Markup.Parsers.BindingExpressionGrammar.Parse(CharacterReader& r) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs:line 50
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlBindingPathParser.Transform(AstTransformationContext context, IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathParser.cs:line 28
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader
```

**Expected behavior**
Compile

**Screenshots**
(none)

**Desktop (please complete the following information):**

- OS: **any**
- Version: **11.0.999-cibuild0034121-beta**

**Workaround**

```xaml
<Button Command="{Binding ((vm:ProjectViewModel)DataContext).GoTo
          ,RelativeSource={RelativeSource FindAncestor,AncestorType={x:Type v:ProjectView}}
          }"
        CommandParameter="{Binding .}"
        HorizontalAlignment="Stretch"
        HorizontalContentAlignment="Stretch"
        >
  <StackPanel>
    <TextBlock Text="{Binding Title}"
               FontWeight="Bold"/>
    <TextBlock Text="{Binding Subtitle}"
              />
  </StackPanel>
</Button>
```

**Comment by timunie** [comment]
I think this should work: 

`{Binding $parent[v:ProjectView].((vm:ProjectViewModel)DataContext).GoTo}`

Can you try it?

**Comment by workgroupengineering** [comment]
> {Binding $parent[v:ProjectView].((vm:ProjectViewModel)DataContext).GoTo}
it works, thanks
