### ISSUE TITLE
Error MSB4018 : The "AvaloniaStatsTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#11308]
**Describe the bug**
```
2>C:\Users\Administrator\.nuget\packages\avalonia.buildservices\0.0.12\buildTransitive\Avalonia.BuildServices.targets(9,9): Error MSB4018 : The "AvaloniaStatsTask" task failed unexpectedly.
System.IO.IOException: The semaphore timeout period has expired.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at Avalonia.Telemetry.AvaloniaStatsTask.ConnectToPipe()
   at Avalonia.Telemetry.AvaloniaStatsTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**To Reproduce**

Build solution.

**Expected behavior**

No error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview8

**Additional context**

**Comment by timunie** [comment]
@DragRedSim which Avalonia version? if 11.0 preview8, please check latest nightly. I'd like to know if that helps in your situation.

**Comment by danwalmsley** [comment]
> 

thats fixed in latest releases, can you confirm in Preview 8 that issue no longer presents?

**Comment by DamianSuess** [comment]
I'm running into this issue after upgrading Prism.Avalonia to v11.0.0-Preview 8.
