### ISSUE TITLE
I am now receiving this error upon application startup. Seems to occur during the first attempt to interact with the application from mouse over to button click and sometimes even further into the application. The error msg and stack varies. How can we track this down.

### ISSUE THREAD

**Issue by KyleC69** [AvaloniaUI/Avalonia#11351]
Internal Exception thrown upon startup.  The error msg and stack varies. How can we track this down.

_Originally posted by @KyleC69 in https://github.com/AvaloniaUI/Avalonia/issues/2063#issuecomment-1546500190_

**Comment by KyleC69** [comment]
Exception thrown: 'System.ObjectDisposedException' in Avalonia.Base.dll: 'Cannot access a disposed object.'
   at Avalonia.Utilities.RefCountable.RefCounter.AddRef()
   at Avalonia.Utilities.RefCountable.Ref`1.Clone()
   at Avalonia.Rendering.SceneGraph.VisualNode.Clone(IVisualNode parent)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.CloneScene()
   at Avalonia.Rendering.DeferredRenderer.UpdateScene()
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.X11.X11Window.DoPaint()
   at Avalonia.X11.X11Window.<EnqueuePaint>b__121_0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Threading.Dispatcher.RunJobs()
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ScraperOne.Program.Main(String[] args) in /storage/Repos/ScraperRepos/ScraperOne/Program.cs:line 47

**Comment by maxkatz6** [comment]
This issue was fixed in 11.0 previews, as SceneGraph/DeferredRenderer don't exist there anymore.
