### ISSUE TITLE
Click property is not implemented

### ISSUE THREAD

**Issue by aarroyoc** [AvaloniaUI/Avalonia#1153]
My program crash when you try to use the Click property in a Button:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> OmniXaml.LoadException: Error loading XAML: OmniXaml.ParseException: Cannot find a property named "Click" in the type Avalonia.Controls.Button
```

XAML file:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="AvaloniaAppTemplate">
	<StackPanel HorizontalAlignment="Center">
		<Button Click="OnClick" Content="Hola"></Button>
	</StackPanel>
</Window>
```

**Comment by jkoritzinsky** [comment]
What version of Avalonia are you using? Our latest release (v0.5.1) doesn't support binding to events, but our nightlies (v0.5.2-alpha*) do. We switched our XAML parser in between to one that supports binding to events.

**Comment by AdrianArroyoCalle** [comment]
Oh, I see. I'm using the latest release from NuGet (v0.5.1). When is expected to release the next version?

**Comment by BlackDragonBE** [comment]
I'm still getting errors in the XAML designer when I try to use the Button Click property with version 0.6.1.

Here's the XAML:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MarkdownToRWGUI">

  <StackPanel Orientation="Vertical" HorizontalAlignment="Center" MaxWidth="400" Width="300">
    <TextBlock Text="{Binding Greeting}"></TextBlock>
    <TextBox Text="{Binding Name}"></TextBox>
    <Button Content="Click me!" Click="OnButtonClicked"></Button> 
    <TextBlock Text="{Binding Result}"></TextBlock>
  </StackPanel>
</Window>
```

Here's the event:

```
        public void OnButtonClicked(object sender, RoutedEventArgs args)
        {
            var context = DataContext as HelloViewModel;
            context.Result = "Hi " + context.Name + " !";
        }
```

The designer crashes and shows me this:

```
Portable.Xaml.XamlObjectWriterException: Could not convert object 'OnButtonClicked' (of type System.String) to {clr-namespace:System;assembly=mscorlib}EventHandler({clr-namespace:Avalonia.Interactivity;assembly=Avalonia.Interactivity}RoutedEventArgs): Referenced value method OnButtonClicked in type Avalonia.Controls.Window indicated by event System.EventHandler`1[[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Interactivity, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null]] was not found ---> Portable.Xaml.XamlObjectWriterException: Referenced value method OnButtonClicked in type Avalonia.Controls.Window indicated by event System.EventHandler`1[[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Interactivity, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null]] was not found
   at Portable.Xaml.ComponentModel.EventConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
```

The weird thing is that it actually works if I run the app, but it's super annoying that I can't use the designer preview anymore now.
Any solution?

**Comment by jkoritzinsky** [comment]
The designer issue is from the lack of support for the x:Class directive. I believe there is already an issue for that, so I'm going to close this issue.

**Comment by tewarid** [comment]
Is that #1282?

**Comment by jkoritzinsky** [comment]
Yeah it falls into that. It can be done on its own though.
