### ISSUE TITLE
System.InvalidOperationException: "Neither DBus nor GTK are available on the system" with preview 11 under Windows 11 WSL Ubuntu 22.04 and FileDialog

### ISSUE THREAD

**Issue by martin-honnen** [AvaloniaUI/Avalonia#11554]
With version 10 of Avalonia I was trying to use OpenFileDialog but run (under Windows 11 WSL Ubuntu 22.04 x64 Linux) into https://github.com/AvaloniaUI/Avalonia/issues/8622. The comments there suggest the issue should be fixed in preview 11 so I tried to adapt my code to 11.0.0-preview8 but I am running into a different exception: 

```
Unhandled exception. System.InvalidOperationException: Neither DBus nor GTK are available on the system
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.EnsureStorageProvider() in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 32
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options) in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 37
   at Avalonia.Controls.Platform.SystemDialogImpl.ShowFileDialogAsync(FileDialog dialog, Window parent) in /_/src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs:line 29
```

**To Reproduce**

1. Use code like
```
        private async Task<string> LoadFileIntoEditor(TextEditor editor, string title, string filter, string name)
        {
            var openFileDialog = new OpenFileDialog();

            openFileDialog.Title = title;

            openFileDialog.AllowMultiple = false;

            openFileDialog.Filters = new List<FileDialogFilter>
            {
                new FileDialogFilter() { Extensions = filter.Split(";").ToList(), Name = name }
            };

            var files = await openFileDialog.ShowAsync(this);
```
in codebehind and build for Linux x64. Then try to run it there, the `var files = await openFileDialog.ShowAsync(this);` gives
```
Unhandled exception. System.InvalidOperationException: Neither DBus nor GTK are available on the system
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.EnsureStorageProvider() in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 32
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options) in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 37
   at Avalonia.Controls.Platform.SystemDialogImpl.ShowFileDialogAsync(FileDialog dialog, Window parent) in /_/src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs:line 29
   at ProjectName.Views.MainWindow.LoadFileIntoEditor(TextEditor editor, String title, String filter, String name) in C:\Users\username\source\repos\SolutionName\ProjectName\Views\MainWindow.axaml.cs:line 136
```

**Expected behavior**
I hoped to get a file dialog up, as it works with running under Windows or Mac.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Windows 11 22H2, `wsl --version` gives
```
>wsl --version
WSL-Version: 1.2.5.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.51
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.22621.1778
```
Ubuntu is Ubuntu 22.04 , WSL version 2.

**Additional context**
The rest of the GUI features seem to work fine under Windows WSL Ubuntu Linux.

I file this as a new bug as https://github.com/AvaloniaUI/Avalonia/issues/8622 didn't seem to accept comments but says "Please let us know if it's still a problem in 11.0 previews.".

**Comment by maxkatz6** [comment]
Have you installed gtk or freedesktop dependencies on the machine? It's not installed by default on WSL.  
If not, then it is expected behavior and error is clear.

**Comment by martin-honnen** [comment]
If it is the expected behaviour with default WSL then close it, sorry about any misunderstanding
Any clue or pointer or link as to what "install gtk or freedesktop dependencies" means for WSL Ubuntu nevertheless appreciated.

**Comment by martin-honnen** [comment]
So `sudo apt install gedit -y` seems one way, it appears, to install GTK dependencies.
