### ISSUE TITLE
Path Control: Portable.Xaml.XamlObjectWriterException 

### ISSUE THREAD

**Issue by GrimR3** [AvaloniaUI/Avalonia#1157]
This sample crashes with Avalonia but renders a hamburger menu in a circle on WPF. Does Avalonia Path control not support SVG style paths?

**XAML**
```XAML
<Grid>
            <Path Fill="Black" Data="M16,32C7,32,0,25,0,16S7,0,16,0s16,7,16,16S25,32,16,32z M16,2C8,2,2,8,2,16s6,14,14,14  s14-6,14-14S24,2,16,2z"/>
            <Path Fill="Black" Data="M22,12H10c-1,0-1-0-1-1s0-1,1-1h12c1,0,1,0,1,1S23,12,22,12z"/>
            <Path Fill="Black" Data="M22,17H10c-1,0-1-0-1-1s0-1,1-1h12c1,0,1,0,1,1S23,17,22,17z"/>
            <Path Fill="Black" Data="M22,22H10c-1,0-1-0-1-1s0-1,1-1h12c1,0,1,0,1,1S23,22,22,22z"/>
</Grid>
```

**Stack Trace**
```StackTrace
Portable.Xaml.XamlObjectWriterException occurred
  HResult=0x80131500
  Message=Could not convert object 'M16,32C7,32,0,25,0,16S7,0,16,0s16,7,16,16S25,32,16,32z M16,2C8,2,2,8,2,16s6,14,14,14  s14-6,14-14S24,2,16,2z' (of type System.String) to {clr-namespace:Avalonia.Media;assembly=Avalonia.Visuals}Geometry: Unexpected path command 'S'.
  Source=Avalonia.Markup.Xaml
  StackTrace:
   at Portable.Xaml.XamlObjectWriterInternal.GetCorrectlyTypedValue(XamlMember xm, XamlType xt, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteValue(Object value)
   at Portable.Xaml.XamlObjectWriter.WriteValue(Object value)
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Object obj)
   at Project.Core.MainWindow.InitializeComponent() in C:\Users\user\Source\Repos\Project\Project - Avalonia\MainWindow.xaml.cs:line 17
   at Project.Core.MainWindow..ctor() in C:\Users\user\Source\Repos\Project - Project\MainWindow.xaml.cs:line 11

Inner Exception 1:
InvalidDataException: Unexpected path command 'S'.
```
svg path reference https://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands

**Comment by kekekeks** [comment]
I think we only support WPF-style geometry syntax:
https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Visuals.UnitTests/Media/PathMarkupParserTests.cs#L59

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/PathMarkupParser.cs

**Comment by kekekeks** [comment]
Or we might simply not support `S` command, which should be easier to fix

**Comment by GrimR3** [comment]
Looks like lack of support for `s` command.
`PathMarkupParser.cs` defines these commands:
```C#
 private static readonly Dictionary<char, Command> Commands = new Dictionary<char, Command> 
         { 
             { 'F', Command.FillRule }, 
             { 'M', Command.Move }, 
             { 'L', Command.Line }, 
             { 'H', Command.HorizontalLine }, 
             { 'V', Command.VerticalLine }, 
             { 'C', Command.CubicBezierCurve }, 
             { 'A', Command.Arc }, 
             { 'Z', Command.Close }, 
         }; 
```
While WPF supports those plus a few additional commands. 
Such as:
Q - Quadratic Bezier Curve
S - Smooth Cubic Bezier Curve
T - Smooth Quadratic Bezier Curve 
https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/path-markup-syntax

WPF's Path syntax is similar to the SVG Path syntax and the XPS document's abbreviated path syntax.
https://www.w3.org/TR/SVG/paths.html (SVG Syntax)
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-388.pdf#page=100 (XPS Standard)

I use SVGs from the https://thenounproject.com/ for  icons and UI elements in WPF and hoped to do the same with Avalonia.

**Comment by kekekeks** [comment]
Our `StreamGeometry` has support for cubic and quadratic bezier curves, so we only need to fix the parser.
