### ISSUE TITLE
System.InvalidOperationException: Cannot change source while update is in progress

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#11617]
**Describe the bug**

```
System.InvalidOperationException: Cannot change source while update is in progress.
   at Avalonia.Controls.Selection.SelectionModel`1.SetSource(IEnumerable value) in .\Avalonia\src\Avalonia.Controls\Selection\SelectionModel.cs:line 282
   at Avalonia.Controls.Selection.InternalSelectionModel.SetSource(IEnumerable value) in .\Avalonia\src\Avalonia.Controls\Selection\InternalSelectionModel.cs:line 121
   at Avalonia.Controls.Selection.InternalSelectionModel.Update(IEnumerable source, Optional`1 selectedItems) in .\Avalonia\src\Avalonia.Controls\Selection\InternalSelectionModel.cs:line 75
   at Avalonia.Controls.Primitives.SelectingItemsControl.EndUpdating() in .\Avalonia\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 1245
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnDataContextEndUpdate() in .\Avalonia\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 546
   at Avalonia.StyledElement.DataContextNotifying(StyledElement element, Boolean updateStarted) in .\Avalonia\src\Avalonia.Base\StyledElement.cs:line 768
   at Avalonia.StyledElement.DataContextNotifying(AvaloniaObject o, Boolean updateStarted) in .\Avalonia\src\Avalonia.Base\StyledElement.cs:line 737
   at Avalonia.PropertyStore.PropertyNotifying.Dispose() in .\Avalonia\src\Avalonia.Base\PropertyStore\PropertyNotifying.cs:line 26
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 795
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.InheritedValueChanged(AvaloniaProperty property, EffectiveValue oldValue, EffectiveValue newValue) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 793
   at Avalonia.PropertyStore.ValueStore.SetInheritanceParent(AvaloniaObject newParent) in .\Avalonia\src\Avalonia.Base\PropertyStore\ValueStore.cs:line 395
   at Avalonia.AvaloniaObject.set_InheritanceParent(AvaloniaObject value) in .\Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 77
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in .\Avalonia\src\Avalonia.Base\StyledElement.cs:line 477
   at Avalonia.Controls.Primitives.PopupFlyoutBase.HideCore(Boolean canCancel) in .\Avalonia\src\Avalonia.Controls\Flyouts\PopupFlyoutBase.cs:line 179
   at Avalonia.Controls.Primitives.PopupFlyoutBase.OnPopupClosed(Object sender, EventArgs e) in .\Avalonia\src\Avalonia.Controls\Flyouts\PopupFlyoutBase.cs:line 384
   at Avalonia.Controls.Primitives.Popup.CloseCore() in .\Avalonia\src\Avalonia.Controls\Primitives\Popup.cs:line 728
   at Avalonia.Controls.Primitives.Popup.Close() in .\Avalonia\src\Avalonia.Controls\Primitives\Popup.cs:line 505
   at Avalonia.Controls.Primitives.Popup.WindowLostFocus() in .\Avalonia\src\Avalonia.Controls\Primitives\Popup.cs:line 899
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in .\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.AppWndProc.cs:line 705
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in .\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.WndProc.cs:line 23
```

**To Reproduce**

1. Run "ControlCatalog.NetCore"
2. Click on "Settings" ➝Switch "Normal" to "Minimized"

**Expected behavior**
The app does not crash

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.0-rc1.1

**Comment by grokys** [comment]
Unable to repro this either on current master or the `11.0.0-rc1.1` tag. Is there anything else I need to do to repro?

**Comment by rstm-sf** [comment]
Sorry, but I do exactly what is described in the issue. Even after updating to [the latest master](https://github.com/AvaloniaUI/Avalonia/commit/8e63c12fee30b392a66cb0e6add7a791057bcd4c), the behavior same.

Similar behavior for other switch — "Maximazed" to "Minimized"

<details>

  <summary>dotnet --info</summary>

  ```sh
  .NET SDK:
  Version:   7.0.202
  Commit:    6c74320bc3

  Runtime Environment:
  OS Name:     Windows
  OS Version:  10.0.19045
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   .\dotnet\sdk\7.0.202\

  Host:
    Version:      7.0.4
    Architecture: x64
    Commit:       0a396acafe

  .NET SDKs installed:
    6.0.406 [.\dotnet\sdk]
    7.0.101 [.\dotnet\sdk]
    7.0.202 [.\dotnet\sdk]

  .NET runtimes installed:
    Microsoft.AspNetCore.App 6.0.14 [.\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.1 [.\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.4 [.\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 6.0.14 [.\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.1 [.\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.4 [.\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 6.0.14 [.\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [.\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [.\dotnet\shared\Microsoft.WindowsDesktop.App]

  Other architectures found:
    None

  Environment variables:
    Not set

  global.json file:
    .\Avalonia\global.json
```


</details>

**Comment by rstm-sf** [comment]
On another system with windows 10 the same

**Comment by timunie** [comment]
@rstm-sf are you able to record a video of what exactly you have been clicking? maybe we don't understand exactly what to do.

**Comment by timunie** [comment]
EDIT: Now I see. You have to do one more step. Click Settings again after switching. Sorry.

**Comment by rabbitism** [comment]
I can reproduce as op said.

**Comment by afunc233** [comment]
in SelectionChanged event make Source change caused this problem

**Comment by workgroupengineering** [comment]
I encountered the same issue. I solved by correcting these lines

https://github.com/AvaloniaUI/Avalonia/blob/6a76df1bddddf40eb212544a03e1e832a619963d/src/Avalonia.Controls/Selection/SelectionModel.cs#L280

 as follows

```csharp
if (_operation?.UpdateCount > 0)
```

**Comment by afunc233** [comment]
> I encountered the same issue. I solved by correcting these lines
> 
> https://github.com/AvaloniaUI/Avalonia/blob/6a76df1bddddf40eb212544a03e1e832a619963d/src/Avalonia.Controls/Selection/SelectionModel.cs#L280
> 
> as follows
> 
> ```cs
> if (_operation?.UpdateCount > 0)
> ```

same as    [here](https://github.com/AvaloniaUI/Avalonia/blob/6a76df1bddddf40eb212544a03e1e832a619963d/src/Avalonia.Controls/Selection/SelectionModel.cs#L430)   ?

https://github.com/AvaloniaUI/Avalonia/blob/6a76df1bddddf40eb212544a03e1e832a619963d/src/Avalonia.Controls/Selection/SelectionModel.cs#L430
