### ISSUE TITLE
TryGetFolderFromPathAsync with empty folder path throws

### ISSUE THREAD

**Issue by alexhelms** [AvaloniaUI/Avalonia#11681]
**Describe the bug**
Calling `IStorageProvider.TryGetFolderFromPathAsync(string)` throws an `ArgumentException` when the string parameter is empty.

**To Reproduce**

1. Call `_storageProvider.TryGetFolderFromPathAsync(string.Empty)`

**Expected behavior**
I expected `TryGetFolderFromPathAsync` to return null if the path was empty since this is a "Try" function that returns a nullable object.

**Desktop:**

- OS: Windows 11
- Version 11 RC1.1

**Additional context**
Stack trace:

```
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at Avalonia.Platform.Storage.FileIO.StorageProviderHelpers.TryCreateBclStorageItem(String path) in /_/src/Avalonia.Base/Platform/Storage/FileIO/StorageProviderHelpers.cs:line 13
   at Avalonia.Platform.Storage.StorageProviderExtensions.TryGetFolderFromPathAsync(IStorageProvider provider, String folderPath) in /_/src/Avalonia.Base/Platform/Storage/StorageProviderExtensions.cs:line 34
```

**Comment by maxkatz6** [comment]
This change makes sense if anybody can pick it up.

**Comment by timunie** [comment]
@alexhelms are you willing to provide a PR for it?
