### ISSUE TITLE
SubpixelAntialias - System.ArgumentException

### ISSUE THREAD

**Issue by Varmod** [AvaloniaUI/Avalonia#11776]
**Describe the bug**
While taking a screenshot of the current window using the RenderTargetBitmap it has a very small chance of crashing with a 
'System.ArgumentException' occurred in Avalonia.Base.dll: 'An item with the same key has already been added. Key: SubpixelAntialias'
I've noticed that also the main composite renderer throws the same exception but it is able to continue afterwards.

**To Reproduce**
I was unsuccessful in reproducing the issue in a separate project, if I manage to I will attach the project later.

**Expected behavior**
No exception.

**Desktop (please complete the following information):**

- OS: custom Linux , Windows 11
- Version 11.0-rc1

**Additional context**
This is issue is more prevalent on the embedded device I'm running Avalonia on, however it also happens on my windows machine. 

**Screenshot code stacktrace:**
An unhandled exception of type 'System.ArgumentException' occurred in Avalonia.Base.dll: 'An item with the same key has already been added. Key: SubpixelAntialias
Stack trace:
at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Avalonia.Skia.GlyphRunImpl.GetTextBlob(RenderOptions renderOptions) in /_/src/Skia/Avalonia.Skia/GlyphRunImpl.cs:line 126
at Avalonia.Skia.DrawingContextImpl.DrawGlyphRun(IBrush foreground, IGlyphRunImpl glyphRun) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 537
at Avalonia.Media.TextFormatting.ShapedTextRun.Draw(DrawingContext drawingContext, Point origin) in /_/src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs:line 70
at Avalonia.Media.TextFormatting.TextLineImpl.Draw(DrawingContext drawingContext, Point lineOrigin) in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 100
at Avalonia.Media.TextFormatting.TextLayout.Draw(DrawingContext context, Point origin) in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 249
at Avalonia.Controls.TextBlock.RenderCore(DrawingContext context) in /_/src/Avalonia.Controls/TextBlock.cs:line 586
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 112
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, Visual visual, Rect clipRect) in /_/src/Avalonia.Base/Rendering/ImmediateRenderer.cs:line 127
at Avalonia.Media.Imaging.RenderTargetBitmap.Render(Visual visual) in /_/src/Avalonia.Base/Media/Imaging/RenderTargetBitmap.cs:line 50
...

**CompositingRenderer stacktrace:**
[Visual]Exception when rendering: 'System.ArgumentException: An item with the same key has already been added. Key: SubpixelAntialias
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Avalonia.Skia.GlyphRunImpl.GetTextBlob(RenderOptions renderOptions) in /_/src/Skia/Avalonia.Skia/GlyphRunImpl.cs:line 88
   at Avalonia.Skia.DrawingContextImpl.DrawGlyphRun(IBrush foreground, IGlyphRunImpl glyphRun) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 542
   at Avalonia.Rendering.Composition.Server.CompositorDrawingContextProxy.DrawGlyphRun(IBrush foreground, IGlyphRunImpl glyphRun) in /_/src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs:line 89
   at Avalonia.Rendering.Composition.Drawing.Nodes.RenderDataGlyphRunNode.Invoke(RenderDataNodeRenderContext& context) in /_/src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataGlyphRunNode.cs:line 20
   at Avalonia.Rendering.Composition.Drawing.Nodes.RenderDataPushNode.Invoke(RenderDataNodeRenderContext& context) in /_/src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataNodes.cs:line 100
   at Avalonia.Rendering.Composition.Drawing.ServerCompositionRenderData.Render(IDrawingContextImpl context) in /_/src/Avalonia.Base/Rendering/Composition/Drawing/ServerCompositionRenderData.cs:line 116
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawListVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawListVisual.cs:line 50
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Controls/BorderVisual.cs:line 64
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Controls.CompositionBorderVisual.ServerBorderVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Controls/BorderVisual.cs:line 64
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionContainerVisual.RenderCore(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs:line 23
   at Avalonia.Rendering.Composition.Server.ServerCompositionVisual.Render(CompositorDrawingContextProxy canvas, Rect currentTransformedClip) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs:line 90
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs:line 205
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore() in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs:line 203'(ServerCompositor #49982922)

**Comment by Gillibald** [comment]
Are you rendering to the RenderTargetBitmap on a background thread?

**Comment by Varmod** [comment]
I'm rendering on the UI thread

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/11777 should prevent that issue
