### ISSUE TITLE
GlyphRun - Index was outside the bounds of the array on Android

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#11877]
**Describe the bug**
Run my app on Android mobile device.
Use Material.Avalonia.
When print  in textbox app crush.
 

**To Reproduce**

Run app on android. Print to textbox.

**Expected behavior**
text in textbox

- OS: Android 13. OneUI 5.1
- Version 11.0.0-rc1

Exception: Index was outside the bounds of the array.
```
   at Avalonia.Media.GlyphRun.CreateGlyphRunMetrics() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 643
   at Avalonia.Media.GlyphRun.get_Metrics() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 164
   at Avalonia.Media.GlyphRun.get_BaselineOrigin() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 171
   at Avalonia.Media.GlyphRun.CreateGlyphRunImpl() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 828
   at Avalonia.Media.GlyphRun.get_PlatformImpl() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 220
   at Avalonia.Media.GlyphRun.get_InkBounds() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 158
   at Avalonia.Media.TextFormatting.TextLineImpl.CreateLineMetrics() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1287
   at Avalonia.Media.TextFormatting.TextLineImpl.FinalizeLine() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1000
   at Avalonia.Media.TextFormatting.TextFormatterImpl.PerformTextWrapping(List`1 textRuns, Boolean canReuseTextRunList, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, FlowDirection resolvedFlowDirection, TextLineBreak currentLineBreak, FormattingObjectPool objectPool) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 889
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 72
   at Avalonia.Media.TextFormatting.TextLayout.CreateTextLines() in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 638
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, FlowDirection flowDirection, Double maxWidth, Double maxHeight, Double lineHeight, Double letterSpacing, Int32 maxLines, IReadOnlyList`1 textStyleOverrides) in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 69
   at Avalonia.Controls.Presenters.TextPresenter.CreateTextLayoutInternal(Size constraint, String text, Typeface typeface, IReadOnlyList`1 textStyleOverrides) in /_/src/Avalonia.Controls/Presenters/TextPresenter.cs:line 321
   at Avalonia.Controls.Presenters.TextPresenter.CreateTextLayout() in /_/src/Avalonia.Controls/Presenters/TextPresenter.cs:line 551
   at Avalonia.Controls.Presenters.TextPresenter.get_TextLayout() in /_/src/Avalonia.Controls/Presenters/TextPresenter.cs:line 248
   at Avalonia.Controls.Presenters.TextPresenter.MoveCaretToTextPosition(Int32 textPosition, Boolean trailingEdge) in /_/src/Avalonia.Controls/Presenters/TextPresenter.cs:line 610
   at Avalonia.Controls.Presenters.TextPresenter.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Controls/Presenters/TextPresenter.cs:line 840
   at Avalonia.AvaloniaObject.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 649
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/Animation/Animatable.cs:line 185
   at Avalonia.AvaloniaObject.RaisePropertyChanged[Int32](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 700
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, Int32 value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 235
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetAndRaise(ValueStore owner, IValueEntry value, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 60
   at Avalonia.PropertyStore.ValueStore.ReevaluateEffectiveValue(AvaloniaProperty property, EffectiveValue current, IValueEntry changedValueEntry, Boolean ignoreLocalValue) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 850
   at Avalonia.PropertyStore.ValueStore.OnBindingValueChanged(IValueEntry entry, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 419
   at Avalonia.PropertyStore.BindingEntryBase`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<SetValue>g__Execute|38_0(BindingEntryBase`2 instance, BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 162
   at Avalonia.PropertyStore.BindingEntryBase`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetValue(BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 171
   at Avalonia.PropertyStore.BindingEntryBase`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(Object value) in /_/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs:line 99
   at Avalonia.Data.TemplateBinding.PublishValue() in /_/src/Avalonia.Base/Data/TemplateBinding.cs:line 175
   at Avalonia.Data.TemplateBinding.TemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Data/TemplateBinding.cs:line 212
   at Avalonia.AvaloniaObject.RaisePropertyChanged[Int32](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 705
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, Int32 value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 235
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetCurrentValueAndRaise(ValueStore owner, StyledProperty`1 property, Int32 value) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 82
   at Avalonia.PropertyStore.ValueStore.SetCurrentValue[Int32](StyledProperty`1 property, Int32 value) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 205
   at Avalonia.AvaloniaObject.SetCurrentValue[Int32](StyledProperty`1 property, Int32 value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 405
   at Avalonia.Controls.TextBox.OnSelectionEndChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/TextBox.cs:line 484
   at Avalonia.Controls.TextBox.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Controls/TextBox.cs:line 854
   at Avalonia.AvaloniaObject.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 649
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/Animation/Animatable.cs:line 185
   at Avalonia.AvaloniaObject.RaisePropertyChanged[Int32](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 700
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, Int32 value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 235
   at Avalonia.PropertyStore.EffectiveValue`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, Int32 value) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 74
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[Int32](StyledProperty`1 property, Int32 value) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 220
   at Avalonia.PropertyStore.ValueStore.SetValue[Int32](StyledProperty`1 property, Int32 value, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 196
   at Avalonia.AvaloniaObject.SetValue[Int32](StyledProperty`1 property, Int32 value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 336
   at Avalonia.Controls.TextBox.set_SelectionEnd(Int32 value) in /_/src/Avalonia.Controls/TextBox.cs:line 474
   at Avalonia.Controls.TextBoxTextInputMethodClient.TextEditable_SelectionChanged(Object sender, EventArgs e) in /_/src/Avalonia.Controls/TextBoxTextInputMethodClient.cs:line 118
   at Avalonia.Android.InputEditable.EndBatchEdit() in /_/src/Android/Avalonia.Android/InputEditable.cs:line 115
   at Avalonia.Android.Platform.SkiaPlatform.AvaloniaInputConnection.EndBatchEdit() in /_/src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs:line 488
   at Android.Views.InputMethods.BaseInputConnection.n_EndBatchEdit(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.InputMethods.BaseInputConnection.cs:line 474
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_Z(_JniMarshal_PP_Z callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 44
   ```

**Comment by CreateLab** [comment]
has no idea, clear cache in Rider, clear cache in device. can't reproduce bug. If u dont need this bug, close it

**Comment by Gillibald** [comment]
Without some reproducible sequence there is not much I can do

**Comment by CreateLab** [comment]
As I say before, cant reproduse, clearing all caches fix problem, just report this bug.
Close it.

**Comment by Natestah** [comment]
I am working on some AvalonEdit, when I made fonts available I get this exception selecting "Marlett" font
