### ISSUE TITLE
NullReferenceException after calling `CompositionDrawingSurface.UpdateAsync`

### ISSUE THREAD

**Issue by jgcodes2020** [AvaloniaUI/Avalonia#12097]
**Describe the bug**

**To Reproduce**
1. Clone commit `d3bff15` of [jgcodes2020/GpuInteropTest](https://github.com/jgcodes2020/GpuInteropTest)
2. Run the program
3. Click the button
4. Internal exception occurs. I have no idea how to debug it.

**Expected behavior**
Either the texture uploads correctly, or a more descriptive exception giving a clear clue as to where my code might be wrong.

**Exception stacktrace**
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Skia.ImmutableBitmap..ctor(SKImage image) in /_/src/Skia/Avalonia.Skia/ImmutableBitmap.cs:line 45
   at Avalonia.Skia.GlSkiaImportedImage.TakeSnapshot() in /_/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaExternalObjectsFeature.cs:line 142
   at Avalonia.Skia.GlSkiaImportedImage.SnapshotWithAutomaticSync() in /_/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaExternalObjectsFeature.cs:line 198
   at Avalonia.Rendering.Composition.Server.ServerCompositionDrawingSurface.UpdateWithAutomaticSync(CompositionImportedGpuImage image) in /_/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawingSurface.cs:line 55
   at Avalonia.Rendering.Composition.CompositionDrawingSurface.<>c__DisplayClass5_0.<UpdateAsync>b__0() in /_/src/Avalonia.Base/Rendering/Composition/CompositionDrawingSurface.cs:line 54
   at Avalonia.Rendering.Composition.Compositor.<>c__DisplayClass40_0.<InvokeServerJobAsync>b__0() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 232
   at Avalonia.Rendering.Composition.Compositor.<>c__DisplayClass41_0`1.<InvokeServerJobAsync>b__0() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 243
--- End of stack trace from previous location ---
   at GpuInteropTest.Controls.Helpers.GLBufferQueue.DisplayNext(GLQueuableImage img) in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Controls/Helpers/GLBufferQueue.cs:line 60
   at GpuInteropTest.Controls.Helpers.GLBufferQueue.DisplayNext(GLQueuableImage img) in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Controls/Helpers/GLBufferQueue.cs:line 66
   at GpuInteropTest.Controls.Helpers.GLBufferQueue.<SwapBuffers>b__16_0() in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Controls/Helpers/GLBufferQueue.cs:line 75
   at GpuInteropTest.Controls.Helpers.GLBufferQueue.SwapBuffers(PixelSize size) in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Controls/Helpers/GLBufferQueue.cs:line 75
   at GpuInteropTest.Controls.IndependentGLControl.SwapBuffers() in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Controls/IndependentGLControl.cs:line 181
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at GpuInteropTest.Views.MainWindow.SwapBuffers() in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/Views/MainWindow.axaml.cs:line 49
   at GpuInteropTest.ViewModels.MainWindowViewModel.OpenGLRun() in /home/jgcodes/Documents/Code/C#/GpuInteropTest/GpuInteropTest/ViewModels/MainWindowViewModel.cs:line 59
```

**Desktop (please complete the following information):**

- OS: Linux (ArcoLinux, based on Arch Linux)
- Kernel version: Linux 6.4.1-arch2-1
- Desktop environment: KDE 5.27.6

**Additional context**
- **NOTE 1**: Adding print statements reveals that the import completes successfully, so there's nothing fishy going on there.

**Comment by kekekeks** [comment]
Skia refuses to use your imported your texture. Unfortunately it doesn't give us any meaningful diagnostics why. Check if normal openglcontrolbase works on your machine

**Comment by jgcodes2020** [comment]
> Check if normal openglcontrolbase works on your machine

It does. Latest commit on that repository now has a working example.

**Comment by jgcodes2020** [comment]
Any updates?

**Comment by timunie** [comment]
@jgcodes2020 if you really want to help us solving this issue, it is really welcome. I guess the best bet is to clone Avalonia source and copy your not working code into `samples -> Sandbox`. Then debug sandbox and if you are lucky. you may find the NRE in source. From there, we may get an idea what to do to fix it. If you get an idea, how to solve the issue, a PR is also welcome

Thanks for your support 👍

**Comment by jgcodes2020** [comment]
The debugging seems to take me here:
https://github.com/AvaloniaUI/Avalonia/blob/9226ef3b222692a92a899e07cd6946b02af44b75/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaExternalObjectsFeature.cs#L140-L142

For some reason `SKSurface.Snapshot` is allowed to return null

**Comment by jgcodes2020** [comment]
@kekekeks alright, so it turns out it's an issue with the OpenGL context being current in two threads at once.

Here's what the fix looked like:
https://github.com/jgcodes2020/GpuInteropTest/blob/9399e7a9ff5e8137c7cb2d1726592daa6d6f2961/GpuInteropTest/Views/MainWindow.axaml.cs#L38

Basically, I had to clear the OpenGL context in the render thread before swapping buffers and re-establish it afterwards.

**Comment by timunie** [comment]
@jgcodes2020 do you think this issue can be closed?

**Comment by jgcodes2020** [comment]
Yeah, but when you guys get to documenting the GPU interop API, document this kind of thread-safety stuff please.

**Comment by timunie** [comment]
good point. open an issue in the docs repo and link this one.
