### ISSUE TITLE
ListBox ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#12185]
Upgrading to v11.0.0

I got a ListBox showing playlist names, and each item expands into another ListBox containing the content.

When I select something in the 2nd ListBox, then change selection in the 1st (which clears the 2nd selection), it throws

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.ItemsSourceView`1.GetAt(Int32 index) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 336
   at Avalonia.Controls.ItemsSourceView`1.get_Item(Int32 index) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 329
   at Avalonia.Controls.Selection.SelectedItems`1.GetEnumerator()+MoveNext() in /_/src/Avalonia.Controls/Selection/SelectedItems.cs:line 81
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e) in /_/src/Avalonia.Controls/Selection/InternalSelectionModel.cs:line 224
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(Operation operation, Boolean raisePropertyChanged) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 714
   at Avalonia.Controls.Selection.SelectionModel`1.EndBatchUpdate() in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 210
   at Avalonia.Controls.Selection.SelectionModel`1.BatchUpdateOperation.Dispose() in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 773
   at Avalonia.Controls.Selection.SelectionModel`1.set_SelectedIndex(Int32 value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 75
   at Avalonia.Controls.Selection.SelectionModel`1.Avalonia.Controls.Selection.ISelectionModel.set_SelectedItem(Object value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 166
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedItem(Object value) in /_/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 233
   at Avalonia.Controls.Primitives.SelectingItemsControl.<>c.<.cctor>b__25_4(SelectingItemsControl o, Object v) in /_/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 65
   at Avalonia.DirectProperty`2.InvokeSetter(AvaloniaObject instance, BindingValue`1 value) in /_/src/Avalonia.Base/DirectProperty.cs:line 125
   at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, BindingValue`1 value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 775
   at Avalonia.PropertyStore.DirectUntypedBindingObserver`1.OnNext(Object value) in /_/src/Avalonia.Base/PropertyStore/DirectUntypedBindingObserver.cs:line 49
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Data.Core.BindingExpression.InnerListener.OnNext(Object value) in /_/src/Avalonia.Base/Data/Core/BindingExpression.cs:line 368
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Data.Core.ExpressionObserver.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionObserver.cs:line 313
   at Avalonia.Data.Core.ExpressionNode.NextValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 92
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 127
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 95
   at Avalonia.Data.Core.Plugins.PropertyAccessorBase.PublishValue(Object value) in /_/src/Avalonia.Base/Data/Core/Plugins/PropertyAccessorBase.cs:line 61
   at Avalonia.Data.Core.Plugins.DataValidationBase.InnerValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/Plugins/DataValidationBase.cs:line 73
   at Avalonia.Data.Core.Plugins.PropertyAccessorBase.PublishValue(Object value) in /_/src/Avalonia.Base/Data/Core/Plugins/PropertyAccessorBase.cs:line 61
   at Avalonia.Data.Core.Plugins.InpcPropertyAccessorPlugin.Accessor.SendCurrentValue() in /_/src/Avalonia.Base/Data/Core/Plugins/InpcPropertyAccessorPlugin.cs:line 178
```

Thrown from here

```
private void Source_CollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
{
    if (_suspendCollectionChanged) { return;}
    
    CollectionChanged?.Invoke(this, e);
    var pos = CurrentPosition;
    _currentPosition = -1;
    OnPropertyChanged(nameof(CurrentPosition));
    OnPropertyChanged(nameof(CurrentItem)); // <-- Exception Thrown here
    SetAndCoercePosition(pos);
}
```

It's a non-fatal error, so the app can still continue; but that error shouldn't be here.

**Comment by timunie** [comment]
Can you file a minimal sample to reproduce?

**Comment by timunie** [comment]
Ping @mysteryx93 please provide a minimum sample and double check with latest master or 11.0.4 

🙏 thx

**Comment by stepangovorko** [comment]
the problem also occurs on 11.0.5 (but there is no stable repro)
https://youtrack.jetbrains.com/issue/DTRC-30252

**Comment by timunie** [comment]
Several fixes went into virtualization. Having no test repro we can't check if this specific case was also fixed. Will close this issue for now, please ping me if you can share a reproduction sample.
