### ISSUE TITLE
CalendarDatePicker Binding SelectedDate by TemplateBinding in TwoWay not deal with invalid value fail, caused crash

### ISSUE THREAD

**Issue by Flithor** [AvaloniaUI/Avalonia#12252]
AvaloniaUI Version: 0.10.21
Runtime: .NET Core 3.1

Use `CalendarDatePicker` in `ControlTemplate` and binding `SelectedDate` by `TemplateBinding` with `TwoWay` Mode on DateTime property, clear the text make crash.
```
<ControlTemplate>
    <CalendarDatePicker Width="150" SelectedDate="{TemplateBinding StartDate, Mode=TwoWay}" />
</ControlTemplate>
```
```
public static readonly DirectProperty<MYCONTROL, DateTime> StartDateProperty =
    AvaloniaProperty.RegisterDirect<MYCONTROL, DateTime>(nameof(StartDate),
        o => o.StartDate, (o, v) => o.StartDate = v, defaultBindingMode: BindingMode.TwoWay);

private DateTime startDate = DateTime.Today.AddDays(-7);

/// <summary>The date of begin</summary>
public DateTime StartDate
{
    get { return startDate; }
    set { SetAndRaise(StartDateProperty, ref startDate, value); }
}
```
```
 ---> System.ArgumentException: Invalid value for Property 'StartDate': '' ((null))
   at Avalonia.DirectPropertyBase`1.RouteSetValue(IAvaloniaObject o, Object value, BindingPriority priority) in /_/src/Avalonia.Base/DirectPropertyBase.cs:line 167
   at Avalonia.AvaloniaObjectExtensions.SetValue(IAvaloniaObject target, AvaloniaProperty property, Object value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 525
   at Avalonia.Data.TemplateBinding.System.IObserver<System.Object>.OnNext(Object value) in /_/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs:line 109
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 70
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 763
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 678
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 703
   at Avalonia.Controls.CalendarDatePicker.set_SelectedDate(Nullable`1 value) in /_/src/Avalonia.Controls/Calendar/CalendarDatePicker.cs:line 330
   at Avalonia.Controls.CalendarDatePicker.SetSelectedDate() in /_/src/Avalonia.Controls/Calendar/CalendarDatePicker.cs:line 1029
   at Avalonia.Controls.CalendarDatePicker.OnLostFocus(RoutedEventArgs e) in /_/src/Avalonia.Controls/Calendar/CalendarDatePicker.cs:line 586
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_1(InputElement x, RoutedEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 215
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 145
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 94
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 100
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 102
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 173
   at Avalonia.Input.FocusManager.SetFocusedElement(IFocusScope scope, IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Input/FocusManager.cs:line 142
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Input/FocusManager.cs:line 70
   at Avalonia.Input.FocusManager.OnPreviewPointerPressed(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Input/FocusManager.cs:line 236
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 94
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 100
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 95
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 264
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 170
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 91
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 36
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 515
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 526
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 66
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 121
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at **MYRPOJECT**.Program.Main(String[] args) in [MYRPOJECT_DIRECTORY]\Program.cs:line 32
   --- End of inner exception stack trace ---
```

Workaround is that make property type allows null, but this is not our intended design.

**Comment by timunie** [comment]
make your property nullable or use a fallback value.

**Comment by timunie** [comment]
idea: 

```cs
public class NullableFallbackConverter : IValueConverter
{
    public static NullableFallbackConverter Instance { get; } = new();
    
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        // return just the value. We are only interested in convert back
        return value;
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        // Return the parameter if value was null. Parameter must be our fallback value. 
        return value ?? parameter;
    }
} 
```

```xml
 <ControlTemplate>
     <CalendarDatePicker Width="150" 
                         SelectedDate="{TemplateBinding StartDate, 
                                                        Mode=TwoWay, 
                                                        Converter={x:Static local:NullableFallbackConverter.Instance}, 
                                                        ConverterParameter={x:Static sys:DateTime.Now}}" />
 </ControlTemplate>
```

**Comment by PentaPinguino** [comment]
Can I ask what are you expecting? What should `StartDate` be when the `CalendarDatePicker` is empty? Shouldn't `StartDate` be a `DateTime?` in order to be able to contain a null value?

Please note that `DateTime` is not a nullable type.

**Comment by Flithor** [comment]
> make your property nullable or use a fallback value.

I know but that not in design.
Take a step back and say that should not crash when the binding value conversion fails.

**Comment by timunie** [comment]
what should happen instead in compiled binding situation in your opinion?

**Comment by Flithor** [comment]
> what should happen instead in compiled binding situation in your opinion?

If not set user convert and use the default converter, it should notify user as a validation error, not crash.
