### ISSUE TITLE
Clicking on a button while having keyboard focus causes null reference error

### ISSUE THREAD

**Issue by daniel-cistech** [AvaloniaUI/Avalonia#12422]
**Describe the bug**

**To Reproduce**
Create a new avalonia project for android.
Update to the latest libraries 11.0.2 (works with 11.0.0)
Update the MainViewModel.cs to have
```

 [ObservableProperty] public string _IPAddress = "239.1.1.5";

    [RelayCommand]
    public void Connect()
    {}

```
And the MainView.axaml to have
```
    <Grid RowDefinitions="Auto,*,Auto">
  <Expander Header="Connection Details" IsExpanded="True" HorizontalAlignment="Stretch">
    <ScrollViewer>
      <StackPanel>
        <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
        <TextBox Text="{Binding IPAddress}" HorizontalAlignment="Center" VerticalAlignment="Center"/>
        <Button Command="{Binding Connect}" Content="Connect" />
      </StackPanel>
    </ScrollViewer>
  </Expander>
    </Grid>
```
Deploy to an actual android device (do not see it in emulator)
Click inside the text field so the keyboard comes up
Click on the button

**Expected behavior**
The keyboard goes away and the button can then be clicked

Stack Trace:
```
   at Avalonia.Android.AndroidInputMethod`1[[Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.ViewImpl, Avalonia.Android, Version=11.0.2.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].OnSelectionChanged()
   at Avalonia.Android.AndroidInputMethod`1[[Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.ViewImpl, Avalonia.Android, Version=11.0.2.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].OnBatchEditedEnded()
   at Avalonia.Android.Platform.SkiaPlatform.AvaloniaInputConnection.EndBatchEdit()
   at Android.Views.InputMethods.BaseInputConnection.n_EndBatchEdit(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.InputMethods.BaseInputConnection.cs:line 474
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_Z(_JniMarshal_PP_Z callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 44
```

**Screenshots**

Android 12.0 - API 31 on a Samsung phone

**Additional context**
It seems this was introduced with https://github.com/AvaloniaUI/Avalonia/commit/24e2321bf1c15dec876fbc67f176d00c11953bf0 I believe

Works with 11.0.0

**Comment by timunie** [comment]
@daniel-cistech as it seems you found the root cause, if you have an idea how to fix, a PR is welcome.

**Comment by IanRawley** [comment]
I was having the same problem while playing around with DialogHost on an emulator.  I think this has already been fixed, as updating to the latest nightly got rid of it.  Specifically PR #12415

**Comment by timunie** [comment]
@daniel-cistech can you try out nightly builds and confirm if the issue can be closed?

**Comment by daniel-cistech** [comment]
> @daniel-cistech can you try out nightly builds and confirm if the issue can be closed?

Can confirm that this is working as expected in the latest nightly.
