### ISSUE TITLE
Exception: "should not happen" in Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/Avalonia#1268]
I'm using the latest nightly, build 4218.
The following style, placed in App.paml:

```
<Style Selector="Button.icon">
  <Setter Property="Template">
    <ControlTemplate>
      <ContentPresenter
                    Background="{TemplateBinding Background}"
                    BorderBrush="{TemplateBinding BorderBrush}"
                    BorderThickness="{TemplateBinding BorderThickness}"
                    ContentTemplate="{TemplateBinding ContentTemplate}"
                    Padding="{TemplateBinding Padding}"
                    TextBlock.Foreground="{TemplateBinding Foreground}"
                    HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                    VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}">
        <Path Fill="Red" Width="32" Height="32"
              Data="M88.008,462V50l335.984,206.002L88.008,462z" RenderTransformOrigin="1,1">
          <Path.RenderTransform>
            <TransformGroup>
              <ScaleTransform ScaleX="0.0585" ScaleY="0.0585" />
            </TransformGroup>
          </Path.RenderTransform>
        </Path>
      </ContentPresenter>
    </ControlTemplate>
  </Setter>
</Style>
```

Causes the following exception:

```
System.Exception: should not happen
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__27.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__17.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__14.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__27.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__17.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__14.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__27.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__17.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__14.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadCollectionItems>d__29.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__27.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__17.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__14.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadCollectionItems>d__29.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__28.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__27.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__17.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__14.MoveNext()
   at Portable.Xaml.XamlXmlParser.<Parse>d__12.MoveNext()
   at Portable.Xaml.XamlXmlReader.Read()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Object obj)
   at ICEPlayer.UI.App.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at ICEPlayer.UI.Windows.Program.Main(String[] args) in <path>\ICEPlayer\ICEPlayer.UI.Windows\Program.cs:line 21
```

**Comment by jkoritzinsky** [comment]
I don't think we allow you to set the `TextBlock.Foreground` property on a non `TextBlock` instance. That would explain the exception with the stack trace. I think this is just another example of bad error messages in Portable.Xaml.

**Comment by jkoritzinsky** [comment]
Ok then this might be another bug somewhere. Most likely it's just an invalid member that I'm not seeing.

**Comment by grokys** [comment]
This now seems to work so closing.
