### ISSUE TITLE
ListBox: System.ArgumentOutOfRangeException: 'Index was out of range. 

### ISSUE THREAD

**Issue by manuc66** [AvaloniaUI/Avalonia#13089]
## Describe the bug
I have a ListBox with an ItemSource bound to a collection ReadOnlyObservableCollection<T> that is bound to a SourceList where filtering, sorting and throttling have been applied.

## To Reproduce

1. Go to to the last element in the list
2. Toggle a filter that reduce the number of element in the list
4. The application then crash with the following exception:
````
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.ReadOnlyCollection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.ItemsSourceView`1.GetAt(Int32 index)
   at Avalonia.Controls.Selection.SelectedItems`1.<GetEnumerator>d__13.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(Operation operation, Boolean raisePropertyChanged)
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSourceCollectionChangeFinished()
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakEventSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged incc, NotifyCollectionChangedEventArgs args, WeakReference`1[] listeners)
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at ImgTagFanOut.Program.Main(String[] args) in C:\Users\Emmanuel\source\ImgTagFanOut\ImgTagFanOut\Program.cs:line 19

````

## Expected behavior
Application does not crash

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/5827164/a4e72c38-717a-4237-a92c-8b7369517fc2)

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.4

**Comment by maxkatz6** [comment]
> SourceList

Do you update your collection/source list from the non-UI threads? It might be a reason.

**Comment by timunie** [comment]
@manuc66 please show us your filter code

**Comment by manuc66** [comment]
Thanks, and sorry, indeed the issue was the lack of 
`    .ObserveOn(RxApp.MainThreadScheduler) `
