### ISSUE TITLE
A bug with TransitioningContentControl and grid

### ISSUE THREAD

**Issue by deryaza** [AvaloniaUI/Avalonia#13509]
If you take ReactiveUIDemo and apply this patch
[0001-1.patch](https://github.com/AvaloniaUI/Avalonia/files/13267189/0001-1.patch)

This fill fail with the following exception:

<details>

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.Grid.ArrangeOverride(Size arrangeSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Grid.cs:line 526
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 660
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 589
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 660
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 589
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Controls.TransitioningContentControl.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\TransitioningContentControl.cs:line 59
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.StackPanel.ArrangeChild(Control child, Rect rect, Size panelSize, Orientation orientation) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\StackPanel.cs:line 355
   at Avalonia.Controls.StackPanel.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\StackPanel.cs:line 341
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 660
   at Avalonia.Controls.Presenters.ScrollContentPresenter.ArrangeWithAnchoring(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 472
   at Avalonia.Controls.Presenters.ScrollContentPresenter.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 401
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.Grid.ArrangeOverride(Size arrangeSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Grid.cs:line 549
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 660
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 589
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.LayoutHelper.ArrangeChildInternal(Layoutable child, Size availableSize, Thickness padding) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutHelper.cs:line 91
   at Avalonia.Layout.LayoutHelper.ArrangeChild(Layoutable child, Size availableSize, Thickness padding) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutHelper.cs:line 86
   at Avalonia.Controls.Decorator.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Decorator.cs:line 60
   at Avalonia.Controls.Primitives.VisualLayerManager.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\Primitives\VisualLayerManager.cs:line 161
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 669
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 721
   at Avalonia.Controls.WindowBase.ArrangeCore(Rect finalRect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Controls\WindowBase.cs:line 296
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\Layoutable.cs:line 418
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 334
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.Arrange(Layoutable control) in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 322
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 272
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 240
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 151
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Layout\LayoutManager.cs:line 111
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Media\MediaContext.cs:line 198
   at Avalonia.Media.MediaContext.RenderCore() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Media\MediaContext.cs:line 135
   at Avalonia.Media.MediaContext.Render() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Media\MediaContext.cs:line 116
   at Avalonia.Threading.DispatcherOperation.InvokeCore() in C:\Users\デリャザ\source\repos\Avalonia\src\Avalonia.Base\Threading\DispatcherOperation.cs:line 274
```

</details>

Some notes:

1) First page must have scrollviewer and a scroll bar appeared (exceed the window height)
2) second page must access RowDefinitions or ColumnDefinitions of the Grid in WhenActivated
3) Disabling page transitions removes this problem

**Comment by timunie** [comment]
@deryaza can you check with the recent build from #13518 ? The build ID should be 41664 of the avalonia-all feed.

**Comment by deryaza** [comment]
@timunie no, I think I have a different issue (tested, doesn't fix it)

**Comment by deryaza** [comment]
A bit different, but a smaller repro (I guess InvalidateArrange is culprit):

```c#
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace ReactiveUIDemo
{
    public class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            var panel = this.FindControl<StackPanel>("Panel");
            var button = this.FindControl<Button>("Button");
            var button2 = this.FindControl<Button>("Button2");
            var grid = new Grid();
            grid.Loaded += (sender, args) => _ = ((Grid)sender).RowDefinitions;
            button.Click += (sender, args) =>
            {
                panel.Children.Add(grid);
            };
            button2.Click += (sender, args) =>
            {
                grid.InvalidateArrange();
            };
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

```xaml
<Window
    Title="AvaloniaUI ReactiveUI Demo"
    x:Class="ReactiveUIDemo.MainWindow"
    x:DataType="vm:MainWindowViewModel"
    xmlns="https://github.com/avaloniaui"
    xmlns:rxui="using:Avalonia.ReactiveUI"
    xmlns:vm="using:ReactiveUIDemo.ViewModels"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <StackPanel x:Name="Panel">
        <Button x:Name="Button">crash</Button>
        <Button x:Name="Button2">crash2</Button>
    </StackPanel>
</Window>
```

**Comment by laolarou726** [comment]
> A bit different, but a smaller repro (I guess InvalidateArrange is culprit in TransitioningContentControl):
> 
> 
> 
> ```c#
> 
> using Avalonia.Controls;
> 
> using Avalonia.Markup.Xaml;
> 
> 
> 
> namespace ReactiveUIDemo
> 
> {
> 
>     public class MainWindow : Window
> 
>     {
> 
>         public MainWindow()
> 
>         {
> 
>             this.InitializeComponent();
> 
>             var panel = this.FindControl<StackPanel>("Panel");
> 
>             var button = this.FindControl<Button>("Button");
> 
>             var button2 = this.FindControl<Button>("Button2");
> 
>             var grid = new Grid();
> 
>             grid.Loaded += (sender, args) => _ = ((Grid)sender).RowDefinitions;
> 
>             button.Click += (sender, args) =>
> 
>             {
> 
>                 panel.Children.Add(grid);
> 
>             };
> 
>             button2.Click += (sender, args) =>
> 
>             {
> 
>                 grid.InvalidateArrange();
> 
>             };
> 
>         }
> 
> 
> 
>         private void InitializeComponent()
> 
>         {
> 
>             AvaloniaXamlLoader.Load(this);
> 
>         }
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> ```xaml
> 
> <Window
> 
>     Title="AvaloniaUI ReactiveUI Demo"
> 
>     x:Class="ReactiveUIDemo.MainWindow"
> 
>     x:DataType="vm:MainWindowViewModel"
> 
>     xmlns="https://github.com/avaloniaui"
> 
>     xmlns:rxui="using:Avalonia.ReactiveUI"
> 
>     xmlns:vm="using:ReactiveUIDemo.ViewModels"
> 
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
> 
>     <StackPanel x:Name="Panel">
> 
>         <Button x:Name="Button">crash</Button>
> 
>         <Button x:Name="Button2">crash2</Button>
> 
>     </StackPanel>
> 
> </Window>
> 
> ```

In your repro it doesn't involve with TCC, so this is a bug from Grid not TCC right?

**Comment by deryaza** [comment]
@laolarou726 it is, but the flow is kind of weird so I can only imagine it in TransitioningContentControl. Maybe it is part of bigger problem like "is it a correct assumption that  MeasureOverride always follows by ArrangeOverride and ArrangeOverride always preceeds MeasureOverride (which brings problems in this example)" but idk, not really into inners of avalonia itself.

**Comment by electro-logic** [comment]
We hit this class of crash in production on 12.1.1 and can answer the open question above concretely: **arrange without a preceding measure is reachable from ordinary user code plus a window resize** — no `InvalidateArrange` call involved. The arming sequence is deterministic:

1. A `Grid` that has **no row/column definitions** gets measured — `MeasureOverride` takes the `_extData == null` simple path, so the definition caches are never populated.
2. User code then calls `grid.RowDefinitions.Clear()` (a natural "reset the table" idiom when the row source is empty). The property **getter lazily creates `_extData`**, and `AvaloniaList<T>.Clear()` on an already-empty list is guarded by `if (Count > 0)` — it raises no `CollectionChanged`, so **nothing calls `InvalidateMeasure`**.
3. The grid is now measure-valid with `_extData != null` but `_extData.DefinitionsU/V` still null (only `MeasureOverride`'s `ValidateDefinitionsUStructure`/`ValidateDefinitionsVStructure` populate them).
4. Any later arrange with changed bounds enters the `_extData != null` branch of `ArrangeOverride` and throws NRE at the first `DefinitionsV.Count`. A window resize is exactly such an arrange: under a `ScrollViewer` the grid's measure constraint is `(Infinity, Infinity)` and never changes, so resizes re-arrange it without ever re-measuring — the state never heals.

In an app this looks like: a panel builds its `Grid` empty, the first data tick finds no rows and calls `RowDefinitions.Clear()`, and the next window resize kills the process. Reproduced on **both the X11 and the native Wayland backend** (Wayland trips it spontaneously because compositor configure batches run a synchronous layout pass via `HandleResized`; X11 needs a manual resize in the armed state).

Two fix directions that would close this particular path, in case they help:
- have the `RowDefinitions`/`ColumnDefinitions` getters call `InvalidateMeasure()` when they lazily create `_extData` on a grid that has already been measured; or
- have `ArrangeOverride` detect `_extData.DefinitionsU/V == null` (created-but-never-measured) and fall back to the simple path / trigger a measure instead of dereferencing.

Workaround for anyone else hitting it: never let a `Grid` be measured while definition-less and then touch its definition collections without actually changing them — e.g. build columns/header before first layout and grow/shrink rows incrementally instead of `Clear()`-and-rebuild.
