### ISSUE TITLE
Crash when opening FilePicker

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#13613]
## Describe the bug
When user opens a FilePicker he gets the crash with the following error message:

```
System.Runtime.InteropServices.COMException: Feil parameter [0x80004005] ---> System.Runtime.InteropServices.COMException: GetDisplayName failed [0x80070057]
   at Avalonia.Win32.Win32Com.Impl.__MicroComIShellItemProxy.GetDisplayName(UInt32 sigdnName)
   at Avalonia.Win32.Win32StorageProvider.GetAbsoluteFilePath(IShellItem shellItem)
   at Avalonia.Win32.Win32StorageProvider.<>c__DisplayClass13_0.<ShowFilePicker>b__0()
   --- End of inner exception stack trace ---
   at Avalonia.Win32.Win32StorageProvider.<>c__DisplayClass13_0.<ShowFilePicker>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Win32.Win32StorageProvider.<OpenFilePickerAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grunt.OutputAdapters.PowerPoint.UI.FileLocator.<Locate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grunt.UI.Services.ChangeDataConnectionGroupFilePathService.<Change>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Altua.Library.Asynchronous.Async.RunTaskInBackground[TResult](Func`1 func)
   at Grunt.UI.Commands.ChangeDataConnectionGroupFileCommandHandler.Execute(ChangeDataConnectionGroupFileCommand command, ICommandContext ctx)
   at Altua.Oak.Core.Behavior.TrackMetricsCommandDecorator`1.Execute(TCommand command, ICommandContext commandContext)
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
```

## To Reproduce
Sadly no repro

## Environment 
- OS:Windows

**Comment by timunie** [comment]
@Takoooooo I haven't seen this on Windows 11 or 10 ever 🤔 Is this an older Windows version?

**Comment by workgroupengineering** [comment]
There is precedent issue https://github.com/AvaloniaUI/Avalonia/issues/3272

HRESULT `0x80070057`  meaning invalid parameter.

The following line probably failed because IShellItem does not have a valid file system path. See [docs](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-sigdn).

https://github.com/AvaloniaUI/Avalonia/blob/0567a6dbe7dc122ba90e019320708e0cbc51b635/src/Windows/Avalonia.Win32/Win32StorageProvider.cs#L196C85-L196C85

We should probably use [System.ItemFolderPathDisplay](https://learn.microsoft.com/en-us/windows/win32/properties/props-system-itemfolderpathdisplay)
