### ISSUE TITLE
Crash when pasting into the TextBox fails

### ISSUE THREAD

**Issue by BAndysc** [AvaloniaUI/Avalonia#13716]
## Describe the bug
It looks like the clipboard methods on Windows can fail and the TextBox doesn't handle the exception in any way thus the application crashes. 

```
System.TimeoutException: Timeout opening clipboard.
   at Avalonia.Win32.ClipboardImpl.OpenClipboard() in //src/Windows/Avalonia.Win32/ClipboardImpl.cs:line 30
   at Avalonia.Win32.ClipboardImpl.GetTextAsync() in //src/Windows/Avalonia.Win32/ClipboardImpl.cs:line 52
   at Avalonia.Controls.TextBox.Paste() in /_/src/Avalonia.Controls/TextBox.cs:line 723
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__1280(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in //src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 217
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in //src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in //src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args)
   ```

## To Reproduce
No idea how to reproduce. An user reported the issue.

## Expected behavior
I think it is okay if the textbox try catches the clipboard method and ignores when it fails?

## Environment 

- OS: Windows
- Avalonia-Version: 0.10.22 (but after a brief look at the TextBox and Clipboard implementations in 11.0.x it looks like nothing has really changed to prevent this exception?)

**Comment by timunie** [comment]
> I think it is okay if the textbox try catches the clipboard method and ignores when it fails?

@Gillibald what do you think, would that be okay? I think yes, but not sure. Should not be really harmful? 🤔
 
@BAndysc if you want to file a PR with a try-catch, that would be welcome I think.
