### ISSUE TITLE
Binding to static method throws InvalidProgramException when executed

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#13776]
## Describe the bug
Binding to static method throws InvalidProgramException when executed.

## To Reproduce
1. Create new MVVM project
2. Add `public static void DoTheThing() { }` to `MainWindowViewModel`
3. Add to MainWindow.xaml: `<Button Command="{Binding DoTheThing}" Content="Do The Thing" />`
4. Run and click button for exception.

## Expected behavior
Work without exception if supported or a compiler error if this scenario is not supported by design.

## Environment 

- OS: Win10
- Avalonia-Version: 11.0.5 and nightly (11.1.999-cibuild0042496-beta)

## Additional context
This scenario was unintentionally discovered by another user when a Rider suggestion added `static` to the method for them. In their case, the app failed silently. I couldn't reproduce the scenario here though.

## Stack Trace
`AvaloniaStaticMethodBinding` is the project name.

```
System.InvalidProgramException
  HResult=0x8013153A
  Message=Common Language Runtime detected an invalid program.
  Source=AvaloniaStaticMethodBinding
  StackTrace:
   at CompiledAvaloniaXaml.XamlIlTrampolines.AvaloniaStaticMethodBinding:AvaloniaStaticMethodBinding.ViewModels.MainWindowViewModel+DoTheThing_0!CommandExecuteTrampoline(Object , Object )
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaStaticMethodBinding.Program.Main(String[] args) in C:\Users\Steve\source\repos\AvaloniaStaticMethodBinding\AvaloniaStaticMethodBinding\Program.cs:line 13
```

**Comment by maxkatz6** [comment]
It is by design that bindings do not work with static members. But I can see it to be extended one day.

**Comment by maxkatz6** [comment]
Maybe better would be to support x:Static conversion from method to command.

**Comment by timunie** [comment]
@maxkatz6 I changed the labels as I think this is a feature request rather than a bug.

**Comment by Countjest** [comment]
what's the alternative? (running into this first time coding)

**Comment by stevemonaco** [comment]
> what's the alternative? (running into this first time coding)

Don't bind to static methods. Use non-static methods, commands, converters, or markupextensions. All four can call into static methods to do the actual work.

**Comment by TheBoxyBear** [comment]
Would it not be possible to handle this case in an analyzer? The IDE gives the incorrect suggestion to turn the method static if it uses no members. An analyser could in theory identity the presence of `RelayCommandAttribute` and suppress the suggestion.
