### ISSUE TITLE
`org.freedesktop.DBus.Error.UnknownMethod` When window close.

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#13863]
## Describe the bug
throw a `Tmds.DBus.Protocol.DBusException` when window close.

## To Reproduce

1. Open a window
2. Close window

## Expected behavior
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service)
 ---> Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   --- End of inner exception stack trace ---
```

## Environment 

- OS: Linux ubuntu22..04
- Avalonia-Version: 11.0.6

## Additional context
```
coloryr@coloryr:~$ gdbus call --system --dest org.freedesktop.DBus \
           --object-path /org/freedesktop/DBus  \
           --method org.freedesktop.DBus.ListNames
(['org.freedesktop.DBus', ':1.7', 'org.freedesktop.timesync1', ':1.8', ':1.9', 'org.freedesktop.systemd1', 'org.freedesktop.ModemManager1', 'org.freedesktop.NetworkManager', 'org.freedesktop.oom1', 'net.hadess.PowerProfiles', 'org.freedesktop.resolve1', 'org.freedesktop.RealtimeKit1', 'org.freedesktop.Accounts', ':1.60', ':1.61', ':1.62', ':1.40', ':1.63', ':1.41', ':1.64', ':1.42', 'org.freedesktop.PolicyKit1', ':1.20', ':1.65', 'org.bluez', ':1.21', ':1.66', ':1.44', ':1.22', 'org.freedesktop.PackageKit', ':1.45', ':1.23', ':1.176', 'net.hadess.SwitcherooControl', ':1.24', ':1.25', ':1.48', 'com.redhat.NewPrinterNotification', ':1.49', 'com.redhat.PrinterDriversInstaller', ':1.218', 'org.gnome.DisplayManager', 'org.freedesktop.Avahi', 'org.freedesktop.UDisks2', 'fi.w1.wpa_supplicant1', 'org.freedesktop.login1', ':1.72', 'org.freedesktop.ColorManager', ':1.50', ':1.51', ':1.74', ':1.52', ':1.30', ':1.75', ':1.31', ':1.184', ':1.76', ':1.54', ':1.10', ':1.32', ':1.185', ':1.11', ':1.33', ':1.186', ':1.56', 'org.freedesktop.UPower', ':1.34', ':1.12', ':1.220', ':1.57', ':1.0', ':1.13', ':1.58', ':1.36', ':1.1', ':1.59', ':1.2', ':1.3', ':1.16', ':1.39', ':1.4', ':1.5', ':1.303', ':1.6'],)
```

**Comment by jangernert** [comment]
Same issue when closing a context menu:

Net8.0, Avalonia 11.0.6 & Fedora Workstation 39

11.0.5 is fine.

**Comment by maxkatz6** [comment]
Can you check nightly builds? If there is any difference

**Comment by Coloryr** [comment]
same in `11.1.999-cibuild0042781-beta`

**Comment by maxkatz6** [comment]
Hi @affederaffe @jmacato are you familiar with this error?

**Comment by Sputnik24** [comment]
Same issue here.
.NET 8.0, Ubuntu 23.04, Avalonia 11.0.6

**Comment by affederaffe** [comment]
Unfortunately I didn't/don't have that much free-time at the moment, but I'll try to take a look soon :tm: (hopefully during the christmas break)

**Comment by affederaffe** [comment]
Should be fixed in master.
