### ISSUE TITLE
EglInterface failing to Initialize

### ISSUE THREAD

**Issue by Anthonywolfe** [AvaloniaUI/Avalonia#13955]
## Describe the bug
Looking into it, it appears eglGetProcAddress shouldn't be used to acquire core functions (see https://mail.gnome.org/archives/commits-list/2012-June/msg04882.html )
And in my case it appears due to me being on a Arm64 platform using a Mali 400 GPU implemented via LibMali it returns 0 for core functions while dlopen / dlsym returns working pointers.

I wrote a quick test to verify this was the case as well
```cs
                unsafe
                {
                    const int EGL_OPENGL_ES_API = 0x30A0;
                    fixed (byte* pFile = "libEGL.so.1"u8)
                    fixed (byte* pBindSymbol = "eglBindAPI"u8)
                    fixed (byte* pErrorSymbol = "eglGetError"u8)
                    fixed (byte* pGetProcAddressSymbol = "eglGetProcAddress"u8)
                    {
                        var pEGL_Handle = LibC.dlopen(pFile, LibC.RTLD_NOW);
                        var pBindHandle = LibC.dlsym(pEGL_Handle, pBindSymbol);
                        var pErrorHandle = LibC.dlsym(pEGL_Handle, pErrorSymbol);
                        var pGetProcAddressHandle = LibC.dlsym(pEGL_Handle, pGetProcAddressSymbol);

                        var EGL_Status = ((delegate* unmanaged[Stdcall]<int, int>)pBindHandle)(EGL_OPENGL_ES_API);
                        var pEGL_ErrorHandle = ((delegate* unmanaged[Stdcall]<byte*, IntPtr>)pGetProcAddressHandle)(pErrorSymbol);
                    }
                }
```

And this is the results I got from it
<HTML>
<body>

  | Name | Value | Type
-- | -- | -- | --
▶ | pFile | 0x0000ffff389c3658 | byte*
▶ | pBindSymbol | 0x0000ffff389c3664 | byte*
▶ | pErrorSymbol | 0x0000ffff389c368d | byte*
▶ | pGetProcAddressSymbol | 0x0000ffff389c3646 | byte*
  | pEGL_Handle | 0x0000aaaab63c77d0 | void*
  | pBindHandle | 0x0000ffbe908322b0 | void*
  | pErrorHandle | 0x0000ffbe90831e78 | void*
  | pGetProcAddressHandle | 0x0000ffbe90832bb8 | void*
  | EGL_Status | 0x00000001 | int
  | pEGL_ErrorHandle | 0x0000000000000000 | System.IntPtr
  | EGL_OPENGL_ES_API | 0x000030a0 | int

</body>
</HTML>

## Expected behavior

Not receiving this error when executing in DRM mode
```
An unhandled exception of type 'System.EntryPointNotFoundException' occurred in Avalonia.OpenGL.dll: '_addr_GetError'
Stack trace:
 >   at Avalonia.OpenGL.Egl.EglInterface.Initialize(Func`2 getProcAddress) in /_/src/Avalonia.OpenGL/DevGenerators/Generator.GetProcAddressInitializationGenerator/globalAvalonia.OpenGL.Egl.EglInterface.cs:line 163
 >   at Avalonia.OpenGL.Egl.EglInterface..ctor(Func`2 getProcAddress) in /_/src/Avalonia.OpenGL/Egl/EglInterface.cs:line 14
 >   at Avalonia.LinuxFramebuffer.Output.DrmOutput.Init(DrmCard card, DrmResources resources, DrmConnector connector, DrmModeInfo modeInfo) in /_/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs:line 177
 >   at Avalonia.LinuxFramebuffer.Output.DrmOutput..ctor(String path, Boolean connectorsForceProbe, DrmOutputOptions options) in /_/src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs:line 82
 >   at LinuxFramebufferPlatformExtensions.StartLinuxDrm(AppBuilder builder, String[] args, String card, Boolean connectorsForceProbe, DrmOutputOptions options, IInputBackend inputBackend) in /_/src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs:line 168
 ```

## Environment 

- OS: Petalinux 5.15.36-xilinx-v2022.2
- OGL Driver: https://github.com/Xilinx/mali-userspace-binaries
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
cc @kekekeks
