### ISSUE TITLE
ListBox virtualization causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#1395]
Hard to reproduce. Only happens with ListBox containing items of DIFFERENT height. Never happens with items of the same height. 100 items in the list and fast up&down scrolling causes this exception.

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at ReactiveUI.ReactiveDerivedCollection`1.get_Item(Int32 index)
   at ReactiveUI.ReactiveList`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value)
   at Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Utilities.DeferredSetter`2.<>c__DisplayClass9_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass46_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass45_0`1.<SetAndRaise>b__0(Object val, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`2.SetAndNotify[TValue](TProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.OnPointerWheelChanged(PointerWheelEventArgs e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseWheel(IMouseDevice device, IInputRoot root, Point p, Vector delta, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.MonoMac.TopLevelImpl.OnInput(RawInputEventArgs args)
   at Avalonia.MonoMac.WindowBaseImpl.OnInput(RawInputEventArgs args)
   at Avalonia.MonoMac.TopLevelImpl.TopLevelView.MouseEvent(NSEvent ev, RawMouseEventType type)
   at Avalonia.MonoMac.TopLevelImpl.TopLevelView.ScrollWheel(NSEvent theEvent)
   at MonoMac.ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(IntPtr receiver, IntPtr selector, IntPtr arg1)
   at MonoMac.AppKit.NSApplication.SendEvent(NSEvent theEvent)
   at Avalonia.MonoMac.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
```

**Comment by x2bool** [comment]
Seems to be Macos-only issue

**Comment by donandren** [comment]
occasionally the issue is happening on windows with items with the same height or different. What i've noticed as sequence to repro (very very hard to repro):

- Scroll to end
- Add few items after the last
- Scroll to end
- Add few items in the middle of the visible part
- Scroll to end
- remove few items in the visible part
- Scroll to end ArgumentOutOfRangeException (if not repeat again and again until eventually exception) 

With this sequence it's not certain that you'll get repro, sometimes you need tens or hundred more repeats of this sequence. I can't find repeatable reproduction, but found the reason for the issue.

I've found one way to mitigate the behavior in unit test, as once was able to reproduce it with VirtualizationDemo app and able to debug and see that virtualizationPanel.PixelOffset was > 0 before scroll to end when this issue happened while debugging and made an unit test #1962 that reproduces the issue.
