### ISSUE TITLE
No Display after Sleep/Wake-up on Windows 10

### ISSUE THREAD

**Issue by J31why** [AvaloniaUI/Avalonia#14077]
## Describe the bug
The application runs fine before the system enters sleep mode, but upon wake-up, there is no visible output on the screen. Avalonia 0.10.21 works fine.

## To Reproduce

1. Run the new project application
2. Turn the system to sleep mode.
3. Wake up the system

## Expected behavior
Display on the screen after wake up system

## Screenshots
before:
![1](https://github.com/AvaloniaUI/Avalonia/assets/44184684/1a1d73b3-9631-4615-895a-05a857cee0b3)
after:
![2](https://github.com/AvaloniaUI/Avalonia/assets/44184684/2c391974-4aeb-4338-b38a-073ab3ad7da8)

## Environment

- OS: Windows 10.0.19045.3803
- Avalonia-Version: 11.0.6

**Comment by maxkatz6** [comment]
Please collect logs from the app (`.LogToTrace(Verbose)` in the BuildAvaloniaApp method). And maybe Windows Event Viewer might have something useful.

**Comment by J31why** [comment]
These are the app logs, but I couldn't find any relevant errors in the Windows Event Viewer.
```
LogHost: Initializing to normal mode (.cctor)
[Property]Set 'ActualThemeVariant' to 'Light' with priority 'LocalValue'(App #51810644)
[Property]Set 'RequestedThemeVariant' to 'Default' with priority 'LocalValue'(App #51810644)
[Property]Set 'ActualThemeVariant' to 'Light' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'Icon' to 'Avalonia.Controls.WindowIcon' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'Title' to 'Avalonia_sleeptest_11' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'Content' to 'Avalonia.Controls.TextBlock' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'HorizontalAlignment' to 'Center' with priority 'LocalValue'(TextBlock #58577354)
[Property]Set 'VerticalAlignment' to 'Center' with priority 'LocalValue'(TextBlock #58577354)
[Property]Set 'Color' to 'White' with priority 'LocalValue'(SolidColorBrush #47145209)
[Property]Set 'Color' to 'White' with priority 'LocalValue'(SolidColorBrush #60665573)
[Property]Set 'Color' to 'Black' with priority 'LocalValue'(SolidColorBrush #9119245)
[Property]Set 'NameScope' to 'Avalonia.Controls.NameScope' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'DataContext' to 'Avalonia_sleeptest_11.ViewModels.MainWindowViewModel' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'IsVisible' to 'True' with priority 'LocalValue'(MainWindow #16246551)
[Control] Creating control template (MainWindow #16246551)
[Property]Set 'IsHitTestVisible' to 'False' with priority 'LocalValue'(Border #47063234)
[Property]Set 'IsHitTestVisible' to 'False' with priority 'LocalValue'(Border #20915929)
[Property]Set 'Background' to 'Transparent' with priority 'LocalValue'(Panel #54025633)
[Property]Set 'ZIndex' to '2147483548' with priority 'LocalValue'(ChromeOverlayLayer #58892473)
[Property]Set 'ChromeOverlayLayer' to 'Avalonia.Controls.Primitives.ChromeOverlayLayer' with priority 'LocalValue'(VisualLayerManager #60270212)
[Property]Set 'Child' to 'Avalonia.Controls.Presenters.ContentPresenter' with priority 'LocalValue'(VisualLayerManager #60270212)
[Visual] Attached to visual tree (Panel #47787675)
[Visual] Attached to visual tree (Border #47063234)
[Visual] Attached to visual tree (Border #20915929)
[Visual] Attached to visual tree (Panel #54025633)
[Visual] Attached to visual tree (VisualLayerManager #60270212)
[Visual] Attached to visual tree (ChromeOverlayLayer #58892473)
[Visual] Attached to visual tree (TitleBar #36936550)
[Property]Set 'Margin' to '0,0,0,0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Height' to '0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'IsVisible' to 'False' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Margin' to '0,0,0,0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Height' to '0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'IsVisible' to 'False' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Margin' to '0,0,0,0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Height' to '0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'IsVisible' to 'False' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Margin' to '0,0,0,0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Height' to '0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'IsVisible' to 'False' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Margin' to '0,0,0,0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'Height' to '0' with priority 'LocalValue'(TitleBar #36936550)
[Property]Set 'IsVisible' to 'False' with priority 'LocalValue'(TitleBar #36936550)
[Visual] Attached to visual tree (ContentPresenter #39070558)
[Property]Set 'Background' to '' with priority 'LocalValue'(Border #47063234)
[Layout]Measure requested '0, 0'(Border #47063234)
[Layout]Measure requested '0, 0'(Border #20915929)
[Layout]Measure requested '0, 0'(Panel #54025633)
[Layout]Measure requested '0, 0'(TitleBar #36936550)
[Layout]Measure requested '0, 0'(ChromeOverlayLayer #58892473)
[Visual] Attached to visual tree (TextBlock #58577354)
[Layout]Measure requested '141.6, 17.6'(TextBlock #58577354)
[Layout]Measure requested '141.6, 17.6'(ContentPresenter #39070558)
[Layout]Measure requested '141.6, 17.6'(VisualLayerManager #60270212)
[Layout]Measure requested '141.6, 17.6'(Panel #47787675)
[Layout]Measure requested '1521.6, 776'(MainWindow #16246551)
[Layout]Arrange to '0, 0, 1521.6, 776' (MainWindow #16246551)
[Layout]Arrange to '0, 0, 1521.6, 776' (Panel #47787675)
[Layout]Arrange to '0, 0, 1521.6, 776' (Border #47063234)
[Layout]Arrange to '0, 0, 1521.6, 776' (Border #20915929)
[Layout]Arrange to '0, 0, 1521.6, 776' (Panel #54025633)
[Layout]Arrange to '0, 0, 1521.6, 776' (VisualLayerManager #60270212)
[Layout]Arrange to '0, 0, 1521.6, 776' (ChromeOverlayLayer #58892473)
[Layout]Arrange to '0, 0, 1521.6, 776' (TitleBar #36936550)
[Layout]Arrange to '0, 0, 1521.6, 776' (ContentPresenter #39070558)
[Layout]Arrange to '0, 0, 1521.6, 776' (TextBlock #58577354)
[Layout]Started layout pass. To measure: '0' To arrange: '0'(LayoutManager #46067993)
[Layout]Layout pass finished in '00:00:00.0015622'(LayoutManager #46067993)
[Property]Set 'Width' to '1521.6' with priority 'LocalValue'(MainWindow #16246551)
[Layout] Invalidated measure (MainWindow #16246551)
[Property]Set 'Height' to '776' with priority 'LocalValue'(MainWindow #16246551)
[Layout]Started layout pass. To measure: '1' To arrange: '0'(LayoutManager #46067993)
[Layout]Measure requested '1521.6, 776'(MainWindow #16246551)
[Layout]Arrange to '0, 0, 1521.6, 776' (MainWindow #16246551)
[Layout]Layout pass finished in '00:00:00.0024938'(LayoutManager #46067993)
[Property]Set 'PointerOverElement' to 'Avalonia.Controls.Panel' with priority 'LocalValue'(MainWindow #16246551)
[Property]Set 'PointerOverElement' to '' with priority 'LocalValue'(MainWindow #16246551)
[Visual]Exception when rendering: 'System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Avalonia.Win32.DirectX.DirectXUnmanagedMethods.D3D11CreateDevice(IntPtr adapter, D3D_DRIVER_TYPE DriverType, IntPtr Software, UInt32 Flags, D3D_FEATURE_LEVEL[] pFeatureLevels, UInt32 FeatureLevels, UInt32 SDKVersion, IntPtr& ppDevice, D3D_FEATURE_LEVEL& pFeatureLevel, IntPtr* ppImmediateContext)
   at Avalonia.Win32.OpenGl.Angle.AngleWin32EglDisplay.CreateD3D11Display(Win32AngleEglInterface egl)
   at Avalonia.Win32.OpenGl.Angle.AngleWin32PlatformGraphics.CreateContext()
   at Avalonia.Rendering.PlatformRenderInterfaceContextManager.EnsureValidBackendContext()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.OpenGL.Egl.EglContext.get_Context()
   at Avalonia.OpenGL.Egl.EglContext.get_IsCurrent()
   at Avalonia.OpenGL.Egl.EglContext.EnsureCurrent()
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Skia.SurfaceRenderTarget.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.OpenGL.Egl.EglContext.get_Context()
   at Avalonia.OpenGL.Egl.EglContext.get_IsCurrent()
   at Avalonia.OpenGL.Egl.EglContext.EnsureCurrent()
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Skia.SurfaceRenderTarget.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
......

[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.OpenGL.Egl.EglContext.get_IsCurrent()
   at Avalonia.OpenGL.Egl.EglContext.EnsureCurrent()
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Skia.SurfaceRenderTarget.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.OpenGL.Egl.EglContext.get_IsCurrent()
   at Avalonia.OpenGL.Egl.EglContext.EnsureCurrent()
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Skia.SurfaceRenderTarget.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
......

[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EglContext'.
   at Avalonia.Skia.FboSkiaSurface.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #49056616)
......

```

**Comment by maxkatz6** [comment]
Looks like Intel GPUs have a similar issue, but even on a startup (which helps, so avalonia can fallback to software renderer) https://github.com/AvaloniaUI/Avalonia/issues/12738

**Comment by J31why** [comment]
My GPU is GTX970 and the driver version is 546.33.

**Comment by maxkatz6** [comment]
When I run `dxcap -forcetdr` in the terminal to simulate GPU driver crash, I don't have D3D11CreateDevice exception. And on `Sleep/Wake-up` it also works perfectly fine even without any gpu crashes at all.

But I noticed that gpu backend restoration doesn't work well after `dxcap -forcetdr` anyway - that's where I can reproduce ObjectDisposedException on get_IsCurrent. 
Can you check if https://github.com/AvaloniaUI/Avalonia/pull/14089 solves your issue?

**Comment by J31why** [comment]
@maxkatz6 Yes, The #14089 works for me, Thank you so much.

**Comment by timunie** [comment]
@J31why just fyi: the PR would have closed this issue automatically. Anyways, thanks for the feedback :-)
