### ISSUE TITLE
Avalonia MVVM Application crashes after window resize

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#1411]
Windows 7. Visual Studio Community 2017.
1. Build and run standard Avalonia MVVM Application from template.
2. Resize window to minimum size. 
![default](https://user-images.githubusercontent.com/4993430/36836247-e6f1ec1c-1d49-11e8-838f-647e3bfe7e2b.png)
3. Resize back.
4. Application crashes with:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Positive number required.
Parameter name: bytesAllocated
   at System.GC.RemoveMemoryPressure(Int64 bytesAllocated)
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.DoDispose()
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.Finalize()
```

**Comment by grokys** [comment]
Duplicate of #1023.

**Comment by xiangzhai** [comment]
:mips-interest
