### ISSUE TITLE
Exception in TextBox creation

### ISSUE THREAD

**Issue by tomschrot** [AvaloniaUI/Avalonia#14152]
The project compiles without errors (for Desktop) but when the control is created that contains TextBox, a exception is thrown due to access violation of property  "CanCopy":

Exception has occurred: CLR/System.Reflection.TargetInvocationException
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll: 'Exception has been thrown by the target of an invocation.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.MethodAccessException : Attempt by method 'WebTest.Controls.Editor.!XamlIlPopulate(System.IServiceProvider, WebTest.Controls.Editor)' to access method 'Avalonia.Controls.TextBox.set_CanCopy(Boolean)' failed.
   at WebTest.Controls.Editor.!XamlIlPopulate(IServiceProvider , Editor ) in C:\Users\tom\Desktop\DOTNET\Avalonia\WebTest\WebTest\Controls/Editor.axaml:line 33
   at WebTest.Controls.Editor.!XamlIlPopulateTrampoline(Editor )
   at WebTest.Controls.Editor.InitializeComponent(Boolean loadXaml) in C:\Users\tom\Desktop\DOTNET\Avalonia\WebTest\WebTest\Avalonia.Generators\Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator\WebTest.Controls.Editor.g.cs:line 22
   at WebTest.Controls.Editor..ctor() in C:\Users\tom\Desktop\DOTNET\Avalonia\WebTest\WebTest\Controls\Editor.axaml.cs:line 24
   at System.RuntimeType.CreateInstanceOfT()

## To Reproduce
Use my template https://www.nuget.org/packages/tomschrot.vscode.Avalonia.SPA,
open the Editor.axaml file
in line 40 add attributes:  CanCopy="True" CanPaste="True" CanCut="True" 
build the project for Desktop
run / debug the project
enter some chars in the start form until Submit is enabled
click Submit

Instancing fails with exception

## Environment 

- OS: Windows 11 Pro 23H2
- Avalonia-Version: 11.0.6
- .NET 8
- VSCode 1.85.1
-

**Comment by Gillibald** [comment]
CanPaste and CanCut are readonly

**Comment by tomschrot** [comment]
Ok, thank you.
Unfortunately, the online documentation is misleading. Please mark as get/readonly.

**Comment by timunie** [comment]
@tomschrot good idea. Can you file a PR?
