### ISSUE TITLE
NullRef with ShowDialog<>()

### ISSUE THREAD

**Issue by latop2604** [AvaloniaUI/Avalonia#1423]
I run into application crash when a close a modal window with the native close button.

Modal opened like that : `myModalWindow.ShowDialog<bool>()`

The woraround to use a nullable type like `bool?`

```System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.Window.<>c__DisplayClass54_0`1.<ShowDialog>b__4(EventPattern`1 _)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Take`1._.OnNext(TSource value)
   at Avalonia.Controls.TopLevel.HandleClosed()
   at Avalonia.Controls.WindowBase.HandleClosed()
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

I use AvaloniaUI beta 1

**Comment by grokys** [comment]
@latop2604 fix here: https://github.com/AvaloniaUI/Avalonia/pull/1426
