### ISSUE TITLE
Gtk3 crash when calling Close in a window.

### ISSUE THREAD

**Issue by Silverfeelin** [AvaloniaUI/Avalonia#1424]
Copied from #729, since it seems my post went unnoticed on the closed issue.

 I'm running into the same problem using Avalonia Beta 1. When calling Close() in a window opened with ShowDialog(), the application throws an exception only on Gtk3.
The gist has been removed in the linked issue, but based on the description it seems like we're doing the same thing.

I have created a repository with the minimal code needed to reproduce the issue.
https://github.com/Silverfeelin/AvaloniaCloseShowDialog

What I'm trying to do is simply use a button click event to close the dialog window (in my actual project I'm using this to notify the user of input errors).

On Windows 10, closing the dialog works perfectly fine. On Linux (Ubuntu 16.04), the below exception occurs when Close() is called from within the dialog code.
(Side note: I created a self contained application for Linux using dotnet publish -c release -f netcoreapp2.0 -r ubuntu.16.04-x64 )

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Gtk3.WindowBaseImpl.StaticTickCallback(IntPtr widget, IntPtr clock, IntPtr userData)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at AvaloniaCloseShowDialog.Program.Main(String[] args) in C:\Users\Silver\source\repos\AvaloniaCloseShowDialog\AvaloniaCloseShowDialog\Program.cs:line 11
```

Related code in the repository linked above:

Opening dialog window: https://github.com/Silverfeelin/AvaloniaCloseShowDialog/blob/master/AvaloniaCloseShowDialog/MainWindow.xaml.cs#L21-L25

Closing dialog window:
https://github.com/Silverfeelin/AvaloniaCloseShowDialog/blob/3fb0cb81f7b388e17158b3003840654feea0508e/AvaloniaCloseShowDialog/Dialog.xaml.cs#L22-L25

Apologies in advance if this is a mistake on my end.

**Comment by Silverfeelin** [comment]
Oh, it seems like the same issue was created 7 hours ago. Apologies, feel free to close this one.
