### ISSUE TITLE
DataGrid crash on clicking on the header using aot

### ISSUE THREAD

**Issue by TrinterSoftware** [AvaloniaUI/Avalonia#14344]
## To Reproduce

1. Use a DataGrid
2. Click on a column header
3. Application crashes
4. See stack trace

## Expected behavior
The DataGrid does not crash.

## Environment 
.net 8 SDK

- OS: Windows
- Avalonia-Version: 11.0.7

## Additional context

Here is the stack trace:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.DataGridColumn.get_DisplayIndex()
   at Avalonia.Controls.DataGridColumnCollection.EnsureVisibleEdgedColumnsWidth()
   at Avalonia.Controls.Primitives.DataGridColumnHeadersPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.DataGrid.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.DockPanel.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at PaketUI.Program.Main(String[] args) in

**Comment by workgroupengineering** [comment]
See [this](https://github.com/AvaloniaUI/Avalonia/discussions/14284#discussioncomment-8186669)

**Comment by TrinterSoftware** [comment]
Thank you for that tip, something new learned how to control sorting in template columns. But it is not the problem. It only occurs within the aot-deployment. When debugging in the dev ui there is no problem.

**Comment by timunie** [comment]
@TrinterSoftware if you want to look into that as you have the stack trace, your contribution would be welcome

**Comment by TrinterSoftware** [comment]
I'm trying for hours to get the project compiled. There are some missing XamlX-dependencies.
I found the project and tried to add it but some build tasks randomly popping up the missing XamlX libs.

How do you handle the XamlX dependencies?

**Comment by timunie** [comment]
Make sure to read building instructions. Most likely git submodule init was not successful. Needs to be recursive.

**Comment by TrinterSoftware** [comment]
Now I've found the building instructions. I'll try again. Thank you.

**Comment by jp2masa** [comment]
Duplicate of #14059?

**Comment by TrinterSoftware** [comment]
Let's say in the same area :-). 
I also got sometimes a crash without clicking anywhere onto the grid. I'll also investigate further.
