### ISSUE TITLE
Headless Renderer crashes if it encounters a GeometryGroup

### ISSUE THREAD

**Issue by yankun** [AvaloniaUI/Avalonia#14356]
If a GeometryGroup is used, the Headless renderer will crash with following exception, while being used in integration tests as example:

`System.NotImplementedException
The method or operation is not implemented.
   at Avalonia.Headless.HeadlessPlatformRenderInterface.CreateGeometryGroup(FillRule fillRule, IReadOnlyList1 children)
   at Avalonia.Media.GeometryGroup.CreateDefiningGeometry()
   at Avalonia.Media.Geometry.get_PlatformImpl()
   at Avalonia.Visual.SynchronizeCompositionProperties()
   at Avalonia.Rendering.Composition.CompositingRenderer.UpdateCore()
   at Avalonia.Rendering.Composition.CompositingRenderer.Update()
   at Avalonia.Rendering.Composition.Compositor.CommitCore()
   at Avalonia.Rendering.Composition.Compositor.Commit()
   at Avalonia.Media.MediaContext.CommitCompositor(Compositor compositor)
   at Avalonia.Media.MediaContext.CommitCompositorsWithThrottling()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Controls.Platform.ManagedDispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Headless.HeadlessUnitTestSession.<>c__DisplayClass9_01.<Dispatch>b__0()`

Here is a quick example to reproduce this:
https://github.com/yankun/AvaloniaHeadlessCrash

## To Reproduce
Create a view containing a geometry group and try to use it in a headless test session.

## Expected behavior
The headless test session should not be affected by the use of geometry groups.

**Comment by yankun** [comment]
Sorry to bring this up, bus as 11.0.10 has been released my changes are still not included, so our IntegrationTests keep failing. Has the issue been forgotten?

**Comment by timunie** [comment]
@yankun should be in 11.1 beta
