### ISSUE TITLE
MacOS : Application crash after MissingMethodException

### ISSUE THREAD

**Issue by latop2604** [AvaloniaUI/Avalonia#1468]
This error occurred after opening a sub windows (`.Show()` method). But not immediately.

```Exception has occurred : CLR/System.MissingMethodException
An unhandled exception of type 'System.MissingMethodException' occurred in System.Private.CoreLib.dll: 'Constructor on type 'MonoMac.Foundation.NSActionDispatcher' not found.'
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at MonoMac.ObjCRuntime.Runtime.GetNSObject(IntPtr ptr)
   at MonoMac.ObjCRuntime.NSObjectMarshaler`1.MarshalNativeToManaged(IntPtr handle)
   at System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToManaged(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
   at MonoMac.ObjCRuntime.Messaging.IntPtr_objc_msgSend_UInt64_IntPtr_IntPtr_bool(IntPtr receiver, IntPtr selector, UInt64 arg1, IntPtr arg2, IntPtr arg3, Boolean arg4)
   at MonoMac.AppKit.NSApplication.NextEvent(UInt64 mask, NSDate expiration, String mode, Boolean deqFlag)
   at Avalonia.MonoMac.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at CouscousManager.App.Main(String[] args) in /Users/aaa/Dev/MyProject/MyProject/App.xaml.cs:line 20```

**Comment by danwalmsley** [comment]
seems similar to https://stackoverflow.com/questions/14324507/nsactiondispatcher-is-garbage-collected-when-instruments-is-attached

although that should be fixed.

I need to find the CreateInstance parameters when this happens if anyone has a repro for this much appreciated.

**Comment by danwalmsley** [comment]
I was able to catch this in debugger, but not able to see the parameters, do I need my own compiled version of monomac?

**Comment by danwalmsley** [comment]
Fixed in new backend available now. http://avaloniaui.net/blog/2018-10-09-avalonia-native-osx
