### ISSUE TITLE
BindingExpression has not been started

### ISSUE THREAD

**Issue by ltetak** [AvaloniaUI/Avalonia#14753]
## Describe the bug
Haven't found the exact place but binding errors do not report properly in some cases and crash the application.
```
System.InvalidOperationException: BindingExpression has not been started.
   at Avalonia.Data.Core.UntypedBindingExpressionBase.GetValue()
   at Avalonia.Data.Core.UntypedBindingExpressionBase.PublishValue(Object value, BindingError error)
   at Avalonia.Data.Core.BindingExpression.ConvertAndPublishValue(Object value, BindingError error)
   at Avalonia.Data.Core.BindingExpression.OnNodeError(Int32 nodeIndex, String error)
   at Avalonia.Data.Core.ExpressionNodes.ExpressionNode.SetError(String message)
   at Avalonia.Data.Core.ExpressionNodes.LogicalAncestorElementNode.TrackedControlChanged(ILogical control)
   at Avalonia.Reactive.AnonymousObserver`1.OnNext(T value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.LogicalTree.ControlLocator.ControlTracker.Detached(Object sender, LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.Avalonia.LogicalTree.ILogical.NotifyDetachedFromLogicalTree(LogicalTreeAttachmentEventArgs e)
   at Avalonia.Controls.TopLevel.HandleClosed()
   at Avalonia.Controls.WindowBase.HandleClosed()
   at Avalonia.Controls.Window.HandleClosed()
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

## To Reproduce
Have a binding error. 
I guess it has something to do with the lifetime of the control. If the property has not yet been initialized and it errors then it fails.
I could repro it either by opening the app or closing it down.
The case when opening has been fixed by using ReflectionBinding. But this was probably just hiding the issue.

## Expected behavior
Don't crash, report the error.

## Environment 

- OS: Windows
- Avalonia-Version: 11.1.999-cibuild0045352-beta - latest master version as of today

**Comment by timunie** [comment]
Any chance you can share sample code?

**Comment by ltetak** [comment]
I haven't isolated it from the production app. This is a "pseudocode"
```
<UserControl ...>
...
        <ItemsControl x:Name="MainPanel" ItemsSource="{Binding $parent[controls:ToolBar].PrimaryItems, Mode=OneTime}">
            ...
```
I see this binding error in debug just before it crashes

```
[Binding]An error occurred binding 'ItemsSource' to '$parent[ToolBar].PrimaryItems' at 'PrimaryItems': 'BindingExpression has not been started.' (ItemsControl #MainPanel)
```
If I change it to ReflectionBinding it does not crash on start and it's even working fine. Something else (or the same thing) crashes when the app closes and detaches controls from the visual tree.

**Comment by TomEdwardsEnscape** [comment]
I have a repro case.

https://gist.github.com/TomEdwardsEnscape/6bcc0db015cc4d6f44067a216b116ea4

Apply this patch to the Avalonia repo, start the Sandbox project, then click the button twice.
