### ISSUE TITLE
Avalonia Exception on BuildAvaloniaApp with latest Beta

### ISSUE THREAD

**Issue by erythana** [AvaloniaUI/Avalonia#14925]
### Describe the bug

Hello,

i get an exception with todays beta build from official nuget sources.
I'm running on latest Fedora with Wayland and the 11.1.0-beta1 nuget package - one of the latest daily builds worked fine a few days ago - no other changes.

```
crit: EveSquadron.Program[0]
      Unhandled exception in Eve Squadron - Application shutdown.
      System.TypeLoadException: Method 'get_SupportsRegions' in type 'Avalonia.Skia.PlatformRenderInterface' from assembly 'Avalonia.Skia, Version=11.0.10.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation.
         at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
         at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
         at Avalonia.AppBuilder.SetupUnsafe()
         at Avalonia.AppBuilder.Setup()
         at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
         at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
```

It seems to me that the implicitly used Skia Nuget-Package is not referenced to the latest beta version:
![image](https://github.com/AvaloniaUI/Avalonia/assets/42657063/f042d909-627e-4be6-9765-66f6b1a66949)

A few of the other implicitly installed packages (the ones shown in the screenshot) are referenced correctly.
After manually installing the Skia package, i get another exception from X11 because thats the old version, too.

I would assume that those references needs to be updated too.

### Avalonia version

11.1.0-beta1

**Comment by erythana** [comment]
I'm really sorry - i missed the Avalonia.Desktop package which included those references...
