### ISSUE TITLE
App crash on button click because of MethodAccessException

### ISSUE THREAD

**Issue by CodeDevAM** [AvaloniaUI/Avalonia#14931]
### Describe the bug

**Some** of many buttons buttons in my App that are defined in the following way causes a crash of the App when they are clicked with the following exception. The exception and the crash disappears when I make `private void ClearSuccessfulAndFailedCount()` at least `internal` instead of `private`. But for many buttons that are defined in the exact same way it's no problem then the function is declared as private.

```Xaml
<Button
    Command="{Binding ClearSuccessfulAndFailedCount}"
    Content="X"
    ToolTip.Tip="Clear successful and failed Count" />
```

```CSharp
internal ICommand ClearSuccessfulAndFailedCountCommand => ReactiveCommand.Create(ClearSuccessfulAndFailedCount);
private void ClearSuccessfulAndFailedCount()
{
    // Some stuff
}
```

Expetion:
```
System.MethodAccessException: Attempt by method 'CompiledAvaloniaXaml.XamlIlTrampolines.XXX.UI:XXX.UI.ViewModels.MainViewModel+ClearSuccessfulAndFailedCount_0!CommandExecuteTrampoline(System.Object, System.Object)' to access method 'XXX.UI.ViewModels.MainViewModel.ClearSuccessfulAndFailedCount()' failed.
   at CompiledAvaloniaXaml.XamlIlTrampolines.XXX.UI:XXX.UI.ViewModels.MainViewModel+ClearSuccessfulAndFailedCount_0!CommandExecuteTrampoline(Object , Object )
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at XXX.Desktop.Program.Main(String[] args) in G:\A\XXX\XXX.Desktop\Program.cs:line 27

```

This is an exerpt of generated code that throws the exception:

```CSharp
using XXX.UI.ViewModels;

namespace CompiledAvaloniaXaml;

internal class XamlIlTrampolines
{
	public static void XXX_002EUI_003AXXX_002EUI_002EViewModels_002EMainViewModel_002BClearSuccessfulAndFailedCount_0_0021CommandExecuteTrampoline(object P_0, object P_1)
	{
		((MainViewModel)P_0).ClearSuccessfulAndFailedCount();
	}
}
```

Out of curiosity: What does `Trampolines` stands for in this context?

### To Reproduce

I tried to create a minimal example but in the minimal example the issue did not occur.

### Expected behavior

No crash

### Avalonia version

11.0.11

### OS

Windows

**Comment by CodeDevAM** [comment]
Sorry my mistake. The binding of the button was wrong. It should have been:

```Xaml
<Button
    Command="{Binding ClearSuccessfulAndFailedCountCommand}"
    Content="X"
    ToolTip.Tip="Clear successful and failed Count" />
```

However the compiler was not complaining. I would prefer Having a compile time error in this situation instead of a runtime error.

**Comment by MrJul** [comment]
Yes, currently the XAML compiler doesn't check the accessibility of members in compiled bindings.
Duplicate of #13067
