### ISSUE TITLE
HtmlControl content isn't assigned

### ISSUE THREAD

**Issue by vertexpipeline** [AvaloniaUI/Avalonia#1493]
I trying to use a HtmlControl but the XAML loader throws exception `Portable.Xaml.XamlObjectWriterException: The value  for 'Content' property is null`
Also I tried to assign Content\Text parameter, but the loader throws exception too.
There is a MainWindows.xaml:
```html
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="AvaloniaApplication2">
  <HtmlControl>
    
  </HtmlControl>
</Window>
```
and Designer's (Loader says it too) log:
```
Portable.Xaml.XamlObjectWriterException: The value  for 'Content' property is null
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteGetObject()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```

**Comment by danwalmsley** [comment]
Html control hasn't been updated in a long time, what do you want from html control? I have a possible alternative see... https://github.com/VitalElement/CefGlue.Core which allows you to embed chrome engine to view Web pages or html, it's not so lightweight though, but does work

**Comment by vertexpipeline** [comment]
Thanks, I was exploring Avalonia and found this control. I have not any tasks for this. Thanks for suggestion.

**Comment by vertexpipeline** [comment]
Can we exclude this project from Avalonia?

**Comment by danwalmsley** [comment]
I think that's probably a good idea

**Comment by jkoritzinsky** [comment]
I've moved the project into a separate repo.
