### ISSUE TITLE
rare exception: TargetInvocationException - Exception has been thrown by the target of an invocation. Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by ejongejans** [AvaloniaUI/Avalonia#15161]
### Describe the bug

Hi, 

I have 2 error reports logged (based on a lot of users) that have a strange exception coming from avalonia somewhere. I do not fully understand what causes it but it seems to be some kind of click event on a button. Perhaps someone knows or can guide me in the right direction what might cause it. 
The stacktrace is fully from avalonia. 

Exception: 
```
**TargetInvocationException**
Exception has been thrown by the target of an invocation. Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```
This is the stack trace of the exception (with line numbering from version 10.x i believe): 
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 149
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 352
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 419
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 143
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 146
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 188
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 58
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 37
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 749
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 810
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 26
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32DispatcherImpl.cs:line 111
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at FAvalonia.Program.Launch(String[] args)
   at FAvalonia.Do.Launch(String[] args)
   at FAvaloniaLauncher.Program.Main(String[] args)
```

### To Reproduce

I can't clearly reproduce it nor do i know the cause. 

### Expected behavior

No exception. 

### Avalonia version

11.0.9, 10.x

### OS

Windows

### Additional context

We generate almost all controls programatically from C#. We use little Xaml.

**Comment by timunie** [comment]
can you check 11.1 beta with said users?

**Comment by ejongejans** [comment]
no.. users are unknown due to privacy. At least; they didn't enter their email in the bug report. 
realizing this is an impossible bug to replicate.. :S

**Comment by timunie** [comment]
I could imagine a Dispatcher.UiThread.Post call is missing but really no idea how to proceed here. A minimal sample to try would be nice to have.

**Comment by maxkatz6** [comment]
Yes, it's likely to be something with threading. Possibly some code should be redirected to UI thread, but it's unknown on which side this error is.

**Comment by ejongejans** [comment]
Does avalonia allows updating controls from background threads? 
i.e., how does it compare to windows forms in that regard where you should redirect all updates to the primary UI thread?

**Comment by timunie** [comment]
No updates should be on the UI thread. You can use Dispatcher.UiThread.Post in the other thread

**Comment by ejongejans** [comment]
Ok thanks i will check that; maybe i missed a piece of code. We have a winforms code on the same code base; so in theory it should be OK. perhaps I missed a spot somewhere. Closing this.

**Comment by ejongejans** [comment]
I just checked my code. I was using this: 

Dispatcher.UIThread.InvokeAsync(action).Wait();

Could that be cause of it? (Instead of UIThread.Post? )

**Comment by timunie** [comment]
InvokeAsync is not Post. Also Wait can be evil.

**Comment by ejongejans** [comment]
yeah i thought so..  it was old code from 4 years ago. Lets see if it occurs again. Thx!
