### ISSUE TITLE
Control Catalog fails when using Wgl

### ISSUE THREAD

**Issue by jameswallacew8** [AvaloniaUI/Avalonia#15191]
### Describe the bug

ControlCatalog.NetCore fails to open when rendering with Win32RenderingMode.Wgl. Setting LogToTrace(LogEventLevel.Verbose) does not show any errors but the program exits with the message: "The program '[19624] ControlCatalog.NetCore.dll' has exited with code -1073741819 (0xc0000005)."

### To Reproduce

In Program.cs of ControlCatalog.NetCore I have used Wgl as the rendering mode under UseSkia():
`.UseSkia()
                .With(new Win32PlatformOptions
                {
                    RenderingMode = new [] {Win32RenderingMode.Wgl}
                })`

### Avalonia version

Latest

### OS

Windows

### Additional context

I'm trying to use Avalonia.OpenGL with the standard Controls but my program exits when interacting (hovering mouse over) a control outside of the OpenGL window. The following error arises when my main program exits on hover over: 

`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Avalonia.OpenGL.GlInterface.Flush()
   at Avalonia.Win32.OpenGl.WglGlPlatformSurface+RenderTarget+Session.Dispose()
   at Avalonia.Skia.GlRenderTarget+GlGpuSession.Dispose()
   at Avalonia.Skia.DrawingContextImpl.Dispose()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderReentrancySafe()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render()
   at Avalonia.Rendering.RenderLoop.TimerTick(System.TimeSpan)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()`

I'm using a Windows VM to develop this App and have had to install Mesa MSVC drivers from [here](https://github.com/pal1000/mesa-dist-win) in order to get any of the OpenGL content to be rendered with Wgl. This works but the program exit is strange when interacting with Avalonia controls.

Any ideas?

**Comment by timunie** [comment]
Please be more precise about Avalonia version. What is latest for you? 11.0.10, 11.1 beta, nightly? 

Nightly would be best to test. Also does it work not using a VM?

**Comment by jameswallacew8** [comment]
Yes, have built from source so I'm using Avalonia nightly. I believe it is likely to be a drivers issue in the VM as I have also tested (and failed on a VM with a GPU). The driver being used is D3D12 (Microsoft Basic Render Driver) version 4.2.

**Comment by maxkatz6** [comment]
WGL is an experimental rendering mode, which is on low support. I would recommend using AngleGL, unless wgl is really necessary.

**Comment by jameswallacew8** [comment]
I would just add for any one else facing similar issues when using a VM: Switching to an NV-series VM with a AMD GPU from Azure resolved the issue. 
Its almost certainly a driver related issue as the WDDM version on my current working VM is 2.7. Previous VMs I tried used an Nvidia GPU or CPU only and defaulted to WDDM 1.3 or simply did not show a driver version when running dxdiag.
