### ISSUE TITLE
Portable.Xaml.XamlParseException: Cannot resolve runtime namespace from XML namespace

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1541]
I added an Avalonia User Control in another Avalonia User Control but I'm getting the following exception in my XAML designer:

`Portable.Xaml.XamlParseException: Cannot resolve runtime namespace from XML namespace 'clr-namespace:OneScreenSwap.User_Controls'
   at Avalonia.Markup.Xaml.PortableXaml.AvaloniaXamlSchemaContext.GetXamlType(String xamlNamespace, String name, XamlType[] typeArguments)
   at Portable.Xaml.XamlSchemaContext.GetXamlType(XamlTypeName xamlTypeName)
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__15.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadCollectionItems>d__31.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__30.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__29.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__18.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__15.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadCollectionItems>d__31.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__30.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__29.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__18.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__15.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMember>d__30.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMemberElement>d__29.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadMembers>d__18.MoveNext()
   at Portable.Xaml.XamlXmlParser.<ReadObjectElement>d__15.MoveNext()
   at Portable.Xaml.XamlXmlParser.<Parse>d__13.MoveNext()
   at Portable.Xaml.XamlXmlReader.Read()
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()`

**Comment by RayyanTahir** [comment]
For future readers, the solution was to declare namespace in xaml with the assembly name like the following:

`xmlns:local="clr-namespace:OneScreenSwap.UserControls;assembly=OneScreenSwap`

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/1389 this PR will resolve this issue when the XAML and the namespace are in the same assembly.
