### ISSUE TITLE
Previewer Unable to find public constructor for type [view model]

### ISSUE THREAD

**Issue by SimonORorke** [AvaloniaUI/Avalonia#15472]
### Describe the bug

In the application I'm developing, the previewer fails to show a preview for any of the views in either Visual Studio 2022 or JetBrains Rider.  The error message is "Unable to find public constructor for type [view model]".  In Visual Studio, this is a `System.Xaml.XamlException`.  In Rider, where I have to look in `idea.log` to see the diagnostics, this is a `XamlX.XamlLoadException`. Here's an example from Rider, where a more fulsome trace is provided:
```
XamlX.XamlLoadException: Unable to find public constructor for type FalconProgrammer.ViewModel:FalconProgrammer.ViewModel.MidiForMacrosViewModel() Line 12, position 10.
   at XamlX.Transform.Transformers.ConstructableObjectTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlPropertyAssignmentNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstConstructableObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Transform.AstTransformationContext.Visit(IXamlAstNode root, IXamlAstTransformer transformer)
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
```

### To Reproduce

In Visual Studio or Rider with the required Avalonia extension/plugin installed and making sure preview is enabled, open any view XAML in my open source project https://github.com/SimonORorke/FalconProgrammer.

### Expected behavior

A preview should be shown.

### Avalonia version

11.0

### OS

Windows

### Additional context

All the view models only have constructors with parameters.

**Comment by maxkatz6** [comment]
But MidiForMacrosViewModel doesn't have a public constructor, while you try to use it as a parameterless DataContext:
https://github.com/SimonORorke/FalconProgrammer/blob/main/FalconProgrammer/Views/MidiForMacrosView.axaml#L12

**Comment by maxkatz6** [comment]
If you want to resolve previewing data context, you should define this context in C# code where you can access your DI container.

**Comment by timunie** [comment]
@SimonORorke 
- parameterless constructor may be internal, but it must be there 
- or as you said, add a designtime one
- or use a static one with {x:Static my:MyDesignerVM.Instance}
- or use `if(Design.IsDesignTime)` in code behind. 

a PR to the docs may be a good idea, could also be cross-linked to this one: https://docs.avaloniaui.net/docs/guides/implementation-guides/how-to-implement-dependency-injection
