### ISSUE TITLE
Setting attached properties on derived custom control throws exception

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1548]
**Exception:**

```
Portable.Xaml.XamlObjectWriterException
  HResult=0x80131500
  Message=Cannot set unknown member '{clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog}CustomBoder.Grid.Row'
  Source=Avalonia.Markup.Xaml
  StackTrace:
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartMember(XamlMember property) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 423
   at Portable.Xaml.XamlWriterInternalBase.WriteStartMember(XamlMember property) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlWriterInternalBase.cs:line 246
   at Portable.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 238
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlWriter.cs:line 75
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlServices.cs:line 127
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlServices.cs:line 113
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoaderPortableXaml.cs:line 203
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoaderPortableXaml.cs:line 183
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Type type, Object rootInstance) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoaderPortableXaml.cs:line 92
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Object obj) in D:\DOWNLOADS\GitHub-Forks\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoaderPortableXaml.cs:line 56
   at ControlCatalog.Pages.CustomBorderPage.InitializeComponent() in D:\DOWNLOADS\GitHub-Forks\Avalonia\samples\ControlCatalog\Pages\CustomBorderPage.xaml.cs:line 19
   at ControlCatalog.Pages.CustomBorderPage..ctor() in D:\DOWNLOADS\GitHub-Forks\Avalonia\samples\ControlCatalog\Pages\CustomBorderPage.xaml.cs:line 14
```

**Version:** 

https://github.com/AvaloniaUI/Avalonia/tree/51eb3e1cef5b68aec2d909e80dc8dbdfadd5687c

**Repro:** 

https://github.com/wieslawsoltes/Avalonia/tree/CannotSetUnknownMember, ControlCatalog.NetCore, CustomBorderPage.xaml

```XAML
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:pages="clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog">
  <Grid RowDefinitions="*" ColumnDefinitions="*">
    <pages:CustomBoder Grid.Row="0" Grid.Column="0"/>
  </Grid>
</UserControl>
```

```C#
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace ControlCatalog.Pages
{
    public class CustomBoder : Border
    {
    }

    public class CustomBorderPage : UserControl
    {
        public CustomBorderPage()
        {
            this.InitializeComponent();
        }
        
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

**Notes:**

This is probably related to recent changes from: https://github.com/AvaloniaUI/Avalonia/pull/1499

**Comment by wieslawsoltes** [comment]
Looks like issue is only present when custom control is defined outside default namespace `"https://github.com/avaloniaui"`. The following hack fixes the exception.

```XAML
<UserControl xmlns="https://github.com/avaloniaui">
  <Grid RowDefinitions="*" ColumnDefinitions="*">
    <CustomBoder Grid.Row="0" Grid.Column="0"/>
  </Grid>
</UserControl>
```

```C#
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Metadata;

[assembly: XmlnsDefinition("https://github.com/avaloniaui", "ControlCatalog.Pages")]

namespace ControlCatalog.Pages
{
    public class CustomBoder : Border
    {
    }

    public class CustomBorderPage : UserControl
    {
        public CustomBorderPage()
        {
            this.InitializeComponent();
        }
        
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

**Comment by grokys** [comment]
This is a bug in Portable.Xaml: https://github.com/cwensley/Portable.Xaml/issues/95. PR submitted upstream at https://github.com/cwensley/Portable.Xaml/pull/96
