### ISSUE TITLE
ColumnDefinitions as a StaticResource throws NullReferenceException when assigning to multiple Grids.

### ISSUE THREAD

**Issue by huestack** [AvaloniaUI/Avalonia#15518]
### Describe the bug

Assigning a `ColumnDefinitions` resource in two or more Grids throws runtime error.

Exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.Grid.ValidateDefinitionsLayout(IReadOnlyList`1 definitions, Boolean treatStarAsAuto)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.Window.ShowCore(Window owner)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at AvaloniaListBox.Program.Main(String[] args) in D:\Projects\Git\AvaloniaListBox\Program.cs:line 13

```

### To Reproduce

This works:

```
<Window.Resources>
    <ColumnDefinitions x:Key="TestDef">
        <ColumnDefinition Width="150" />
        <ColumnDefinition Width="10" />
        <ColumnDefinition Width="Auto" />
    </ColumnDefinitions>
</Window.Resources>

<StackPanel>
    <Grid ColumnDefinitions="{StaticResource TestDef}">
        <TextBlock Grid.Column="0">List</TextBlock>
        <TextBox Grid.Column="2" />
    </Grid>
    <Grid ColumnDefinitions="150, 10, Auto">
        <TextBlock Grid.Column="0">List</TextBlock>
        <TextBox Grid.Column="2" />
    </Grid>
</StackPanel>
```

This doesn't:
```
<Window.Resources>
    <ColumnDefinitions x:Key="TestDef">
        <ColumnDefinition Width="150" />
        <ColumnDefinition Width="10" />
        <ColumnDefinition Width="Auto" />
    </ColumnDefinitions>
</Window.Resources>

<StackPanel>
    <Grid ColumnDefinitions="{StaticResource TestDef}">
        <TextBlock Grid.Column="0">List</TextBlock>
        <TextBox Grid.Column="2" />
    </Grid>
    <Grid ColumnDefinitions="{StaticResource TestDef}">
        <TextBlock Grid.Column="0">List</TextBlock>
        <TextBox Grid.Column="2" />
    </Grid>
</StackPanel>
```

### Expected behavior

A resource is expected to be applied to multiple controls.

### Avalonia version

11.0.10, 11.1.0-beta-2

### OS

Windows

**Comment by maxkatz6** [comment]
Never seen this application of ColumnDefinitions, but looks handy.

**Comment by workgroupengineering** [comment]
the problem is there

https://github.com/AvaloniaUI/Avalonia/blob/262c1b08c79609b619839e85fe4d137df73fd55a/src/Avalonia.Controls/Grid.cs#L177-L183

exactly on line 181.

StaticResource return same instance for each grid.
 
two possible solutions could be:

- Deep cloning like this code:

  ```c#
            set
            {
                if (_extData == null) { _extData = new ExtendedData(); }
                var def = value is null
                    ? new ColumnDefinitions()
                    : new ColumnDefinitions(value.Count);
                if (value is not null)
                {
                    foreach (var item in value)
                    {
                        def.Add(new ColumnDefinition()
                        {
                            MaxWidth = item.MaxWidth,
                            MinWidth = item.MinWidth,
                            SharedSizeGroup = item.SharedSizeGroup,
                            Width = item.Width,
                        });
                    }
                }
                _extData.ColumnDefinitions = def;
                _extData.ColumnDefinitions.Parent = this;
                InvalidateMeasure();
            }
  ```

- `x:Shared` directive like [WPF](https://learn.microsoft.com/en-us/dotnet/desktop/xaml-services/xshared-attribute)

Personally I prefer `x:Shared`

**Comment by workgroupengineering** [comment]
Can i work on `x:Shared`?

**Comment by kekekeks** [comment]
Given that we already have support for resource factories for lazy resource loading, x:Shared can be implemented by calling AddNotShared (or smth) instead of AddDeferred.
