### ISSUE TITLE
Tmds.DBus.Protocol.DBusException when hovering from a Datagrid Popup

### ISSUE THREAD

**Issue by erythana** [AvaloniaUI/Avalonia#15551]
### Describe the bug

Hello,
this might be (somewhat) related to: https://github.com/AvaloniaUI/Avalonia/issues/12281#issuecomment-2082142152

I'm using the latest Avalonia 11.1.0-beta2 from nuget but this problem persists since at least 11.0.7.
I am running Fedora 40 with Gnome and Wayland.

Here you can find a minimal sample of the problem:
https://github.com/erythana/DBusExceptionMinimalSample/tree/master

When you hover over the datagrid, a popup is shown. When you hover away (to another line or out of the grid), this exception is shown in the Debug Window:
```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #54787541)
```
This results in a short stutter in the UI.

Also, i am pretty sure this issue did not occur on nightly "11.1.999-cibuild0045778-beta" from avalonias nuget reference.

### To Reproduce

Open program
Hover over Datagrid-Line
Check Debug Output

### Expected behavior

No exception when hovering away from an tooltip

### Avalonia version

11.0.7, 11.1.0-beta1, 11.1.0-beta2

### OS

Linux

**Comment by erythana** [comment]
Hello @maxkatz6 

Do you have any news on this? If i recall correctly, it was fixed in 
https://github.com/AvaloniaUI/Avalonia/pull/14548#issuecomment-1934755210
 but it seems it won't work in the latest builds.

**Comment by xecrets** [comment]
Still there in 11.2.1

```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #12156768)
```
To reproduce, enable a tool tip, hover over the control and when exiting the control and the tool tip is hidden this is logged.

**Comment by prensing** [comment]
I am getting this bug with a context menu for a Grid Row. It happens when I click on the menu item. Running version 11.3.2 of Avalonia and DataGrid.
```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #21331933)
[IME] Error:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/IBus/InputContext_2”
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.IBus.IBusX11TextInputMethod.SetCapabilitiesCore(Boolean supportsPreedit, Boolean supportsSurroundingText)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.<>c__DisplayClass40_0.<<UpdateCapabilities>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Avalonia.FreeDesktop.DBusCallQueue.Process() (IBusX11TextInputMethod #21331933)
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/freedesktop/IBus/InputContext_2”
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.QueueOnErrorAsync(Exception e) (IBusX11TextInputMethod #21331933)
```

**Comment by MacKey-255** [comment]
Same problem when I close a window manually in Linux Debian 12 with Avalonia 11.3.6
Error:
```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose()
```

**Comment by slavslavin** [comment]
Similar problem with context menu Astra Linux 1.8.2 with Avalonia 11.3.5:

UnobservedTaskException: Exception type: System.AggregateException
Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files)
Inner #1/1 in AggregateException: 
Exception type: Tmds.DBus.Protocol.DBusException
Message: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
Source: System.Private.CoreLib
Stack trace:
```
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)

```

**Comment by hhyyrylainen** [comment]
I think I have this same problem on basically any popup closing, for example tooltips and combo boxes as well, which is not something anyone has mentioned yet). So it was a bit hard to find as the issue tile in my opinion should highlight how this affects every single tooltip, popup menu etc.

I'm using Avalonia `11.3.9` on Fedora 43 with GNOME on Wayland.

Edit: some similar logs that no one has reported here yet:

```
2026-01-06 18:09:11.7185|WARN|Avalonia||[X11Platform] SMLib/ICELib reported a new error: SESSION_MANAGER environment variable not defined (X11PlatformLifetimeEvents #53182860)

2026-01-06 18:10:13.5400|WARN|Avalonia||[IME] Error:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.IBus.InputContext” on object at path /org/freedesktop/IBus/InputContext_1117
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.IBus.IBusX11TextInputMethod.SetCapabilitiesCore(Boolean supportsPreedit, Boolean supportsSurroundingText)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.<>c__DisplayClass40_0.<<UpdateCapabilities>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Avalonia.FreeDesktop.DBusCallQueue.Process() (IBusX11TextInputMethod #12435494) 

2026-01-06 18:10:19.5392|WARN|Avalonia||[IME] Error:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.IBus.InputContext” on object at path /org/freedesktop/IBus/InputContext_1119
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.IBus.IBusX11TextInputMethod.SetCapabilitiesCore(Boolean supportsPreedit, Boolean supportsSurroundingText)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.<>c__DisplayClass40_0.<<UpdateCapabilities>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Avalonia.FreeDesktop.DBusCallQueue.Process() (IBusX11TextInputMethod #54273197) 

2026-01-06 18:11:07.3354|WARN|Avalonia||[IME] Error:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.IBus.InputContext” on object at path /org/freedesktop/IBus/InputContext_1128
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.IBus.IBusX11TextInputMethod.SetCapabilitiesCore(Boolean supportsPreedit, Boolean supportsSurroundingText)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.<>c__DisplayClass40_0.<<UpdateCapabilities>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Avalonia.FreeDesktop.DBusCallQueue.Process() (IBusX11TextInputMethod #46594488)
```

**Comment by torum** [comment]
Still there in Avalonia v12.0.0 with the latest Tmds.DBus.Protocol 0.92.0.

**Comment by jurihock** [comment]
The issue occurs even with very basic things, such as the context menu on a blank window...

Please consider following *minimal* example how to reproduce the DBus issue on Ubuntu 26.04 LTS using Avalonia 12.0.2:

https://github.com/jurihock/AvaloniaLinuxDBusIssue

This repo essentially presents an example of the context menu as outlined in the [official Avalonia docs](https://docs.avaloniaui.net/controls/menus/contextmenu#basic-example) with an additional [LogToDelegate](https://docs.avaloniaui.net/docs/app-development/logging-errors-and-warnings#logtodelegate) callback to make the error message visible.

Please let me know if anything is unclear.
