### ISSUE TITLE
Avalonia 11.1 beta2 crashes on start with SkiaSharp 3.0 on Ubuntu Linux

### ISSUE THREAD

**Issue by nil4** [AvaloniaUI/Avalonia#15575]
### Describe the bug

Apps built with Avalonia 11.1.0-beta2 and SkiaSharp 3.0crash on startup on Ubuntu 22.04: *The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [115.0, 116.0).*

### To Reproduce

Install Avalonia project templates (one-time setup):

```shell
dotnet new install Avalonia.Templates
```

Create a new project:

```shell
dotnet new avalonia.app -o TestAppBeta   -av 11.1.0-beta1
```

Edit the generated `TestAppBeta.csproj` to use Avalonia 11.1 beta2:

```diff
-<PackageReference Include="Avalonia" Version="11.1.0-beta1" />
+<PackageReference Include="Avalonia" Version="11.1.0-beta2" />
-<PackageReference Include="Avalonia.Desktop" Version="11.1.0-beta1" />
+<PackageReference Include="Avalonia.Desktop" Version="11.1.0-beta2" />
-<PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0-beta1" />
+<PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0-beta2" />
-<PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0-beta1" />
+<PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0-beta2" />
 <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
-<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0-beta1" />
+<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0-beta2" />
```

`dotnet run` -- the application starts up as expected, showing the *Welcome to Avalonia!* window.

Edit the `TestAppBeta.csproj` and add a reference to SkiaSharp 3:

```diff
 <PackageReference Include="Avalonia" Version="11.1.0-beta2" />
 <PackageReference Include="Avalonia.Desktop" Version="11.1.0-beta2" />
 <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0-beta2" />
 <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0-beta2" />
 <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
 <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0-beta2" />
+<PackageReference Include="SkiaSharp" Version="3.0.0-preview.3.1" />
```

`dotnet run` -- the application crashes on startup:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [115.0, 116.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKFontManager..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKFontManager.SKFontManagerStatic..ctor(IntPtr x)
   at SkiaSharp.SKFontManager..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKFontManager.get_Default()
   at Avalonia.Skia.FontManagerImpl..ctor()
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at TestAppBeta.Program.Main(String[] args)
```

### Expected behavior

Apps using Avalonia 11.1 beta2 together with SkiaSharp 3.0.* start up correctly on Linux.

### Avalonia version

11.1.0-beta2

### OS

Linux

### Additional context

Ubuntu Desktop 22.04.02

```shell
uname -a
Linux ubuntu-linux-22-04-02-desktop 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by maxkatz6** [comment]
Add
```
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.0.0-preview.3.1" />
```
