### ISSUE TITLE
Project build error Avalonia for android (XAPRAS7000 System.BadImageFormatException: Invalid number of sections declared in PE header)

### ISSUE THREAD

**Issue by ComradeSwarog** [AvaloniaUI/Avalonia#15632]
### Describe the bug

Project build error Avalonia for android (XAPRAS7000 System.BadImageFormatException: Invalid number of sections declared in PE header)

### To Reproduce

Create an Avalonia project using the wizard (Visual Studio 2022)

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/df46c760-658f-4749-8930-4cb8b9578d95)

Install the latest packages 

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/65b5f599-c567-4d60-a95b-ac5ac42cc76a)

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/9768d386-e008-4d7f-b80b-02c6cf57c8f5)

Call the project build
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/f5f78422-1ccf-42e7-8780-703e9e67afa6)

Result
```
Rebuild started at 21:23...
Restored W:\MyProjects\AvaloniaApplication1\AvaloniaApplication1\AvaloniaApplication1.csproj (in 52 ms).
Restored W:\MyProjects\AvaloniaApplication1\AvaloniaApplication1.Android\AvaloniaApplication1.Android.csproj (in 110 ms).
Restored W:\MyProjects\AvaloniaApplication1\MauiApp1\MauiApp1.csproj (in 381 ms).
1>------ Rebuild All started: Project: AvaloniaApplication1, Configuration: Debug Any CPU ------
1>AvaloniaApplication1 -> W:\MyProjects\AvaloniaApplication1\AvaloniaApplication1\bin\Debug\net7.0\AvaloniaApplication1.dll
2>------ Rebuild All started: Project: AvaloniaApplication1.Android, Configuration: Debug Any CPU ------
2>AvaloniaApplication1.Android -> W:\MyProjects\AvaloniaApplication1\AvaloniaApplication1.Android\bin\Debug\net7.0-android\AvaloniaApplication1.Android.dll
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000: System.BadImageFormatException: Invalid number of sections in declared in PE header.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(PEBinaryReader& reader)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at System.Reflection.PortableExecutable.PEHeaders..ctor(Stream peStream, Int32 size, Boolean isLoadedImage)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at System.Reflection.PortableExecutable.PEReader.InitializePEHeaders()
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at System.Reflection.PortableExecutable.PEReader.GetMetadataBlock()
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at Xamarin.Android.Tasks.ProcessAssemblies.DeduplicateAssemblies(List`1 output, Dictionary`2 symbols)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at Xamarin.Android.Tasks.ProcessAssemblies.RunTask()
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(107,5): error XAPRAS7000:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
2>Done building project "AvaloniaApplication1.Android.csproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 21:23 and took 06,527 seconds ==========

```

Similar problem on all versions
net7.0-android and net8.0-android

The build machine has all the necessary dependencies installed
- All net platform from net6.0 - net8.0
- Android SDK 
- MAUI

![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/cc7fc4ac-d04a-4da5-bada-afb1fb27b1f4)
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/a8358968-9c2d-4942-92c2-555272d518fd)

### Expected behavior

Correct build of the project without errors

### Avalonia version

11.0.10

### OS

Android

**Comment by timunie** [comment]
can you try 11.1 beta?

**Comment by ComradeSwarog** [comment]
> can you try 11.1 beta?

Problem still exists =(
![изображение](https://github.com/AvaloniaUI/Avalonia/assets/46655729/d4006a9a-77e3-4e1f-886d-eaf8a2583a3c)

Maybe someone has encountered a similar error?

**Comment by timunie** [comment]
can you upload a very minimal sample for me to double-check? Is it a real world device or an emulator?
