### ISSUE TITLE
Closing a trivial dialog shows errors on Debian [Gtk3, netcoreapp2.0]

### ISSUE THREAD

**Issue by SteveGilham** [AvaloniaUI/Avalonia#1593]
netcoreapp2.0 built on Windows, works happily on Windows, but has problems when executed on a recent vanilla install of Debian 9 with dotnet version 2.1.4; using
```
    <PackageReference Include="Avalonia" Version="0.6.1" />
```

Failing dialog example --

XAML
```
<Window
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="About WPFAppSkeleton" MinWidth="500"
        HorizontalAlignment="Center"
        ShowInTaskbar="False"
        Background="{DynamicResource ControlBrush}"
        Foreground="{DynamicResource ControlTextBrush}"
        Height="500" Width="600"
>
  <StackPanel Margin="10">
    <Button Name="Close" IsDefault="True" Content="Close" HorizontalAlignment="Center" Padding="15,5" />
  </StackPanel>
</Window>
```
Code-behind
```
open Avalonia.Controls
open Avalonia.Markup.Xaml

type AboutBox () as this =
    inherit Window()

    do this.InitializeComponent()
    member this.InitializeComponent() =
        AvaloniaXamlLoader.Load(this)
        this.Title <- "About"

        let aboutClose = this.FindControl<Button>("Close")
        aboutClose.Click |> Event.add (fun _ -> this.Hide())
```
Launched with `ShowDialog()`.

Pressing the `Close` button gives
```
(dotnet:1346): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
If I use `Close()`, rather than `Hide()` in the `Click` handler, the whole application crashes out with 
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Gtk3.WindowBaseImpl.StaticTickCallback(IntPtr widget, IntPtr clock, IntPtr userData)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Program.main(String[] _arg1) in C:\Users\steve\Documents\BitBucket\altcover.visualizer\Visualizer\Visualizer\AltCover.Visualizer\Program.fs:line 13
Aborted
```

**Comment by SteveGilham** [comment]
Fixed the Linux distro -- (the Ubuntu VMs are on my other box).

**Comment by SteveGilham** [comment]
FWIW, using the Avalonia OpenFileDialog() generates similar GTK messages to the console when displayed via ShowAsync and then closed; this with build 5873.

**Comment by kekekeks** [comment]
GTK backend is discontinued. 
There are still GTK-based file dialogs, and they will continue to complain about a dialog being mapped without a transient parent (it's being set immediately afterwards), that's not a bug, that's just how things work.
