### ISSUE TITLE
"Call from invalid thread" process crash after tray icon menu item is invoked

### ISSUE THREAD

**Issue by logiclrd** [AvaloniaUI/Avalonia#15940]
### Describe the bug

I have a TrayIcon with a menu. The menu actions are attached to commands. One such command:
```
public ICommand ShowWindowCommand { get; }
```
This command is initialized thusly:
```
ShowWindowCommand = ReactiveCommand.Create(ShowWindow);
```
It is bound to the menu item like this:
```
<NativeMenuItem Header="_Show Status Window" Command="{Binding ShowWindowCommand}" />
```
The `ShowWindow` handler method is:
```
void ShowWindow()
{
	MainWindow ??= new MainWindow();
	MainWindow.Show();
}
```
When I activate this menu item, the process immediately crashes with the exception:
```
Unhandled exception. System.InvalidOperationException: Call from invalid thread
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Scan.cs:line 48
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 30
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.LongScheduledWorkItem`1.<>c.<.ctor>b__3_0(Object thisObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 181
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<StartThread>b__8_0(Object itemObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 75
```
This exception occurs directly after the `MainWindow` constructor is called. The `ShowWindow` handler definitely does execute; a breakpoint placed in the method is hit. For what it's worth, `Dispatcher.UIThread.CheckAccess()` returns `true` prior to the call to the constructor -- and testing has confirmed that, in this situation, `Dispatcher.UIThread.Invoke` is a no-op.

When I try to trace into it with a debugger, it appears that the crash is triggered by something happening in the base `Window` class constructor before my `MainWindow` constructor starts executing. I have verified that `Thread.CurrentThread.ManagedThreadId` is the same (1, in practice) in both the `OnFrameworkInitializationComplete` call and the menu item callback. When the exception occurs, it is happening on the thread with a different `ManagedThreadId`, such as 14. So, the exception isn't happening _in_ the base class constructor, but the base class constructor is doing something that causes another thread to do something it shouldn't.

If I override `Application.OnFrameworkInitializationCompleted` in my `App` class and place a call to `ShowWindow()` inside that override, then the window displays and runs normally, no exception.

I have also checked that if I create the `MainWindow` instance earlier and defer only the call to `MainWindow.Show` that it still crashes, this time triggered by something the `Show` method is doing.

### To Reproduce

https://github.com/logiclrd/CrashShowWindowFromTrayIconMenuItemClick

### Expected behavior

Window appears, process does not crash.

### Avalonia version

11.0.10

### OS

Linux

**Comment by logiclrd** [comment]
An update, if I remove all code from the `ShowWindow` method, the crash still occurs after `ShowWindow` returns.

**Comment by logiclrd** [comment]
I have also verified that using the `App` instance as its own `DataContext` is not the cause. Using a separate class just to house the `CrashProcessCommand` property to which to bind does not affect whether the exception happens.

**Comment by timunie** [comment]
Can you try latest nightly build or 11.1 beta? Many fixes in and maybe also for this usecase

**Comment by logiclrd** [comment]
I'll have a go, thanks.

**Comment by logiclrd** [comment]
Crash confirmed on 11.1.0-beta2 as well.
