### ISSUE TITLE
Render in FrameBuffer on Raspbian

### ISSUE THREAD

**Issue by Feroks** [AvaloniaUI/Avalonia#1600]
I am using .NET Core 2.0 and Skia binary from [here](https://github.com/toburger/skiasharp-raspberry/releases/tag/arm)
Following command was used for publishing: dotnet publish -r linux-arm -f netcoreapp2.0 -c Release

Launching application on full Rapsbian (with GTK) works great, but when i try to use a FaremBuffer, i am getting the following exception:

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.ImmediateRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.LinuxFramebuffer.FramebufferToplevelImpl.<Invalidate>b__9_0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Controls.Platform.InternalPlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(ICloseable closable)
   at LinuxFramebufferPlatformExtensions.InitializeWithLinuxFramebuffer[T](T builder, Action`1 setup, CancellationToken stop, String fbdev)
   at AvaloniaFramebuffer.Program.Main(String[] args)
```

The output in publish directory does not have libSkiaSharp and i am not sure where to take it from.
Did someone manage to get Avalonia working on Raspbian Lite in FrameBuffer?

**Comment by danwalmsley** [comment]
I think you libskiasharp is probably not compatible or has a missing method, @kekekeks do you know who built libskiasharp for arm?

**Comment by kekekeks** [comment]
Seems to work for multiple people now
