### ISSUE TITLE
System.InvalidOperationException: Neither DBus nor GTK are available on the system

### ISSUE THREAD

**Issue by Hannes1909** [AvaloniaUI/Avalonia#16078]
### Describe the bug

Hi, 
I'm running NixOS unstable on Hyprland - when installing OpenUtau (built on Avalonia 11.0.4) and opening any FileBrowserDialog like "File --> Open/Save/Import Audio...." etc. it crashes with the error in title.
Stacktrace:
```
Unhandled exception. System.InvalidOperationException: Neither DBus nor GTK are available on the system
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.EnsureStorageProvider()
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options)
   at OpenUtau.App.FilePicker.OpenFile(Window window, String titleKey, String startLocation, FilePickerFileType[] types) in /build/source/OpenUtau/FilePicker.cs:line 61
   at OpenUtau.App.FilePicker.OpenFile(Window window, String titleKey, FilePickerFileType[] types) in /build/source/OpenUtau/FilePicker.cs:line 53
   at OpenUtau.App.Views.MainWindow.OnMenuImportAudio(Object sender, RoutedEventArgs args) in /build/source/OpenUtau/Views/MainWindow.axaml.cs:line 298
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenUtau.App.Program.Run(String[] args) in /build/source/OpenUtau/Program.cs:line 77
   at OpenUtau.App.Program.Main(String[] args) in /build/source/OpenUtau/Program.cs:line 42
```

### To Reproduce

NixOS Unstable, Hyprland.
Install OpenUtau with home-manager like:
```
{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.openutau
  ];
}
```
run it, open FileBrowserDialog / FilePicker.

### Expected behavior

FilePicker opens as expected and lets me select a file to open/save to etc.

### Avalonia version

11.0.4

### OS

Linux

### Additional context

Dependencies from [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/openutau/deps.nix)
It seems to work on a test VM with NixOS Stable Gnome (Boot upo ISO, Install, nix-shell -p OpenUtau), so it could be only related to Hyprland, maybe? Or some Nix-Packages/Dependencies for FilePicker I'm missing?

**Comment by kekekeks** [comment]
1) Avalonia attempts to use xdg-desktop-portal DBUS protocol provided by any normal modern Linux distro
2) Avalonia attempts to load GTK using default library load path (which works with anything except for gobolinux and its spiritual followers)

If both of those fail, Avalonia will not be able to show the system file dialog.

Please, adjust your environment in a way that either (1) or (2) will be available.

**Comment by Hannes1909** [comment]
Thanks for your replies, I was able to find a solution thanks to this upstream [issue](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/47#issuecomment-2174510110)
Moving my xdg-portal configuration from homemanager to /etc/nixos/configuration.nix did the trick.
