### ISSUE TITLE
11.1.0-rc1. TrayIcon is not working on Windows 7.  Unable to load DLL 'shcore.dll' or one of its dependencies. 

### ISSUE THREAD

**Issue by evgeniylevakhin** [AvaloniaUI/Avalonia#16146]
### Describe the bug

TrayIcon stopped working after upgrading from 11.0.10 to 11.1.0-rc1 on Windows 7 [Version 6.1.7601]

```
2024-06-26 14:01:32.749 -05:00 [FTL] [737508C3] App Unhandled error occured
System.DllNotFoundException: Unable to load DLL 'shcore.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Avalonia.Win32.Interop.UnmanagedMethods.GetDpiForMonitor(IntPtr hmonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at Avalonia.Win32.TrayIconImpl.UpdateIcon(Boolean remove)
   at Avalonia.Win32.TrayIconImpl.SetIcon(IWindowIconImpl icon)
   at Avalonia.Controls.TrayIcon.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.Controls.TrayIcon.set_Icon(WindowIcon value)
```

It appears that Win32.TrayIconImpl is missing some platform checks:

https://github.com/AvaloniaUI/Avalonia/blob/eb882213be5438f6cd039f607b8952ae1153b808/src/Windows/Avalonia.Win32/TrayIconImpl.cs#L130

E.g.:

https://github.com/AvaloniaUI/Avalonia/blob/eb882213be5438f6cd039f607b8952ae1153b808/src/Windows/Avalonia.Direct2D1/HwndRenderTarget.cs#L25

Is this a bug or there are no plans to add this?

### To Reproduce

A minimal project with TrayIcon. 

### Avalonia version

11.1.0-rc1

### OS

Windows

**Comment by thevortexcloud** [comment]
Avalonia does not officially support Windows 7. But fixes from the community are generally accepted as long as they have a low chance of breaking other things.

https://docs.avaloniaui.net/docs/faq#what-versions-of-windows-are-supported
