### ISSUE TITLE
Datagrid - Out of range exception upon expanding group after PC wakes up from sleep

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#16233]
### Describe the bug

Crash upon collapsing/expanding a group if the computer has been previously put in a sleep state then woken up

### To Reproduce

1. Collapse a group, then minimize into the taskbar;
2. put PC into sleep (start button in taskbar -> power ->sleep);
3. turn PC on then bring application back and click the button to EXPAND any of the collapsed groups

### Avalonia version

11.0.5

### OS

Windows

### Additional context

https://github.com/0x90d/videoduplicatefinder/issues/520

```
Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Avalonia.Controls.DataGridDisplayData.UnloadScrollingElement(Int32 slot, Boolean updateSlotInformation, Boolean wasDeleted)
   at Avalonia.Controls.DataGrid.RemoveNonDisplayedRows(Int32 newFirstDisplayedSlot, Int32 newLastDisplayedSlot)
   at Avalonia.Controls.DataGrid.UpdateRowGroupVisibility(DataGridRowGroupInfo targetRowGroupInfo, Boolean newIsVisible, Boolean isDisplayed)
   at Avalonia.Controls.DataGrid.OnRowGroupHeaderToggled(DataGridRowGroupHeader groupHeader, Boolean newIsVisible, Boolean setCurrent)
   at Avalonia.Controls.DataGridRowGroupHeader.ToggleExpandCollapse(Boolean isVisible, Boolean setCurrent)
   at Avalonia.Controls.DataGridRowGroupHeader.<OnApplyTemplate>b__59_0(Nullable`1 v)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`2.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.ValueStore.SetCurrentValue[T](StyledProperty`1 property, T value)
   at Avalonia.AvaloniaObject.SetCurrentValue[T](StyledProperty`1 property, T value)
   at Avalonia.Controls.Primitives.ToggleButton.Toggle()
   at Avalonia.Controls.Primitives.ToggleButton.OnClick()
   at Avalonia.Controls.Button.OnPointerPressed(PointerPressedEventArgs e)
```

**Comment by schavelev** [comment]
Sometimes the application crashes (unhandled exception) when scrolling DataGrid

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

The debuger stops here:
https://github.com/AvaloniaUI/Avalonia/blob/a04af7cebf3d49b81c228cbb6c18eb2e860ada58/src/Avalonia.Controls.DataGrid/DataGridDisplayData.cs#L221

Second exception:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Avalonia.Controls.DataGridDisplayData.GetDisplayedElement(Int32 slot)
   at Avalonia.Controls.DataGrid.ApplyDisplayedRowsState(Int32 startSlot, Int32 endSlot)
   at Avalonia.Controls.DataGrid.DataGrid_LostFocus(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers)
   at Avalonia.Controls.TopLevel.PlatformImpl_LostFocus()
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

First exception::
```
System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Avalonia.Controls.DataGridDisplayData.LoadScrollingSlot(Int32 slot, Control element, Boolean updateSlotInformation)
   at Avalonia.Controls.DataGrid.InsertDisplayedElement(Int32 slot, Control element, Boolean wasNewlyAdded, Boolean updateSlotInformation)
   at Avalonia.Controls.DataGrid.InsertDisplayedElement(Int32 slot, Boolean updateSlotInformation)
   at Avalonia.Controls.DataGrid.GetExactSlotElementHeight(Int32 slot)
   at Avalonia.Controls.DataGrid.ScrollSlotsByHeight(Double height)
   at Avalonia.Controls.DataGrid.OnRowsMeasure()
   at Avalonia.Controls.Primitives.DataGridRowsPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at VisarApp.Desktop.Program.Main(String[] args) in D:\Git\visar-ava\VisarApp.Desktop\Program.cs:line 28
```

**Comment by timunie** [comment]
@schavelev in case you have an idea hiw to overcome this and a test repo, a PR would be welcome 🤗

**Comment by schavelev** [comment]
@timunie Thanks for the reply. This error is reliably reproduced in my project. Unfortunately, I haven't been able to create a small test application yet.

**Comment by timunie** [comment]
@schavelev if possible for you, consider to clone Avalonia and add your App to src/samples/Sandbox. From there you could debug into Avalonia itself. Changes to Sandbox should not be pushed to origin, so can be private code. Just as an idea.
