### ISSUE TITLE
StyleInclude CherylUI Index.axaml throws exception

### ISSUE THREAD

**Issue by PerfectlyFineCode** [AvaloniaUI/Avalonia#16460]
### Describe the bug

Including CherylUI's Index.axaml throws this exception using Avalonia 11.1.0
```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<System.Object> Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlEagerParentStackProvider.get_DirectParents()'.
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Index.axaml(IServiceProvider, Styles)
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Index.axaml(IServiceProvider)
   at MyFridge.App.!XamlIlPopulate(IServiceProvider, App) in D:\Coding\Softwares\Avalonia\MyFridge\MyFridge\MyFridge\App.axaml:line 15
   at MyFridge.App.!XamlIlPopulateTrampoline(App)
   at MyFridge.App.Initialize() in D:\Coding\Softwares\Avalonia\MyFridge\MyFridge\MyFridge\App.axaml.cs:line 15
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at MyFridge.Desktop.Program.Main(String[] args) in D:\Coding\Softwares\Avalonia\MyFridge\MyFridge\MyFridge.Desktop\Program.cs:line 12
```

### To Reproduce

1. Make a new Cross-platform project using Avalonia 11.1.0
2. Install CherylUI Nuget
3. Include the style as seen in <https://github.com/kikipoulet/CherylUI/wiki/1.-Installation>

### Expected behavior

It should not throw an exception and should work like expected.

### Avalonia version

11.1.0

### OS

Windows

### Additional context

Same result if you compiled and ran it for Android and probably the others.

**Comment by maxkatz6** [comment]
CherylUI currently targets unsupported `11.1.0-beta2` version. It should target either 11.0 or 11.1 stable.
