### ISSUE TITLE
ReactiveUI's `WhenActivated` does not work with `WinFormsAvaloniaControlHost`

### ISSUE THREAD

**Issue by daniel-lerch** [AvaloniaUI/Avalonia#16463]
### Describe the bug

I created an Avalonia user control using `Avalonia.ReactiveUI.ReactiveUserControl<TViewModel>` in the code behind file I call `this.WhenActivated(d => d(....))`. The controls works in an Avalonia application. If I host this user control in an `WinFormsAvaloniaControlHost`, however, it throws an exception at runtime:

<details>
<summary>Argument Exception: Don't know how to detect when Vocup.Views.LicensesControl is activated/deactivated, you may need to implement IActivationForViewFetcher</summary>

```
System.ArgumentException
  HResult=0x80070057
  Message=Don't know how to detect when Vocup.Views.LicensesControl is activated/deactivated, you may need to implement IActivationForViewFetcher
  Source=ReactiveUI
  StackTrace:
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Func`1 block, IViewFor view)
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block, IViewFor view)
   at ReactiveUI.ViewForMixins.WhenActivated(IActivatableView item, Action`1 block)
   at Avalonia.ReactiveUI.ReactiveUserControl`1..ctor()
   at Vocup.Views.LicensesControl..ctor() in C:\source\vocup\src\Vocup\Views\LicensesControl.axaml.cs:line 10
   at Vocup.Forms.AboutBox..ctor() in C:\source\vocup\src\Vocup.WinForms\Forms\AboutBox.cs:line 18
   at Vocup.MainForm.TsmiAbout_Click(Object sender, EventArgs e) in C:\Users\danie\source\vocup\src\Vocup.WinForms\MainForm.cs:line 293
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
</details>

### To Reproduce

1. Create an Avalonia project with ReactiveUI for Windows
2. Make your main view inherit from `ReactiveUserControl<MainViewModel>` instead `UserControl`
3. Add `this.WhenActivated(d => d(new System.IO.MemoryStream()));` to the constructor
4. Create a WinForms project referencing the Avalonia project
5. Add a `WinFormsAvaloniaControlHost` to your WinForms project
6. Add `winFormsAvaloniaControlHost1.Content = new MainView { DataContext = new MainViewModel() };` to the constructor
7. Launch your WinForms application

### Expected behavior

No exception should be thrown and the control should be rendered, just like it is in an Avalonia application.

### Avalonia version

11.1.0

### OS

Windows

### Additional context

I also tried adding a reference to `ReactiveUI.WinForms` to my WinForms project but the same exception was still thrown.

Please let me know if you need a minimal reproducible example in a separate repository.

**Comment by maxkatz6** [comment]
It might be tricky to support with the way how ReactiveUI works.

Normally, you have to create Avalonia AppBuilder, and call registration method `.UseReactiveUI()`: https://github.com/AvaloniaUI/Avalonia/blob/d3f234bad58d8b45f13f981e3e1926ee20f30f49/src/Avalonia.ReactiveUI/AppBuilderExtensions.cs#L16-L27

In your case this call is either missed or is overridden by another similar WinForms related registration.
AFAIK, ReactiveUI can only have single `IActivationForViewFetcher` which means - it's either Avalonia or WinForms, but not both to work with ReactiveUI.
