### ISSUE TITLE
Prerequisites check and better requirements documentation

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#1656]
A "nice to have" would be some sort of check for prerequisites and versions at runtime with user understandable error messages and actions.

Prerequisites and minimum versions need documenting.

The motivation for this was a user with an old version of GTK3 which produced:-

Unhandled Exception: Avalonia.Gtk3.Interop.NativeException: Exception of type 'Avalonia.Gtk3.Interop.NativeException' was thrown.
   at Avalonia.Gtk3.Interop.UnixLoader.GetProcAddress(IntPtr dll, String proc, Boolean optional)
   at Avalonia.Gtk3.Interop.Resolver.Resolve(String basePath)
   at Avalonia.Gtk3.Gtk3Platform.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at SparkSDR.avalonia.Program.Main(String[] args)
Aborted (core dumped)

**Comment by MonkAlex** [comment]
Fast test 0.7.0 on linux:

 - ubuntu 14.04 not work with the same error
 - ubuntu 16.04 work well
 - linux mint 17.3 not work with the same error
 - linux mint 18.3 work well

Updating 14.04 and 17.3 not help.
