### ISSUE TITLE
[Bug]: iOS BindCommand throws exception when executing on iPad (device)

### ISSUE THREAD

**Issue by yvcabrerago** [AvaloniaUI/Avalonia#16673]
### Describe the bug

Using Avalonia 11.0.10, when binding a command using BindCommand in the code behind of the view as follows:

```
public MainView()
{
    this.WhenActivated(disposed =>
    {
        this.BindCommand(ViewModel, vm => vm.MyCommand, v => v.Button).DisposeWith(disposed);
    });
    
    InitializeComponent();
}
```

The following exception is being throw: 

Terminating app due to uncaught exception 'System.ArgumentException', reason: 'Property set method not found. (System.ArgumentException)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object , Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at ReactiveUI.CreatesCommandBindingViaCommandParameter.BindCommandToObject(ICommand command, Object target, IObservable`1 commandParameter) in /_/src/ReactiveUI/Bindings/Command/CreatesCommandBindingViaCommandParameter.cs:line 60
   at ReactiveUI.CreatesCommandBinding.BindCommandToObject(ICommand command, Object target, IObservable`1 commandParameter) in /_/src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs:line 39

### To Reproduce

1. Create a Cross Platform Avalonia Application.
2. Create a ReactiveCommand and bind to a control in the code behing file of the view.
3. Run the app using a iPad.

Can use the folowing repo:
https://github.com/yvcabrerago/AvaloniaReactiveApplication

### Expected behavior

The application should not crash.

### Avalonia version

11.0.10

### OS

iOS

**Comment by maxkatz6** [comment]
BindCommand uses reflection as you can see. Reflection does not work well with AOT.
I recommend opening such issues at https://github.com/reactiveui/ReactiveUI.

**Comment by maxkatz6** [comment]
@yvcabrerago btw, if you use XAML Bindings approach, there won't be such an issue too.
