### ISSUE TITLE
OpenGlException: Window 0 is invalid

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#16741]
Hi, we are using Avanolia 11.0.10 on a Windows 10 Build 14393.
The Main Window is shown, but when showing an addition Window, the WIndow has no content.
The following Exception is occuring on an on:

[Visual]Exception when rendering: 'Avalonia.OpenGL.OpenGlException: Window 0 is invalid.
   at Avalonia.OpenGL.Egl.EglDisplay.CreateWindowSurface(IntPtr window)
   at Avalonia.OpenGL.Egl.EglGlPlatformSurface.RenderTarget.BeginDrawCore()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext()
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()'(ServerCompositor #66009902)

### To Reproduce

Use Windows 10 Build 14393.
Use Avanolia 11.0.10.
Use a NativeMenu inside you app.
Click on a NativeMenuItem and show another window.

### Expected behavior

No error is occuring and the Window is shown correctly.

### Avalonia version

11.0.10

### OS

Windows

**Comment by FG-rgb** [comment]
When upgrading to Avalonia 11.1.3 the bug is solved. There for I closed it.
