### ISSUE TITLE
Open and Save file dialogs crash under Windows 7

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1700]
```
Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IShellItem.GetDisplayName(UInt32 sigdnName, IntPtr& ppszName)
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem)
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass0_0.<ShowFileDialogAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Controls.SaveFileDialog.ShowAsync(Window window)
   at Core2D.Avalonia.Editor.AvaloniaProjectEditorPlatform.OnSaveAs() in C:\projects\core2d\src\Core2D.Avalonia\Editor\AvaloniaProjectEditorPlatform.c
s:line 83
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Core2D.Avalonia.App.Start(IServiceProvider serviceProvider, AboutInfo aboutInfo) in C:\projects\core2d\src\Core2D.Avalonia\App.xaml.cs:line 147
```
```
Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IShellItem.GetDisplayName(UInt32 sigdnName, IntPtr& ppszName)
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem)
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass0_0.<ShowFileDialogAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Core2D.Avalonia.Editor.AvaloniaProjectEditorPlatform.OnOpen(String path) in C:\projects\core2d\src\Core2D.Avalonia\Editor\AvaloniaProjectEditorP
latform.cs:line 43
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Core2D.Avalonia.App.Start(IServiceProvider serviceProvider, AboutInfo aboutInfo) in C:\projects\core2d\src\Core2D.Avalonia\App.xaml.cs:line 147
```

**Comment by KvanTTT** [comment]
Unfortunately, it reproduced in the version of 0.7.0

**Comment by nopara73** [comment]
Correct: https://github.com/zkSNACKs/WalletWasabi/pull/1663#issuecomment-508287351
