### ISSUE TITLE
Assemblies referenced in namespaceresolver that are not included in build

### ISSUE THREAD

**Issue by Justin113D** [AvaloniaUI/Avalonia#17040]
### Describe the bug

I've had testers run a desktop app i made on their linux systems, and while it worked for some, it didn't work for the one using Fedora.

I received the following stack trace: 
<details> <summary>(Collapsible due to size)</summary>

    Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Controls.ColorPicker, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
    
    File name: 'Avalonia.Controls.ColorPicker, Culture=neutral, PublicKeyToken=null'
       at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
       at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
       at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.XamlTypeResolver.Resolve(String qualifiedTypeName)
       at Avalonia.Markup.Xaml.Extensions.ResolveType(IServiceProvider ctx, String namespacePrefix, String type)
       at Avalonia.Markup.Parsers.ExpressionNodeFactory.LookupType(Func`3 typeResolver, String namespace, String name)
       at Avalonia.Markup.Parsers.ExpressionNodeFactory.LogicalAncestorNode(Func`3 typeResolver, AncestorNode ancestor)
       at Avalonia.Markup.Parsers.ExpressionNodeFactory.CreateFromAst(List`1 astNodes, Func`3 typeResolver, INameScope nameScope, Boolean& isRooted)
       at Avalonia.Data.Binding.InstanceCore(AvaloniaProperty targetProperty, AvaloniaObject target, Object anchor, Boolean enableDataValidation)
       at Avalonia.Data.Binding.Instance(AvaloniaObject target, AvaloniaProperty targetProperty, Object anchor)
       at Avalonia.Data.BindingBase.Avalonia.Data.Core.IBinding2.Instance(AvaloniaObject target, AvaloniaProperty property, Object anchor)
       at Avalonia.AvaloniaObject.Bind(AvaloniaProperty property, IBinding binding, Object anchor)
       at Avalonia.AvaloniaObject.Bind(AvaloniaProperty property, IBinding binding)
       at Avalonia.AvaloniaObjectExtensions.Bind(AvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
       at CompiledAvaloniaXaml.!AvaloniaResources.XamlClosure_3.Build_57(IServiceProvider) in U:\Development\Repositories\J113D\Translation Editor\Libraries\J113D.Avalonia\J113D.Avalonia\Theme/Controls/SCRControls.axaml:line 57
       at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.PointerDeferredContent`1.InvokeBuilder(IServiceProvider serviceProvider)
       at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.DeferredContent`1.Build(IServiceProvider serviceProvider)
       at Avalonia.Markup.Xaml.Templates.TemplateContent.Load[T](Object templateContent)
       at Avalonia.Markup.Xaml.Templates.TemplateContent.Load(Object templateContent)
       at Avalonia.Markup.Xaml.Templates.ControlTemplate.Build(TemplatedControl control)
       at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
       at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
       at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
       at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
       at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
       at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
       at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
       at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
       at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
       at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
       at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding)
       at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize)
       at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
       at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
       at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
       at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
       at Avalonia.Controls.Window.ShowCore(Window owner)
       at Avalonia.Controls.Window.Show()
       at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
       at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
       at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
       at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
       at J113D.TranslationEditor.ProjectApp.Program.Main(String[] args) in U:\Development\Repositories\J113D\Translation Editor\Translation Editor\Program.cs:line 14
</details>

I looked into it by debugging the decompiled avalonia code, and after reaching the namespace resolve, i found these entries in the list:
![image](https://github.com/user-attachments/assets/3b28ccc0-9535-47e6-8f7b-d8c670b8c360)

As you can see, the app references `Avalonia.Controls.ColorPicker`, `Avalonia.Controls.DataGrid` or `Avalonia.Themes.Simple`, which is correct here, as they are transitive packages from `Avalonia.Diagnostics`. But the diagnostics package does not get included in release builds, and so its transitive packages don't get included either, yet somehow the namespace references do.

These references seem to originate from my external class library, which provides a custom avalonia theme i made. There i also include the package reference `<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.3" />` to allow for debugging (not including this line and instead just including it in the app project "works" too, but all controls start glitching out when opening the debug window).

### To Reproduce

NA

### Expected behavior

The app should not try to look up nonexistent assembly references.

### Avalonia version

11.1.3, 11.2.0-beta1

### OS

Linux

**Comment by timunie** [comment]
Diagnose package adds these references for DevTools. If you build it for release, these are not included unless you install them via nuget explicitly.
