### ISSUE TITLE
Scrolling ListBox items vigorously throws indexoutofboundsexception

### ISSUE THREAD

**Issue by RayyanTahir** [AvaloniaUI/Avalonia#1724]
I'm getting the following exception when I was vigorously scrolling a ListBox that was just freshly bound to a collection:

`System.IndexOutOfRangeException: 'Could not recycle container: not materialized.'`

**Stacktrace**

```
   at Avalonia.Controls.Generators.ItemContainerGenerator`1.TryRecycle(Int32 oldIndex, Int32 newIndex, Object item, IMemberSelector selector)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value)
   at Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value)
   at Avalonia.Controls.Presenters.ItemsPresenter.Avalonia.Controls.Primitives.IScrollable.set_Offset(Vector value)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.<>c__DisplayClass34_0.<UpdateScrollableSubscription>b__3(Vector x)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Skip`1._.OnNext(TSource value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.<>c__DisplayClass47_0`1.<SetAndRaiseCore>b__0()
   at Avalonia.Utilities.DeferredSetter`2.<>c__DisplayClass9_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass46_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass45_0`1.<SetAndRaise>b__0(Object val, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`2.SetAndNotify[TValue](TProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, SetAndRaiseCallback`1 setterCallback, T value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.set_Offset(Vector value)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.OnPointerWheelChanged(PointerWheelEventArgs e)
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass1_0`1.<AddClassHandler>b__0(Object sender, RoutedEventArgs e)
```

This exception is not raised that easily. You'll have to play with a ListBox being re-binded with two or more lists and immediately scrolling after the ListBox is bound.

**Comment by x2bool** [comment]
Probably dublicate of https://github.com/AvaloniaUI/Avalonia/issues/1395

**Comment by grokys** [comment]
Is this still happening @RayyanTahir ?

**Comment by grokys** [comment]
No reply for 2 years, closing.
