### ISSUE TITLE
TimePicker crash with Avalonia 11.2.0

### ISSUE THREAD

**Issue by beginor** [AvaloniaUI/Avalonia#17419]
### Describe the bug

TimePicker crashed when upgrade avalonia from 11.0.x to 11.2.0, the error log is:

```
00:00:00.002 |N| Application ReloadConfig: Loading configuration from: /Users/[redacted]/Library/Application Support/Ryujinx/Config.json
00:00:00.105 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.115 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.117 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.117 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.117 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.118 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.119 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.119 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xE0603EF
00:00:00.120 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.120 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.120 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.121 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.122 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: True
00:00:00.122 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.122 |I| Configuration LogValueChange: EnableLowPowerPtc set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.124 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.124 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.125 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.125 |I| Configuration LogValueChange: AudioVolume set to: 0.9
00:00:00.125 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.126 |I| Configuration LogValueChange: DramSize set to: MemoryConfiguration4GiB
00:00:00.126 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.126 |I| Configuration LogValueChange: UseHypervisor set to: False
00:00:00.127 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.128 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-dirty+04f014c777c5d2039573db9e300c4f22dac9d869
00:00:00.134 |N| Application Print: Operating System: macOS 15.1.0 (24B83) (Arm64)
00:00:00.134 |N| Application Print: CPU: Apple M1 Max ; 10 logical
00:00:00.135 |N| Application Print: RAM: Total 64 GiB ; Available 43.5 GiB
00:00:00.137 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.137 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.955 |E| .NET TP Worker 2024-11-03 10:25:48.649 Ryujinx[8352:423896] +[IMKClient subclass]: chose IMKClient_Modern
00:00:01.955 |E| .NET TP Worker 2024-11-03 10:25:48.649 Ryujinx[8352:423896] +[IMKInputSession subclass]: chose IMKInputSession_Modern
00:00:06.503 |E| .NET TP Worker [mvk-info] MoltenVK version 1.2.0, supporting Vulkan version 1.2.231.
00:00:06.503 |E| .NET TP Worker         The following 83 Vulkan extensions are supported:
00:00:06.503 |E| .NET TP Worker                 VK_KHR_16bit_storage v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_8bit_storage v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_bind_memory2 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_buffer_device_address v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_create_renderpass2 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_dedicated_allocation v3
00:00:06.503 |E| .NET TP Worker                 VK_KHR_depth_stencil_resolve v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_descriptor_update_template v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_device_group v4
00:00:06.503 |E| .NET TP Worker                 VK_KHR_device_group_creation v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_driver_properties v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_dynamic_rendering v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_fence v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_fence_capabilities v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_memory v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_memory_capabilities v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_semaphore v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_external_semaphore_capabilities v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_fragment_shader_barycentric v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_get_memory_requirements2 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_get_physical_device_properties2 v2
00:00:06.503 |E| .NET TP Worker                 VK_KHR_get_surface_capabilities2 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_imageless_framebuffer v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_image_format_list v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_maintenance1 v2
00:00:06.503 |E| .NET TP Worker                 VK_KHR_maintenance2 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_maintenance3 v1
00:00:06.503 |E| .NET TP Worker                 VK_KHR_multiview v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_portability_subset v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_push_descriptor v2
00:00:06.504 |E| .NET TP Worker                 VK_KHR_relaxed_block_layout v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_sampler_mirror_clamp_to_edge v3
00:00:06.504 |E| .NET TP Worker                 VK_KHR_sampler_ycbcr_conversion v14
00:00:06.504 |E| .NET TP Worker                 VK_KHR_separate_depth_stencil_layouts v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_shader_draw_parameters v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_shader_float_controls v4
00:00:06.504 |E| .NET TP Worker                 VK_KHR_shader_float16_int8 v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_shader_subgroup_extended_types v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_spirv_1_4 v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_storage_buffer_storage_class v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_surface v25
00:00:06.504 |E| .NET TP Worker                 VK_KHR_swapchain v70
00:00:06.504 |E| .NET TP Worker                 VK_KHR_swapchain_mutable_format v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_timeline_semaphore v2
00:00:06.504 |E| .NET TP Worker                 VK_KHR_uniform_buffer_standard_layout v1
00:00:06.504 |E| .NET TP Worker                 VK_KHR_variable_pointers v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_buffer_device_address v2
00:00:06.504 |E| .NET TP Worker                 VK_EXT_debug_marker v4
00:00:06.504 |E| .NET TP Worker                 VK_EXT_debug_report v10
00:00:06.504 |E| .NET TP Worker                 VK_EXT_debug_utils v2
00:00:06.504 |E| .NET TP Worker                 VK_EXT_descriptor_indexing v2
00:00:06.504 |E| .NET TP Worker                 VK_EXT_fragment_shader_interlock v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_hdr_metadata v2
00:00:06.504 |E| .NET TP Worker                 VK_EXT_host_query_reset v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_image_robustness v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_inline_uniform_block v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_memory_budget v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_metal_objects v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_metal_surface v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_post_depth_coverage v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_private_data v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_robustness2 v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_sample_locations v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_scalar_block_layout v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_separate_stencil_usage v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_shader_stencil_export v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_shader_viewport_index_layer v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_subgroup_size_control v2
00:00:06.504 |E| .NET TP Worker                 VK_EXT_swapchain_colorspace v4
00:00:06.504 |E| .NET TP Worker                 VK_EXT_texel_buffer_alignment v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_texture_compression_astc_hdr v1
00:00:06.504 |E| .NET TP Worker                 VK_EXT_vertex_attribute_divisor v3
00:00:06.504 |E| .NET TP Worker                 VK_AMD_gpu_shader_half_float v2
00:00:06.504 |E| .NET TP Worker                 VK_AMD_negative_viewport_height v1
00:00:06.504 |E| .NET TP Worker                 VK_AMD_shader_image_load_store_lod v1
00:00:06.504 |E| .NET TP Worker                 VK_AMD_shader_trinary_minmax v1
00:00:06.504 |E| .NET TP Worker                 VK_IMG_format_pvrtc v1
00:00:06.504 |E| .NET TP Worker                 VK_INTEL_shader_integer_functions2 v1
00:00:06.504 |E| .NET TP Worker                 VK_GOOGLE_display_timing v1
00:00:06.504 |E| .NET TP Worker                 VK_MVK_macos_surface v3
00:00:06.504 |E| .NET TP Worker                 VK_MVK_moltenvk v36
00:00:06.504 |E| .NET TP Worker                 VK_NV_fragment_shader_barycentric v1
00:00:06.504 |E| .NET TP Worker                 VK_NV_glsl_shader v1
00:00:06.504 |E| .NET TP Worker [mvk-info] GPU device:
00:00:06.504 |E| .NET TP Worker                 model: Apple M1 Max
00:00:06.504 |E| .NET TP Worker                 type: Integrated
00:00:06.504 |E| .NET TP Worker                 vendorID: 0x106b
00:00:06.504 |E| .NET TP Worker                 deviceID: 0xf0103ef
00:00:06.504 |E| .NET TP Worker                 pipelineCacheUUID: 260BAD42-0F01-03EF-0000-000000000000
00:00:06.504 |E| .NET TP Worker         supports the following Metal Versions, GPU's and Feature Sets:
00:00:06.504 |E| .NET TP Worker                 Metal Shading Language 2.4
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 7
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 6
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 5
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 4
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 3
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 2
00:00:06.504 |E| .NET TP Worker                 GPU Family Apple 1
00:00:06.504 |E| .NET TP Worker                 GPU Family Mac 2
00:00:06.504 |E| .NET TP Worker                 GPU Family Mac 1
00:00:06.504 |E| .NET TP Worker                 GPU Family Common 3
00:00:06.504 |E| .NET TP Worker                 GPU Family Common 2
00:00:06.504 |E| .NET TP Worker                 GPU Family Common 1
00:00:06.504 |E| .NET TP Worker                 macOS GPU Family 2 v1
00:00:06.504 |E| .NET TP Worker                 macOS GPU Family 1 v4
00:00:06.504 |E| .NET TP Worker                 macOS GPU Family 1 v3
00:00:06.504 |E| .NET TP Worker                 macOS GPU Family 1 v2
00:00:06.504 |E| .NET TP Worker                 macOS GPU Family 1 v1
00:00:06.504 |E| .NET TP Worker [mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 0 Vulkan extensions enabled:
00:00:17.854 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.TimePicker.SetGrid()
   at Avalonia.Controls.TimePicker.OnApplyTemplate(TemplateAppliedEventArgs e)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceEventsVTable.Signaled(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Ryujinx.Ava.Program.Main(String[] args) in /Users/[redacted]/Developer/dotnet/ryujinx/src/Ryujinx/Program.cs:line 64
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.TimePicker.SetGrid()
   at Avalonia.Controls.TimePicker.OnApplyTemplate(TemplateAppliedEventArgs e)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceEventsVTable.Signaled(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Ryujinx.Ava.Program.Main(String[] args) in 
```

### To Reproduce

1. Clone code from `https://github.com/GreemDev/Ryujinx.git` ;
2. Change Avalonia related package version from `11.0.x` to `11.2.0` in `Directory.Packages.props` file;
3. Start project `src/Ryujinx` ;
4. Open Settings dialog from menu `Options` > `Settings`;
5. Click `System` on the left side;

### Avalonia version

11.2.0

### OS

macOS

**Comment by rabbitism** [comment]
There is an update in TimePicker. You need to wait for FluentAvalonia newer version that implement this change.
