### ISSUE TITLE
If set x:DataType to a control type, binding command to method in the control is not invalid for Android

### ISSUE THREAD

**Issue by Supheria** [AvaloniaUI/Avalonia#17829]
### Describe the bug

When set DataContext to a control type, binding command to method in the control will cause `InvalidCastException` for Android, but which works ok on Windows (Linux and iOS hasn't tested).

Versions:
- Avalonia: 11.2.3
- Avalonia.Android: 11.2.3
- .Net: 9
- Android Platform API level: 35

Content of the exception:
> System.InvalidCastException: Specified cast is not valid.
>    at CompiledAvaloniaXaml.XamlIlTrampolines.Sample:Sample.Views.MyBorder+Test_0!CommandExecuteTrampoline(Object , Object )
>    at Avalonia.Data.Core.ExpressionNodes.MethodCommandNode.Command.Execute(Object parameter)
>    at Avalonia.Controls.Button.OnClick()
>    at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
>    at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
>    at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass1_0`1[[Avalonia.Input.PointerReleasedEventArgs, Avalonia.Base, Version=11.2.3.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b],[Avalonia.Input.InputElement, Avalonia.Base, Version=11.2.3.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e)
>    at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args)
>    at Avalonia.Reactive.AnonymousObserver`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.2.3.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(ValueTuple`2 value)
>    at Avalonia.Reactive.LightweightObservableBase`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.2.3.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].PublishNext(ValueTuple`2 value)
>    at Avalonia.Reactive.LightweightSubject`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.2.3.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(ValueTuple`2 value)
>    at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Input.TouchDevice.ProcessRawEvent(RawInputEventArgs ev)
>    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
>    at Avalonia.Controls.TopLevel.<>c.<HandleInput>b__145_0(Object state)
>    at Avalonia.Threading.Dispatcher.Send(SendOrPostCallback action, Object arg, Nullable`1 priority)
>    at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
>    at Avalonia.Android.Platform.Specific.Helpers.AndroidMotionEventsHelper.DispatchMotionEvent(MotionEvent e, Boolean& callBase)
>    at Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.ViewImpl.DispatchTouchEvent(MotionEvent e)
>    at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_(IntPtr jnienv, IntPtr native__this, IntPtr native_e) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Views.View.cs:line 16430
>    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_Z(_JniMarshal_PPL_Z callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 132

### To Reproduce

Create a solution with template: Avalonia Cross Platform Application

MainView.cs
```c#
using Avalonia.Controls;

namespace Sample.Views;

public partial class MainView : UserControl
{
    public MainView()
    {
        InitializeComponent();
        DataContext = TestBorder;
    }
}
```
---
MainView.axml
```xaml
<UserControl
    x:Class="Sample.Views.MainView"
    x:DataType="vm:MainViewModel"
    xmlns="https://github.com/avaloniaui"
    xmlns:views="using:Sample.Views"
    xmlns:vm="clr-namespace:Sample.ViewModels"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <views:MyBorder Name="TestBorder">
        <Button
            Command="{Binding Test}"
            Content="Test"
            x:DataType="views:MyBorder" />
    </views:MyBorder>
</UserControl>
```
---
MyBorder.cs
```c#
using System.Diagnostics;
using Avalonia.Controls;

namespace Sample.Views;

public class MyBorder : Border
{
    public void Test()
    {
        Debug.WriteLine("test invoked");
    }
}
```

### Expected behavior

Debug outputs "test invoked" same as on Windows.

### Avalonia version

11.2.3

### OS

Android

**Comment by oli-g-sk** [comment]
I was **just** about to report this.

In my case, it **definitely happens on Windows**.

```csharp
public class MainViewModel : ViewModelBase
{
    public ChildViewModel Child { get; } = new();
}

public class ChildViewModel : ViewModelBase
{
    public string HelloWorld { get; } = "Hello World";
}
```

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:app="clr-namespace:AvaloniaApplication2"
        x:Class="AvaloniaApplication2.MainWindow"
        x:DataType="app:MainViewModel">
    <Window.DataContext>
        <app:MainViewModel />
    </Window.DataContext>
    
    <app:ChildView DataContext="{Binding Child}" />
</Window>
```

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:app="clr-namespace:AvaloniaApplication2"
             x:Class="AvaloniaApplication2.ChildView"
             x:DataType="app:ChildViewModel">
    <TextBox Text="{Binding HelloWorld}" />
</UserControl>
```

**Comment by timunie** [comment]
@oli-g-sk your issue seems to be completely unrelated and I doubt it is even a bug in Avalonia. Please open a discussion and share the entire AvaloniaApplication2 test project without bin and obj folders there.
