### ISSUE TITLE
UiaRaiseAutomationPropertyChangedEvent causing exception code 0xc0000005 (AccessViolation)

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#17827]
### Describe the bug

Sorry I don't have too much information other than stack trace unfortunately.
Some of my Windows 11 users experience the following crash - 
Exception code: 0xc0000005
```
Application: FluentSearch.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Stack:
   at Avalonia.Win32.Automation.Interop.UiaCoreProviderApi.<UiaRaiseAutomationPropertyChangedEvent>g____PInvoke|5_0(Void*, Int32, Avalonia.Win32.Automation.Marshalling.ComVariant, Avalonia.Win32.Automation.Marshalling.ComVariant)
   at Avalonia.Win32.Automation.Interop.UiaCoreProviderApi.<UiaRaiseAutomationPropertyChangedEvent>g____PInvoke|5_0(Void*, Int32, Avalonia.Win32.Automation.Marshalling.ComVariant, Avalonia.Win32.Automation.Marshalling.ComVariant)
   at Avalonia.Win32.Automation.Interop.UiaCoreProviderApi.UiaRaiseAutomationPropertyChangedEvent(Avalonia.Win32.Automation.Interop.IRawElementProviderSimple, Int32, System.Object, System.Object)
   at Avalonia.Win32.Automation.AutomationNode.OnPeerPropertyChanged(System.Object, Avalonia.Automation.AutomationPropertyChangedEventArgs)
   at Avalonia.Automation.Peers.AutomationPeer.RaisePropertyChangedEvent(Avalonia.Automation.AutomationProperty, System.Object, System.Object)
   at Avalonia.Automation.Peers.ControlAutomationPeer.OwnerPropertyChanged(System.Object, Avalonia.AvaloniaPropertyChangedEventArgs)
   at Avalonia.Layout.Layoutable.ArrangeCore(Avalonia.Rect)
   at Avalonia.Layout.Layoutable.Arrange(Avalonia.Rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Avalonia.Size)
   at Avalonia.Layout.Layoutable.ArrangeCore(Avalonia.Rect)
   at Avalonia.Layout.Layoutable.Arrange(Avalonia.Rect)
   at Avalonia.Layout.LayoutManager.Arrange(Avalonia.Layout.Layoutable)
   at Avalonia.Layout.LayoutManager.Arrange(Avalonia.Layout.Layoutable)
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(Avalonia.Threading.DispatcherOperation)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(System.Threading.CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(Avalonia.Threading.IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(Avalonia.Threading.DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(System.String[])
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(System.String[])
   at Blast.Program.Main(System.String[])
```

### To Reproduce

It seems to happen when using `DataGrid`, I can't personally reproduce it.

### Expected behavior

Not crash

### Avalonia version

master

### OS

Windows

**Comment by adirh3** [comment]
@maxkatz6 I finally got some lead - it happens for ARM laptop users, when moving an Avalonia window between screens.
Will see if I can somehow emulate ARM64 and repro this myself.

**Comment by adirh3** [comment]
@maxkatz6 got other users reporting this. I personally don't have ARM64 laptop, but seems like users with ARM processors are getting this crash when UIA is getting triggered by any screen reader.
Do we want to disable UIA for now for ARM64 processors?

https://github.com/adirh3/Fluent-Search/issues/1156

**Comment by maxkatz6** [comment]
I don't think anybody on the team has an arm laptop on hands. I have had one temporary.

In the part we had an issue with incorrect PInvoke definitions, which worked fine on x64 ABI, but was failing on ARM.
In case of UiaRaiseAutomationPropertyChangedEvent it _shouldn't_ be the case, as there are three pointers and a single int32 parameter. Presence of COM and variants makes it tricky though.

**Comment by adirh3** [comment]
@maxkatz6 do we plan to make any workaround? Avalonia apps on Windows ARM64 are unusable in case the user has any kind of screen reader/accessibility program running.
Maybe we can disable UIA in ARM64 until this is fixed?

**Comment by kekekeks** [comment]
You can intercept and ignore WM_GETOBJECT as a temporary workaround. That will disable UIA

**Comment by AndreyRusyaev** [comment]
I've also stumbled into this problem as well. Workaround with ignoring WM_OBJECT brokes automation completely, so it's not a good solution, need a proper fix.

Researched the problem and find out that it was introduced here: https://github.com/AvaloniaUI/Avalonia/pull/16543 
And it seems that implementation of [ComVariant](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Automation/Marshalling/ComVariant.cs) is a root cause of native crash. 
Original dotnet implementation https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/ComVariant.cs has even ctor with Debug.Assert that properly fail on Avalonia ComVariant implementation in ARM64 platform.

Fix is pretty easy with just adding a Record field to ensure proper ComVariant native size. PR: https://github.com/AvaloniaUI/Avalonia/pull/20017
