### ISSUE TITLE
NullReferenceException using the VirtualizingStackPanel  [0.6.2-build5919-beta]

### ISSUE THREAD

**Issue by carlosga** [AvaloniaUI/Avalonia#1829]
NullReferenceException using a VirtualizingStackPanel inside as ItemsControl Panel Template:
```
    <ScrollViewer Name="MessageExplorerScrollViewer">

        <ItemsControl
            Classes="MessageExplorer" 
            Items="{Binding EntitiesView, Mode=OneWay}"
            ScrollViewer.HorizontalScrollBarVisibility="Disabled">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <VirtualizingStackPanel Orientation="Vertical" Margin="5" />
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
        </ItemsControl>

    </ScrollViewer>
```
Changing it to a StackPanel works fine:

```
    <ScrollViewer Name="MessageExplorerScrollViewer">

        <ItemsControl
            Classes="MessageExplorer" 
            Items="{Binding EntitiesView, Mode=OneWay}"
            ScrollViewer.HorizontalScrollBarVisibility="Disabled">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <StackPanel Orientation="Vertical" Margin="5" />
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
        </ItemsControl>

    </ScrollViewer>
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:

CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'

Stack trace:
   at Avalonia.Controls.Presenters.ItemVirtualizer.InvalidateScroll()
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Skip`1.Count._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Skip.cs:line 55
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass45_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, SetAndRaiseCallback`1 setterCallback, T value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ItemVirtualizer.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding)
   at Avalonia.Controls.Border.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding)
   at Avalonia.Controls.Primitives.AdornerDecorator.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding)
   at Avalonia.Controls.Border.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Controls.WindowBase.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Int32 index)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Object item)
   at Avalonia.Controls.Primitives.SelectingItemsControl.SelectedItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.System.Collections.IList.Add(Object value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.<set_SelectedItem>b__28_0(Object val, Object& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedItem(Object value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.<set_SelectedIndex>b__25_0(Int32 val, Int32& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedIndex(Int32 value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelection(Int32 index, Boolean select, Boolean rangeModifier, Boolean toggleModifier)
   at Avalonia.Controls.ListBox.OnPointerPressed(PointerPressedEventArgs e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   at System.Reactive.Observer`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Observers.cs:line 80
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt32 timestamp, IInputElement root, Point p, MouseButton button, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass28_0.<Signal>b__0()
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(Window mainWindow)
   at Conversa.Program.Run(IServiceProvider provider) in /../../Program.cs:line 59
   at Conversa.Program.Main(String[] args) in /../../Program.cs:line 25
```

### Further technical details
AvaloniaUI version: 0.6.2-build5919-beta
Operating system: Ubuntu 18.08
.NET Core Version: 2.1.302
IDE: Visual Studio Code

**Comment by Kryptos-FR** [comment]
That stack trace looks scary. Why is there some much depth? Probably not related to your issue though,  but it feels like there is an opportunity to change some recursive algorithm into an iterative one.

**Comment by jkoritzinsky** [comment]
I took a quick glance at the code and I think the problem is that somehow the virtualizer is being created with a null owner.

@Kryptos-FR the stack trace is large because it's deep in the visual tree running the layout algorithms.

**Comment by carlosga** [comment]
Doing some debugging today, it looks like the Owner has value, but the ItemVirtualizer being created is an ItemVirtualizerNone instance, and it looks like it doesn't have a way to perform the scroll invalidation.
I'm not sure why it's not being created as ItemVirtualizerSimple, will try to look further if i can.

**Comment by grokys** [comment]
Hmm yes `ItemsControl` has not really been tested with virtualization. Will fix.
