### ISSUE TITLE
Invoking button command via code causes "System.ObjectDisposedException"

### ISSUE THREAD

**Issue by thezaza101** [AvaloniaUI/Avalonia#1854]
Added code to invoke a button command via code when the user presses enter in a TextBox. When the button command is invoked via code it causes a "System.ObjectDisposedException", if the button is pressed manually by a user no exception occurs.

```
Exception has occurred: CLR/System.ObjectDisposedException
An unhandled exception of type 'System.ObjectDisposedException' occurred in Avalonia.Base.dll: 'Cannot access a disposed object.'
   at Avalonia.Utilities.RefCountable.Ref`1.Clone()
   at Avalonia.Rendering.SceneGraph.VisualNode.Clone(IVisualNode parent)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.Clone(VisualNode source, IVisualNode parent, Dictionary`2 index)
   at Avalonia.Rendering.SceneGraph.Scene.CloneScene()
   at Avalonia.Rendering.DeferredRenderer.UpdateScene()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at ui.Program.Main(String[] args) in D:\Projects\sc_ANN\ui\Program.cs:line 13
```

[code](https://github.com/thezaza101/sc_ANN/tree/master/ui/Views).

**Comment by MihaMarkic** [comment]
What is command doing? Did you try with empty command?

**Comment by jkoritzinsky** [comment]
Does this happen every time?

**Comment by thezaza101** [comment]
This does happen everytime. After more debugging it seems like the isssue is caused by calling the "            OnPropertyChanged" method in the ViewModel. The button is bound to the "RunCommand" method. When the command is run due to the user pressing the button it works fine.

```
        public void RunCommand(object s = null)
        {
            Log(CurrentCommand);
            _currentCommand = "";
            //if the "OnPropertyChanged" method isnt called then the error doesnt occur.
            OnPropertyChanged("CurrentCommand");
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName=null)
        {
            PropertyChanged?.Invoke(this,new PropertyChangedEventArgs(propertyName));
        }
```

**Comment by jkoritzinsky** [comment]
Perfect! I've been trying to track down a repro for this bug for a while. I'll take a look next time I have time to work on Avalonia!

**Comment by MihaMarkic** [comment]
@thezaza101 @jkoritzinsky 
I tested it for fun with original project first. I reproduced it on second enter. Then I updated Avalonia to 0.6.1 (from 0.6.0) and couldn't reproduce it anymore.
