### ISSUE TITLE
Shcore.dll is present but GetDpiForMonitor does not exist

### ISSUE THREAD

**Issue by Cyberboss** [AvaloniaUI/Avalonia#1912]
This is on Windows Server 2012 *NOT* R2. Seems it has the .dll but not this function

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetDpiForMonitor' in DLL 'shcore.dll'.
   at Avalonia.Win32.Interop.UnmanagedMethods.GetDpiForMonitor(IntPtr hmonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at Avalonia.Win32.WindowImpl.CreateWindow()
   at Avalonia.Win32.WindowImpl..ctor()
   at Avalonia.Win32.Win32Platform.CreateWindow()
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow()
   at Tgstation.Server.ControlPanel.Views.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Avalonia.Controls.AppBuilderBase1.Start[TMainWindow](Func1 dataContextProvider)
   at Tgstation.Server.ControlPanel.ControlPanel.Run(IUrlEncoder urlEncoder, IUpdater updater)
   at Tgstation.Server.ControlPanel.Windows.Program.Main()
```

**Comment by Gillibald** [comment]
We only support Windows 7 and newer and Windows Server 2012 is older as far as I know. Only Windows Server 2012 R2 could work.

**Comment by nc4rrillo** [comment]
I believe this API call recently gave us grief on Windows 8.1 too. Can’t we just check for IntPtr.Zero from GetProcAddress and avoid the OS check at all?

**Comment by grokys** [comment]
@Cyberboss this should have been fixed, is this still happening with the latest CI builds?

**Comment by PJB3005** [comment]
For what it's worth, we just had a user come in just now with the same problem. Avalonia version of our program being 0.9.9 (since we haven't published an update since). That should still have it fixed though so?

**Comment by caunt** [comment]
Today we have users with same problem - Avalonia 0.10-preview5

**Comment by danwalmsley** [comment]
@caunt @PJB3005 any info on what windows version? / setup?

**Comment by caunt** [comment]
> @caunt @PJB3005 any info on what windows version? / setup?

Windows 8
Intel Pentium N3540
NVIDIA GeForce 920M

**Comment by caunt** [comment]
We can gather more information from our users if it may help you with investigation. Just tell an list of details that you need from our users with that problem :)

**Comment by Gillibald** [comment]
As mentioned above this is supported from Windows 8.1 onwards so there might be an issue with the version detection.

**Comment by caunt** [comment]
![IMG_20201021_122553_037](https://user-images.githubusercontent.com/5324218/96700905-a50d4880-1398-11eb-98ee-988dc606c15f.jpg)
![IMG_20201021_122555_323](https://user-images.githubusercontent.com/5324218/96700909-a5a5df00-1398-11eb-9fba-66571b2dbe2b.jpg)

**Comment by caunt** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/1801#issuecomment-438151403

**Comment by caunt** [comment]
![IMG_20201029_202632_523](https://user-images.githubusercontent.com/5324218/97616331-15653b00-1a25-11eb-90ae-0565c53cc8d7.jpg)
