### ISSUE TITLE
Impossible to create WindowIcon as a resource in case of using path as Source.

### ISSUE THREAD

**Issue by FlaviusHouk** [AvaloniaUI/Avalonia#1947]
Environment: Fedora 28 x64, LXDE.

Code:
```
<Application.Resources>
<WindowIcon Source="valid-path-to-file" x:Key="key"/>
</Application.Resources>
```

Causes an exception in runtime, while CodeBehind works fine.
```
Icon=new WindowIcon("valid-path-to-file");
```

**Comment by danwalmsley** [comment]
@FlaviusHouk are you using embedded resource or a file in the build directory?

**Comment by FlaviusHouk** [comment]
```
<WindowIcon Source="NewFolder/music.png" x:Key="logo"/>
```
Here is original XAML code. NewFolder/music.png realy exists in the folder where application situates. 
And here is exception
```
Exception has occurred: CLR/Portable.Xaml.XamlObjectWriterException
An unhandled exception of type 'Portable.Xaml.XamlObjectWriterException' occurred in Avalonia.Markup.Xaml.dll: 'Cannot set unknown member '{clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls}WindowIcon.Source''
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartMember(XamlMember property)
   at Portable.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Object obj)
   at Music.App.Initialize() in /run/media/Flavius/3E38-C4D3/Music/Music/App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at Music.Program.Main(String[] args) in /run/media/Flavius/3E38-C4D3/Music/Music/Program.cs:line 11
```

**Comment by jmacato** [comment]
I just double-checked the exception and it seems that `WindowIcon` doesnt have a `Source` property.

**Comment by FlaviusHouk** [comment]
@jmacato, so there is no opportunity to create WindowIcon in XAML?

**Comment by FlaviusHouk** [comment]
@jmacato suggested solution works well. Thank you.
