### ISSUE TITLE
System.ArgumentOutOfRangeException in ReactiveCollectionMixins

### ISSUE THREAD

**Issue by nopara73** [AvaloniaUI/Avalonia#1988]
I've received this bug report today that makes my app crash: https://github.com/zkSNACKs/WalletWasabi/issues/750  

There are way too many turtles down as to spot at first sight what's causing this issue. While I am investigating it, I was hoping someone else have a better eye to spot the problem here, due to the familiarity with the code base.

## Relevant lines:

- Avalonia.Base\Threading\AvaloniaScheduler.cs:line 40
- Avalonia.Base\Threading\Dispatcher.cs:line 65
- Avalonia.Controls\Application.cs:line 237

## Stack trace:

```
2018-10-21 17:08:01 CRITICAL Program: System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at ReactiveUI.Legacy.ReactiveDerivedCollection`2.onSourceCollectionChanged(NotifyCollectionChangedEventArgs args) in D:\a\1\s\src\ReactiveUI\ReactiveCollectionMixins.cs:line 494
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 46
   at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 254
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Recursive.cs:line 89
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1() in C:\projects\Avalonia\src\Avalonia.Base\Threading\AvaloniaScheduler.cs:line 40
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in C:\projects\Avalonia\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\projects\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in C:\projects\Avalonia\src\Avalonia.Controls\Application.cs:line 237
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder,TMainWindow](TAppBuilder builder, String appName, IDockFactory layoutFactory, Func`1 dataContextProvider) in C:\Users\user\Desktop\WalletWasabi\WalletWasabi.Dependencies\AvalonStudio.Shell\src\AvalonStudio.Shell\Shell.cs:line 14
   at WalletWasabi.Gui.Program.Main(String[] args) in C:\Users\user\Desktop\WalletWasabi\WalletWasabi.Gui\Program.cs:line 26
```

**Comment by danwalmsley** [comment]
that's the problem. We initially implemented it as NotifyCollectionChanged, and we had this issue. Because its a hashset you cant know the insertion indexes (in theory) for collection changed event args.

So we made it a simple event to simply signal there has been a change, and the reactive list has an api to handle this scenario where it works out whats been removed, added and unchanged.

Was there a need to implement INCC interface?

**Comment by nopara73** [comment]
> Was there a need to implement INCC interface?

I was just adding test cases for this.

@danwalmsley Thank you! I fixed it and commented in the code that in the future don't make it change and linked to this issue.

**Comment by danwalmsley** [comment]
Good to hear its fixed I was getting worried :)

**Comment by nopara73** [comment]
I need to be much more careful from the 1.0 release. This was very bad.
