### ISSUE TITLE
Exception in render loop

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2063]
I have recently started seeing these exceptions. I've yet to create a simple repro but they occur in my app which has a lot of the screen being continuously updated, the exceptions only seem to occur when I do things like mouseover a button.  

```
Visual: Exception in render loop: "System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in D:\a\1\s\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 120"
```

```
Visual: Exception in render loop: "System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Ref<Avalonia.Rendering.SceneGraph.Scene>'.
   at Avalonia.Utilities.RefCountable.Ref`1.Clone() in D:\a\1\s\src\Avalonia.Base\Utilities\Ref.cs:line 186
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 173
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in D:\a\1\s\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 120"
```

**Comment by ahopper** [comment]
appears fixed in v0.7.1-build731-beta possibly by #2117 ?

**Comment by ahopper** [comment]
fixed by #2351

**Comment by EgorOkhotin** [comment]
I have this issue in 0.8.1 version
`'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.13\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Visual: Exception in render update: "System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Visual node for {node.Visual}'.
   at Avalonia.Rendering.SceneGraph.VisualNode.ReplaceChild(Int32 index, IVisualNode node) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\VisualNode.cs:line 155
   at Avalonia.Rendering.SceneGraph.DeferredDrawingContextImpl.BeginUpdate(VisualNode node) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\DeferredDrawingContextImpl.cs:line 60
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(DrawingContext context, Scene scene, VisualNode node, Rect clip, Boolean forceRecurse) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 166
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(DrawingContext context, Scene scene, VisualNode node, Rect clip, Boolean forceRecurse) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 222
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(DrawingContext context, Scene scene, VisualNode node, Rect clip, Boolean forceRecurse) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 222
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(DrawingContext context, Scene scene, VisualNode node, Rect clip, Boolean forceRecurse) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 222
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(DrawingContext context, Scene scene, VisualNode node, Rect clip, Boolean forceRecurse) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 222
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(Scene scene, IVisual visual) in D:\a\1\s\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 83
   at Avalonia.Rendering.DeferredRenderer.UpdateScene() in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 526
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Update(TimeSpan time) in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 210
   at Avalonia.Rendering.RenderLoop.<>c__DisplayClass11_0.<TimerTick>b__1() in D:\a\1\s\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 107"
`
What could it be? Is my code reason for an error or it is a bug of Avalonia?

**Comment by KyleC69** [comment]
I am now receiving this error upon application startup. Seems to occur during the first attempt to interact with the application from mouse over to button click and sometimes even further into the application. The error msg and stack varies. How can we track this down.
