### ISSUE TITLE
InvalidOperationException when pressing TAB to change focus

### ISSUE THREAD

**Issue by lontivero** [AvaloniaUI/Avalonia#2089]
## Summary
Avalonia throws an `InvalidOperationException` exception when navigating controls pressing TAB ke. 

## How to reproduce it

1. Run the ControlCatalog.NetCore project
2. Go to the TextBox panel
3. Do click on any textbox to focus it
4. Press Tab key until the exception is rised

## Original issue
https://github.com/zkSNACKs/WalletWasabi/issues/814

## Exception details

<details>
<summary>Stack trace (click to open)</summary>

```
Unhandled Exception: System.InvalidOperationException: Control is not attached to visual tree.
   at Avalonia.VisualExtensions.GetRootAndPosition(IVisual v) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/VisualExtensions.cs:line 74
   at Avalonia.VisualExtensions.TranslatePoint(IVisual visual, Point point, IVisual relativeTo) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/VisualExtensions.cs:line 50
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 175
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at System.Linq.Enumerable.<CastIterator>d__34`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/InputExtensions.cs:line 39
   at Avalonia.Input.MouseDevice.SetPointerOver(IPointerDevice device, IInputRoot root, Point p) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 323
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, IInputRoot root, Point p, InputModifiers inputModifiers) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 208
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 139
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 104
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/InputManager.cs:line 38
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/TopLevel.cs:line 350
   at Avalonia.Gtk3.WindowBaseImpl.<>c__DisplayClass94_0.<OnInput>b__0() in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/WindowBaseImpl.cs:line 400
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 169
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 40
   at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass29_0.<Signal>b__0() in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 135
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data) in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Interop/GlibTimeout.cs:line 12
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken) in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 108
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/Dispatcher.cs:line 64
   at Avalonia.Application.Run(Window mainWindow) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/Application.cs:line 259
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/AppBuilderBase.cs:line 128
   at ControlCatalog.NetCore.Program.Main(String[] args) in /home/lontivero/GitHub/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 33
```

</details>

**Comment by ahopper** [comment]
This looks like an exception fixed in https://github.com/AvaloniaUI/Avalonia/pull/2067 and described in https://github.com/AvaloniaUI/Avalonia/issues/2079
