### ISSUE TITLE
Skia exception on resize with no Window MinWidth and MinHeight set

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2119]
To repro, remove the MinHeight and MinWidth from ControlCatalog MainWindow.xml then resize by dragging the bottom right corner to the top of the window or just run the Virtualization demo and resize the same way.
This was on windows using skia.
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to create Skia render target surface
  Source=Avalonia.Skia
  StackTrace:
   at Avalonia.Skia.SurfaceRenderTarget..ctor(CreateInfo createInfo) in C:\Users\alan\Documents\GitHub\Avalonia\src\Skia\Avalonia.Skia\SurfaceRenderTarget.cs:line 43
   at Avalonia.Skia.DrawingContextImpl.CreateRenderTarget(Int32 width, Int32 height, Vector dpi, Nullable`1 format) in C:\Users\alan\Documents\GitHub\Avalonia\src\Skia\Avalonia.Skia\DrawingContextImpl.cs:line 629
   at Avalonia.Skia.DrawingContextImpl.CreateLayer(Size size) in C:\Users\alan\Documents\GitHub\Avalonia\src\Skia\Avalonia.Skia\DrawingContextImpl.cs:line 231
   at Avalonia.Rendering.RenderLayer.ResizeBitmap(Size size, Double scaling) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\RenderLayer.cs:line 34
   at Avalonia.Rendering.RenderLayers.Update(Scene scene, IDrawingContextImpl context) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\RenderLayers.cs:line 32
   at Avalonia.Rendering.DeferredRenderer.Render(Scene scene, Boolean forceComposite) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 236
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 208
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 147
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect) in C:\Users\alan\Documents\GitHub\Avalonia\src\Avalonia.Controls\TopLevel.cs:line 258
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\alan\Documents\GitHub\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.cs:line 656
```

**Comment by Gillibald** [comment]
This prevents the exception:
```
        private static SKImageInfo MakeImageInfo(int width, int height, PixelFormat? format)
        {
            var colorType = PixelFormatHelper.ResolveColorType(format);

            return new SKImageInfo(Math.Max(width, 1), Math.Max(height, 1), colorType, SKAlphaType.Premul);
        }
```
