### ISSUE TITLE
InvalidCastException on Popup.Open

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#2137]
Version: 0.7.0

Occurs when adding a `Popup` to the `LogicalChildren` of a `PopupRoot`.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'RoslynPad.MainWindow' to type 'Avalonia.Controls.Primitives.Popup'.
   at Avalonia.Controls.Primitives.Popup.Open() in D:\a\1\s\src\Avalonia.Controls\Primitives\Popup.cs:line 255
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 505
   at Avalonia.AvaloniaObject.<>c__DisplayClass46_0`1.<SetAndRaiseCore>b__0() in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 596
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 144
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 597
   at Avalonia.AvaloniaObject.<>c__DisplayClass45_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 576
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 553
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 140
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, SetAndRaiseCallback`1 setterCallback, T value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 547
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 572
```

**Comment by grokys** [comment]
@ahopper this was introduced in #1489. The problem is that on [this line](https://github.com/AvaloniaUI/Avalonia/blob/fe74dfe53856f6c4866464e42708edbd2a6af4a9/src/Avalonia.Controls/Primitives/Popup.cs#L257):

```csharp
((Popup)(parentPopuproot.Parent)).Closed += ParentClosed;
```

`parentPopuproot.Parent` is not a `Popup`, it's an instance of `AvaloniaEdit.Demo.MainWindow`. This si because AvaloniaEdit is manually creating and reparenting the `PopupRoot`.

I guess the solution here is simply to make sure that parent is a `Popup`, but I wanted to run it by you first.
