### ISSUE TITLE
Unable to load Gdk

### ISSUE THREAD

**Issue by deinok** [AvaloniaUI/Avalonia#2140]
Hi, Seems like Avalonia is throwing me the following error:

```log
Unhandled Exception: System.AggregateException: Unable to load Gdk (Exception of type 'Avalonia.Platform.Interop.DynamicLibraryLoaderException' was thrown.) ---> Avalonia.Platform.Interop.DynamicLibraryLoaderException: Exception of type 'Avalonia.Platform.Interop.DynamicLibraryLoaderException' was thrown.
   at Avalonia.Shared.PlatformSupport.UnixLoader.LoadLibrary(String dll)
   at Avalonia.Gtk3.Interop.Resolver.LoadDll(IDynamicLibraryLoader loader, GtkDll dll)
   --- End of inner exception stack trace ---
   at Avalonia.Gtk3.Interop.Resolver.LoadDll(IDynamicLibraryLoader loader, GtkDll dll)
   at Avalonia.Gtk3.Interop.Resolver.<>c__DisplayClass8_0.<Resolve>b__1(GtkDll x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Avalonia.Gtk3.Interop.Resolver.Resolve(String basePath)
   at Avalonia.Gtk3.X11.XInitThreads()
   at Avalonia.Gtk3.Gtk3Platform.Initialize(Gtk3PlatformOptions options)
   at Avalonia.Gtk3AppBuilderExtensions.<>c__DisplayClass0_0`1.<UseGtk3>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
```

I supose that there is some libraries missing in my OS.
The OS is build with Buildroot an Arch is ARM. 
Code published using the `linux-arm`. What *.so is expected the OS to have?

**Comment by deinok** [comment]
So, libgtk-3-0 and rebuild SkiaSharp for ARM. Thanks ;)
