### ISSUE TITLE
NumericUpDown.ValueChanged crashes

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2216]
First of all, the event doesn't fire when the control loses focus; it only fires when using the spin buttons. However, when you do use the spin buttons, it crashes with `ArgumentException: Object of type 'Avalonia.Controls.NumericUpDownValueChangedEventArgs' cannot be converted to type 'Avalonia.Controls.SpinEventArgs'.`
StackTrace:
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 192
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 156
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 141
   at Avalonia.Controls.Button.OnClick() in D:\a\1\s\src\Avalonia.Controls\Button.cs:line 218
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Button.cs:line 262
   at Avalonia.Controls.RepeatButton.OnPointerReleased(PointerReleasedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\RepeatButton.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args) in D:\a\1\s\src\Avalonia.Interactivity\RoutedEvent.cs:line 115
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 188
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 156
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 141
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, IInputRoot root, Point p, MouseButton button, InputModifiers inputModifiers) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 247
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 109
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in D:\a\1\s\src\Avalonia.Input\InputManager.cs:line 39
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\a\1\s\src\Windows\Avalonia.Win32\WindowImpl.cs:line 692
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 108
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
   at Kermalis.PokemonBattleEngineClient.App.Main(String[] args) in D:\Development\GitHub\PokemonBattleEngine\PokemonBattleEngineClient\App.xaml.cs:line 10
```

**Comment by Kermalis** [comment]
Same error when setting Value programmatically.

**Comment by grokys** [comment]
@DmitryZhelnin you ported this control to Avalonia. Did you want to fix this issue?

**Comment by DmitryZhelnin** [comment]
> 
> 
> @DmitryZhelnin you ported this control to Avalonia. Did you want to fix this issue?

Hi! I'll try to fix this as soon as possible!

**Comment by DmitryZhelnin** [comment]
Hi @Kermalis . Could you provide some more info about your issue? What OS do you use? What version of Avalonia? Could  you include minimal example?

**Comment by Gillibald** [comment]
Is that line I posted valid code? Doesn't look to me that the event args are right. Maybe I am missing something.

**Comment by DmitryZhelnin** [comment]
@Gillibald yea, changing `SpinEventArgs` to `NumericUpDownValueChangedEventArgs` fixes the issue.
Should I create PR or you can just fix it in the main repo?

**Comment by Kermalis** [comment]
I'm on windows 7, using avalonia nightly builds.
```cs
            NumericUpDown level = this.FindControl<NumericUpDown>("Level");
            level.ValueChanged += shellOnly;
            level.Value = 1; // Crash here, or when using spin buttons
```
I assume it's crashing only when there's an event handler added like I have here. I don't know how it'd go unnoticed otherwise.
