### ISSUE TITLE
UniformGrid Unusable

### ISSUE THREAD

**Issue by LFP6** [AvaloniaUI/Avalonia#2223]
At least in XAML, I have not tried using it outside of XAML at this point. Also noticed that it's in the "Primatives" folder, which would imply it is supposed to be a component of something else, but it is not used anywhere (and is a component which I would like to use in my layout at any rate).

**Test case 1**
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1">
      <UniformGrid Columns="2" FirstColumn="1">
        <TextBlock>Test</TextBlock>
        <TextBlock>Test</TextBlock>
      </UniformGrid>
</Window>
```
Error:
```
Portable.Xaml.XamlObjectWriterException: The value  for 'Content' property is null
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteGetObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteGetObject()
   at Portable.Xaml.XamlObjectWriter.WriteGetObject()
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```
**Test case 2**
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1">
  <StackPanel>
      <UniformGrid Columns="2" FirstColumn="1">
        <TextBlock>Test</TextBlock>
        <TextBlock>Test</TextBlock>
      </UniformGrid>
  </StackPanel>
</Window>
```
Error:
```
System.NotSupportedException: Current operation is valid only when the underlying type on a XamlType is known, but it is unknown for '{https://github.com/avaloniaui}UniformGrid'
   at Portable.Xaml.Schema.XamlTypeInvoker.ThrowIfUnknown()
   at Portable.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at Portable.Xaml.XamlObjectWriterInternal.InitializeObjectIfRequired(Boolean waitForParameters, Boolean required)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteStartObject(XamlType xamlType)
   at Portable.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.Load(Stream stream, Object rootInstance, Uri uri)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```
**Test case 3**
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1">
  <ItemsControl>
    <ItemsControl.ItemsPanel>
      <ItemsPanelTemplate>
        <UniformGrid></UniformGrid>
      </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>
  </ItemsControl>
</Window>
```
Error:
```
Portable.Xaml.XamlObjectWriterException: GetObject is not allowed at current state Initial
   at Portable.Xaml.XamlWriterStateManager.CheckState(XamlNodeType next)
   at Portable.Xaml.XamlWriterInternalBase.WriteGetObject()
   at Portable.Xaml.XamlObjectWriter.WriteGetObject()
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoaderPortableXaml.LoadFromReader(XamlReader reader, AvaloniaXamlContext context)
   at Avalonia.Markup.Xaml.Templates.TemplateContent.Load()
   at Avalonia.Markup.Xaml.Templates.ItemsPanelTemplate.Build()
   at Avalonia.Controls.Presenters.ItemsPresenterBase.CreatePanel()
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Border.MeasureOverrideImpl(Size availableSize, IControl child, Thickness padding, Double borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Primitives.AdornerDecorator.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Border.MeasureOverrideImpl(Size availableSize, IControl child, Thickness padding, Double borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass(ILayoutRoot root)
   at Avalonia.Controls.Window.Show()
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```

**Comment by ahopper** [comment]
Not sure what is happening here, I tried all you examples in a fresh project from the vs mvvm template and they all work both on 0.7.0 and current nightly builds.

**Comment by LFP6** [comment]
That clued me in to the issue - the NuGet package was out of date. >.< Should've figured that was the issue since the component didn't look like it was being recognized. Sorry about that, but thanks for getting me on the right track.
