### ISSUE TITLE
NullReferenceException in DeferredRenderer

### ISSUE THREAD

**Issue by lontivero** [AvaloniaUI/Avalonia#2284]
This issue was originally reported in Wasabi wallet repository https://github.com/zkSNACKs/WalletWasabi/issues/1147

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 266
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect) in D:\a\1\s\src\Avalonia.Controls\TopLevel.cs:line 269
   at Avalonia.X11.X11Window.DoPaint() in D:\a\1\s\src\Avalonia.X11\X11Window.cs:line 611
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.X11\X11PlatformThreading.cs:line 167
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.X11\X11PlatformThreading.cs:line 240
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 64
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
```
 
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs#L266

It seems for some reason the `scene.Item` is null.

**Comment by nopara73** [comment]
While it can be inferred from the Exception, I think it's worth explicitly noting that, this is Linux related.
