### ISSUE TITLE
NullReferenceException disposing WindowBaseImpl

### ISSUE THREAD

**Issue by lontivero** [AvaloniaUI/Avalonia#2308]
Cross posted from https://github.com/zkSNACKs/WalletWasabi/issues/1163#issuecomment-464037101
```
2019-02-15 13:05:20 INFO UiConfig: UiConfig is saved.
2019-02-15 13:05:20 WARNING MainWindow: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowBaseImpl.Dispose() in /Users/vsts/agent/2.144.2/work/1/s/src/Avalonia.Native/WindowImplBase.cs:line 257
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in D:\a\1\s\src\Avalonia.Controls\Window.cs:line 312
   at WalletWasabi.Gui.MainWindow.ClosingAsync() in /Users/molnardavid/Desktop/work/WalletWasabi/WalletWasabi.Gui/MainWindow.xaml.cs:line 110
```
related with this line: https://github.com/AvaloniaUI/Avalonia/blob/dbbb5bd944d2f20a3013b6edd1a9830eff6e07d8/src/Avalonia.Native/WindowImplBase.cs#L256
---

**Comment by danwalmsley** [comment]
Fixed
