### ISSUE TITLE
ArgumentException when Animation.Duration has a Binding in XAML

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/Avalonia#2386]
Setting `Animation.Duration` with a `Binding` like so:

```
<Animation IterationCount="Infinite" Duration="{Binding Duration}">
    <!-- ... -->
</Animation>
```

Causes the following exception on startup:

```
System.ArgumentException: 'Value of type Avalonia.Data.Binding cannot be assigned to member with type System.TimeSpan
Parameter name: value'
   at Portable.Xaml.MemberExpressionExtensions.<>c__DisplayClass8_0.<BuildCallExpression>b__0(Object instance, Object value)
   at Avalonia.Markup.Xaml.PortableXaml.AvaloniaXamlObjectWriter.DelayedValuesHelper.ApplyAll()
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at Sage.Views.MainWindow.InitializeComponent()
   at Sage.Views.MainWindow..ctor()
```

Setting `Duration` to a hardcoded value, or creating the binding in code works as expected:

```
public class MainWindowViewModel : ViewModelBase
{
    public void Test()
    {
        var anim = new Animation();
        anim.Bind(Animation.DurationProperty, new Binding { Source = this, Path = nameof(Duration) });
        Console.WriteLine("Duration: " + anim.Duration.Seconds);
    }

    public TimeSpan Duration => TimeSpan.FromSeconds(3);
}
```

The above example prints `Duration: 3`.

**Comment by jmacato** [comment]
Those properties [(Animation.cs)](https://github.com/AvaloniaUI/Avalonia/blob/a8d5814a10198b0c42fff3a5b13d24eccb77703a/src/Avalonia.Animation/Animation.cs) are Direct properties, perhaps they could be changed to Styled ones? But iirc bindings should work with Direct Properties too...

**Comment by grokys** [comment]
Yes, bindings should work with direct properties.

**Comment by OronDF343** [comment]
This has been fixed at some point. Closing the issue.
