### ISSUE TITLE
(macOS) ContextMenu.Open(Control control) fails when debugging with VS Code

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2396]
I have a XAML defined Canvas with a ContextMenu. I prefer the Left Click for opening this one, so I'm using Canvas Click event to open it with `Canvas.ContextMenu.Open(Canvas);`.

This works as expected on Windows and the ContextMenu appears under the pointer. 

However it fails on macOS with trace:
```
Exception thrown: 'System.NullReferenceException' in Avalonia.Native.dll: 'Object reference not set to an instance of an object.'
   at Avalonia.Native.ScreenImpl.get_AllScreens()
   at Avalonia.Controls.Screens.ScreenFromPoint(PixelPoint point)
   at Avalonia.Controls.Primitives.PopupRoot.SnapInsideScreenEdges()
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass50_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass49_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.Controls.ContextMenu.Open(Control control)
```

The same trace if I instead try `Canvas.ContextMenu.Open(this);`. Both attempts work perfectly if using `$ dotnet run` instead of VS Code's debugger.

**Comment by mat1jaczyyy** [comment]
This doesn't crash anymore in both 0.8.999-cibuild0003269-beta and 0.8.999-cibuild0003524-beta.
