### ISSUE TITLE
Thumb doesn't fire PointerPressed and PointerReleased

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2454]
I would like to handle these events because their EventArgs allow me to check for which mouse button was pressed. For my use case, either allowing these events to be handled or adding mouse button info to the Drag events would be nice.

**Comment by Gillibald** [comment]
Thumb marks these events as handled and that might be the reason these events aren't raised for you. I wonder if marking them as handled is really needed. The only way to react to these events is to override OnPointerPressed etc.

**Comment by mat1jaczyyy** [comment]
@Gillibald, if i override the method, i would need to rewrite the logic that handles dragging, I would avoid this if possible

**Comment by grokys** [comment]
@mat1jaczyyy do you know how this is handled in WPF or UWP?

**Comment by mat1jaczyyy** [comment]
@grokys in WPF, MouseUp does not fire, however PreviewMouseUp does. As far as I know, Avalonia does not have an equivalent event.

**Comment by grokys** [comment]
It does actually, though it's not exposed via a CLR event. Like in WPF you can use `AddHandler` to listen for an event: https://wpf.2000things.com/2012/07/03/593-addhandler-method-can-add-handler-for-any-event/

If you pass `RoutingStrategies.Tunnel` you will get the tunneling event that the `Preview*` events expose in WPF. Here's an example:

https://github.com/AvaloniaUI/Avalonia/blob/b6ee0d025bc32469c17e56934e4981e164a424e1/src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs#L57

Note you can also pass `handledEventsToo: true` to get events that have been marked as `e.Handled = true`: https://github.com/AvaloniaUI/Avalonia/blob/b6ee0d025bc32469c17e56934e4981e164a424e1/src/Avalonia.Interactivity/Interactive.cs#L39

**Comment by mat1jaczyyy** [comment]
@grokys thanks, I didn't think of AddHandler. I've added the handler to the thumb like this:
```cs
// in .ctor
Base.AddHandler(InputElement.PointerReleasedEvent, MouseUp, RoutingStrategies.Tunnel, true);

// handler method
private void MouseUp(object sender, PointerReleasedEventArgs e) {
    // do stuff
}
```

However I run into a crash:
```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'Control is not attached to visual tree.'
   at Avalonia.Input.MouseDevice.GetPosition(IVisual relativeTo)
   at Avalonia.Controls.Primitives.Thumb.OnPointerReleased(PointerReleasedEventArgs e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, IInputRoot root, Point p, MouseButton button, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(Window mainWindow)
   at Apollo.Core.Program.Main(String[] args) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Core\Program.cs:line 91
```

What's interesting is that there is no crash and the event works as expected if I start holding the mouse button outside the Thumb, drag it into the Thumb and release the button. I've also tried the PointerPressed event, which crashes with the same error as soon as I click.

**Comment by grokys** [comment]
> Control is not attached to visual tree.

Are you removing controls in response to these events?

**Comment by mat1jaczyyy** [comment]
@grokys Yes, the code inside PointerReleased does indeed remove the Thumb itself from its parent.

**Comment by grokys** [comment]
Ok, yeah that's not something that `Thumb` (or any control really)  expects to happen... Maybe we need to not throw when calling `e.GetPosition` on a control that has been removed from the visual tree - only problem is that it's impossible to return a meaningful result from that method if the control isn't shown.

Need to look around and find out how other frameworks handle this.

**Comment by mat1jaczyyy** [comment]
@grokys the crash is avoided by setting Handled to true
