### ISSUE TITLE
An item with the same key has already been added. Key: [0, Avalonia.Controls.Generators.ItemContainerInfo]

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2507]
```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: [0, Avalonia.Controls.Generators.ItemContainerInfo]
  Source=System.Collections
  StackTrace:
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Materialize(Int32 index, Object item, IMemberSelector selector) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Generators\ItemContainerGenerator.cs:line 65
   at Avalonia.Controls.Presenters.ItemContainerSync.AddContainers(ItemsPresenterBase owner, Int32 index, IEnumerable items) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 91
   at Avalonia.Controls.Presenters.ItemContainerSync.<ItemsChanged>g__Add|0_0(<>c__DisplayClass0_0& ) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 32
   at Avalonia.Controls.Presenters.ItemContainerSync.ItemsChanged(ItemsPresenterBase owner, IEnumerable items, NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 43
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsChanged(NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 214
   at Avalonia.Controls.Presenters.CarouselPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\CarouselPresenter.cs:line 102
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 252
   at Avalonia.Collections.NotifyCollectionChangedExtensions.<>c__DisplayClass1_0.<WeakSubscribe>b__0(NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Collections\NotifyCollectionChangedExtensions.cs:line 43
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Reactive\LightweightObservableBase.cs:line 132
   at Avalonia.Collections.NotifyCollectionChangedExtensions.WeakCollectionChangedObservable.OnEvent(Object sender, NotifyCollectionChangedEventArgs e) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Collections\NotifyCollectionChangedExtensions.cs:line 76
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Utilities\WeakSubscriptionManager.cs:line 187
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 502
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in C:\DOWNLOADS\GitHub-Forks\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 190
   at ControlCatalog.Pages.ReproPage.AddView() in C:\DOWNLOADS\GitHub-Forks\Avalonia\samples\ControlCatalog\Pages\ReproPage.xaml.cs:line 52
```

Repro (click `AddView` button):
```XAML
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog"
             x:Class="ControlCatalog.Pages.ReproPage">
    <DockPanel>
        <TabStrip Items="{Binding Views}" SelectedItem="{Binding CurrentView, Mode=TwoWay}" Focusable="false" DockPanel.Dock="Bottom">
            <TabStrip.ItemsPanel>
                <ItemsPanelTemplate>
                    <WrapPanel/>
                </ItemsPanelTemplate>
            </TabStrip.ItemsPanel>
            <TabStrip.DataTemplates>
                <DataTemplate DataType="local:View">
                    <StackPanel Orientation="Horizontal" Spacing="2">
                        <TextBlock Text="{Binding Title}" Foreground="Red" Margin="2"/>
                    </StackPanel>
                </DataTemplate>
            </TabStrip.DataTemplates>
        </TabStrip>
        <StackPanel Orientation="Horizontal" Spacing="2" DockPanel.Dock="Top">
            <Button Content="AddView" Command="{Binding AddView}"/>
        </StackPanel>
        <Border>
            <Carousel Items="{Binding Views}" SelectedItem="{Binding CurrentView, Mode=TwoWay}" IsVirtualized="False">
                <Carousel.DataTemplates>
                    <DataTemplate DataType="local:View">
                        <Border>
                            <TextBlock Text="{Binding Title}"/>
                        </Border>
                    </DataTemplate>
                </Carousel.DataTemplates>
            </Carousel>
        </Border>
    </DockPanel>
</UserControl>
```

```C#
using System.Linq;
using Avalonia;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace ControlCatalog.Pages
{
    public class View
    {
        public string Title { get; set; }
    }

    public class ReproPage : UserControl
    {
        public static readonly AvaloniaProperty ViewsProperty =
            AvaloniaProperty.Register<AutoCompleteBoxPage, AvaloniaList<View>>(nameof(Views));

        public static readonly AvaloniaProperty CurrentViewProperty =
            AvaloniaProperty.Register<AutoCompleteBoxPage, View>(nameof(CurrentView));

        public AvaloniaList<View> Views
        {
            get => (AvaloniaList<View>)GetValue(ViewsProperty);
            set => SetValue(ViewsProperty, value);
        }

        public View CurrentView
        {
            get => (View)GetValue(CurrentViewProperty);
            set => SetValue(CurrentViewProperty, value);
        }

        public AvaloniaList<View> CreateViews()
        {
            return new AvaloniaList<View>()
            {
            };
        }
        int count = 0;
        public void RemoveCurrentView()
        {
            Views.Remove(CurrentView);
            CurrentView = Views.FirstOrDefault();
        }

        public void AddView()
        {
            Views.Add(new View() { Title = $"--{count++}--" });
            CurrentView = Views.LastOrDefault();
        }

        public void RestoreViews()
        {
            Views = CreateViews();
            CurrentView = Views.FirstOrDefault();
        }

        public ReproPage()
        {
            this.InitializeComponent();

            RestoreViews();

            DataContext = this;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

https://github.com/wieslawsoltes/Avalonia/tree/SelectingItemsControlIssue

**Comment by danwalmsley** [comment]
I am also experiencing this issue in Wasabi Wallet and AvalonStudio
