### ISSUE TITLE
Unknown pixel format: Bgra8888 in docker

### ISSUE THREAD

**Issue by gosha20777** [AvaloniaUI/Avalonia#2530]
I am trying to run avalon ui app in ubuntu16.04 docker from tensorflow/tensorflow:1.2.0-py3
And app in running! But when I try to load jpeg files it crashes with error:

```
Unhandled Exception: System.ArgumentException: Unknown pixel format: Bgra8888
   at Avalonia.Skia.SkiaSharpExtensions.ToPixelFormat(SKColorType fmt)
   at RescuerLaApp.Models.Frame.<>c__DisplayClass27_0.<Load>b__0(Object o) in /app/install/RescuerLaApp/Models/Frame.cs:line 91
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Here are *Frame.cs* file:

```CSharp
70      public void Load(string imgFileName, Enums.ImageLoadMode loadMode = Enums.ImageLoadMode.Full)
        {
            ThreadPool.QueueUserWorkItem(o =>
            {
                _name = imgFileName;
75              switch (loadMode)
                {
                    case Enums.ImageLoadMode.Full:
                        _bitmap = new Bitmap(imgFileName);
                        break;
90                  case Enums.ImageLoadMode.Miniature:
91*                     using (SKStream stream = new SKFileStream(imgFileName))
                        using (SKBitmap src = SKBitmap.Decode(stream))
                        {
                            float scale = 100f / src.Width;
95                          SKBitmap resized = new SKBitmap(
                                (int)(src.Width * scale),
                                (int)(src.Height * scale), 
                                src.ColorType, 
                                src.AlphaType);
100                         SKBitmap.Resize(resized, src, SKBitmapResizeMethod.Hamming);
                            _bitmap = new Bitmap(
                                resized.ColorType.ToPixelFormat(),
                                resized.GetPixels(),
                                new PixelSize(resized.Width, resized.Height), 
105                             SkiaPlatform.DefaultDpi, 
                                resized.RowBytes);
                        }
                        break;
                    default:
110                     throw new Exception($"invalid ImageLoadMode:{loadMode.ToString()}");
                }
                Dispatcher.UIThread.InvokeAsync(() =>
                {
                    _imageBrush.Source = _bitmap;
115                 onLoad?.Invoke();
                });
            });
        }
```
I do not know why. I've installed GDK3+ and libSkiaSharp from [here](https://www.nuget.org/packages/Avalonia.Skia.Linux.Natives/1.68.0.2):

```
 dotnet add package Avalonia.Skia.Linux.Natives --version 1.68.0.2 
```

Maybe I do smth wrong? How correctly install libSkiaSharp.so?

Here are my Dockerfile:

```Dockerfile
FROM tensorflow/tensorflow:1.2.0-py3

# install debian packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y \
    # install essentials
    build-essential \
    g++ \
    git \
    wget \
    apt-transport-https \
    curl \
    cython \
    # requirements for numpy
    libopenblas-base \
    python3-numpy \
    python3-scipy \
    # requirements for keras
    python3-h5py \
    python3-yaml \
    python3-pydot \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# manually update numpy
RUN pip3 --no-cache-dir install -U numpy==1.13.3

ARG KERAS_VERSION=2.1.4
ENV KERAS_BACKEND=tensorflow
RUN pip3 --no-cache-dir install --no-dependencies git+https://github.com/fchollet/keras.git@${KERAS_VERSION}

# quick test and dump package lists
RUN python3 -c "import tensorflow; print(tensorflow.__version__)" \
 && dpkg-query -l > /dpkg-query-l.txt \
 && pip3 freeze > /pip3-freeze.txt

# install application
RUN mkdir /app && cd /app && mkdir install

WORKDIR /app/install
COPY ./RetinaNet ./RetinaNet
COPY ./RescuerLaApp ./RescuerLaApp
# git clone
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y dotnet-sdk-2.2

RUN pip3 install --upgrade setuptools

RUN cd RetinaNet \
    && pip3 install opencv-python \
    && pip3 install numpy --user && pip3 install . --user \
    && python3 setup.py build_ext --inplace

RUN cd RescuerLaApp \
    && dotnet restore && dotnet add package Avalonia.Skia.Linux.Natives --version 1.68.0.2
RUN cd RescuerLaApp \
    && dotnet publish --framework netcoreapp2.2 --runtime="ubuntu.16.10-x64" -c Release -o /app

RUN cp -r /app/install/RetinaNet /app/python

RUN apt-get install -y libgtk-3-dev

WORKDIR /app
ENTRYPOINT ["/app/RescuerLaApp"]
```

And the Run command:
```
sudo docker run --rm \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e DISPLAY=unix$DISPLAY \
--device=/dev/snd/controlC0 \
--device=/dev/snd/pcmC0D0p \
--device=/dev/snd/seq \
--device=/dev/snd/timer \
--workdir=$(pwd) \
--volume="/home/$USER:/home/$USER" \
--volume="/etc/group:/etc/group:ro" \
--volume="/etc/passwd:/etc/passwd:ro" \
--volume="/etc/shadow:/etc/shadow:ro" \
--volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
rescuer_la
```

**Comment by kekekeks** [comment]
> dotnet add package Avalonia.Skia.Linux.Natives --version 1.68.0.2 

Make sure that you are using at least Avalonia 0.8 and SkiaSharp 1.68. Different Skia versions are binary incompatible

**Comment by gosha20777** [comment]
Wow! It works. I hav some problems with my python script and the app works quite slow (i think that's why i read image files from internal volume).

Thank you so much!
