### ISSUE TITLE
TextBox throws exception on PointerPressed

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2552]
I got the following exception on clicking on a TextBox. The content of the TextBox was being updated in code at the time (via a binding and all on the ui thread) and had enough content for the scroll bar to be visible. I've not managed to repeat it but will try.
```
Index was outside the bounds of the array.
Avalonia.Controls
Int32 CoerceCaretIndex(Int32, Int32)
   at Avalonia.Controls.TextBox.CoerceCaretIndex(Int32 value, Int32 length)
   at Avalonia.Controls.TextBox.set_CaretIndex(Int32 value)
   at Avalonia.Controls.TextBox.OnPointerPressed(PointerPressedEventArgs e)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   at System.Reactive.Observer`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Observers.cs:line 80
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, MouseButton button, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(CancellationTokenSource tokenSource)
   at SparkSDR.avalonia.Program.AppMain(Application app, String[] args)
```

**Comment by ahopper** [comment]
I think the issue is here
https://github.com/AvaloniaUI/Avalonia/blob/b777bfa187d7dd5fca749453eba7957c1c9d27e9/src/Avalonia.Controls/TextBox.cs#L694
if value == length
