### ISSUE TITLE
Non-URL-safe characters in project path break AvaloniaResource generation

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#2555]
At least on Linux.

Originally reported [here](https://github.com/AvaloniaUI/avalonia-dotnet-templates/issues/22) with project path `/home/darksait88/Документы/ak_window/`

**Comment by ygra** [comment]
Also broken on Windows:

```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 238
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 188
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAsset(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 172
   at Avalonia.Shared.PlatformSupport.AssetLoader.Exists(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 58
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.GetUrisFor(IAssetLoader assetLocator, Type type)+MoveNext() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 220
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 70
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at Документы.App.Initialize() in d:\Users\Joey\Stuff\Документы\App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at Документы.Program.Main(String[] args) in d:\Users\Joey\Stuff\Документы\Program.cs:line 14
```

**Comment by maxkatz6** [comment]
Uri parser for "avares" is configured with ```UriParser.Register(new GenericUriParser(GenericUriParserOptions.GenericAuthority))``` which forces UriParser to escape these non-ascii assembly names.

**Comment by uthidata** [comment]
[Джон äöü.tar.gz](https://github.com/AvaloniaUI/Avalonia/files/12279806/aou.tar.gz)
Just tested with Avalonia 11, problem seems to have been solved. Attached is a project I tested with.
The namespace name cannot contain space, but unicode works fine.
