### ISSUE TITLE
Unable to load shared library "libSkiaSharp"

### ISSUE THREAD

**Issue by curtisy1** [AvaloniaUI/Avalonia#2608]
Hi, I'm facing issues when trying to run a build of a sample Avalonia project with .NET Core 3 Preview 5 (3.0.100-preview5-011568) on Linux. The error message is as follows:
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.gr_glinterface_assemble_gl_interface(IntPtr ctx, IntPtr get)
   at SkiaSharp.GRGlInterface.AssembleGlInterface(Object context, GRGlGetProcDelegate get)
   at SkiaSharp.GRGlInterface.AssembleGlInterface(GRGlGetProcDelegate get)
   at Avalonia.Skia.PlatformRenderInterface..ctor()
   at Avalonia.Skia.SkiaPlatform.Initialize()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args)
   at UdsUI.Program.Main(String[] args) in /home/curtisy/Projects/Avalonia/UdsUI/Program.cs:line 12
```
I know there's issue #2504 but somehow copying libSkiaSharp.so to ./bin/Debug/netcoreapp3.0 doesn't do the trick for me. Because the error message says something about liblibSkiaSharp, I even tried copying that to runtimes/linux-x64/ but to no avail. There is, however, a libSkiaSharp.so in the runtimes folder, as well as is the case for the /netcoreapp3.0 directory. The same setup is working fine on my Windows system.

Any idea what is causing this issue and how I could troubleshoot or work around this?

**Comment by curtisy1** [comment]
Thanks for the heads up!
Using netcoreapp2.2 and .NET Core 2.2 indeed works just fine. I'll submit an issue in the appropriate .NET Core repo in that case
