### ISSUE TITLE
ScrollBar control causes an exception when clicking

### ISSUE THREAD

**Issue by FoasMat** [AvaloniaUI/Avalonia#2675]
When you click, and not when dragging, the exception: System.Reflection.TargetInvocationException: "Exception has been thrown by the target of an invocation."

ArgumentException: NaN is not a valid value for Value.

StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 192
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 156
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 141
   at Avalonia.Controls.Button.OnClick() in D:\a\1\s\src\Avalonia.Controls\Button.cs:line 239
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Button.cs:line 283
   at Avalonia.Controls.RepeatButton.OnPointerReleased(PointerReleasedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\RepeatButton.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args) in D:\a\1\s\src\Avalonia.Interactivity\RoutedEvent.cs:line 115
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 188
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 156
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 141
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, IInputRoot root, Point p, MouseButton button, InputModifiers inputModifiers) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 260
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 122
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in D:\a\1\s\src\Avalonia.Input\InputManager.cs:line 39
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\a\1\s\src\Windows\Avalonia.Win32\WindowImpl.cs:line 697
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 114
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
   at ArmCross.Program.AppMain(Application app, String[] args) in C:\Projects\ArmCross\Program.cs:line 57
   at ArmCross.Program.Main(String[] args) in C:\Projects\ArmCross\Program.cs:line 17

![exception_scrollbar](https://user-images.githubusercontent.com/3223553/59907284-69b0e180-9413-11e9-94fd-c60967a3fec7.gif)

p.s. Handlers on Control is not attached.

**Comment by grokys** [comment]
@FoasMat what version of Avalonia is this with?

**Comment by FoasMat** [comment]
@grokys Avalonia 0.8.1
