### ISSUE TITLE
Weird AvaloniaList.Insert() crash

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2678]
I have the following class:
```cs
    public sealed class Test<T> : IReadOnlyList<T>, INotifyCollectionChanged
    {
        private void OnCollectionChanged(NotifyCollectionChangedEventArgs e)
        {
            CollectionChanged?.Invoke(this, e);
        }
        public event NotifyCollectionChangedEventHandler CollectionChanged;

        private readonly List<T> list;
        public int Count => list.Count;
        public T this[int index] => list[index];

        internal Test(List<T> list)
        {
            this.list = list;
        }

        internal void Add(T item)
        {
            list.Add(item);
            OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, item));
        }
        internal bool Remove(T item)
        {
            bool b = list.Remove(item);
            if (b)
            {
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Remove, item));
            }
            return b;
        }

        public bool Contains(T item)
        {
            return list.Contains(item);
        }

        public IEnumerator<T> GetEnumerator()
        {
            return list.GetEnumerator();
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
```

Essentially, the goal is to have a list that is accessible by my own dll, but the outside sees it as a ReadOnlyObservableCollection of sorts. When I call Test.Add, I get the following crash:

"Index must be within the bounds of the List.\r\nParameter name: index"
### EDIT: The stacktrace is slightly different between .NET Framework and .NET Core
Stacktrace (.NET Framework):
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Avalonia.Collections.AvaloniaList`1.Insert(Int32 index, T item)
   at Avalonia.Controls.Presenters.ItemContainerSync.AddContainers(ItemsPresenterBase owner, Int32 index, IEnumerable items)
   at Avalonia.Controls.Presenters.ItemContainerSync.<ItemsChanged>g__Add|0_0(<>c__DisplayClass0_0& )
   at Avalonia.Controls.Presenters.ItemContainerSync.ItemsChanged(ItemsPresenterBase owner, IEnumerable items, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.NotifyCollectionChangedExtensions.<>c__DisplayClass1_0.<WeakSubscribe>b__0(NotifyCollectionChangedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Collections.NotifyCollectionChangedExtensions.WeakCollectionChangedObservable.OnEvent(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs)
   at Kermalis.PokemonBattleEngine.Data.Test`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Kermalis.PokemonBattleEngine.Data.Test`1.Add(T item)
   at Kermalis.PokemonBattleEngine.Data.PBEMovesetBuilder.Set(Int32 slotIndex, Nullable`1 move, Nullable`1 ppUps)
```

Stacktrace: (.NET Core)
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Avalonia.Collections.AvaloniaList`1.Insert(Int32 index, T item) in D:\a\1\s\src\Avalonia.Base\Collections\AvaloniaList.cs:line 292
   at Avalonia.Controls.Presenters.ItemContainerSync.AddContainers(ItemsPresenterBase owner, Int32 index, IEnumerable items) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 98
   at Avalonia.Controls.Presenters.ItemContainerSync.<ItemsChanged>g__Add|0_0(<>c__DisplayClass0_0& ) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 33
   at Avalonia.Controls.Presenters.ItemContainerSync.ItemsChanged(ItemsPresenterBase owner, IEnumerable items, NotifyCollectionChangedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemContainerSync.cs:line 43
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemVirtualizerNone.cs:line 62
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in D:\a\1\s\src\Avalonia.Base\Reactive\LightweightObservableBase.cs:line 132
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in D:\a\1\s\src\Avalonia.Base\Utilities\WeakSubscriptionManager.cs:line 187
   at Kermalis.PokemonBattleEngine.Data.Test`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in D:\Development\GitHub\PokemonBattleEngine\PokemonBattleEngine\Data\Test.cs:line 11
   at Kermalis.PokemonBattleEngine.Data.Test`1.Add(T item) in D:\Development\GitHub\PokemonBattleEngine\PokemonBattleEngine\Data\Test.cs:line 27
   at Kermalis.PokemonBattleEngine.Data.PBEMovesetBuilder.Set(Int32 slotIndex, Nullable`1 move, Nullable`1 ppUps) in D:\Development\GitHub\PokemonBattleEngine\PokemonBattleEngine\Data\MovesetBuilder.cs:line 183
```

I'm not sure why this doesn't work

**Comment by Kermalis** [comment]
If I change my "Add" method to the following, then it will not crash, so it is definitely not my code:
```cs
        internal void Add(T item)
        {
            int pos = list.Count;
            list.Insert(pos, item);
            OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, item, pos));
        }
```

**Comment by Gillibald** [comment]
It is your code. You have to specify the index when you raise the CollectionChangedEvent. https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedeventargs.-ctor?view=netframework-4.8#System_Collections_Specialized_NotifyCollectionChangedEventArgs__ctor_System_Collections_Specialized_NotifyCollectionChangedAction_System_Object_System_Int32_

You already fixed it in your second post.

**Comment by Kermalis** [comment]
Closing because my issue was resolved
