### ISSUE TITLE
Object of type 'Avalonia.Data.Binding' cannot be converted to type '...'.

### ISSUE THREAD

**Issue by antrv** [AvaloniaUI/Avalonia#2738]
Hi,

I'm trying to bind the custom defined property in my UserControl, but either I'm doing something wrong or there is a bug in the AvaloniaUI 0.8.1.

I'm getting the System.ArgumentException: 'Object of type 'Avalonia.Data.Binding' cannot be converted to type 'Avro.Schemas.Schema'.'

Stack trace:
```
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Portable.Xaml.Schema.XamlMemberInvoker.SetDelegateReflection(Object instance, Object value) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml.Schema\XamlMemberInvoker.cs:line 186
   at Avalonia.Markup.Xaml.PortableXaml.AvaloniaXamlObjectWriter.DelayedValuesHelper.ApplyAll() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\AvaloniaXamlObjectWriter.cs:line 184
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 194
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 169
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 77
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at AvroViewer.MainWindow.InitializeComponent() in D:\Workspace\GitLab\avro.net\AvroViewer\MainWindow.xaml.cs:line 19
   at AvroViewer.MainWindow..ctor() in D:\Workspace\GitLab\avro.net\AvroViewer\MainWindow.xaml.cs:line 11
   at AvroViewer.Program.AppMain(Application app, String[] args) in D:\Workspace\GitLab\avro.net\AvroViewer\Program.cs:line 26
   at AvroViewer.Program.Main(String[] args) in D:\Workspace\GitLab\avro.net\AvroViewer\Program.cs:line 13

```

First I created my control. XAML is left untouched as created by default:
```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvroViewer.Controls.UserControl2">
    Welcome to Avalonia!
</UserControl>
```

Then I added the custom property into UserControl2 class:
```
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avro.Schemas;

namespace AvroViewer.Controls
{
    public class UserControl2 : UserControl
    {
        public static readonly DirectProperty<RecordView, Schema> SchemaProperty =
            AvaloniaProperty.RegisterDirect<RecordView, Schema>(nameof(Schema),
                                                                x => x.Schema,
                                                                (x, value) => x.Schema = value);

        private Schema _schema;

        public UserControl2()
        {
            InitializeComponent();
        }

        public Schema Schema
        {
            get => _schema;
            set => SetAndRaise(SchemaProperty, ref _schema, value);
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}

```

And finally I'm binding `Schema` property of UserControl2 class in MainWindow:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:controls="clr-namespace:AvroViewer.Controls;assembly=AvroViewer"
        xmlns:vm="clr-namespace:AvroViewer.ViewModels;assembly=AvroViewer"
        mc:Ignorable="d"
        d:DesignWidth="800"
        d:DesignHeight="450"
        x:Class="AvroViewer.MainWindow">

  <Window.DataContext>
    <vm:MainWindowViewModel />
  </Window.DataContext>

  <controls:UserControl2 Schema="{Binding Schema}" />

</Window>

```

The `MainWindowViewModel` is straightforward:
```
using System.Linq;
using Avalonia.Diagnostics.ViewModels;
using Avro.IO;
using Avro.Model;
using Avro.Schemas;

namespace AvroViewer.ViewModels
{
    public sealed class MainWindowViewModel : ViewModelBase
    {
        private Schema _schema;

        public MainWindowViewModel()
        {
            _schema = ...;
        }

        public Schema Schema
        {
            get => _schema;
            set => RaiseAndSetIfChanged(ref _schema, value);
        }
    }
}

```

Any suggestions?
Thanks.

**Comment by ahopper** [comment]
I think you should be using UserControl2 and not RecordView in registering your direct property, not quite sure if that explains the whole issue.

**Comment by antrv** [comment]
@ahopper Thanks for pointing. When I made this simplified example, I copied this line from another control. Anyway the exception happens everywhere.

**Comment by kekekeks** [comment]
Please, try with nightly builds, we've completely replaced our XAML engine
