### ISSUE TITLE
Hit test null reference when hiding the window

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#2758]
Hey I'm getting the following exception when I add items programmatically to the my main Canvas control and hide/show the window during it.
I'm still trying to figure how to properly recreate this issue, posting here in case the stack trace is enough to solve the issue, thanks.
`System.NullReferenceException: Object reference not set to an instance of an object.
  at at Avalonia.Rendering.SceneGraph.VisualNode.HitTest(Point p)
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at Avalonia.Rendering.SceneGraph.Scene.HitTest(IVisualNode node, Point p, Nullable`1 clip, Func`2 filter)+MoveNext()
  at at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
  at at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
  at at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
  at at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p)
  at at Avalonia.Input.MouseDevice.SetPointerOver(IPointerDevice device, IInputRoot root, Point p)
  at at Avalonia.Input.MouseDevice.SceneInvalidated(IInputRoot root, Rect rect)
  at at Avalonia.Controls.TopLevel.SceneInvalidated(Object sender, SceneInvalidatedEventArgs e)
  at at Avalonia.Rendering.DeferredRenderer.UpdateScene()
  at at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Update(TimeSpan time)
  at at Avalonia.Rendering.RenderLoop.<>c__DisplayClass11_0.<TimerTick>b__1()
`
and this:
`
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
   at Avalonia.Rendering.DeferredRenderer.RenderToLayers(Scene scene)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Func`1 contextFactory, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
`

**Comment by adirh3** [comment]
@grokys  @kekekeks 
Not sure if fixed this too but it also happens in DeferredRenderer line 351: 
`System.NullReferenceException: Object reference not set to an instance of an object.
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds)
  at at Avalonia.Rendering.DeferredRenderer.RenderToLayers(Scene scene)
  at at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Func`1 contextFactory, Boolean recursiveCall)
  at at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
  at at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect)
  at at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
  at at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
`
