### ISSUE TITLE
XAMLIL internal compiler error for converter

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2835]
Using build 0.8.999-cibuild0003548-beta I get an internal compiler error when setting a converter using a markup extension. This used to work in v0.8.1.
Note: using a StaticResource compiles OK.

```
<TextBlock Text="{Binding MyProperty}" IsVisible="{Binding MyProperty, Converter={cv:MyBooleanConverter Invert='True'}}" />
```

```
    public class MyBooleanConverter : IValueConverter
    {
        public bool Invert { get; set; }

        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            bool result = value is string s ? string.IsNullOrEmpty(s) : value == null;
            return Invert ? !result : result;
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture) => throw new InvalidOperationException("Can't convert back");

        public object ProvideValue() => this;
    }

```

```
Error	XAMLIL	Internal compiler error while transforming node XamlIl.Ast.XamlIlAstXamlPropertyValueNode:
System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at XamlIl.TypeSystem.TypeSystemHelpers.<ParseConstantIfTypeAllows>g__Parse|4_0(<>c__DisplayClass4_0& ) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystemHelpers.cs:line 87
   at XamlIl.TypeSystem.TypeSystemHelpers.ParseConstantIfTypeAllows(String s, IXamlIlType type, IXamlIlLineInfo info, XamlIlConstantNode& rv) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystemHelpers.cs:line 91
   at XamlIl.Transform.XamlIlTransformHelpers.TryConvertValue(XamlIlAstTransformationContext context, IXamlIlAstValueNode node, IXamlIlType type, IXamlIlAstValueNode& rv) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\Transform\XamlIlTransformHelpers.cs:line 224
   at XamlIl.Transform.Transformers.XamlIl... Line 8, position 42.	AvaloniaApplication7	D:\VSS2\AvaloniaApplication1\AvaloniaApplication7\AvaloniaApplication7.Views.ViewA.xaml	8	
```

**Comment by aguahombre** [comment]
On further investigation, using StaticResource for a IValueConverter that also has a ProvideValue markup extension method (as in the example above) fails with an error where the converter is declared:

Line 20-22
```
<UserControl.Resources>
    <cv:MyBooleanConverter Invert='True'/>
</UserControl.Resources>
```

```
Error	XAMLIL	Unable to find emitter for node type: XamlIl.Ast.XamlIlAstXmlDirective (line 21 position 6) Line 21, position 6.
```

If I comment out the ProvideValue method above, this will compile.

**Comment by kekekeks** [comment]
Try changing `public object ProvideValue() => this;` to `public IValueConverter ProvideValue() => this`

**Comment by aguahombre** [comment]
That gives the same error for the first example using markup.
But a different error for the second example using resources.

```
Error	XAMLIL	Unable to find suitable setter or adder for property Resources of type Avalonia.Styling:Avalonia.StyledElement for argument Avalonia.Base:Avalonia.Data.Converters.IValueConverter, available setter parameter lists are:
Avalonia.Controls.IResourceDictionary
System.Collections.Generic.KeyValuePair`2<System.Object,System.Object>
System.Collections.Generic.KeyValuePair`2<TKey,TValue> (line 9 position 6) Line 9, position 6.	AvaloniaApplication7	D:\VSS2\AvaloniaApplication1\AvaloniaApplication7\AvaloniaApplication7.Views.ViewA.xaml	9	
```

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cv="clr-namespace:AvaloniaApplication7;assembly=AvaloniaApplication7"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication7.Views.ViewA">
  <UserControl.Resources>
    <cv:MyBooleanConverter Invert='True'/>
  </UserControl.Resources>
  <TextBlock Text="{Binding MyProperty}" IsVisible="{Binding MyProperty, Converter={StaticResource MyBooleanConverter}}" />
 
</UserControl>
```

**Comment by kekekeks** [comment]
I think for the markup extension one it complains about the quotes around `Invert='True'`.
For the second one you need `x:Key="something"`, otherwise it can't be added to ResourceDictionary.

**Comment by aguahombre** [comment]
Just checked this in 0.9.999-cibuild0008173-beta and no longer occurs
