### ISSUE TITLE
XAMLIL compiler NRE

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2838]
Using build 0.8.999-cibuild0003548-beta, I get a XAMLIL compiler NRE for the following XAML

```
Error	XAMLIL	Internal compiler error while emitting node Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlOrSelectorNode:
System.NullReferenceException: Object reference not set to an instance of an object.
   at XamlIl.TypeSystem.XamlIlTypeSystemExtensions.EmitCall(IXamlIlEmitter emitter, IXamlIlMethod method, Boolean swallowResult) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystem.cs:line 474
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlSelectorNode.EmitCall(XamlIlEmitContext context, IXamlIlEmitter codeGen, Func`2 method) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\CompilerExtensions\Transformers\AvaloniaXamlIlSelectorTransformer.cs:line 164
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlOrSelectorNode.DoEmit(XamlIlEmitContext context, IXamlIlEmitter codeGen) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\CompilerExtensions\Transformers\AvaloniaXamlIlSelectorTransformer.cs:line 334
   a... Line 9, position 6.	AvaloniaApplication7	
...\AvaloniaApplication7.Views.ViewA.xaml	9	
```

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cv="clr-namespace:AvaloniaApplication7;assembly=AvaloniaApplication7"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication7.Views.ViewA">
  <UserControl.Styles>
    <Style Selector="NumericUpDown,ListBox,ComboBox">
      <Setter Property="Margin" Value="5"/>
    </Style>
  </UserControl.Styles>
   <TextBox Text="{Binding UrlPathSegment}"/>
</UserControl>
```

**Comment by mat1jaczyyy** [comment]
I believe it's possible to temporarily work around this by doing 

```xaml
<Style Selector="NumericUpDown">
    <Setter Property="Margin" Value="5"/>
</Style>
<Style Selector="ListBox">
    <Setter Property="Margin" Value="5"/>
</Style>
<Style Selector="ComboBox">
    <Setter Property="Margin" Value="5"/>
</Style>
```

**Comment by aguahombre** [comment]
Thanks, the workaround gets rid of the compiler error.
Sometimes, just moving one selector to a separate style works.

**Comment by aguahombre** [comment]
My previous comment was wrong, comma separated selectors are broken.
Sometimes they compile without error but only the first selector in the list is applied.

**Comment by adroslice** [comment]
For anyone still having to work around this, for simple multi-selectors where all that's different is the type of a control (for example TextBox vs.ComboBox vs. other inputs), very often since you are styling them the same way, which means they serve a common function, they will also have a common base class (in the mentioned example, TemplatedControl). Therefore it's often possible to use the :is-pseudoclass. I'm sure there's many more tricks like this.
