### ISSUE TITLE
XAML NRE parsing double array

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2853]
Using build 0.8.999-cibuild0003548-beta.
I get an NRE when loading XAML for a window that parses a string containing a list of doubles and assigns it to a property.
In Avalonia 0.8.1 the XAML parser would create the list and assign it without having to create a list in the code behind.
In 0.8.9999 the XAML parser calls the property getter (which returns null) and does not create a new list; hence the NRE.

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:AvaloniaApplication9;assembly=AvaloniaApplication9"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication9.MainWindow"
        Title="AvaloniaApplication9"
        MyDoubles="1,2,3">
  <TextBlock Text="Welcome"/>
</Window>
```

```
    public class MainWindow : Window
    {
        public IAvaloniaList<double> MyDoubles { get; set; } //= new AvaloniaList<double>();

        public MainWindow()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
```

Is this a breaking change or undefined behaviour in 0.8.1?

Also, if I uncomment the property initialisation ```public IAvaloniaList<double> MyDoubles { get; set; } = new AvaloniaList<double>()```, I get a single double value 123 added to the list, not three value 1,2,3.

If I change the XAML to ```MyDoubles="1.1,2.2,3.3"```, I get an internal compiler error:
```
Error	XAMLIL	Internal compiler error while transforming node XamlIl.Ast.XamlIlAstXamlPropertyValueNode:
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at XamlIl.TypeSystem.TypeSystemHelpers.<ParseConstantIfTypeAllows>g__Parse|4_0(<>c__DisplayClass4_0& ) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystemHelpers.cs:line 85
   at XamlIl.TypeSystem.TypeSystemHelpers.ParseConstantIfTypeAllows(String s, IXamlIlType type, IXamlIlLineInfo info, XamlIlConstantNode& rv) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystemHelpers.cs:line 91
   at XamlIl.Transform.XamlIlTransformHelpers.TryConvertValue(XamlIlAstTransformationContext context, IXamlIlAstValueNode node, IXamlIlType type, IXamlIlAstValueNode& rv) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\Transform\XamlIlTransformHelpers.cs:line... Line 1, position 2.	AvaloniaApplication9	D:\VSS2\AvaloniaApplication1\AvaloniaApplication9\MainWindow.xaml	1	
```

**Comment by aguahombre** [comment]
If I change the property to a concrete type ```public AvaloniaList<double> MyDoubles { get; set; }```, then I get correct behaviour with a list of three doubles.
So it appears to be a problem when using ```IAvaloniaList```.
