### ISSUE TITLE
Avalonia.Input.InputExtensions.GetInputElementsAt throws System.NullReferenceException'

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2854]
```
Exception thrown: 'System.NullReferenceException' in Avalonia.Visuals.dll
Object reference not set to an instance of an object.
   at Avalonia.VisualTree.VisualExtensions.GetVisualsAt(IVisual visual, Point p, Func`2 filter)
   at Avalonia.Input.InputExtensions.GetInputElementsAt(IInputElement element, Point p)
   at Dock.Avalonia.Controls.DockState.GetControl(IInputElement input, Point point, AvaloniaProperty`1 property) in C:\DOWNLOADS\GitHub\Dock\src\Dock.Avalonia\Controls\Docking\DockState.cs:line 142
```

Version: 0.8.999-cibuild0003548-beta

**Comment by wieslawsoltes** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/ba0860b34af44aec6ac6b8a98132fb7e348fa9eb/src/Avalonia.Input/InputExtensions.cs#L28

This should check for null?
```C#
return element.GetVisualsAt(p, IsHitTestVisible)?.Cast<IInputElement>();
```

https://github.com/AvaloniaUI/Avalonia/blob/ba0860b34af44aec6ac6b8a98132fb7e348fa9eb/src/Avalonia.Input/InputExtensions.cs#L39

This should check for null?
```C#
return element.GetInputElementsAt(p)?.FirstOrDefault();
```
