### ISSUE TITLE
InvalidOperationException thrown by InvokeCommandAction on Window.Closing event

### ISSUE THREAD

**Issue by dasSubjekt** [AvaloniaUI/Avalonia#2869]
This is my MainWindow.xaml: 

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:AvaloniaMvvmTest.ViewModels;assembly=AvaloniaMvvmTest"
        xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
        xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions"
        x:Class="AvaloniaMvvmTest.Views.MainWindow"
        Name="TheMainWindow">
  <i:Interaction.Behaviors>
    <ia:EventTriggerBehavior EventName="Closing" SourceObject="{Binding #TheMainWindow}">
      <ia:InvokeCommandAction Command="{Binding ClosingCommand}" />
    </ia:EventTriggerBehavior>
  </i:Interaction.Behaviors>
    <Design.DataContext><vm:MainWindowViewModel/></Design.DataContext>
    <TextBlock Text="Nothing here yet." HorizontalAlignment="Center" VerticalAlignment="Center"/>
</Window>
```

This is my ViewModelBase.cs:
```
using ReactiveUI;

namespace AvaloniaMvvmTest.ViewModels
{
    public class ViewModelBase : ReactiveObject
    {
        public ReactiveCommand ClosingCommand { get; }

        public ViewModelBase()
        {
            ClosingCommand = ReactiveCommand.Create(ExecuteClosing);
        }

        protected virtual void ExecuteClosing()
        {
        }
    }
}
```

When I start the application I get:
```
Binding: Error in binding to "Avalonia.Xaml.Interactions.Core.InvokeCommandAction"."Command": "Null value in expression ''."
```

And when I close the window I get:
```
Exception thrown: System.InvalidOperationException
    at ReactiveUI.ReactiveCommandBase`2.ICommandExecute(Object parameter) in D:\a\1\s\src\ReactiveUI\ReactiveCommand.cs:line 714
    at Avalonia.Xaml.Interactions.Core.InvokeCommandAction.Execute(Object sender, Object parameter)
    at Avalonia.Xaml.Interactivity.Interaction.ExecuteActions(Object sender, ActionCollection actions, Object parameter)
    at Avalonia.Xaml.Interactions.Core.EventTriggerBehavior.OnEvent(Object sender, Object eventArgs)
    at Avalonia.Controls.Window.HandleClosing()
    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
  HResult=0x80131509
  Message = Command requires parameters of type System.Reactive.Unit, but received parameter of type System.ComponentModel.CancelEventArgs.
  Source = ReactiveUI
```

Is this a bug or is there a better way to react to the Window.Closing event?

**Comment by kekekeks** [comment]
You probably need `ReactiveCommand.Create<CancelEventArgs, Unit>`

**Comment by dasSubjekt** [comment]
That solves it. Thank you so much!
