### ISSUE TITLE
Including Avalonia.Controls.DataGrid style fail

### ISSUE THREAD

**Issue by ido-ran** [AvaloniaUI/Avalonia#2925]
I've tried to follow a [tutorial on using Avalonia DataGrid](https://www.nequalsonelifestyle.com/2019/06/13/avalonia-datagrid-getting-started/) but when I just create a .NET Core 2.1 app using Avalonia.app template and add `Avalonia.Controls.DataGrid` - all version are `0.8.1` when I try to add `<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Default.xaml"/>` to `App.xaml` I'm getting the exception bellow.

You can get the [full (minimal) app from this git repo](https://github.com/ido-ran/avalonia-data-grid).

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=The resource avares://Avalonia.Controls.DataGrid/Themes/Default.xaml could not be found.
  Source=Avalonia.DesktopRuntime
  StackTrace:
   at Avalonia.Shared.PlatformSupport.AssetLoader.OpenAndGetAssembly(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 94
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 117
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\Styling\StyleInclude.cs:line 49
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Styling.ISetStyleParent.NotifyResourcesChanged(ResourcesChangedEventArgs e) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\Styling\StyleInclude.cs:line 90
   at Avalonia.Styling.Styles.<.ctor>b__4_0(IStyle x) in D:\a\1\s\src\Avalonia.Styling\Styling\Styles.cs:line 36
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items) in D:\a\1\s\src\Avalonia.Base\Collections\AvaloniaListExtensions.cs:line 82
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index) in D:\a\1\s\src\Avalonia.Base\Collections\AvaloniaList.cs:line 505
   at Portable.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml.Schema\XamlTypeInvoker.cs:line 135
   at Portable.Xaml.XamlObjectWriterInternal.AddToCollectionIfAppropriate(XamlType xt, XamlMember xm, Object parent, Object obj, Object keyObj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 691
   at Portable.Xaml.XamlObjectWriterInternal.StoreAppropriatelyTypedValue(ObjectState state, MemberAndValue ms, Object obj, Object keyObj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 673
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteEndObject() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 454
   at Portable.Xaml.XamlWriterInternalBase.WriteEndObject() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlWriterInternalBase.cs:line 268
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlServices.cs:line 136
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 193
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 169
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 77
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at ParametersEditor2.App.Initialize() in C:\Users\ido.ran\Documents\dev\ObjetStudio-2\Tools\ParametersEditor2\App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at ParametersEditor2.Program.Main(String[] args) in C:\Users\ido.ran\Documents\dev\ObjetStudio-2\Tools\ParametersEditor2\Program.cs:line 12
```

**Comment by ahopper** [comment]
I think you need
```
<StyleInclude Source="resm:Avalonia.Controls.DataGrid.Themes.Default.xaml?assembly=Avalonia.Controls.DataGrid"/>
      
```
and probably `.UseDataGrid()` on app builder in program.cs

**Comment by ahopper** [comment]
Or update to nightly builds and it should just run (once you have followed this https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes)..

**Comment by maxkatz6** [comment]
UseDataGrid is not required anymore.
You only need to include ```avares://Avalonia.Controls.DataGrid/Themes/Default.xaml``` or ```avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml``` styles (depending on yours app theme).
