### ISSUE TITLE
 AutoScrollToSelectedItem crash

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/Avalonia#2967]
Since #2953 it is possible to get a crash if you have a Listbox with `AutoScrollToSelectedItem = true`, if you call `.Clear()` at the `ObservableCollection` in the corresponding ViewModel

```
System.ArgumentNullException: Value cannot be null.
   at Avalonia.Controls.Utils.IEnumerableUtils.IndexOf(IEnumerable items, Object item) in D:\a\1\s\src\Avalonia.Controls\Utils\IEnumerableUtils.cs:line 40
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Object item) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 298
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelectedItem(Int32 index, Boolean clear) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 1049
   at Avalonia.Controls.Primitives.SelectingItemsControl.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 339
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in D:\a\1\s\src\Avalonia.Base\Reactive\LightweightObservableBase.cs:line 132
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in D:\a\1\s\src\Avalonia.Base\Utilities\WeakSubscriptionManager.cs:line 187
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionReset()
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at VHDPlus.Create.CompileHelper.<>c__DisplayClass2_0.<CompileVHDL>b__1(Object o, RunWorkerCompletedEventArgs args) in C:\Users\HendrikMennen\Source\Repos\VHDP\VHDPlus\Create\CompileHelper.cs:line 118
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 174
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 121
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in D:\a\1\s\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 107
   at VHDPlus.Program.Main(String[] args) in C:\Users\HendrikMennen\Source\Repos\VHDP\VHDPlus\Program.cs:line 54
```

**Comment by danwalmsley** [comment]
@HendrikMennen can you confirm if https://github.com/AvaloniaUI/Avalonia/pull/2968 fixes the issue for you?

**Comment by HendrikMennen** [comment]
@danwalmsley tested it with ControlCatalog, looks like you fixed it

**Comment by danwalmsley** [comment]
@HendrikMennen i couldnt repro in control catalog before I added this fix

do you have sample code, for your list?

**Comment by HendrikMennen** [comment]
Just noticed something really weird. If I check if the list is empty before clearing it like this: 
`if(fpga.Signals.Count > 0) fpga.Signals.Clear();`
it does not crash. But this is only needed if I have AutoScrollToSelectedItem = true.
So it only crashes if it tries to clear the list that is already empty.
Still this only appears since one of the latest nightly builds so I am not sure what could cause it.

I was not able to reproduce this on the ControlCatalog tho so I might have something wrong myself

```xaml
<ListBox AutoScrollToSelectedItem="True"
             BorderThickness="0,1,0,0" 
             BorderBrush="{StaticResource NormalBrush}" 
             Name="SignalList" Grid.Row="1" FontSize="13" 
             Items="{Binding Path=SelectedFPGA.Signals}" SelectedItem="{Binding                                                                                        
             Path=SelectedFPGA.SelectedSignal, Mode=TwoWay}" 
             Background="{StaticResource DarkColor}" VerticalAlignment="Stretch">
</ListBox>
````

**Comment by danwalmsley** [comment]
fix will be merged soon, so you will be able to test a build with that fix in soon

**Comment by danwalmsley** [comment]
@HendrikMennen are you setting Items to null and then changing SelectedItem?

**Comment by danwalmsley** [comment]
@HendrikMennen anychance you could send me a zip of your project to debug the issue, I can be contacted privately on gitter if its a closed source one.

**Comment by danwalmsley** [comment]
@HendrikMennen dont worry about that, we have fixed it and about to be merged to master
