### ISSUE TITLE
MVVM applications with special characters in the name don't run

### ISSUE THREAD

**Issue by camas** [AvaloniaUI/Avalonia#3029]
Could be related to #2879 

Using .NET Core on a Linux system

Steps to reproduce:

- `dotnet new avalonia.mvvm -o "example space"`
- `dotnet run --project "example space"`

Output:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'example%20space, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 238
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 188
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAsset(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 172
   at Avalonia.Shared.PlatformSupport.AssetLoader.Exists(Uri uri, Uri baseUri) in D:\a\1\s\src\Shared\PlatformSupport\AssetLoader.cs:line 58
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.GetUrisFor(IAssetLoader assetLocator, Type type)+MoveNext() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 220
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 70
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at example_space.App.Initialize() in /home/camas/tmp/example space/App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at example_space.Program.Main(String[] args) in /home/camas/tmp/example space/Program.cs:line 14
```

Works as expected if the special characters are removed.

**Comment by camas** [comment]
Fixed in 0.9. mb
