### ISSUE TITLE
Crash on startup (Win 7)

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#3072]
I am trying to upgrade from 0.8.999-cibuild0003925-beta to 0.8.999-cibuild0004423-beta (latest) and I get this crash immediately upon starting the program:

```
   at Avalonia.Controls.Screens.<>c__DisplayClass9_0.<ScreenFromPoint>b__0(Screen x) in D:\a\1\s\src\Avalonia.Controls\Screens.cs:line 46
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Avalonia.Controls.Screens.ScreenFromPoint(PixelPoint point) in D:\a\1\s\src\Avalonia.Controls\Screens.cs:line 46
   at Avalonia.Controls.Window.SetWindowStartupLocation(IWindowBaseImpl owner) in D:\a\1\s\src\Avalonia.Controls\Window.cs:line 502
   at Avalonia.Controls.Window.Show() in D:\a\1\s\src\Avalonia.Controls\Window.cs:line 409
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in D:\a\1\s\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 104
   at Kermalis.MapEditor.Program.Main() in D:\Development\GitHub\PokemonGameEngine\MapEditor\Program.cs:line 11
```

This happens in both net461 and netcore2.2

**Comment by Kermalis** [comment]
After testing the versions between, `0.8.999-cibuild0004152-beta` is the first time this crash will occur for me. (Released on Friday, September 20 2019)

**Comment by kekekeks** [comment]
Duplicates https://github.com/AvaloniaUI/Avalonia/issues/3069
