### ISSUE TITLE
XAMIL: NullReferenceException while parsing comma-separated selectors

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3093]
```
<Style
        Selector="xy|DropDownButton.transparent, xy|DropDownButton.transparent:pointerover /template/ ToggleButton#PART_ToggleButton /template/ ContentPresenter, xy|DropDownButton.transparent /template/ ToggleButton#PART_ToggleButton:pressed /template/ ContentPresenter, xy|DropDownButton.transparent /template/ ToggleButton#PART_ToggleButton:checked /template/ ContentPresenter">
        <Setter Property="Background" Value="Transparent" />
        <Setter Property="BorderBrush" Value="Transparent" />
        <Setter Property="Padding" Value="0" />
</Style>
```

This code produces a `NullReferenceException` inside the XAMLIL compiler. It seems to be choking on long and complex comma-separated selectors.

> Severity	Code	Description	Project	Line
Error	XAMLIL	Internal compiler error while emitting node Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlOrSelectorNode:
System.NullReferenceException: Object reference not set to an instance of an object.
   at XamlIl.TypeSystem.XamlIlTypeSystemExtensions.EmitCall(IXamlIlEmitter emitter, IXamlIlMethod method, Boolean swallowResult) in C:\Repositories\Avalonia-Own\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystem.cs:line 476
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlSelectorNode.EmitCall(XamlIlEmitContext context, IXamlIlEmitter codeGen, Func`2 method) in C:\Repositories\Avalonia-Own\src\Markup\Avalonia.Markup.Xaml\XamlIl\CompilerExtensions\Transformers\AvaloniaXamlIlSelectorTransformer.cs:line 164
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.XamlIlOrSelectorNode.DoEmit(XamlIlEmitContext context, IXamlIlEmitter codeGen) in C:\Repositories\Avalonia-Own\src\Markup\Avalonia.Markup.Xaml\XamlIl\CompilerExtensions\Tran... Line 21, position 10.

**Comment by mat1jaczyyy** [comment]
Dupe #2838?
