### ISSUE TITLE
RenderDemo unable to run in ubuntu

### ISSUE THREAD

**Issue by sunneo** [AvaloniaUI/Avalonia#3112]
@jmacato 
OS/Distribution: linux ubuntu 18.04
It happens to occur an exception: 
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in /media/user/storage-2nd/Downloads/src/Avalonia/src/Avalonia.Controls/AppBuilderBase.cs:line 130
   at RenderDemo.App.Main(String[] args) in /media/user/storage-2nd/Downloads/src/Avalonia/samples/RenderDemo/App.xaml.cs:line 20
```

Because Instance is null at the mean time. 

I try to rearrange it by moving start() into AfterSetup() and the exception gone.

```
diff --git a/src/Avalonia.Controls/AppBuilderBase.cs b/src/Avalonia.Controls/AppBuilderBase.cs
index d9be9171e..937f66629 100644
--- a/src/Avalonia.Controls/AppBuilderBase.cs
+++ b/src/Avalonia.Controls/AppBuilderBase.cs
@@ -115,20 +115,23 @@ public TAppBuilder AfterPlatformServicesSetup(Action<TAppBuilder> callback)
         public void Start<TMainWindow>(Func<object> dataContextProvider = null)
             where TMainWindow : Window, new()
         {
+
             AfterSetup(builder =>
             {
+                var lifetime = new ClassicDesktopStyleApplicationLifetime(Instance) {ShutdownMode = ShutdownMode.OnMainWindowClose};
+                Instance.ApplicationLifetime = lifetime;
+
                 var window = new TMainWindow();
                 if (dataContextProvider != null)
                     window.DataContext = dataContextProvider();
                 ((IClassicDesktopStyleApplicationLifetime)builder.Instance.ApplicationLifetime)
                     .MainWindow = window;
+                lifetime.Start(Array.Empty<string>());
+
             });

             // Copy-pasted because we can't call extension methods due to generic constraints
-            var lifetime = new ClassicDesktopStyleApplicationLifetime(Instance) {ShutdownMode = ShutdownMode.OnMainWindowClose};
-            Instance.ApplicationLifetime = lifetime;
             SetupWithoutStarting();
-            lifetime.Start(Array.Empty<string>());
         }

         public delegate void AppMainDelegate(Application app, string[] args);
@@ -264,6 +267,7 @@ public TAppBuilder With<T>(Func<T> options)
         /// </summary>
         private void Setup()
         {
+            Console.WriteLine("Setup...");
             if (RuntimePlatformServicesInitializer == null)
             {
                 throw new InvalidOperationException("No runtime platform services configured.");
```

**Comment by jmacato** [comment]
I'll fix this, i encountered this too just a few nightly builds ago.. forgot to report haha. Will post a PR later

**Comment by kekekeks** [comment]
```
Instance.ApplicationLifetime = lifetime;
SetupWithoutStarting();
```
Replace with `SetupWithLifetime` like [here](https://github.com/AvaloniaUI/Avalonia/blob/e80ddf5c6591bff9e936fa3c8655e0daff9fd39b/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs#L127)

**Comment by metal450** [comment]
I'm getting this crash when trying to run AvaloniaMauiHybrid on Windows (it works on iOS). Why closed as "not planned" to be fixed?
