### ISSUE TITLE
IsSelected crush app

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#3180]
```xml
 <TabControl>
                    <TabItem Header="Tab item 1">
                        <TextBlock Margin="10" Text="something" />
                    </TabItem>
                    <TabItem Header="Tab item 2" IsSelected="True">
                        <TextBlock Margin="10" Text="something else" />
                    </TabItem>
                    <TabItem IsEnabled="False" Header="Disabled tab item 2">
                        <TextBlock Margin="10" Text="something else" />
                    </TabItem>
                </TabControl>
```
without is selected everything is ok, but if i set it
app crush and I have this logs
```
Unhandled Exception: Portable.Xaml.XamlObjectWriterException: Set value of member '{clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls}TabItem.IsSelected' threw an exception ---> System.NullReferenceException: Object reference not set to an instance
 of an object.
   at Avalonia.Controls.TabItem.UpdateSelectedContent(AvaloniaPropertyChangedEventArgs e) in D:\a\1\s\src\Avalonia.Controls\TabItem.cs:line 103
   at System.Reactive.Observer`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Observers.cs:line 78
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 490
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 378
   at Avalonia.ValueStore.AddValue(AvaloniaProperty property, Object value, Int32 priority) in D:\a\1\s\src\Avalonia.Base\ValueStore.cs:line 88
   at Avalonia.AvaloniaObject.SetStyledValue(AvaloniaProperty property, Object value, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 710
   at Portable.Xaml.XamlObjectWriterInternal.SetValue(XamlMember member, Object target, Object value) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 590
   --- End of inner exception stack trace ---
   at Portable.Xaml.XamlObjectWriterInternal.SetValue(XamlMember member, Object target, Object value) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 595
   at Portable.Xaml.XamlObjectWriterInternal.SetValue(XamlMember member, Object value) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 584
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteEndMember() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlObjectWriter.cs:line 568
   at Portable.Xaml.XamlWriterInternalBase.WriteEndMember() in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlWriterInternalBase.cs:line 278
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\PortableXaml\portable.xaml.github\src\Portable.Xaml\Portable.Xaml\XamlServices.cs:line 136
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 193
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 169
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 77
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at Avalonia.NETCoreMVVMApp.Views.MainWindow.InitializeComponent() in C:\Users\name\Desktop\WpfApplication1\Avalonia.NETCoreMVVMApp\Views\MainWindow.xaml.cs:line 16
   at Avalonia.NETCoreMVVMApp.Views.MainWindow..ctor() in C:\Users\name\Desktop\WpfApplication1\Avalonia.NETCoreMVVMApp\Views\MainWindow.xaml.cs:line 11
   at Avalonia.NETCoreMVVMApp.Program.AppMain(Application app, String[] args) in C:\Users\name\Desktop\WpfApplication1\Avalonia.NETCoreMVVMApp\Program.cs:line 27
   at Avalonia.NETCoreMVVMApp.Program.Main(String[] args) in C:\Users\name\Desktop\WpfApplication1\Avalonia.NETCoreMVVMApp\Program.cs:line 14
```

**Comment by Gillibald** [comment]
Can confirm the issue and will provide a fix tomorrow.
