### ISSUE TITLE
Unhandled exception in Linux

### ISSUE THREAD

**Issue by lenonk** [AvaloniaUI/Avalonia#3276]
I have this issue when I try to run my app in Linux.  I've systematically removed code to make the example at simple as possible.

`
~/dev/Myrina/MyrinaUI/bin/Release/netcoreapp3.1/linux-x64/publish (master ✘)✹✭ ᐅ ./MyrinaUI 
Unhandled exception. System.InvalidOperationException: Invalid Arrange rectangle.
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverrideImpl(Size finalSize, Vector offset)
   at Avalonia.Controls.Presenters.ContentPresenter.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding)
   at Avalonia.Controls.Primitives.VisualLayerManager.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.ArrangeChild(ILayoutable child, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Controls.Window.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass(ILayoutRoot root)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow)
   at MyrinaUI.Program.AppMain(Application app, String[] args)
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args)
   at MyrinaUI.Program.Main(String[] args)
[1]    10388 abort (core dumped)  ./MyrinaUI
`
The main xaml view looks like this:
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cv="clr-namespace:MyrinaUI.Converters;assembly=MyrinaUI"
             xmlns:vm="clr-namespace:MyrinaUI.ViewModels;assembly=MyrinaUI"
             xmlns:v="clr-namespace:MyrinaUI.Views;assembly=MyrinaUI"
             mc:Ignorable="d" d:DesignWidth="1200" d:DesignHeight="850"
             x:Class="MyrinaUI.Views.MainView">

   <Grid ColumnDefinitions="5, auto, *, 5" RowDefinitions="*, auto, auto, 5">

    <!-- Row 0 Col 1-->
    <v:DataGridView Grid.Row="0" Grid.Column="1" />

    <!-- Row 2 Col 1-->
    <v:LogView Grid.Row="1" Grid.Column="1"/>

    <!-- Row 3 Col 1-->
     <v:InstanceInfoView Grid.Row="2" Grid.Column="1" />
  </Grid>
 </UserControl>
```

Where DataGridView, LogView, and InstanceInfoView are all brand new UserControls created from the VS template.

Note: It seems to work if you change ColumnDefinitions to `5,*,*,5.`  Also, it doesn't seem to matter whether there's anything in grid column 2 or not.

**Comment by lenonk** [comment]
Oh, this is with .9-preview7

**Comment by Gillibald** [comment]
Pls show use your Longview definition

**Comment by lenonk** [comment]
LogView.xaml is:
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:MyrinaUI.ViewModels;assembly=MyrinaUI"
             mc:Ignorable="d" d:DesignWidth="765" d:DesignHeight="100" Name="LogView"
             x:Class="MyrinaUI.Views.LogView">
</UserControl>
```

**Comment by Gillibald** [comment]
The code behind is also important

**Comment by lenonk** [comment]
Oh, here it is, it's just default.  There was some xaml in all of these files, but I deleted it trying to narrow down the problem.
```c#
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Media.Imaging;
using System;

namespace MyrinaUI.Views {
    public class LogView : UserControl {
        public LogView() {
            InitializeComponent();
        }

        private void InitializeComponent() {
            AvaloniaXamlLoader.Load(this);
        }
    }
}

```

**Comment by lenonk** [comment]
Also of note, it works just fine on Windows and MacOS Mojave

**Comment by lenonk** [comment]
I posted the wrong stack trace.  My apologies.  It has been corrected in the OP.

**Comment by Gillibald** [comment]
Can you try to define width and height on LogView?

**Comment by lenonk** [comment]
I'm just going to close this.  I can't reproduce it now with the limited example above.  I'm going to spin up a new Ubuntu VM and try again.  If it still happens on a new VM, I'll investigate further and reopen this issue, or create a new one.
