### ISSUE TITLE
RangeBase Generates - ArgumentException in AvaloniaObject

### ISSUE THREAD

**Issue by lontivero** [AvaloniaUI/Avalonia#3284]
One of our users reports this exception during testing the new Wasabi version that will be released with Avalonia 0.9. The user OS is a Qubes 4, Debian 10. Please let me know if more info is required.

```
2019-11-10 09:39:12 CRITICAL	Program (50)	System.ArgumentException: NaN is not a valid value for Value.
   at Avalonia.Controls.Primitives.RangeBase.ValidateDouble(Double value, String property) in D:\a\1\s\src\Avalonia.Controls\Primitives\RangeBase.cs:line 175
   at Avalonia.Controls.Primitives.RangeBase.set_Value(Double value) in D:\a\1\s\src\Avalonia.Controls\Primitives\RangeBase.cs:line 132
   at Avalonia.AvaloniaObject.<>c__DisplayClass54_0.<SetDirectValue>g__Set|0() in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 662
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in D:\a\1\s\src\Avalonia.Base\Reactive\LightweightObservableBase.cs:line 132
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 520
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify(AvaloniaObject source, AvaloniaProperty`1 property, TSetRecord& backing, TSetRecord value) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 42
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 554
   at Avalonia.Controls.Primitives.Track.ThumbDragged(Object sender, VectorEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Primitives\Track.cs:line 415
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 208
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 316
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 177
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 159
   at Avalonia.Controls.Primitives.Thumb.OnPointerMoved(PointerEventArgs e) in D:\a\1\s\src\Avalonia.Controls\Primitives\Thumb.cs:line 72
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 204
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 316
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 177
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 159
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 258
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 128
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in D:\a\1\s\src\Avalonia.Input\InputManager.cs:line 39
   at Avalonia.X11.X11Window.<ScheduleInput>b__97_0() in D:\a\1\s\src\Avalonia.X11\X11Window.cs:line 633
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.X11\X11PlatformThreading.cs:line 200
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in D:\a\1\s\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 106
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory)
   at WalletWasabi.Gui.Program.Main(String[] args) in /home/user/WalletWasabi/WalletWasabi.Gui/Program.cs:line 46
```

**Comment by danwalmsley** [comment]
Scenario here seems to be:
Window manager behaves differently to other OS in that, it wont allow min window size to be obeyed, so you may have minWidth or Height set to 200, but the OS says, no this window is going to be 600 x 800.... and Avalonia assumes that if window manager was told min size is X then it gets its way.

Probably we can fix the crash, but they layout issues will have to be solved in a future version.

@kekekeks think this is i3 window manager?
