### ISSUE TITLE
Moving expanded TreeView from one window to another.  

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#3328]
We have issue with moving tree view from one window to a new window. If you detach tree view from one visual tree by removing it from its parent and then assign it as content to newly created window we will get following error: `Avalonia.AvaloniaInternalException: 'Was attached to logical tree but cannot find root.'`. This happens only if you expand items before moving the tree view.

This is the stack trace:

```
Unhandled exception. Avalonia.AvaloniaInternalException: Was attached to logical tree but cannot find root.
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ItemVirtualizer.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ItemVirtualizer.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass(ILayoutRoot root)
   at Avalonia.Controls.Window.Show()
   at GritGene.UI.Sandbox.Views.DockingSandboxView.OnClick(Object sender, RoutedEventArgs e) in C:\Repo1\Engine\ModulesNet\GritGene.UI.Sandbox\Source\Views\DockingSandboxView.xaml.cs:line 42
   at Avalonia.Interactivity.Interactive.<>c__7`1.<AddHandler>g__InvokeAdapter|7_0(Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at GritGene.UI.Sandbox.Program.Main() in C:\Repo1\Engine\ModulesNet\GritGene.UI.Sandbox\Source\Program.cs:line 18
```

**Comment by grokys** [comment]
Turns out this is a bit of a tricky one. It's caused by this code introduced in #3216:

https://github.com/AvaloniaUI/Avalonia/blob/7f11d8374b21a450fa574e0dc51e4250e7abd838/src/Avalonia.Controls/Generators/TreeItemContainerGenerator.cs#L130-L146

What this is intended to do is allow `TreeViewItems` to be removed and re-attached to the logical tree. To do so, the `TreeViewItem` needs to remove its containers from the `TreeContainerIndex` when its detached from the logical tree, and when it's re-attached find the new `TreeContainerIndex` and rebuild its containers.

The problem is, that this code gets called not only when a `TreeViewItem` is removed from a `TreeView`, but also when a `TreeView` is removed from the logical tree completely.

In this case, the code linked above causes all but the top-level `TreeViewItem`s to get removed, which isn't correct, however there's a more insidious bug: these `TreeViewItem`s are still present in the `TreeViewItem.Presenter.Panel.Children` collection, but they have a `LogicalParent` of null because the [logical parent gets cleared when the items are dematerialized by the call to `ItemContainerGenerator.Clear()`](https://github.com/AvaloniaUI/Avalonia/blob/7f11d8374b21a450fa574e0dc51e4250e7abd838/src/Avalonia.Controls/ItemsControl.cs#L267-L295). This is what causes the exception in the issue stacktrace posted above.

All other code that calls `ItemContainerGenerator.Clear()` clears the items from the panel after the call. We can do that here, and it fixes the crash, but now when the `TreeView` is re-attached to a new root, only the top-level of `TreeViewItem`s are present - so this isn't much better.

What _should_ be happening is that when the `TreeViewItem` is detached from the logical tree, it should be able to tell whether it's been detached from the `TreeView` or whether the whole `TreeView` has been detached.

However, that's not possible because of [this innocuous commit](https://github.com/AvaloniaUI/Avalonia/commit/766a814f4e03afa0d99ad33e153d6502501a1c5a) from 2016 which says:

> This also has a side effect in that Parent will now be non-null when DetachedFromLogicalTree is called.

So when `DetachedFromLogicalTree` is called for the `TreeViewItem`, its `Parent` property is still set, meaning that there's no way to tell where the detachment occured. This feels wrong to me, but fixing it breaks a number of other things, so we need to tread carefully...
