### ISSUE TITLE
TreeView expanding multiple TreeViewItems that contain same children throws exception 

### ISSUE THREAD

**Issue by iihnat** [AvaloniaUI/Avalonia#3393]
I am currently using nightly build 0.9.999-cibuild0005228-beta

Added multiple TreeViewItems to TreeView. Each TreeviewItem has one child with the same text ("TWO" in example below). Expanding first TreeViewItem - treeview shows child ("TWO" in example), expanding second TreeViewItem - system throws exception: 

Message:
"An item with the same key has already been added. Key: TWO"
StackTrace:
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Avalonia.Controls.Generators.TreeContainerIndex.Add(Object item, IControl container) in D:\a\1\s\src\Avalonia.Controls\Generators\TreeContainerIndex.cs:line 52
   at Avalonia.Controls.Generators.TreeItemContainerGenerator`1.CreateContainer(Object item) in D:\a\1\s\src\Avalonia.Controls\Generators\TreeItemContainerGenerator.cs:line 98
   at Avalonia.Controls.Generators.ItemContainerGenerator.Materialize(Int32 index, Object item) in D:\a\1\s\src\Avalonia.Controls\Generators\ItemContainerGenerator.cs:line 59
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.AddContainers(Int32 index, IEnumerable items) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemVirtualizerNone.cs:line 93
   at Avalonia.Controls.Presenters.ItemVirtualizerNone..ctor(ItemsPresenter owner) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemVirtualizerNone.cs:line 26
   at Avalonia.Controls.Presenters.ItemVirtualizer.Create(ItemsPresenter owner) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemVirtualizer.cs:line 188
   at Avalonia.Controls.Presenters.ItemsPresenter.PanelCreated(IPanel panel) in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 142
   at Avalonia.Controls.Presenters.ItemsPresenterBase.CreatePanel() in D:\a\1\s\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 236
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in D:\a\1\s\src\Avalonia.Layout\Layoutable.cs:line 510
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in D:\a\1\s\src\Avalonia.Layout\Layoutable.cs:line 316
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in D:\a\1\s\src\Avalonia.Layout\LayoutManager.cs:line 196
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in D:\a\1\s\src\Avalonia.Layout\LayoutManager.cs:line 147
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in D:\a\1\s\src\Avalonia.Layout\LayoutManager.cs:line 105
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 174
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 121
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at AvaloniaApplication4.Program.AppMain(Application app, String[] args) in C:\source\repos\AvaloniaApplicationTest\AvaloniaApplicationTest\Program.cs:line 25
   at AvaloniaApplication4.Program.Main(String[] args) in C:\source\repos\AvaloniaApplicationTest\AvaloniaApplicationTest\Program.cs:line 13

Xaml: 

 ```
  <Grid>
       <StackPanel>
         <Button Width="100" Height="100" Content="TEST" Click="OnButton_Clicked"></Button>
         <TreeView x:Name="tvItems" Margin="5,5,5,5"/>
       </StackPanel>
     </Grid>
```
 

Code behind: 
  ```
 public class MainWindow : Window
    {
        TreeView tvItems;
        public MainWindow()
        {
            InitializeComponent();
            this.AttachDevTools();
            this.tvItems = this.Get<TreeView>("tvItems");
        }

        private void InitializeComponent()
        {

            AvaloniaXamlLoader.Load(this);
        }

        public void OnButton_Clicked(object sender, RoutedEventArgs e)
        {
            TreeViewItem nodeOne = new TreeViewItem();
            nodeOne.Header = "One";
            ((IList)nodeOne.Items).Add("TWO");
            TreeViewItem nodeTwo = new TreeViewItem();
            nodeTwo.Header = "One";
            ((IList)nodeTwo.Items).Add("TWO");
            ((IList)this.tvItems.Items).Add(nodeOne);
            ((IList)this.tvItems.Items).Add(nodeTwo);
        }
    }
```

**Comment by iihnat** [comment]
@kekekeks Any possible workarounds? Thanks!

**Comment by iihnat** [comment]
Adding TreeViewItems rather than strings solves the problem. 

`public void OnButton_Clicked(object sender, RoutedEventArgs e)
      {
          TreeViewItem nodeOne = new TreeViewItem();
          nodeOne.Header = "One";
          ((IList)nodeOne.Items).Add(new TreeViewItem(){ Header = "TWO"});
          TreeViewItem nodeTwo = new TreeViewItem();
          nodeTwo.Header = "One";
          ((IList)nodeTwo.Items).Add(new TreeViewItem(){ Header = "TWO"});
          ((IList)this.tvItems.Items).Add(nodeOne);
          ((IList)this.tvItems.Items).Add(nodeTwo);
      }`

**Comment by grokys** [comment]
Yeah, this is a bit of a special case because usually tree views will have a hierarchical structure, and using plain `string`  you're not going to have the structure to do that (so a `ListBox` would be more suitable for example). Having said that, we shouldn't crash, but probably instead just index a single one of the duplicated items.

**Comment by iihnat** [comment]
Thanks!

**Comment by Pyrdacor** [comment]
This still crashes in 0.10.12 with data templates if you use the same source object twice. I accidently added the same objects to two different ObservableCollections which themselves were part of some tree node parents. The data template then made a tree view item out of it, but as mentioned the same crash happened as above.

**Comment by grokys** [comment]
Fixed by PR #9677.
