### ISSUE TITLE
XAML compiler internal error when trying to bind property defined in generic class

### ISSUE THREAD

**Issue by mishun** [AvaloniaUI/Avalonia#3395]
On attempt to bind property XAML compiler fails with following error message:

```
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL: Internal compiler error while emitting node XamlIl.Ast.XamlIlMarkupExtensionNode:
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL: System.NullReferenceException: Object reference not set to an instance of an object.
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>C:\Users\User\source\repos\avalonia-generic\A\MainWindow.xaml(15,37,15,37): Avalonia error XAMLIL:    at Mono.Cecil.DefaultMetadataImporter.ImportReference(TypeReference type, IGenericParameterProvider context)
```

Following contrived conditions appear to be necessary for replication:
* Property must be defined inside generic class
* XAML must specify property binding
* XAML and generic class must be declared in different assemblies

See [minimal replication example](https://github.com/mishun/avalonia-xaml-compiler-bug-replication)

That usage attempt may be malformed, but in that case it should cause compilation error, not internal compiler error. It could actually be Cecil's bug, but unfortunately I don't know enough about XAML compiler internal to judge that.

**Comment by mishun** [comment]
Well, today I kinda realized that Avalonia actually tries to access underlying DirectProperty with reflection and I have this line of code in my example:
```F#
    static let TestProperty =
        AvaloniaProperty.RegisterDirect<MyControlBase<'T>, string>
            ("Test", (fun o -> o.Test), (fun o v -> o.Test <- v))
```
which is compiled into internal static field. It may cause problems due to "internal" part, so I did the identical thing in c# with public static field and result was identical to the above.

By the way, does Avalonia support StyledProperty/DirectProperty defined as static properties in a class (as opposed to static fields)? Public fields are not very f#-friendly. My first naive attempt didn't work, but maybe I did something wrong.

**Comment by kekekeks** [comment]
>By the way, does Avalonia support StyledProperty/DirectProperty defined as static properties in a class (as opposed to static fields)?

We are using the same convention (`public static readonly`) as WPF, UWP and Xamarin.Forms. So maaay be it's worth to create an issue in F# compiler to make it more UI-toolkit friendly?

**Comment by mishun** [comment]
Well, attempt to write "static val mutable public" with DefaultValue attribute get pommeled down with a weirdly specific error message, so it looks like that is by design :(. There're examples in tangentially relevant discussion [here](https://github.com/xamarin/Xamarin.Forms/issues/2425) of what f# stuff gets decompiled into so they (f# design team) want to keep their runtime initialization order checks I guess?

If I understand correctly, static getters are not supported by design?

**Comment by kekekeks** [comment]
XAML and dependency property engines, on the other hand, require that field is guaranteed to be immutable. One can't achieve such guarantees by contract via static properties.

**Comment by mishun** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/6c99236a03a3ef08a15b88fcb8d27fc0e2cd145c/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/Transformers/AvaloniaXamlIlTransformInstanceAttachedProperties.cs#L31-L32
https://github.com/AvaloniaUI/Avalonia/blob/6c99236a03a3ef08a15b88fcb8d27fc0e2cd145c/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/XamlIlAvaloniaPropertyHelper.cs#L38-L39
https://github.com/AvaloniaUI/Avalonia/blob/6c99236a03a3ef08a15b88fcb8d27fc0e2cd145c/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/XamlIlAvaloniaPropertyHelper.cs#L67-L69

I searched around for a little bit, and it doesn't appear FieldInfo.IsInitOnly is forced to true anywhere. (Also, why sometimes IsPublic is required and sometimes --- not?). Xamarin doesn't do that either:

https://github.com/xamarin/Xamarin.Forms/blob/e86299bd2053852268cf73eea5dcb9e63db4b33e/Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs#L285-L292

**Comment by kekekeks** [comment]
It's not forced, because compiler is technically not complete (while working fine for valid XAML in most cases) and doesn't validate a *lot* of things. 

What we can do is to relax this check for F# assemblies if there is a way to ensure immutability of the static property enforced by F# compiler.

**Comment by mishun** [comment]
F# generally discourages mutability (i.e. one needs to write additional stuff to make something mutable), but it is quite possible to make (static) property without setter that can change it's value and compiler doesn't mark properties with any attributes indicating immutability.

WPF doesn't seem to check readonly too:
https://github.com/dotnet/wpf/blob/02d2b1e39df8faaba2602095a8e8889bb3b76ba5/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs#L2371

**Comment by grokys** [comment]
I've looked into this issue and the problem seems to be when generating the `IProvideValueTarget` instance to the `{Binding}` markup extension.

When doing this, the compiler tries to emit an `Ldsfld` IL instruction to load the value of the field, but it does this with a partially bounded generic type: `Avalonia.DirectProperty`2<Test.MyControlBase`1<T>,System.String>`

Cecil doesn't like this, and indeed its not possible to do e.g. `typeof(Avalonia.DirectProperty`2<Test.MyControlBase`1<>,System.String>)` in C# because a generic type must be fully bounded or fully unbounded, which probably explains it (would be nice if it threw a nice exception than a NRE though).

The reason this passes if the type is in the same assembly is [a short-circuit in cecil](https://github.com/jbevain/cecil/blob/e9a4815fdb102a3bc87a606c6e9ee5f61c00414a/Mono.Cecil/ModuleDefinition.cs#L849-L850) that suggests that maybe this should be possible?

In this particular case a workaround is to declare the field as a `DirectPropertyBase<T>` instead of a `DirectProperty<T,T>` but this isn't going to work for e.g. properties that have the generic parameter in the value.

@kekekeks not sure what the fix is here: do we need to construct a bound type based on the containing type (fiddly) or do you think cecil should allow importing references to partially bound types?

**Comment by kekekeks** [comment]
> that suggests that maybe this should be possible?

It will likely cause InvalidProgramException in runtime.

We need to fix the initial problem that generates an incomplete generic class access

**Comment by grokys** [comment]
Hmm, yeah actually whenever I try to repro this, I'm getting the properly bounded type. Need to work out why in this case it's not finding a bounded type. I don't think it's due to F# as @pr8x is seeing this in C# too.

**Comment by grokys** [comment]
Actually I don't think we need to make the generic types bounded. The field type is loaded [at this line](https://github.com/kekekeks/XamlX/blob/7d15a9227461cf4d62bc2ed251fcc25c96b28aaf/src/XamlX.IL.Cecil/CecilEmitter.cs#L37) but the calling method [only ever uses the `Field`](https://github.com/kekekeks/XamlX/blob/7d15a9227461cf4d62bc2ed251fcc25c96b28aaf/src/XamlX.IL.Cecil/CecilEmitter.cs#L118) and not the `FieldType`.

What the `Import(rv.FieldType)` does is make sure all the references are loaded however. We still need to do this.

**Comment by rstm-sf** [comment]
It looks like it's worth reopening, since https://github.com/kekekeks/XamlX/pull/42?

**Comment by grokys** [comment]
Yeah kekekeks/XamlX#42 tried to fix the issue but broke the following (more simple) case:

```
diff --git a/samples/Sandbox/TestControl.cs b/samples/Sandbox/TestControl.cs
new file mode 100644
index 000000000..ae241f3cc
--- /dev/null
+++ b/samples/Sandbox/TestControl.cs
@@ -0,0 +1,55 @@
+﻿using System;
+using System.Globalization;
+using Avalonia;
+using Avalonia.Controls;
+using Avalonia.Data.Converters;
+
+namespace Sandbox
+{
+    public class BoolToValueConverter<T> : AvaloniaObject, IValueConverter
+    {
+        public static readonly DirectProperty<BoolToValueConverter<T>, T> TrueValueProperty =
+            AvaloniaProperty.RegisterDirect<BoolToValueConverter<T>, T>(
+                nameof(TrueValue),
+                o => o.TrueValue,
+                (o, v) => o.TrueValue = v);
+
+        public static readonly DirectProperty<BoolToValueConverter<T>, T> FalseValueProperty =
+            AvaloniaProperty.RegisterDirect<BoolToValueConverter<T>, T>(
+                nameof(FalseValue),
+                o => o.FalseValue,
+                (o, v) => o.FalseValue = v);
+
+#pragma warning disable 8618
+        private T _trueValue;
+        private T _falseValue;
+#pragma warning restore 8618
+
+        public T TrueValue
+        {
+            get => _trueValue;
+            set => SetAndRaise(TrueValueProperty, ref _trueValue, value);
+        }
+
+        public T FalseValue
+        {
+            get => _falseValue;
+            set => SetAndRaise(FalseValueProperty, ref _falseValue, value);
+        }
+
+        public object? Convert(object? value, Type? targetType, object? parameter, CultureInfo? culture)
+        {
+            if (value is null || !(bool) value)
+            {
+                return FalseValue;
+            }
+
+            return TrueValue;
+        }
+
+        public object ConvertBack(object? value, Type? targetType, object? parameter, CultureInfo? culture)
+        {
+            throw new NotImplementedException();
+        }
+    }
+}
diff --git a/samples/Sandbox/MainWindow.axaml b/samples/Sandbox/MainWindow.axaml
index 6929f192c75098fa26851573ddd5a3fb70d19e30..a2a15696f2ad405876eb646f0502adee71a48b3a 100644
--- a/samples/Sandbox/MainWindow.axaml
+++ b/samples/Sandbox/MainWindow.axaml
@@ -1,4 +1,15 @@
 <Window xmlns="https://github.com/avaloniaui"
         xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
+        xmlns:sandbox="clr-namespace:Sandbox"
+        xmlns:system="clr-namespace:System;assembly=System.Runtime"
         x:Class="Sandbox.MainWindow">
+
+    <Window.Resources>
+        <system:Double x:Key="O">41</system:Double>
+        <sandbox:BoolToValueConverter x:Key="OpacityConverter"
+                                      x:TypeArguments="system:Double"
+                                      TrueValue="1" 
+                                      FalseValue="{StaticResource O}" />
+    </Window.Resources>
+
 </Window>
 ```

The two failure cases are:

- `Avalonia.DirectProperty`2<Test.MyControlBase`1<T>,System.String>` - this fails with an NRE in Cecil at compile time. if you resolve it to `Avalonia.DirectProperty`2<Test.MyControlBase`1<System.String>,System.String>` then it passes
- `Avalonia.DirectProperty`2<Sandbox.BoolToValueConverter`1<T>,T>` which using the above rule gets resolved to `Avalonia.DirectProperty`2<Sandbox.BoolToValueConverter`1<System.Double>,System.Double>` - this fails at runtime

**Comment by pr8x** [comment]
@grokys @jkoritzinsky Was this fixed, actually?

**Comment by grokys** [comment]
I don't think it was. I'm not sure why GitHub closed it.

**Comment by maxkatz6** [comment]
Tested with a similar C# code (couldn't get F# working) and generics and it is fixed now in master (likely after https://github.com/kekekeks/XamlX/pull/114 or https://github.com/kekekeks/XamlX/pull/113):
```
public class MyControlBase2<T> : Control
{
    private string _test;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("AvaloniaProperty", "AVP1002", Justification = "Generic avalonia property is expected here.")]
    public static readonly DirectProperty<MyControlBase2<T>, string> TestProperty = AvaloniaProperty.RegisterDirect<MyControlBase2<T>, string>(
        "Test", o => o.Test, (o, v) => o.Test = v);

    public string Test
    {
        get => _test;
        set => SetAndRaise(TestProperty, ref _test, value);
    }

    public override void Render(DrawingContext context)
    {
        context.DrawText(
            new FormattedText(_test, CultureInfo.CurrentCulture, FlowDirection.LeftToRight,
                new Typeface(FontFamily.Default), 12, Brushes.Green), new Point());
    }
}

public class MyControl : MyControlBase2<string>
{
}
```

**Comment by maxkatz6** [comment]
Also, code in https://github.com/AvaloniaUI/Avalonia/issues/3395#issuecomment-766792549 didn't regress this time.
