### ISSUE TITLE
Aalonia.SkiaSharp.dll NullReference when window started Minimized

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3410]
It doesn't crash the application tho.

```
 public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#else
            this.WindowState = WindowState.Minimized;
#endif
            DataContext = new MainWindowViewModel(this);
        }
```

```
Exception thrown: 'System.NullReferenceException' in Avalonia.Skia.dll
[Visual] Exception in render loop: "System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time)" (Avalonia.Rendering.RenderLoop #54181145)
```

**Comment by bsglinux16** [comment]
Does Not Crash The Application But Prevents The Debugger

**Comment by bsglinux16** [comment]
#4715

**Comment by MikeCodesDotNET** [comment]
Tested with v11 RC and it worked as expected.
