### ISSUE TITLE
Switching tabs in TabControl using dynamic ContextMenu results in empty ContextMenu

### ISSUE THREAD

**Issue by openmandev** [AvaloniaUI/Avalonia#3468]
Switching tabs in TabControl using dynamic ContextMenu results in empty (very small rectangle) ContextMenu above new Tab.

Repro project:
https://github.com/openmandev/DynamicTabs

Run.
On the left pane in the context menu click "TabType1".
On the TreeView right click "TnkCode" and select menu "Context TabType2".

**Comment by openmandev** [comment]
One more bug on the same Tabs. Maybe they're both about the same thing.

Run.
On the left pane in the context menu click "TabType1".
On the TreeView right click "Code".
Than right click "TnkCode" and select menu "Conext TabType2".
You've got empty Tab Body.
Trying to switch to another Tab results in exception:

Unhandled exception. Avalonia.AvaloniaInternalException: Was attached to logical tree but cannot find root.
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)
   at Avalonia.StyledElement.ClearLogicalParent(IEnumerable`1 children)
   at Avalonia.StyledElement.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Visual.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyRemove(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Remove(T item)
   at Avalonia.Controls.ItemsControl.OnContainersDematerialized(ItemContainerEventArgs e)
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnContainersDematerialized(ItemContainerEventArgs e)
   at Avalonia.Controls.ItemsControl.<get_ItemContainerGenerator>b__12_1(Object _, ItemContainerEventArgs e)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Clear()
   at Avalonia.Controls.Presenters.ItemContainerSync.ItemsChanged(ItemsPresenterBase owner, IEnumerable items, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenterBase.set_Items(IEnumerable value)
   at Avalonia.Controls.ItemsControl.ItemsChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.Primitives.SelectingItemsControl.ItemsChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.ItemsControl.<>c.<.cctor>b__9_0(ItemsControl x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass7_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Utilities.DeferredSetter`1.SetAndRaisePropertyChanged(AvaloniaObject source, AvaloniaProperty`1 property, TSetRecord& backing, TSetRecord value)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify(AvaloniaObject source, AvaloniaProperty`1 property, TSetRecord& backing, TSetRecord value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.ItemsControl.set_Items(IEnumerable value)
   at Avalonia.Controls.ItemsControl.<>c.<.cctor>b__9_4(ItemsControl o, IEnumerable v)
   at Avalonia.DirectProperty`2.Avalonia.IDirectPropertyAccessor.SetValue(IAvaloniaObject instance, Object value)
   at Avalonia.AvaloniaObject.<>c__DisplayClass54_0.<SetDirectValue>g__Set|0()
   at Avalonia.AvaloniaObject.SetDirectValue(AvaloniaProperty property, Object value)
   at Avalonia.AvaloniaObject.DirectBindingSubscription.OnNext(Object value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Data.Core.BindingExpression.InnerListener.OnNext(Object value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Data.Core.ExpressionObserver.ValueChanged(Object value)
   at Avalonia.Data.Core.ExpressionNode.NextValueChanged(Object value)
   at Avalonia.Data.Core.ExpressionNode.NextValueChanged(Object value)
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify)
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value)
   at Avalonia.Data.Core.Plugins.PropertyError.Subscribe(Action`1 listener)
   at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference)
   at Avalonia.Data.Core.ExpressionNode.StartListening()
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify)
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value)
   at Avalonia.Data.Core.Plugins.PropertyAccessorBase.PublishValue(Object value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.set_InheritanceParent(IAvaloniaObject value)
   at Avalonia.StyledElement.Avalonia.Controls.ISetInheritanceParent.SetParent(IAvaloniaObject parent)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.Presenters.ContentPresenter.<>c.<.cctor>b__14_0(ContentPresenter x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass7_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.PriorityValue.SetAndNotify(ValueTuple`2& backing, ValueTuple`2 update)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotifyCallback[TValue](AvaloniaProperty property, ISetAndNotifyHandler`1 setAndNotifyHandler, TValue& backing, TValue value)
   at Avalonia.PriorityValue.UpdateValue(Object value, Int32 priority)
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value)
   at Avalonia.Data.TemplateBinding.PublishValue()
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.AddValue(AvaloniaProperty property, Object value, Int32 priority)
   at Avalonia.AvaloniaObject.SetStyledValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at Avalonia.Controls.TabControl.set_SelectedContent(Object value)
   at Avalonia.Controls.TabControl.UpdateSelectedContent(IContentControl item)
   at Avalonia.Controls.TabControl.UpdateSelectedContent(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Controls.TabControl.<>c.<.cctor>b__7_0(TabControl x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass7_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelectedItem(Int32 index, Boolean clear)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelection(Int32 index, Boolean select, Boolean rangeModifier, Boolean toggleModifier, Boolean rightButton)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelection(IControl container, Boolean select, Boolean rangeModifier, Boolean toggleModifier, Boolean rightButton)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateSelectionFromEventSource(IInteractive eventSource, Boolean select, Boolean rangeModifier, Boolean toggleModifier, Boolean rightButton)
   at Avalonia.Controls.TabControl.OnPointerPressed(PointerPressedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_8(InputElement x, PointerPressedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.X11.X11Window.<ScheduleInput>b__97_0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at DynamicTabs.Program.Main(String[] args) in /home/ashirokov/devel/cs/DynamicTabs/Program.cs:line 20

**Comment by grokys** [comment]
Is this the same as #2719 do you think?

**Comment by openmandev** [comment]
_Highly likely_ it's the first case from #2719.

**Comment by MonkAlex** [comment]
Simple fix for my case:
[ContextMenu.cs](https://github.com/MonkAlex/MangaReader/blob/master/MangaReader.Avalonia/View/ContextMenu.cs)

**Comment by openmandev** [comment]
> Simple fix for my case:
> [ContextMenu.cs](https://github.com/MonkAlex/MangaReader/blob/master/MangaReader.Avalonia/View/ContextMenu.cs)

I just have tried this fix. Nothing changed.

**Comment by MonkAlex** [comment]
Reproduced in my project too.

> Unhandled exception. Avalonia.AvaloniaInternalException: Was attached to logical tree but cannot find root.

**Comment by openmandev** [comment]
This bug:
"Unhandled exception. Avalonia.AvaloniaInternalException: Was attached to logical tree but cannot find root."
was fixed in nightly builds.
It is not reproduced in my project.
In 0.9.9 still exists.

**Comment by openmandev** [comment]
> > Simple fix for my case:
> > [ContextMenu.cs](https://github.com/MonkAlex/MangaReader/blob/master/MangaReader.Avalonia/View/ContextMenu.cs)
> 
> I just have tried this fix. Nothing changed.

Using
`
    private void OnDataContextChanged(PropertyValue<ContextMenu, object> obj)
    {
      if ( obj.Value == null && IsOpen )
      {
        Dispatcher.UIThread.InvokeAsync((Action)(() => Close()));
      }
    }
`
in some case helps to close empty menu. But it really depends on cpu loading and timing characteristics of the code.
Very annoying effect.
