### ISSUE TITLE
[0.9.3] [Mac OS] SharpGen.Runtime.SharpGenException

### ISSUE THREAD

**Issue by VakhtinAndrey** [AvaloniaUI/Avalonia#3533]
AvaloniaUI 0.93

OS is running under virtual machine:
```
macOS 10.13.6 (17G66)
Darwin 17.7.0
```
Got the following error when executing an application:
```
Unhandled exception. SharpGen.Runtime.SharpGenException: HRESULT: [0x80004005], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown
   at SharpGen.Runtime.Result.CheckError()
   at Avalonia.Native.Interop.IAvnGlDisplay.CreateContext(IAvnGlContext share)
   at Avalonia.Native.GlPlatformFeature..ctor(IAvnGlDisplay display)
   at Avalonia.Native.AvaloniaNativePlatform.DoInitialize(AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(IntPtr factory, AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at PanelCreator.App.Program.Main(String[] args)
Abort trap: 6
```

Probably related to a commit 643217452896a0bfd1d037ce6af4fa3ffaa36b9c

**Comment by kekekeks** [comment]
OSX doesn't support OpenGL when running in virtual machines. We've been trying to use it anyway which caused various visual artifacts. You can disable OpenGL acceleration by adding `.With(new AvaloniaNativePlatformOptions { UseGpu = false })`  to your AppBuilder.

**Comment by kekekeks** [comment]
@danwalmsley we might want to detect the failure to create a hw-accelerated OpenGL context and just disable OpenGL in that case.

**Comment by VakhtinAndrey** [comment]
Yep, I've faced various artifacts as well (like window is not updating) and app crashes.
Thank you, @kekekeks, I'll try it.

**Comment by VakhtinAndrey** [comment]
Looks like it helps, thank you!
@kekekeks, could please you confirm if turning off gpu rendering requires only for virtual machine and there is no reason to turn it off on a real hardware?

**Comment by kekekeks** [comment]
The recent change [has added](https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/cgl.mm#L7) `kCGLPFAAccelerated` flag which enforces CGL to only use hw-accelerated contexts. So CGL context creation now fails on virtual machines.

**Comment by VakhtinAndrey** [comment]
There is another unhandled system exception. It appears after application was closed (ShutdownMode.OnMainWindowClose is used).
[MacOS error.txt](https://github.com/AvaloniaUI/Avalonia/files/4176893/MacOS.error.txt)
