### ISSUE TITLE
macOS: Crash when closing any window

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3544]
Crash on macOS with cibuild5911 when closing any window. [mat1jaczyyy/apollo-studio](github.com/mat1jaczyyy/apollo-studio)

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowBaseImpl.get_Scaling()
   at Avalonia.Controls.TopLevel.Avalonia.Layout.ILayoutRoot.get_LayoutScaling()
   at Avalonia.Layout.Layoutable.GetLayoutScale()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Controls.WindowBase.HandleResized(Size clientSize)
   at Avalonia.Controls.Window.HandleResized(Size clientSize)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Resized(AvnSize size)
   at Avalonia.Native.Interop.IAvnWindowBaseEventsShadow.IAvnWindowBaseEventsVtbl.Resized(IntPtr thisObject, Void* param0)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Apollo.Core.Program.Main(String[] args) in /Users/mat1jaczyyy/Code/apollo-studio/Apollo/Core/Program.cs:line 125
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by kekekeks** [comment]
@danwalmsley it looks like that we are trying to handle resize on a window that's considered to be closed by Acalonia. Osx probably triggers that event on performClose or something
