### ISSUE TITLE
AppBuilder throws exception for some Win10 users

### ISSUE THREAD

**Issue by DooblyNoobly** [AvaloniaUI/Avalonia#3601]
A user of our app hasn't been able to start the program due to the exception below:

```
Application: StationHub.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.CompareString(ReadOnlySpan`1 string1, ReadOnlySpan`1 string2, CompareOptions options)
   at System.Globalization.CompareInfo.Compare(String string1, String string2, CompareOptions options)
   at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant()
   at System.Globalization.TextInfo.ChangeCaseCommon[TConversion](String source)
   at System.Globalization.TextInfo.ToLower(String str)
   at System.String.ToLowerInvariant()
   at System.UriParser.IsKnownScheme(String schemeName)
   at Avalonia.Shared.PlatformSupport.AssetLoader.RegisterResUriParsers()
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatformServices.Register(Assembly assembly)
   at Avalonia.AppBuilder.<>c.<.ctor>b__0_0(AppBuilder builder)
   at Avalonia.Controls.AppBuilderBase`1.<>c__DisplayClass44_0.<.ctor>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at UnitystationLauncher.Program.Main(String[] args) in D:\GitHub\UnitystationLauncher\UnitystationLauncher\Program.cs:line 9
```
This what is found on line 9: 
` 
public static void Main(string[] args) => BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);`

And here is my AppBuilder code:
```cs
class Program
    {
        public static void Main(string[] args) => BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .With(new X11PlatformOptions { UseGpu = true })
                .With(new AvaloniaNativePlatformOptions { UseGpu = true, UseDeferredRendering = false })
                .With(new MacOSPlatformOptions { ShowInDock = true })
                .With(new Win32PlatformOptions
                {
                    UseDeferredRendering = false
                })
                .LogToDebug()
                .UseReactiveUI(); 
    }
```

Any ideas on how to fix it?

**Comment by grokys** [comment]
Hmm, seems that `CompareInfo.CompareString` is throwing, which isn't part of Avalonia. I just did a few google searches for the error and came up with some stuff that might be useful?

https://stackoverflow.com/questions/58613263/serviceprovider-getservicetype-throw-exception-for-every-usage
https://github.com/dotnet/runtime/issues/31540

The stackoverflow answer suggests it might be a packaging problem?

**Comment by kekekeks** [comment]
Definitely not Avalonia issue since it's actually thrown by code called from `System.String.ToLowerInvariant`. You are most likely packaging your app in unorthodox way.
