### ISSUE TITLE
linux-musl-x64 RID not supported by avalonia.skia.linux.natives

### ISSUE THREAD

**Issue by randoaccount123** [AvaloniaUI/Avalonia#3632]
I have an application that tries to start a DRM session when running on linux like this:

```
public static AppBuilder GetBuilder()
  => AppBuilder.Configure<App>().UsePlatformDetect();

public static int Main(string[] args)
{
	var builder = GetBuilder();
	if(RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
		builder.StartLinuxDrm(args);
	else
		builder.Start(AppMain, args);
	return 0;
}
```

The application was published using:
`dotnet.exe publish -c Release -r linux-musl-x64 --self-contained -o tmp_release_dir`

When I try to run my application on the deployment host, I get this error:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory
   at SkiaSharp.SkiaApi.gr_glinterface_assemble_gles_interface(IntPtr ctx, IntPtr get)
   at SkiaSharp.GRGlInterface.AssembleGlesInterface(Object context, GRGlGetProcDelegate get)
   at SkiaSharp.GRGlInterface.AssembleGlesInterface(GRGlGetProcDelegate get)
   at Avalonia.Skia.PlatformRenderInterface..ctor(ICustomSkiaGpu customSkiaGpu)
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at LinuxFramebufferPlatformExtensions.StartLinuxDirect[T](T builder, String[] args, IOutputBackend backend)
   at LinuxFramebufferPlatformExtensions.StartLinuxDrm[T](T builder, String[] args, String card, Double scaling)
```

Following the advice in #2054, I tried to copy from `~/.nuget` but the only supported runtimes are linux-arm and linux-64, both of which are linked against glibc, and unlikely to work against a musl-linked system.

How can I build avalonia.skia.linux.natives for linux-musl-x64?

**Comment by kekekeks** [comment]
https://github.com/mono/SkiaSharp/wiki/Building-on-Linux (make sure to checkout the correct version, the guide might have a different one)

**Comment by jmacato** [comment]
I wonder if we should setup a new Avalonia Skia native bins package with all RIDs from dotnet in it...

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/skia-build-docker - feel free to continue the work there.

Another alternative is to link `libc` statically, so we will only depend on libfontconfig.

**Comment by Gillibald** [comment]
First step would be changing the build to use Clang. Not so sure if a pre build toolchain is available. If not a build will take some time.
