### ISSUE TITLE
Binding to explicitly implemented interface property

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#3635]
Example
```XAML
<TextBox Text="{Binding Path=(local:ISomeInterface.SomeProperty)}" />
```

**Comment by wieslawsoltes** [comment]
Current status - throws excpetion: Object reference not set to an instance of an object.

```
   at Avalonia.Data.Core.AvaloniaPropertyAccessorNode.get_PropertyType()
   at Avalonia.Data.Core.ExpressionObserver.get_ResultType()
   at Avalonia.Data.Core.BindingExpression.OnNext(Object value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.Subscribed(IObserver`1 observer, Boolean first)
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer)
   at Avalonia.Data.BindingOperations.Apply(IAvaloniaObject target, AvaloniaProperty property, InstancedBinding binding, Object anchor)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at SvgXml.Diagnostics.Views.Attributes.CommonProperties.!XamlIlPopulate(IServiceProvider , CommonProperties ) in C:\DOWNLOADS\GitHub\Svg.Skia\src\SvgXml.Diagnostics\Views/Attributes/CommonProperties.xaml:line 23
   at SvgXml.Diagnostics.Views.Attributes.CommonProperties.!XamlIlPopulateTrampoline(CommonProperties )
   at SvgXml.Diagnostics.Views.Attributes.CommonProperties.InitializeComponent() in C:\DOWNLOADS\GitHub\Svg.Skia\src\SvgXml.Diagnostics\Views\Attributes\CommonProperties.xaml.cs:line 15
   at SvgXml.Diagnostics.Views.Attributes.CommonProperties..ctor() in C:\DOWNLOADS\GitHub\Svg.Skia\src\SvgXml.Diagnostics\Views\Attributes\CommonProperties.xaml.cs:line 10
   at SvgXml.Diagnostics.Views.MainWindow.XamlIlClosure_e78cddc8-84b3-4990-be4b-0077c75a6f4a.Build(IServiceProvider ) in C:\DOWNLOADS\GitHub\Svg.Skia\src\SvgXml.Diagnostics\Views/MainWindow.xaml:line 1119
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.<>c__DisplayClass0_0.<DeferredTransformationFactoryV1>b__0(IServiceProvider sp)
   at Avalonia.Markup.Xaml.Templates.TemplateContent.Load(Object templateContent)
   at Avalonia.Markup.Xaml.Templates.DataTemplate.Build(Object data)
   at Avalonia.Controls.Presenters.ContentPresenter.CreateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SvgXml.Diagnostics.Program.Main(String[] args) in C:\DOWNLOADS\GitHub\Svg.Skia\src\SvgXml.Diagnostics\Program.cs:line 14
```

**Comment by maxkatz6** [comment]
Works with compiled bindings.
```{CompiledBinding $parent.((local:IHasImplicitProperty)DataContext).ImplicitProperty}```
