### ISSUE TITLE
XOpenDisplay exception

### ISSUE THREAD

**Issue by gnilsson2** [AvaloniaUI/Avalonia#3673]
Running VS-code remoteSSH
xterm in Terminal works
but stepping in to the program gives:
```
Exception has occurred: CLR/System.Exception
An unhandled exception of type 'System.Exception' occurred in Avalonia.X11.dll: 'XOpenDisplay failed'
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at MyApp.Program.Main(String[] args) in /home/gunnarni/tools/Ava1/MyApp/Program.cs:line 14
```

**Comment by kekekeks** [comment]
You need to set DISPLAY environment variable. If that doesn't help, also try running `xhost +` from said xterm.
