### ISSUE TITLE
Null ref on binding to static property

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3815]
## Environment

* Visual Studio 16.5
* Windows 10
* Avalonia latest `master` (0.9.999-cibuild0006779-beta)

## Bug

Trying to bind to a static property fails outright with a null ref:

```csharp
class AnObject
{
    public static event PropertyChangedEventHandler StaticPropertyChanged;

    private static void OnStaticPropertyChanged(string propertyName)
    {
        StaticPropertyChanged?.Invoke(null, new PropertyChangedEventArgs(propertyName));
    }

    private static bool _myProperty = true;

    public static bool MyProperty
    {
        get => _myProperty;
        set
        {
            _myProperty = value;
            OnStaticPropertyChanged(nameof(MyProperty));
        }
    }
}
```

```xml
<CheckBox
      IsChecked="{Binding Path=(local:AnObject.MyProperty)}"
      Content="I should be checked on startup"/>
```

The info on binding to a static property came from [this SO post](https://stackoverflow.com/a/34763286/3938401).

## Stack Trace

```
   at Avalonia.Data.Core.AvaloniaPropertyAccessorNode.get_PropertyType()
   at Avalonia.Data.Core.ExpressionObserver.get_ResultType()
   at Avalonia.Data.Core.BindingExpression.OnNext(Object value)
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.Subscribed(IObserver`1 observer, Boolean first)
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer)
   at Avalonia.Data.BindingOperations.Apply(IAvaloniaObject target, AvaloniaProperty property, InstancedBinding binding, Object anchor)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at StaticObjectBinding.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in C:\Users\myname\source\repos\AvaloniaBugs\StaticObjectBinding\MainWindow.xaml:line 10
```

On an earlier CI build (0.9.999-cibuild0006647-beta), the binding fails silently (although I'm using it for a `MenuItem`'s `IsVisible` property).

## Reproducible Sample

https://github.com/Deadpikle/AvaloniaBugs/tree/master/StaticObjectBinding

**Comment by kekekeks** [comment]
I don't think we support binding to static properties. You should be able to use `x:Static` instead.

**Comment by Deadpikle** [comment]
OK, sounds fine. Thank you. I was able to come up with a solution for my application.

Should this issue be closed (read: "we won't support this") or left open (read: "we'll support this eventually maybe")?

**Comment by tomenscape** [comment]
+1 to this feature request.

**Comment by Takoooooo** [comment]
Tested and seems it is fixed already
