### ISSUE TITLE
Multi window NRE in Dev Tools

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#3827]
1. Have two windows open
2. Open DevTools in a window
3. Close that window, DevTools will not close
4. Attempt to Ctrl+Shift inspect something on the leftover other window

Result:
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Avalonia.Visuals.dll: 'Object reference not set to an instance of an object.'
   at Avalonia.VisualTree.VisualExtensions.GetVisualsAt(IVisual visual, Point p, Func`2 filter)
   at Avalonia.Diagnostics.Views.MainWindow.RawKeyDown(RawKeyEventArgs e)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 146
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Apollo.Core.Program.Main(String[] args) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Core\Program.cs:line 123
```

Not sure what the intended behavior is, but IMO would be nicer for DevTools to switch its tree base to the other window upon inspection.

cibuild0006806

**Comment by mat1jaczyyy** [comment]
Not an issue anymore, on step 3 DevTools now closes. 0.10.999-cibuild0012650-beta
