### ISSUE TITLE
Segfault on default template in Ubuntu 20.04

### ISSUE THREAD

**Issue by trinitrotoluene** [AvaloniaUI/Avalonia#3881]
**Environment:**
- Ubuntu 20.04 x86_64
- .NET SDK 3.1.201
- Target framework: netcoreapp3.1
- Avalonia 0.9.0
- Avalonia-Desktop 0.9.0

**Reproduce:**
- Install the `dotnet new` Avalonia templates
- create a new `avalonia.app` project
- build it
- run either `./Project.Name` or `dotnet Project.Name.dll`
- `Thread 1 "Project.Name" received signal SIGSEGV, Segmentation fault.`

```

**GDB Output**
(gdb) backtrace
#0  0x00007fffef1c2804 in ?? () from [cleaned]/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so
#1  0x00007fffef1c2fcd in ?? () from [cleaned]/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so
#2  0x00007fffef1a5cce in ?? () from [cleaned]/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so
#3  0x00007fffeef9bda7 in gr_glinterface_assemble_gl_interface () from [cleaned]/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so
#4  0x00007fff7e43c833 in ?? ()
#5  0x000000003030003a in ?? ()
#6  0x00000000003c598e in ?? ()
#7  0x00007ffff7528728 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.3/libcoreclr.so
#8  0x00007fffffffd0f8 in ?? ()
```

**Comment by kekekeks** [comment]
Try updating to 0.9.9

**Comment by trinitrotoluene** [comment]
That fixed it. I'll go open a PR on the template repo to update the dependencies, then.

Thanks!
