### ISSUE TITLE
Empty TabControl causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/Avalonia#3919]
## Environment

* CI build 0.9.999-cibuild0007310-beta
* Windows 10

## Bug

Looks like if your `TabControl.Items` property is initially empty on data bind, things go kaboom with an `ArgumentOutOfRangeException`. Probably related to the recent [selection changes](https://github.com/AvaloniaUI/Avalonia/pull/3583).

What's going on is that the `SelectionNode` has a single selected index _before_ the `TabControl` is data bound (see [this line](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs#L860)). `TabControl` has a `SelectionMode` of `AlwaysSelected`, so it tries to retain a selected index of 0. The selection isn't cleared on source change (data context binding), so when the `TabControl` tries to re-select index 0, which doesn't exist, the app crashes.

## Stack Trace

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.SelectionNode.PopulateSelectedItemsFromSelectedIndices()
   at Avalonia.Controls.SelectionNode.set_Source(Object value)
   at Avalonia.Controls.SelectionModel.set_Source(Object value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateFinished()
   at Avalonia.Controls.Primitives.SelectingItemsControl.InternalEndInit()
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnDataContextEndUpdate()
   at Avalonia.StyledElement.DataContextNotifying(StyledElement element, Boolean updateStarted)
   at Avalonia.StyledElement.DataContextNotifying(IAvaloniaObject o, Boolean updateStarted)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.Avalonia.IAvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](StyledPropertyBase`1 property, BindingPriority priority, Optional`1 oldValue, BindingValue`1 newValue)
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority)
   at Avalonia.StyledElement.set_DataContext(Object value)
   at TabControlRenderBreak.MainWindow..ctor() in C:\Users\me\source\repos\AvaloniaBugs\TabControlRenderBreak\MainWindow.xaml.cs:line 12
   at TabControlRenderBreak.App.OnFrameworkInitializationCompleted() in C:\Users\me\source\repos\AvaloniaBugs\TabControlRenderBreak\App.xaml.cs:line 18
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at TabControlRenderBreak.Program.Main(String[] args) in C:\Users\me\source\repos\AvaloniaBugs\TabControlRenderBreak\Program.cs:line 13
```

## Code

`MainWindow.xaml`:

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TabControlRenderBreak.MainWindow"
        Title="TabControlRenderBreak">
  <TabControl Items="{Binding Tabs}"/>
</Window>
```

`MainWindow.xaml.cs`:

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace TabControlRenderBreak
{
    public class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = new ViewModel();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

`ViewModel.cs`:

```csharp
using System.Collections.Generic;

namespace TabControlRenderBreak
{
    class ViewModel
    {
        public ViewModel()
        {
            Tabs = new List<string>() {}; // no crash if you give this something initially
        }

        public List<string> Tabs { get; set; }
    }
}
```

## Repro

https://github.com/Deadpikle/AvaloniaBugs/tree/master/TabControlRenderBreak

**Comment by grokys** [comment]
Seems to be a problem caused by the new `SelectionModel` with `RetainSelectionOnReset`. The following unit test fails:

```
[Fact]
public void RetainSelectionOnReset_Assigning_Source_With_Less_Items_Than_Selection_Trims_Selection()
{
    var data = new[] { "foo", "bar", "baz" };
    var target = new SelectionModel { RetainSelectionOnReset = true };
    target.SelectedIndex = new IndexPath(4);
    target.Source = data;
    Assert.Empty(target.SelectedIndices);
}
```

**Comment by Deadpikle** [comment]
Thanks again for your time in Gitter.

I took a look at this, but I wasn't able to solve it in the time I had today. I'm not sure when or if I'll be able to look at this in-depth, sorry. 

I have added some more tests on my branch here for a few more cases, including some from Gitter: https://github.com/Deadpikle/Avalonia/tree/fix/3919-attempt-2

This is specifically an issue with going from `null` source to a non-null source. Right now, if you go from valid (non-null) source to another source, the selection is _cleared_, so the bug doesn't happen then. ...granted, that clearing of selection doesn't currently check `RetainSelectionOnReset`, so I'm not sure where that comes into play, here. ([Probably don't need to check if `_rootNode.Source` is `null` 2x, too](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/SelectionModel.cs#L48)).

Here are the unit tests I added in my fork based on our chat in Gitter. Not sure they are all necessary.

```
// test that going from non-null source to non-null source clears selection
[Fact]
public void Assigning_Source_With_Less_Items_Than_Previous_Clears_Selection()
{
    var data = new[] { "foo", "bar", "baz", "boo", "hoo" };
    var smallerData = new[] { "foo", "bar", "baz" };
    var target = new SelectionModel { RetainSelectionOnReset = true };
    target.Source = data;
    target.SelectedIndex = new IndexPath(4);
    target.Source = smallerData;
    Assert.Empty(target.SelectedIndices);
}

// test from grokys for trimming selection with null source to non-null source
[Fact]
public void Assigning_Source_With_Less_Items_Than_Selection_Trims_Selection()
{
    var data = new[] { "foo", "bar", "baz" };
    var target = new SelectionModel { RetainSelectionOnReset = true };
    target.SelectedIndex = new IndexPath(4);
    target.Source = data;
    Assert.Empty(target.SelectedIndices);
}

// test multiple item selection is trimmed properly
[Fact]
public void Assigning_Source_With_Less_Items_Than_Multiple_Selection_Trims_Selection()
{
    var data = new[] { "foo", "bar", "baz" };
    var target = new SelectionModel { RetainSelectionOnReset = true };
    target.Select(4);
    target.Select(2);
    target.Source = data;
    Assert.Equal(1, target.SelectedIndices.Count);
    Assert.Equal(new IndexPath(2), target.SelectedIndices.First());
}
```

**Comment by Deadpikle** [comment]
Another test that fails that should probably pass (changing source always clears selection, so should `RetainSelectionOnReset` be looked at before `ClearSelection` is called?):

```csharp
[Fact]
public void Testificateasdfljasldfj()
{
    var data = new[] { "foo", "bar", "baz", "boo", "hoo" };
    var smallerData = new[] { "foo", "bar", "baz" };
    var target = new SelectionModel { RetainSelectionOnReset = true };
    target.Source = data;
    target.SelectedIndex = new IndexPath(2);
    target.Source = smallerData;
    Assert.Equal(1, target.SelectedIndices.Count);
}
```
