### ISSUE TITLE
ControlCatalog throws AccessViolationException on OpenGL page

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#3968]
## Environment
- master, commit https://github.com/AvaloniaUI/Avalonia/commit/29ee78661fc430e096039ea7658a46fead581b0f
- Windows 10 19041.254 Insider Slow Ring
- Renderer: ANGLE (NVIDIA GeForce RTX 2060 SUPER Direct3D9Ex vs_3_0 ps_3_0) Version: OpenGL ES 2.0 (ANGLE 2.1.0.f2ed299569c0)

## Steps to reproduce:
1. Open ControlCatalog.NetCore
2. Navigate to OpenGL sample page
3. Change value of DISCO slider. Or change value of Yaw\Pitch\Roll slides, but when I try with Minimum (0) or Maximum (10) values everything works as expected.

## Stack Trace / Console output:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ControlCatalog.Pages.OpenGlPageControl.OnOpenGlRender(Avalonia.OpenGL.GlInterface, Int32)
   at Avalonia.OpenGL.OpenGlControlBase.Render(Avalonia.Media.DrawingContext)
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(Avalonia.Media.DrawingContext, Avalonia.Rendering.SceneGraph.Scene, Avalonia.Rendering.SceneGraph.VisualNode, Avalonia.Rect, Boolean)
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(Avalonia.Rendering.SceneGraph.Scene, Avalonia.VisualTree.IVisual)
   at Avalonia.Rendering.DeferredRenderer.UpdateScene()
   at Avalonia.Rendering.DeferredRenderer.UpdateSceneIfNeeded()
   at Avalonia.Threading.JobRunner+Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(System.Nullable`1<Avalonia.Threading.DispatcherPriority>)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG ByRef)
   at Avalonia.Win32.Win32Platform.RunLoop(System.Threading.CancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(System.String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.String[], Avalonia.Controls.ShutdownMode)
   at ControlCatalog.NetCore.Program.Main(System.String[])

C:\Work\Projects\Avalonia\samples\ControlCatalog.NetCore\bin\Debug\netcoreapp3.1\ControlCatalog.NetCore.exe (process 7304) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by kekekeks** [comment]
Seems to be triggered by rendering on every frame. What might be happening here is NVIDIA driver being unable to render to a texture and consume the same texture at the same time.

**Comment by danwalmsley** [comment]
@kekekeks I get the same thing on intel integrated gpu...

**Comment by maxkatz6** [comment]
I have also tried to run with integrated GPU:
"Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D9Ex vs_3_0 ps_3_0) Version: OpenGL ES 2.0 (ANGLE 2.1.0.f2ed299569c0)"

Same exception with same steps to reproduce.

**Comment by JamRemco** [comment]
Yup, me to

>Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Line
```C#
GL.DrawElements(GL_TRIANGLES, _indices.Length, GL_UNSIGNED_SHORT, IntPtr.Zero);
```

**Comment by SparkyTD** [comment]
Same exception on a custom OpenGL control that I made. Seems to happen when the control is being re-rendered too often/too quickly.
