### ISSUE TITLE
Preview Loaded and then Process Exited

### ISSUE THREAD

**Issue by sdb7** [AvaloniaUI/Avalonia#4068]
Hi can't reliably see xaml preview, the view shown for just a moment and then display warning process exited 

![image](https://user-images.githubusercontent.com/6058513/83476220-4fec9b00-a4ba-11ea-9e4d-03594dcfe555.png)

And i checked the output window, this is shown :

10:12:41.477 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()

already done, clean, rebuild and the problem persist, what should i do?.

**Comment by kekekeks** [comment]
Most likely a crash after XAML was loaded. Those aren't really handled by the previewer.
Try adding 
```cs
while(!Debugger.IsAttached)
   Thread.Sleep(100);
```
to you control's constructor and attaching debugger to the previewer process from another Visual Studio instance (the same workflow as with debugging issues with WPF's previewer basically)

**Comment by sdb7** [comment]
Okay, will try and look into it much further, thanks.
