### ISSUE TITLE
MIPS platform

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#4086]
Does Avalonia need to adapt to MIPS architecture?

**Comment by hez2010** [comment]
It needs [.NET Core Runtime](https://github.com/dotnet/runtime) support MIPS architecture.

**Comment by jinyuttt** [comment]
ok

**Comment by kekekeks** [comment]
Should work with Mono runtime, but you'll also have to build libSkiaSharp.so

**Comment by xiangzhai** [comment]
:mips-interest

**Comment by xiangzhai** [comment]
Hi @kekekeks 

libSkiaSharp.so is https://github.com/mono/SkiaSharp ?

Thanks,
Leslie Zhai

**Comment by jmacato** [comment]
@xiangzhai yes, we need to make Skia/SkiaSharp to compile to MIPS platform.

**Comment by xiangzhai** [comment]
Hi @jmacato 

Thanks for your response!

> you'll need to make Skia/SkiaSharp to compile to MIPS platform.

I am on it.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @jinyuttt 

It is easy to cross compile libSkiaSharp for MIPS64:

```
./bin/gn gen 'out/linux/x64' --args='
    cc="mips64el-linux-gnuabi64-gcc"
    cxx="mips64el-linux-gnuabi64-g++"
    is_official_build=true skia_enable_tools=false
    target_os="linux" target_cpu="mips64"
    skia_use_icu=false skia_use_sfntly=false skia_use_piex=true
    skia_use_system_expat=false skia_use_system_freetype2=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false
    skia_enable_gpu=true
    extra_cflags=[ "-DSKIA_C_DLL", "-w" ]
    extra_ldflags=[ "--sysroot=/chroots/mips64el_stretch" ]
    linux_soname_version="60.1.0"'


depot_tools/ninja 'SkiaSharp' -C 'out/linux/x64'
```

Then there is libSkiaSharp:

```
$ file out/linux/x64/libSkiaSharp.so.60.1.0 
out/linux/x64/libSkiaSharp.so.60.1.0: ELF 64-bit LSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, BuildID[sha1]=79cef834fd1a2da0230545626908bad3ab5f64d7, with debug_info, not stripped
```

Please read the [cross-building](https://github.com/gsvm/coreclr/blob/mips64-port/Documentation/building/cross-building.md) document about generating an mips64el rootfs.

Or just use docker image `aoqi/dotnet-buildtools:x86_64-ubuntu-16.04-c103199-20180628134544-upstream-cross-mips64el` there is `/crossrootfs/mips64el` in it by following [linux-instructions](https://github.com/gsvm/coreclr/blob/mips64-port/Documentation/building/linux-instructions.md) document.

Thanks,
Leslie Zhai

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @jmacato 

What version of libHarfBuzzSharp do you suggest?  [skia-2.80.1](https://github.com/mono/skia/tree/v2.80.1) unable to find an entry point named `hb_face_create_for_tables` in shared library `libHarfBuzzSharp`:

```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'hb_face_create_for_tables' in shared library 'libHarfBuzzSharp'.
   at HarfBuzzSharp.HarfBuzzApi.hb_face_create_for_tables(GetTableDelegateProxyDelegate reference_table_func, IntPtr user_data, ReleaseDelegateProxyDelegate destroy)
   at HarfBuzzSharp.Face..ctor(GetTableDelegate getTable, ReleaseDelegate destroy)
   at HarfBuzzSharp.Face..ctor(GetTableDelegate getTable)
   at Avalonia.Skia.GlyphTypefaceImpl..ctor(SKTypeface typeface) in /home/loongson/Avalonia/src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs:line 18
   at Avalonia.Skia.FontManagerImpl.CreateGlyphTypeface(Typeface typeface) in /home/loongson/Avalonia/src/Skia/Avalonia.Skia/FontManagerImpl.cs:line 141
   at Avalonia.Media.GlyphTypeface..ctor(Typeface typeface) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/GlyphTypeface.cs:line 9
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/Typeface.cs:line 71
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 131
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 62
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 40
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 260
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 15
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 223
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides) in /home/loongson/Avalonia/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 71
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text) in /home/loongson/Avalonia/src/Avalonia.Controls/TextBlock.cs:line 453
   at Avalonia.Controls.TextBlock.get_TextLayout() in /home/loongson/Avalonia/src/Avalonia.Controls/TextBlock.cs:line 165
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Controls/TextBlock.cs:line 499
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /home/loongson/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Controls.ComboBox.UpdateSelectionBoxItem(Object item) in /home/loongson/Avalonia/src/Avalonia.Controls/ComboBox.cs:line 376
   at Avalonia.Controls.ComboBox.SelectedItemChanged(AvaloniaPropertyChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Controls/ComboBox.cs:line 337
   at Avalonia.Controls.ComboBox.<>c.<.cctor>b__13_0(ComboBox x, AvaloniaPropertyChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Controls/ComboBox.cs:line 91
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass23_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 583
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 146
   at Avalonia.AvaloniaProperty.NotifyChanged(AvaloniaPropertyChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Base/AvaloniaProperty.cs:line 483
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /home/loongson/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 727
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /home/loongson/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 640
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 726
   at Avalonia.Controls.SelectionModel.OnSelectionChanged(SelectionModelSelectionChangedEventArgs e) in /home/loongson/Avalonia/src/Avalonia.Controls/SelectionModel.cs:line 654
   at Avalonia.Controls.SelectionModel.EndOperation() in /home/loongson/Avalonia/src/Avalonia.Controls/SelectionModel.cs:line 841
   at Avalonia.Controls.SelectionModel.Operation.Dispose() in /home/loongson/Avalonia/src/Avalonia.Controls/SelectionModel.cs:line 891
   at Avalonia.Controls.SelectionModel.set_SelectedIndex(IndexPath value) in /home/loongson/Avalonia/src/Avalonia.Controls/SelectionModel.cs:line 196
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedIndex(Int32 value) in /home/loongson/Avalonia/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 166
   at Avalonia.Controls.Primitives.SelectingItemsControl.UpdateFinished() in /home/loongson/Avalonia/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 865
   at Avalonia.Controls.Primitives.SelectingItemsControl.InternalEndInit() in /home/loongson/Avalonia/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 892
   at Avalonia.Controls.Primitives.SelectingItemsControl.EndInit() in /home/loongson/Avalonia/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 334
   at ControlCatalog.Pages.ComboBoxPage.!XamlIlPopulate(IServiceProvider , ComboBoxPage ) in /home/loongson/Avalonia/samples/ControlCatalog/Pages/ComboBoxPage.xaml:line 27
   at ControlCatalog.Pages.ComboBoxPage.!XamlIlPopulateTrampoline(ComboBoxPage )
   at ControlCatalog.Pages.ComboBoxPage.InitializeComponent() in /home/loongson/Avalonia/samples/ControlCatalog/Pages/ComboBoxPage.xaml.cs:line 17
   at ControlCatalog.Pages.ComboBoxPage..ctor() in /home/loongson/Avalonia/samples/ControlCatalog/Pages/ComboBoxPage.xaml.cs:line 12
   at ControlCatalog.MainView.!XamlIlPopulate(IServiceProvider , MainView ) in /home/loongson/Avalonia/samples/ControlCatalog/MainView.xaml:line 23
   at ControlCatalog.MainView.!XamlIlPopulateTrampoline(MainView )
   at ControlCatalog.MainView..ctor() in /home/loongson/Avalonia/samples/ControlCatalog/MainView.xaml.cs:line 18
   at ControlCatalog.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in /home/loongson/Avalonia/samples/ControlCatalog/MainWindow.xaml:line 80
   at ControlCatalog.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at ControlCatalog.MainWindow.InitializeComponent() in /home/loongson/Avalonia/samples/ControlCatalog/MainWindow.xaml.cs:line 78
   at ControlCatalog.MainWindow..ctor() in /home/loongson/Avalonia/samples/ControlCatalog/MainWindow.xaml.cs:line 19
   at ControlCatalog.App.OnFrameworkInitializationCompleted() in /home/loongson/Avalonia/samples/ControlCatalog/App.xaml.cs:line 78
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /home/loongson/Avalonia/src/Avalonia.Controls/AppBuilderBase.cs:line 295
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /home/loongson/Avalonia/src/Avalonia.Controls/AppBuilderBase.cs:line 162
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /home/loongson/Avalonia/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at ControlCatalog.NetCore.Program.Main(String[] args) in /home/loongson/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 102
```

Thanks,
Leslie Zhai

**Comment by kekekeks** [comment]
You need harfbuzz 2.6.1. Build script is here https://github.com/mono/SkiaSharp/blob/be889396a5b8455cf52f0c00859c31c4bd5dac77/native/linux/build.cake#L94

**Comment by mattleibow** [comment]
I also have docker containers for cross compiling. Right now it is just for arm, but you might just be able to pass in the mips values to the docker build

**Comment by xiangzhai** [comment]
Hi @mattleibow 

> Does clang support cross compiling to mips?

Yes! [CoreCLR MIPS64 porting](https://github.com/dotnet/runtime/issues/38069) is using clang  https://github.com/gsvm/coreclr/blob/mips64-port/Documentation/building/linux-instructions.md#docker-images

@kekekeks 

> You need harfbuzz 2.6.1. Build script is here https://github.com/mono/SkiaSharp/blob/be889396a5b8455cf52f0c00859c31c4bd5dac77/native/linux/build.cake#L94

Thanks for your advice!  `visibility_hidden=false` is the root cause.

Cheers,
Leslie Zhai

**Comment by jmacato** [comment]
@xiangzhai kind of a offtopic question: does your port of MIPS will support SGI Octane (it's MIPS IV iirc) or only the latest MIPS32/64 ones?

**Comment by xiangzhai** [comment]
Hi @jmacato 

> does your CoreCLR port of MIPS will support SGI Octane?

Nope!

But we [open source MIPS64 (mips64r2) porting](https://github.com/gsvm/coreclr).  It is easy to port to MIPS O32/N32 ABI.

Thanks,
Leslie Zhai

**Comment by jmacato** [comment]
Haha thanks! was just really curious!

**Comment by kekekeks** [comment]
Closing due to inactivity
