### ISSUE TITLE
Treeview item selection causes exception (devtools problem?)

### ISSUE THREAD

**Issue by openmandev** [AvaloniaUI/Avalonia#4156]
Any click on the tree leads to an error (the error appeared last week on the master branch):
```
Unhandled exception. System.ArgumentException: Interval must be positive (Parameter 'interval')
   at Avalonia.X11.X11PlatformThreading.StartTimer(DispatcherPriority priority, TimeSpan interval, Action tick)
   at Avalonia.Threading.DispatcherTimer.Start()
   at Avalonia.Threading.DispatcherTimer.RunOnce(Action action, TimeSpan interval, DispatcherPriority priority)
   at Avalonia.Controls.TreeView.OnSelectionModelPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Avalonia.Controls.SelectionModel.RaisePropertyChanged(String propertyName)
   at Avalonia.Controls.SelectionModel.EndOperation()
   at Avalonia.Controls.SelectionModel.Operation.Dispose()
   at Avalonia.Controls.SelectionModel.set_SelectedIndex(IndexPath value)
   at Avalonia.Controls.TreeView.UpdateSelectionFromContainer(IControl container, Boolean select, Boolean rangeModifier, Boolean toggleModifier, Boolean rightButton)
   at Avalonia.Controls.TreeView.UpdateSelectionFromEventSource(IInteractive eventSource, Boolean select, Boolean rangeModifier, Boolean toggleModifier, Boolean rightButton)
   at Avalonia.Controls.TreeView.OnPointerPressed(PointerPressedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_8(InputElement x, PointerPressedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.X11.X11Window.<ScheduleInput>b__101_0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
```

**Comment by maxkatz6** [comment]
In TreeView timer is called with TimeSpan.Zero interval:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TreeView.cs#L350
When it is forbidden by X11 backend:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11PlatformThreading.cs#L267

Shouldn't we use Task.Yield instead of DispatcherTimer.RunOnce(..., TimeSpan.Zero) ?

**Comment by openmandev** [comment]
The problem has gone in latest nightlies.
