### ISSUE TITLE
macos crash on tooltip closing

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4161]
On 0.9.999-cibuild0008603-beta my app crashes on High Sierra 10.13.6 when the mouse is moved once a tooltip is shown (i.e. when the tool tip closes) with
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Avalonia.Native.ScreenImpl.get_AllScreens()
at Avalonia.Native.WindowBaseImpl.get_MaxAutoSizeHint()
at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size availableSize)
at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
at Avalonia.Layout.Layoutable.Measure(Size availableSize)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Boolean priorityContainsMeaningfulValue)
at Avalonia.Native.Interop.IAvnSignaledCallbackShadow.IAvnSignaledCallbackVtbl.Signaled(IntPtr thisObject, Int32 param0, Byte param1)
--- End of stack trace from previous location where exception was thrown ---
at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetimeT
at SparkSDR.Program.Main(String[] args)
```

**Comment by kekekeks** [comment]
@grokys

**Comment by grokys** [comment]
Seems to be an NRE in `Avalonia.Native` so passing it onto @danwalmsley

**Comment by ahopper** [comment]
I'm still getting the same crash on macos with 0.9.999-cibuild0008678-beta.  It is and was fine on windows, not tried on linux for a while.

**Comment by grokys** [comment]
@ahopper with the same stacktrace?

**Comment by ahopper** [comment]
just checked

Hermes Lite 2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.ScreenImpl.get_AllScreens()
   at Avalonia.Native.WindowBaseImpl.get_MaxAutoSizeHint()
   at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Boolean priorityContainsMeaningfulValue)
   at Avalonia.Native.Interop.IAvnSignaledCallbackShadow.IAvnSignaledCallbackVtbl.Signaled(IntPtr thisObject, Int32 param0, Byte param1)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SparkSDR.Program.Main(String[] args)

**Comment by grokys** [comment]
Strange. We should not be running a layout on a closed popup anymore, which I assumed would fix it. @danwalmsley could you take a look?

**Comment by ahopper** [comment]
I just triple checked and built with 0.9.999-cibuild0008722-beta and got the same error. It is 100% repeatable.

**Comment by ahopper** [comment]
Just tried 0.9.999-cibuild0008870-beta on a fresh mvvm template project and `<Button ToolTip.Tip="crash me" Content="hoho"/>`  is all that is needed to trigger a crash.
