### ISSUE TITLE
TextBlock exception

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4269]
Using 0.9.999-cibuild0009164-beta I'm getting this exception, it happens after a few minutes of many textBlocks being updated. I'm afraid I don't know the text that causes it. 

Index was outside the bounds of the array.
Avalonia.Visuals
T get_Item(Int32)
   at Avalonia.Utilities.ReadOnlySlice`1.get_Item(Int32 index)
   at Avalonia.Media.TextFormatting.Unicode.Codepoint.ReadAt(ReadOnlySlice`1 text, Int32 index, Int32& count)
   at Avalonia.Skia.TextShaperImpl.FillBuffer(Buffer buffer, ReadOnlySlice`1 text)
   at Avalonia.Skia.TextShaperImpl.ShapeText(ReadOnlySlice`1 text, Typeface typeface, Double fontRenderingEmSize, CultureInfo culture)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides)
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text)
   at Avalonia.Controls.TextBlock.get_TextLayout()
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)

**Comment by Gillibald** [comment]
Will make some tests but it is hard to tell why it can't read the string. The indexer of the underlying Memory<T> is throwing.

**Comment by ahopper** [comment]
It has happened since 0.9.999-cibuild0008839-beta as that has been run 24/7 by many people for the last week. Not much has changed, I am using compiled bindings.

**Comment by Gillibald** [comment]
Could you give me an example how you bind the text and how the text could look like

**Comment by ahopper** [comment]
![image](https://user-images.githubusercontent.com/1388864/87242591-0f236280-c426-11ea-886a-a1df1426892a.png)

I guess it is the text in the table bottom left, I've just noticed one line wraps which it did not before, maybe because of theme changes.

the code for the table -
```
<ListBox MinHeight="165" MaxHeight="320" Grid.Row="1" 
                        Items="{CompiledBinding allSpots}" VirtualizationMode="Simple" 
                        Name="lb"  HorizontalAlignment="Stretch" BorderBrush="LightGray" >
                <ListBox.Styles>
                  <Style Selector="ListBoxItem">
                    <Setter Property="Padding" Value="0,0,0,0" />
                  </Style>
                  </ListBox.Styles>
                  <ListBox.ItemsPanel>
                      <ItemsPanelTemplate>
                          <VirtualizingStackPanel />
                      </ItemsPanelTemplate>
                  </ListBox.ItemsPanel>
                  <ListBox.ItemTemplate>
                      <DataTemplate>
                          <StackPanel Orientation="Horizontal">
                              <TextBlock Width="150" Text="{CompiledBinding time}"/>
                              <TextBlock Width="50" Text="{CompiledBinding frequency}"/>
                              <TextBlock Width="30" Text="{CompiledBinding snr}"/>
                              <TextBlock Width="30" Text="{CompiledBinding dt}"/>
                              <TextBlock Width="50" Text="{CompiledBinding mode}"/>
                              <TextBlock Width="60" Text="{CompiledBinding distance, StringFormat=\{0:0\}}" />
                           
                              <Button Width="150" Classes="LinkButton" 
                                      Command="{Binding $parent[ListBox].DataContext.SpotSelectedCommand}"
                                      CommandParameter="{Binding}" 
                                      Margin="0" Padding="0" >
                                  <TextBlock Text="{Binding msg}" 
                                              Margin="0" Padding="0"
                                              Foreground="{CompiledBinding color, Converter={x:Static r:Converters.SpotToColor}}"/>
                              </Button>
                          </StackPanel>
                      </DataTemplate>
                  </ListBox.ItemTemplate>
              </ListBox>
```

**Comment by Gillibald** [comment]
That line wrapping is a bug and should be fixed by #4260 
Will finish that shortly.

**Comment by ahopper** [comment]
I've tweaked the layout and set NoWrap and have left it running, have to wait for someone to transmit what ever makes it fail.

**Comment by Gillibald** [comment]
I will change the default to NoWrap again. It seems that should be the default.

**Comment by ahopper** [comment]
No exception after 100,000 decoded messages, do you believe the exception is related to the wrap bug?

**Comment by Gillibald** [comment]
Y it could be

**Comment by Gillibald** [comment]
`0.9.999-cibuild0009225-beta` can be tested now. It reverts to default to `NoWrap` so you don't need to specify it explictitly

**Comment by ahopper** [comment]
No exceptions using 0.9.999-cibuild0009225-beta on a long test

**Comment by ShadowDancer** [comment]
I can repro it, sadly I cannot make repro from ground up (just in my app, which I cannot publish). Code fails in class
`Avalonia.Media.TextFormatting.Unicode.Codepoint.ReadAt`.

```
            if (index > text.End)
            {
                return ReplacementCodepoint;
            }
```
However index is relative to `text.Start`. In my case `text.End=161` and `text.Length=61` and `index=61`. 
The next line then causes exception:
`var code = text[index];`.

**Comment by Gillibald** [comment]
Y good catch. This should still not happen. Will fix that line asap. Does it crash with the preview and with the build mentioned above?

**Comment by Gillibald** [comment]
Please try out build 9322

**Comment by Gillibald** [comment]
Build 9328 has this corrected

**Comment by Gillibald** [comment]
Build 9341 should fix your findings

**Comment by ShadowDancer** [comment]
I am unable to verify this because i have dependencies on non-ci builds. I'll check it again on preview 2

**Comment by Gillibald** [comment]
#4260

**Comment by ahopper** [comment]
My issue is fixed so I'll close, hopefully it works for @ShadowDancer
