### ISSUE TITLE
Precompiled XAML error on Pop! OS 20.04

### ISSUE THREAD

**Issue by flabbet** [AvaloniaUI/Avalonia#4280]
Running `dotnet run` on application with Avalonia 0.9.11 returns XAML no precompiled error on Pop! Os 20.04. Running it on Windows works normally, on Visual Studio and `dotnet run`. I managed to fix this by renaming .axaml files to .xaml. Is this an intended behavior?

Target framework is .NET Core 3.1

**Comment by kekekeks** [comment]
Please, show your csproj file

**Comment by flabbet** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-x86;osx-x64;linux-x64</RuntimeIdentifiers>
    <ApplicationIcon>swaglyrics_pfp.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Fonts\Roboto-Regular.ttf" />
    <None Remove="Bridge\SwagLyrics_api_bridge.py" />
    <None Remove="Bridge\swaglyrics_installer.py" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Bridge\swaglyrics_api_bridge.py">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Bridge\swaglyrics_installer.py">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.11" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.11" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.9.11" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="app.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by kekekeks** [comment]
Please, check if adding 
```xml
<AvaloniaResource Include="**\*.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
```
fixes the issue.

**Comment by flabbet** [comment]
Nope, still
```
Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for SwagLyricsGUI.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at SwagLyricsGUI.App.Initialize() in /home/flabbet/Git/SwagLyricsGUI/SwagLyricsGUI/App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SwagLyricsGUI.Program.Main(String[] args) in /home/flabbet/Git/SwagLyricsGUI/SwagLyricsGUI/Program.cs:line 14
```

**Comment by ahopper** [comment]
I get this for both project types created in 0.9.11 on vs using the extension.

**Comment by kekekeks** [comment]
Could you send your `obj/Debug/netcoreapp3.1/Avalonia/resources` file?

**Comment by ahopper** [comment]
not sure if you meant me
[resources.zip](https://github.com/AvaloniaUI/Avalonia/files/4927653/resources.zip)
 but this is mine from a fresh mvvm project

**Comment by kekekeks** [comment]
@ahopper your resource index is
```xml
<AvaloniaResourcesIndex xmlns="http://schemas.datacontract.org/2004/07/Avalonia.Utilities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Entries>
    <AvaloniaResourcesIndexEntry>
      <Offset>0</Offset>
      <Path>/Assets/avalonia-logo.ico</Path>
      <Size>176111</Size>
    </AvaloniaResourcesIndexEntry>
    <AvaloniaResourcesIndexEntry>
      <Offset>176111</Offset>
      <Path>/!AvaloniaResourceXamlInfo</Path>
      <Size>282</Size>
    </AvaloniaResourcesIndexEntry>
  </Entries>
</AvaloniaResourcesIndex>
```

`axaml` files weren't included to resources by `GenerateAvaloniaResources` target.

Which means either nuget package version mismatch somewhere or me not understanding how MSBuild works.

Please, check that all package references are pointing to 0.9.11. If that doesn't help,  and try disabling node reuse. If that doesn't help either, please, collect an [MSBuildStructuredLog](https://github.com/KirillOsenkov/MSBuildStructuredLog)-compatible logs from MSBuild.

**Comment by ahopper** [comment]
The references in the .csproj are all the same. These were just untouched fresh projects created from vs as a number of people were mentioning issues on gitter. If I update to 0.10.preview 1 it works. I'll try the other stuff later.

**Comment by ahopper** [comment]
Here is the log for a MVVM project
[msbuild.zip](https://github.com/AvaloniaUI/Avalonia/files/4930973/msbuild.zip)
