### ISSUE TITLE
OpenFileDialog crashes program

### ISSUE THREAD

**Issue by localcc** [AvaloniaUI/Avalonia#4311]
When canceling on OpenFileDialog on linux the application crashes.
Steps to reproduce:
 1. Open OpenFileDialog
 2. Press Cancel

expected behavior: the application does not crash
behavior: the application crashes

<details>
     <summary>Exception</summary>
     Unhandled exception. ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at FrameTimeHandler.ViewModels.MainWindowViewModel.<.ctor>b__94_0()
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in d:\a\1\s\src\ReactiveUI\RxApp.cs:line 103
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 254
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler s, Action a) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex) in d:\a\1\s\src\ReactiveUI\RxApp.cs:line 108
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 44
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 577
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 509
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ScheduledObserver.cs:line 497
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at FrameTimeHandler.Program.Main(String[] args)
</details>

**Comment by localcc** [comment]
DotNet Core 3.1.301 
OS: Ubuntu 19.04 64bit
Build configurations tried: both release and debug
Source code link: https://github.com/FlexxxerAlex/frametime-handler

**Comment by FlexxxerAlex** [comment]
Have the same problem

**Comment by kekekeks** [comment]
It seems that you aren't handing a `null` returned from `fileDialog.ShowAsync`. 

We need to make it more consistent across platforms though

**Comment by localcc** [comment]
The null check is there, and app works fine on windows 2004 and mac os 10.15.5.

**Comment by kekekeks** [comment]
>The null check is there

No, it is not: https://github.com/FlexxxerAlex/frametime-handler/blob/master/FrameTimeHandler/ViewModels/MainWindowViewModel.cs#L285-L287
