### ISSUE TITLE
Can't start an Avalonia App on MacOSX High Sierra

### ISSUE THREAD

**Issue by Nemirtingas** [AvaloniaUI/Avalonia#4386]
Hi, 
I was trying to build a portable GUI app on Windows and started it with no problems on Linux but MacOS doesn't even start.
I've downloaded the runtime on official Microsoft .Net Core page.
Is there any extra steps to setup Avalonia on MacOS ? I'm running it in a Virtual Box VM on my Windows PC.
Many games that use 2D/3D works, so I was expecting it would start.

There's no specific stuff in the project, just a new Avalonia MVVM project.

[AvaloniaAwaitCrash.zip](https://github.com/AvaloniaUI/Avalonia/files/4984079/AvaloniaAwaitCrash.zip)

```
MacBook-Pro-de-test_user:netcoreapp3.1 test_user$ dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
MacBook-Pro-de-test_user:netcoreapp3.1 test_user$ dotnet AvaloniaAwaitCrash.dll
Unhandled exception. SharpGen.Runtime.SharpGenException: HRESULT: [0x80004005], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown
   at SharpGen.Runtime.Result.CheckError()
   at Avalonia.Native.Interop.IAvnGlDisplay.CreateContext(IAvnGlContext share)
   at Avalonia.Native.GlPlatformFeature..ctor(IAvnGlDisplay display)
   at Avalonia.Native.AvaloniaNativePlatform.DoInitialize(AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(IntPtr factory, AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaAwaitCrash.Program.Main(String[] args) in D:\Visual\AvaloniaAwaitCrash\AvaloniaAwaitCrash\Program.cs:line 14
Abort trap: 6
```

**Comment by danwalmsley** [comment]
you will need to turn off GPU rendering to run in a VM, we only support running on actual hardware on OSX.

`.With(new AvaloniaNativePlatformOptions { UseDeferredRendering = true, UseGpu = false })`

try this in your appbuilder.

**Comment by Nemirtingas** [comment]
Thx, it works. I'll be able to debug the app on MacOS until I ship it to someone who has a real Mac.

I've modified the appbuilder with a check on MacOS 
```
        public static AppBuilder BuildAvaloniaApp()
        {
            AppBuilder ab = AppBuilder.Configure<App>();
            ab.UsePlatformDetect();
#if DEBUG
            if (OSDetector.IsMacOS())
            {
                ab.With(new AvaloniaNativePlatformOptions { UseDeferredRendering = true, UseGpu = false });
            }
#endif
            ab.LogToDebug();

            return ab;
        }
```
