### ISSUE TITLE
Avalonia.Markup.Xaml.XamlLoadException

### ISSUE THREAD

**Issue by squidgyberries** [AvaloniaUI/Avalonia#4426]
I don't know if this is the right place to ask, but I get the error `Avalonia.Markup.Xaml.XamlLoadException: 'No precompiled XAML found for AvaloniaTest.App, make sure to specify x:Class and include your XAML file as AvaloniaResource'` when I try to run any Avalonia application. This is code generated when I used the Visual Studio extension to create a project. Doesn't work for regular Avalonia applications or MVVM ones.

**Comment by rstm-sf** [comment]
Hello, this one can help you https://github.com/AvaloniaUI/Avalonia/issues/4373

**Comment by grokys** [comment]
@Pxlop @mate1213 I'd be interested to know whether doing a build from the command line using `dotnet build` fixes this problem?

**Comment by mate1213** [comment]
@grokys I tried it. The buid was without error.
![image](https://user-images.githubusercontent.com/36986834/89760846-7992f580-daed-11ea-89fa-e05471ed1ee6.png)

But this is the same result when I'm running the build from VS19.
![image](https://user-images.githubusercontent.com/36986834/89761373-82d09200-daee-11ea-82c5-efbea14fccb3.png)

Only at the Avalonia Diagnostic segment showing some wierdness:
```
09:44:18.049 [Information]  Avalonia Package initialized
09:46:07.777 [Information] 0 Starting previewer process for '"C:\Users\VirtualUser\source\repos\test\test2\bin\Debug\netcoreapp2.0\test2.dll"'
09:46:07.800 [Information] 9612 Started previewer process for '"C:\Users\VirtualUser\source\repos\test\test2\bin\Debug\netcoreapp2.0\test2.dll"'. Waiting for connection to be initialized.
09:46:08.723 [Information] 9612 Connection initialized
09:46:12.985 [Error] 9612 <= "Unhandled Exception: Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for test2.App, make sure to specify x:Class and include your XAML file as AvaloniaResource"
09:46:13.026 [Error] 9612 <= "   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 26"
09:46:13.227 [Error] 9612 <= "   at test2.App.Initialize() in C:\Users\VirtualUser\source\repos\test\test2\App.axaml.cs:line 13"
09:46:13.862 [Error] 9612 <= "   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 294"
09:46:13.873 [Error] 9612 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.GetConfiguredApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in D:\a\1\s\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 120"
09:46:13.904 [Error] 9612 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in D:\a\1\s\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 145"
09:46:13.921 [Error] 9612 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
09:46:19.850 [Information]  Process exited
09:46:19.850 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()
09:46:21.088 [Information]  Stopping previewer process
09:46:21.529 [Information]  Stopping previewer process
09:46:24.236 [Information]  Starting previewer process for '"C:\Users\VirtualUser\source\repos\test\test2\bin\Debug\netcoreapp2.0\test2.dll"'
09:46:24.257 [Information] 13364 Started previewer process for '"C:\Users\VirtualUser\source\repos\test\test2\bin\Debug\netcoreapp2.0\test2.dll"'. Waiting for connection to be initialized.
09:46:24.817 [Information] 13364 Connection initialized
09:46:27.209 [Error] 13364 <= "Unhandled Exception: Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for test2.App, make sure to specify x:Class and include your XAML file as AvaloniaResource"
09:46:27.221 [Error] 13364 <= "   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 26"
09:46:27.242 [Error] 13364 <= "   at test2.App.Initialize() in C:\Users\VirtualUser\source\repos\test\test2\App.axaml.cs:line 13"
09:46:27.245 [Error] 13364 <= "   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 294"
09:46:27.248 [Error] 13364 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.GetConfiguredApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in D:\a\1\s\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 120"
09:46:27.251 [Error] 13364 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in D:\a\1\s\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 145"
09:46:27.254 [Error] 13364 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
09:46:31.672 [Information]  Process exited
09:46:31.676 [Information]  Stopping previewer process
09:46:31.672 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()
```

But I didn't tried yet the solution in the issue #4379 
So 'til now thats seems to realy promesing. When I will have some resul about that, will let you know.
Thanks for Help!

**Comment by mate1213** [comment]
@grokys I forget to mention before, after I build from console I build it from VS too and the pictures came from that build sequence.

**Comment by maxkatz6** [comment]
Not an issue with "axaml" files.
