### ISSUE TITLE
Interop issue (shcore.dll)

### ISSUE THREAD

**Issue by caunt** [AvaloniaUI/Avalonia#4485]
```
System.EntryPointNotFoundException: Unable to find an entry point named 'GetDpiForMonitor' in DLL 'shcore.dll'.
   at Avalonia.Win32.Interop.UnmanagedMethods.GetDpiForMonitor(IntPtr hmonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at Avalonia.Win32.WindowImpl.CreateWindow()
   at Avalonia.Win32.WindowImpl..ctor()
   at Avalonia.Win32.Win32Platform.CreateWindow()
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow()
   at Avalonia.Controls.Window..ctor()
```

Avalonia - 0.10.0-preview2
OS: Windows 8 (https://imgur.com/OhGFMyQ)

**Comment by rstm-sf** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/1801#issuecomment-438151403

**Comment by caunt** [comment]
#1912 
Closing as duplicate.
