### ISSUE TITLE
0.10 preview3 fails on mac at start up

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4511]
A fresh program straight from the template fails to start on mac with this exception -
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.LocalInterop.CalliThisCallint(Void* thisObject, Void* param0, Void* methodPtr)
   at Avalonia.Native.Interop.IAvaloniaNativeFactory.Initialize(IAvnGCHandleDeallocatorCallback deallocator)
   at Avalonia.Native.AvaloniaNativePlatform.DoInitialize(AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(IntPtr factory, AvaloniaNativePlatformOptions options)
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at TestApp.Program.Main(String[] args) in /Users/alan/Documents/TestApp/Program.cs:line 14
```

**Comment by danwalmsley** [comment]
@ahopper which version?

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/4512 fixed.

**Comment by jkoritzinsky** [comment]
Let's keep this open until the PR is merged.
