### ISSUE TITLE
Opening the context menu in the TextBox exits the application

### ISSUE THREAD

**Issue by MagnificentEagle** [AvaloniaUI/Avalonia#4562]
Hello!
I just don't have to test your new context menu for the TextBox. I got an exception:
```
System.InvalidOperationException: Attempted to open a popup not attached to a TopLevel
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1 e)
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__21_1(Popup x, AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 146
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean value)
   at Avalonia.Controls.ContextMenu.Open(Control control)
   at Avalonia.Controls.ContextMenu.ControlPointerReleased(Object sender, PointerReleasedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow)
   at OlibKey.Program.AppMain(Application app, String[] args) in E:\OlibKey\Program.cs:line 72
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args)
   at OlibKey.Program.Main(String[] args) in E:\OlibKey\Program.cs:line 43
```
But the situation is that I have not yet figured out how to reproduce it and whether my application is to blame. When the window with the TextBox opens, everything is fine. As soon as I reload this window with the same TextBox, the application exits with an error.

Avalonia version: 0.10.999-cibuild0010242-beta

**Comment by danwalmsley** [comment]
fixed.
