### ISSUE TITLE
[ Suggestion ] Any mistakes in a binding path shouldn't lead to runtime exception

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4600]
I think it's unsafe to throw this kind of exception here.

For example binding below with an obvious typo causes `Avalonia.Data.Core.ExpressionParseException`: 'Expected end of expression.'

```xml
Command="{Binding $parent[ItemsRepeater]DataContext.DoSomething}"
```

That was totally unexpected to me. 
If this is "by design" it would be nice to see a clear message with details. Current one is not obvious at all. I had to comment parts of view and check them carefully one by one to localize this simple typo.

**Comment by kekekeks** [comment]
The binding is clearly invalid, so we take the fail fast approach. XAML line information should be available in the stack trace

**Comment by FoggyFinder** [comment]
> The binding is clearly invalid, so we take the fail fast approach. XAML line information should be available in the stack trace

Yeah, it's available but it would be much better if message itself contained helpful information 

```
  at Avalonia.Markup.Parsers.ExpressionObserverBuilder.Parse(String expression, Boolean enableValidation, Func`3 typeResolver, INameScope nameScope)
   at Avalonia.Data.Binding.CreateExpressionObserver(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation)
   at Avalonia.Data.BindingBase.Initiate(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at AvaloniaApplication3Templated.MainWindow.XamlClosure_1.Build(IServiceProvider ) in AvaloniaApplication3Templated.MainWindow.xaml:line 32
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.<>c__DisplayClass0_0.<DeferredTransformationFactoryV1>b__0(IServiceProvider sp)
   at Avalonia.Markup.Xaml.Templates.TemplateContent.Load(Object templateContent)
   at Avalonia.Markup.Xaml.Templates.DataTemplate.Build(Object data, IControl existing)
   at Avalonia.Markup.Xaml.Templates.DataTemplate.Build(Object data)
   at Avalonia.Controls.ItemTemplateWrapper.GetElement(IControl parent, Object data)
   at Avalonia.Controls.ItemTemplateWrapper.GetElement(ElementFactoryGetArgs args)
   at Avalonia.Controls.ViewManager.<GetElementFromElementFactory>g__GetElement|28_1(<>c__DisplayClass28_0& )
   at Avalonia.Controls.ViewManager.GetElementFromElementFactory(Int32 index)
   at Avalonia.Controls.ViewManager.GetElement(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle)
   at Avalonia.Controls.ItemsRepeater.GetElementImpl(Int32 index, Boolean forceCreate, Boolean supressAutoRecycle)
   at Avalonia.Controls.RepeaterLayoutContext.GetOrCreateElementAtCore(Int32 index, ElementRealizationOptions options)
   at Avalonia.Layout.VirtualizingLayoutContext.GetOrCreateElementAt(Int32 index, ElementRealizationOptions options)
   at Avalonia.Layout.StackLayout.GetAverageElementSize(Size availableSize, VirtualizingLayoutContext context, StackLayoutState stackLayoutState)
   at Avalonia.Layout.StackLayout.GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context)
   at Avalonia.Layout.StackLayout.Avalonia.Layout.IFlowLayoutAlgorithmDelegates.Algorithm_GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context)
   at Avalonia.Layout.FlowLayoutAlgorithm.GetAnchorIndex(Size availableSize, Boolean isWrapping, Double minItemSpacing, String layoutId)
   at Avalonia.Layout.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, Int32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId)
   at Avalonia.Layout.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize)
   at Avalonia.Layout.AttachedLayout.Measure(LayoutContext context, Size availableSize)
   at Avalonia.Controls.ItemsRepeater.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.Window.ShowCore(Window parent)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaApplication3Templated.Program.Main(String[] args) in 
```

**Comment by kekekeks** [comment]
Try switching to `AvaloniaResource`, that will allow the debugger to highlight the corresponding line when exception is thrown

**Comment by FoggyFinder** [comment]
Thank you. Impressive. I had issues with AvaloniaResource in my F# projects - now I don't remember what it was exactly but I'm stick to EmbeddedResource since then.

I'll try to switch to them everywhere again.
