### ISSUE TITLE
TypeInitializationException on ControlCatalog.Desktop

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#4652]
When try tu run Control Catalog.Desktop from last source code trows following exception:

```
System.TypeInitializationException
  HResult=0x80131534
  Message= the type initializer for 'Avalonia.Skia.PlatformRenderInterface'  threw an exception.
  Source=Avalonia.Skia
  StackTrace:
   at Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\PlatformRenderInterface.cs:line 36
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\SkiaPlatform.cs:line 21
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in C:\GitHub\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 304
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in C:\GitHub\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 179
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in C:\GitHub\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 143
   at ControlCatalog.Program.Main(String[] args) in C:\GitHub\Avalonia\samples\ControlCatalog.Desktop\Program.cs:line 17

Inner Exception 1:
BadImageFormatException: attempt was made to load a program with an incorrect format(Exception  HRESULT: 0x8007000B)

   at SkiaSharp.SkiaApi.sk_font_new()
   at SkiaSharp.SKFont..ctor()
   at Avalonia.Skia.PlatformRenderInterface..cctor() in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\PlatformRenderInterface.cs:line 160

```

OS: **Windows 10 2004 (19041.508)**
Video Card: **Intel HD 4400 driver 20.19.15.4835**
Build Env: **Microsoft Visual Studio 2019 Version 16.7.2+30413.136**

**Comment by maxkatz6** [comment]
It seems .Net Framework sample is broken now. 
.Net Core one is fine though.

**Comment by jensbrak** [comment]
Ok, so I wasn't alone on this one. Since it was my first ever attempt I assumed it was me or my setup but maybe not then...

**Comment by workgroupengineering** [comment]
the problem occurs when the platform is set to any. If you set it to x86 or x64 it works fine.
If you want you can close the issue.
