### ISSUE TITLE
ControlCatalog.Netcore OpenGL exception

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#4653]
When run ControlCatalog.Netcore from last  source code and use OpenGL sample , throws followings exceptions:

C:\GitHub\Avalonia\samples\ControlCatalog\Pages\OpenGlPage.xaml.cs line 333
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

C:\GitHub\Avalonia\samples\ControlCatalog\Pages\OpenGlPage.xaml.cs line 365
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

```
Avalonia.OpenGL.OpenGlException
  HResult=0x80131500
  Message=eglMakeCurrent failed with error EGL_CONTEXT_LOST (0x300E)
  Source=Avalonia.OpenGL
  StackTrace:
   at Avalonia.OpenGL.EglContext.MakeCurrent() in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglContext.cs:line 71
   at Avalonia.OpenGL.OpenGlControlBase.DoCleanup(Boolean callUserDeinit) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\OpenGlControlBase.cs:line 47
   at Avalonia.OpenGL.OpenGlControlBase.OnDetachedFromVisualTree(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\OpenGlControlBase.cs:line 75
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 437
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Visual.cs:line 451
   at Avalonia.Layout.Layoutable.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 774
   at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Input\InputElement.cs:line 410
   at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in C:\GitHub\Avalonia\src\Avalonia.Controls\Control.cs:line 150
   at Avalonia.Controls.TopLevel.HandleClosed() in C:\GitHub\Avalonia\src\Avalonia.Controls\TopLevel.cs:line 350
   at Avalonia.Controls.WindowBase.HandleClosed() in C:\GitHub\Avalonia\src\Avalonia.Controls\WindowBase.cs:line 210
   at Avalonia.Controls.Window.HandleClosed() in C:\GitHub\Avalonia\src\Avalonia.Controls\Window.cs:line 895
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.AppWndProc.cs:line 77
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.WndProc.cs:line 30
```

```
[Visual] Exception in render loop: 'Avalonia.OpenGL.OpenGlException: eglMakeCurrent failed with error EGL_CONTEXT_LOST (0x300E)
   at Avalonia.OpenGL.EglContext.MakeCurrent(EglSurface surface) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglContext.cs:line 81
   at Avalonia.OpenGL.EglPlatformSurfaceRenderTargetBase.BeginDraw(EglSurface surface, IEglWindowGlPlatformSurfaceInfo info, Action onFinish, Boolean isYFlipped) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglGlPlatformSurfaceBase.cs:line 45
   at Avalonia.OpenGL.EglGlPlatformSurface.RenderTarget.BeginDraw() in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglGlPlatformSurface.cs:line 47
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession() in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlRenderTarget.cs:line 58
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\SkiaGpuRenderTarget.cs:line 25
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 547
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 310
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 266
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 220
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 147' (RenderLoop #51288387)
Exception thrown: 'Avalonia.OpenGL.OpenGlException' in Avalonia.OpenGL.dll
Exception thrown: 'Avalonia.OpenGL.OpenGlException' in Avalonia.OpenGL.dll
[Visual] Exception in render loop: 'Avalonia.OpenGL.OpenGlException: eglMakeCurrent failed with error EGL_CONTEXT_LOST (0x300E)
   at Avalonia.OpenGL.EglContext.MakeCurrent(EglSurface surface) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglContext.cs:line 81
   at Avalonia.OpenGL.EglPlatformSurfaceRenderTargetBase.BeginDraw(EglSurface surface, IEglWindowGlPlatformSurfaceInfo info, Action onFinish, Boolean isYFlipped) in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglGlPlatformSurfaceBase.cs:line 45
   at Avalonia.OpenGL.EglGlPlatformSurface.RenderTarget.BeginDraw() in C:\GitHub\Avalonia\src\Avalonia.OpenGL\EglGlPlatformSurface.cs:line 47
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession() in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlRenderTarget.cs:line 58
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\SkiaGpuRenderTarget.cs:line 25
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 547
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 310
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 266
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 220
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in C:\GitHub\Avalonia\src\Avalonia.Visuals\Rendering\RenderLoop.cs:line 147' (RenderLoop #51288387)
Exception thrown: 'Avalonia.OpenGL.OpenGlException' in Avalonia.OpenGL.dll
Exception thrown: 'Avalonia.OpenGL.OpenGlException' in Avalonia.OpenGL.dll
```

OS: **Windows 10 2004 (19041.508)**
Video Card: **Intel HD 4400 driver 20.19.15.4835**
Build Env: **Microsoft Visual Studio 2019 Version 16.7.2+30413.136**

**Comment by kekekeks** [comment]
Broken with Windows right now since it turned out that ANGLE context sharing isn't actually thread safe with most GPU drivers. There is a rework of OpenGL interop planned for 0.10 release, expect it somewhere in September or October.

**Comment by shults-s** [comment]
@kekekeks
> Broken with Windows right now since it turned out that ANGLE context sharing isn't actually thread safe with most GPU drivers. There is a rework of OpenGL interop planned for 0.10 release, expect it somewhere in September or October.

In addition to what @workgroupengineering described, rendering also behaves very strangely. From your description, I understand what the problem is, but maybe these screenshots will help you.

The first screenshot along with the ```AccessViolationException``` looks like someone is writing to the wrong memory... If you move the sliders slowly, the application will not crash immediately.

Avalonia: 0.10.0-preview5
OS: Windows 10 1909 x64 (18363.1082)
GPU: Intel HD Graphics 3000, driver 9.17.10.4459

![Screenshot 1](https://user-images.githubusercontent.com/7778592/93092229-d9aa2800-f6a7-11ea-9cee-131021495477.png)

![Screenshot 2](https://user-images.githubusercontent.com/7778592/93092269-e464bd00-f6a7-11ea-8714-569d63056db8.png)

![Screenshot 3](https://user-images.githubusercontent.com/7778592/93092293-edee2500-f6a7-11ea-8588-09ede85e5a38.png)
