### ISSUE TITLE
AmbiguousMatchException when bind to property overriden with new from base class

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#4733]
```
System.Reflection.AmbiguousMatchException
  HResult=0x8000211D
  Message=Ambiguous match found.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at Avalonia.Data.Core.Plugins.InpcPropertyAccessorPlugin.GetPropertyWithName(Type type, String propertyName) in D:\Development\GitHub\Avalonia\src\Avalonia.Base\Data\Core\Plugins\InpcPropertyAccessorPlugin.cs:line 52
   at Avalonia.Data.Core.Plugins.InpcPropertyAccessorPlugin.Match(Object obj, String propertyName) in D:\Development\GitHub\Avalonia\src\Avalonia.Base\Data\Core\Plugins\InpcPropertyAccessorPlugin.cs:line 15
   at Avalonia.Data.Core.PropertyAccessorNode.GetPropertyAccessorPluginForObject(Object target) in D:\Development\GitHub\Avalonia\src\Avalonia.Base\Data\Core\PropertyAccessorNode.cs:line 87
   at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference) in D:\Development\GitHub\Avalonia\src\Avalonia.Base\Data\Core\PropertyAccessorNode.cs:line 48
   at Avalonia.Data.Core.ExpressionNode.StartListening() in D:\Development\GitHub\Avalonia\src\Avalonia.Base\Data\Core\ExpressionNode.cs:line 141
```
reproduction:
if we have a data context like:
```
    public class MyViewModelBase { public object Name => "Name"; }
    public class MyViewModel : MyViewModelBase { public new string Name => "NewName"; }
```
and we bind to `Name` property in xaml like: `{Binding Name}`, binding is crashing the ui.

this is a Breaking change 0.9 -> 0.10, in avalonia 0.9 same binding wasn't causing trouble.
Problem is here:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/Plugins/InpcPropertyAccessorPlugin.cs#L52

essentially `typeof(MyViewModel).GetProperty("Name")` throws `AmbiguousMatchException`

**Comment by MarchingCube** [comment]
We need to implement this in the same way as method binding then. It will regress performance but hopefully it can be improved with fully compiled expression observers later.

**Comment by workgroupengineering** [comment]
I think the current behavior is correct and the problem is in your vm.
If you need to change the behavior of a method or property, it is better to declare them virtual in the base class.

[Here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords) you will find the reasons.
