### ISSUE TITLE
libGL error: failed to create drawable

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4742]
Using 0.10.999-cibuild0010825-beta on linux I'm seeing 'libGL error: failed to create drawable' in the terminal, they always appear two at a time. I have also had a couple of crashes with no exceptions logged, no idea if they are related and am trying to recreate.

**Comment by kekekeks** [comment]
Does that happen on popup or window close?

**Comment by ahopper** [comment]
It does not happen often so I'm not sure at the moment, there could be tooltips or dropdowns closing. The crashes have certainly been when I am using the mouse.

**Comment by kekekeks** [comment]
Do you have a backtrace of a crash?

**Comment by ahopper** [comment]
I'm afraid I haven't. I've now enabled core dumps on that test machine but haven't managed to make it crash again. I was testing a .deb install of my app when it crashed so I didn't even have a terminal open. Is there anything else I can log?

**Comment by sn4k3** [comment]
I have same warning/error on terminal but so far it never crashed. I tried to look for missing dependencies (libGL) but everything is there.

**Comment by ahopper** [comment]
I don't know it this is connected or a different issue but I've had this reported by a user

13/11/2020 11:48:57 am v2.0.3.5
Main error
glXMakeContextCurrent failed
Avalonia.X11
System.IDisposable MakeCurrent(IntPtr)
   at Avalonia.X11.Glx.GlxContext.MakeCurrent(IntPtr xid)
   at Avalonia.X11.Glx.GlxGlPlatformSurface.RenderTarget.BeginDraw()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.X11.X11Window.DoPaint()
   at Avalonia.X11.X11Window.<OnEventSync>b__104_0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)

   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SparkSDR.Program.Main(String[] args)

**Comment by ahopper** [comment]
this
https://github.com/AvaloniaUI/Avalonia/blob/a1350a0a28da0c51095b5c8bd9765b11db5ef416/src/Avalonia.X11/Glx/GlxContext.cs#L89-L107
throws an exception that causes the program to exit, is this really fatal or could it recover next frame?

**Comment by kekekeks** [comment]
It should probably be ignored in Expose handler, yes.

**Comment by ahopper** [comment]
not seen the error the error for ages so closing
