### ISSUE TITLE
Crashes with DatePicker due to Unpresentable Dates

### ISSUE THREAD

**Issue by VisualMelon** [AvaloniaUI/Avalonia#4793]
The `DatePicker` crashes if you click on it (i.e. bring up the pop-up) when the Day of the selected date is outside the range of any Month. Tested with the current development branch and the 0.1.0-preview5 release on Windows 10

The exception is on `"System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.'"` in DateTimePickerPanel.cs on Line 491.

https://github.com/AvaloniaUI/Avalonia/blob/3d33abafeb698b9e7fcc423d9ec67ed694d67dd7/src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs#L491

Basically, when it is rendering the Months, it renders a whole date with a format that only reports the month, so when it tries to renter e.g. `February 31` it fails.

The exception goes away if you change the day on that line to be 1 rather than the chosen day. Need to change line 409 (year rendering) to deal with leap years (e.g. selecting February 29 has the same problem, because it doesn't exist in some years). The time formatting has hardcoded values for minute/second; I don't know why the dates do not, but I'm not a date/time expert.

I'm not sure what the best solution is, but at the moment the control is not really usable. If hardcoding those sounds sensible - or someone has a better suggestion - I'll be happy to put a PR together.

Full stacktrace from the .NET Core Control Catalog:

```
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at Avalonia.Controls.Primitives.DateTimePickerPanel.FormatContent(Int32 value, DateTimePickerPanelType panelType) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 491
   at Avalonia.Controls.Primitives.DateTimePickerPanel.UpdateItems() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 475
   at Avalonia.Controls.Primitives.DateTimePickerPanel.set_MaximumValue(Int32 value) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 149
   at Avalonia.Controls.DatePickerPresenter.InitPicker() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePickerPresenter.cs:line 335
   at Avalonia.Controls.DatePickerPresenter.set_Date(DateTimeOffset value) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePickerPresenter.cs:line 133
   at Avalonia.Controls.DatePicker.OnFlyoutButtonClicked(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePicker.cs:line 399
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 63
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 66
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 120
   at Avalonia.Controls.Button.OnClick() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\Button.cs:line 267
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\Button.cs:line 306
   at Avalonia.Input.InputElement.<>c.<.cctor>b__26_9(InputElement x, PointerReleasedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\InputElement.cs:line 181
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 143
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 92
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 99
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 120
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 289
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 162
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 84
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\TopLevel.cs:line 473
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.AppWndProc.cs:line 459
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 129
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 105
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 128
   at ControlCatalog.NetCore.Program.Main(String[] args) in C:\Users\Murdo\source\repos\Avalonia\samples\ControlCatalog.NetCore\Program.cs:line 102
```

**Comment by amwx** [comment]
Not sure how this one slipped through the cracks...
The reason why FormatDate is used instead of hard coded values is so that full date info is available. Though, the only instance I can see this mattering is if you request the day of the week to appear in the Day column, as the Month and Year columns *should* only display their respective values. So I think your solution of hard coding could be applied to both the Month and Year columns (first of the month for Month column, and probably just use Jan 1 for Year column)

**Comment by driver1998** [comment]
I also got block by this issue, hope the PR will be accepted soon.
