### ISSUE TITLE
ArgumentOutOfRangeException TextBlock

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4828]
I wasn't able to repro it, but sometimes the `start` parameter is bigger than the length of the actual string, causing this exception.
@Gillibald Any idea why this is happening?
Thanks

**Update**
Seems like it happens only with Segoe UI font (maybe due to it taking more space than default?)
Repro -
```
<TextBlock
            DockPanel.Dock="Top"
            HorizontalAlignment="Center"
            TextAlignment="Left"
            Margin="0,0,0,6"
            FontSize="14"
            MaxLines="3"
            FontFamily="Segoe UI"
            FontWeight="DemiBold"
            TextWrapping="Wrap"
            MaxWidth="320"
            Text="www.htzone.co.il - מועדון הצרכנות של ההייטקיסטים and 5 more pages - Personal - Microsoft​ Edge" />
```
Application: fluentsearch.exe
CoreCLR Version: 5.0.20.47505
.NET Version: 5.0.0-rc.2.20475.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at Avalonia.Utilities.ReadOnlySlice`1.Take(Int32 length)
   at Avalonia.Media.TextFormatting.ShapedTextCharacters.Split(Int32 length)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.SplitTextRuns(List`1 textRuns, Int32 length)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.PerformTextWrapping(List`1 textRuns, TextRange textRange, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak currentLineBreak)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides)
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text)
   at Avalonia.Controls.TextBlock.get_TextLayout()
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Blast.Program.Main(String[] args) in C:\Users\adirh\RiderProjects\Blast\Blast\Program.cs:line 85
```

**Comment by adirh3** [comment]
![image](https://user-images.githubusercontent.com/27368554/95469166-fc1e2100-0987-11eb-9c10-0b4e1d45be7b.png)
Seems like the length is minus (not sure if this somehow intended)

**Comment by adirh3** [comment]
Found the issue, it's text in Hebrew (RTL) - when displaying this in `TextBlock` with this code-
```
   <TextBlock
                        DockPanel.Dock="Top"
                        HorizontalAlignment="Center"
                        TextAlignment="Left"
                        Margin="0,0,0,6"
                        FontSize="14"
                        MaxLines="3"
                        FontWeight="DemiBold"
                        TextWrapping="Wrap"
                        MaxWidth="320"
                        Text="{Binding ResultName}" />
```
and this text -
`www.htzone.co.il - מועדון הצרכנות של ההייטקיסטים and 5 more pages - Personal - Microsoft​ Edge`

**Comment by Gillibald** [comment]
Thanks for all the details. Helps a lot to fix this. Having a look asap.

**Comment by Gillibald** [comment]
![Screenshot 2020-10-08 180822](https://user-images.githubusercontent.com/5928797/95484864-48ba2a00-0991-11eb-807e-bb18f9bc2805.png)

Not sure about the directional embedding here

**Comment by adirh3** [comment]
> ![Screenshot 2020-10-08 180822](https://user-images.githubusercontent.com/5928797/95484864-48ba2a00-0991-11eb-807e-bb18f9bc2805.png)
> 
> Not sure about the directional embedding here
> 
> Need to compare this to Chrome

Thanks for looking into this so quickly.
Did it not crash for you?
As for the text in the image you sent, it is wrapping the wrong direction, it should look like this - 
![image](https://user-images.githubusercontent.com/27368554/95488059-c2581500-099d-11eb-9004-019205d52958.png)

**Comment by srl17** [comment]
Gillibald, I get the exact same issue with a textblock I have in a window which is bound to a buffered RS422 data input (I only allow text to get updated every 100ms).

Here is my textbox

               <ScrollViewer x:Name="logScroller" Grid.Column="1" VerticalScrollBarVisibility="Visible" Height="330">
                  <TextBlock Name="txtLogFile" FontFamily="Courier New" FontSize="13" TextWrapping="Wrap"
                             Background="#ECE9D8" Text="{Binding LogFileText}" MinHeight="330" />
               </ScrollViewer>

I literally just got my "workaround" working locally

        public ReadOnlySlice<T> Take(int length)
        {
            if (IsEmpty)
            {
                return this;
            }

            if (length > Length)
            {
                length = Length;
            }

            return new ReadOnlySlice<T>(Buffer.Slice(0, length), Start, length);
        }

        /// <summary>
        ///     Bypasses a specified number of elements in the slice and then returns the remaining elements.
        /// </summary>
        /// <param name="length">The number of elements to skip before returning the remaining elements.</param>
        /// <returns>A <see cref="ReadOnlySlice{T}"/> that contains the elements that occur after the specified index in this slice.</returns>
        public ReadOnlySlice<T> Skip(int length)
        {
            if (IsEmpty)
            {
                return this;
            }

            if (length > Length)
            {
                //throw new ArgumentOutOfRangeException(nameof(length));
                length = Length;
            }

            return new ReadOnlySlice<T>(Buffer.Slice(length), Start + length, Length - length);
        }

Just returning what it does have when it requests something hasn't caused me any visual issues yet; it's not a perfect solution because I haven't determined why it gets out of track.

**Comment by Gillibald** [comment]
I am currently not properly splitting RTL text in the  wrapping algorithm. This needs more work. In the meantime I will introduce a workaround that produces the above result.

**Comment by Gillibald** [comment]
The crash is fixed. The RTL text wrapping has its own issue.
