### ISSUE TITLE
Exception in render loop

### ISSUE THREAD

**Issue by thatbakamono** [AvaloniaUI/Avalonia#4881]
After spending some time on playing with the app, my friend found out that after he minimized the window, a new exception appeared in the logs:
```
[2020-10-16 19:36:03] [ERR] [Visual - Avalonia.Rendering.RenderLoop] Exception in render loop: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time)
```
I found two issues with exactly the same exception (#2063 #1943) but both are closed and resolved, I believe, so it might be regression or a completely new problem.

PS: We currently use 0.10.0-preview5, he uses windows 8.1

**Comment by jampot5000** [comment]
For extra context I would assume this is happening at this line https://github.com/AvaloniaUI/Avalonia/blob/36855456762e4837052dc9a4acd80989bc2fe9bd/src/Avalonia.Visuals/Rendering/RenderLoop.cs#L102 as this is the only foreach loop for the items without a lock. Is there any reason there is no lock on _items here?
