### ISSUE TITLE
TestServices: Loading theme with StyleInclude will crash

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#4894]
It seems that loading a theme (like fluent) inside `TestServices.CreateDefaultTheme()` that `StyleInclude`s other styles will not work correctly.

[repro_xaml_load_unit_test.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/5410210/repro_xaml_load_unit_test.patch.txt)

```
Avalonia.Markup.Xaml.XamlLoadException
No precompiled XAML found for avares://avalonia.themes.fluent/ToolTip.xaml (baseUri: avares://avalonia.themes.fluent/FluentTheme.xaml), make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in R:\Avalonia\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 76
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in R:\Avalonia\src\Markup\Avalonia.Markup.Xaml\Styling\StyleInclude.cs:line 54
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in R:\Avalonia\src\Markup\Avalonia.Markup.Xaml\Styling\StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in R:\Avalonia\src\Avalonia.Styling\Styling\Styles.cs:line 240
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in R:\Avalonia\src\Avalonia.Styling\Styling\Styles.cs:line 289
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in R:\Avalonia\src\Avalonia.Styling\Styling\Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index) in R:\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 646
   at Avalonia.Collections.AvaloniaList`1.InsertRange(Int32 index, IEnumerable`1 items) in R:\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 381
   at Avalonia.Collections.AvaloniaList`1.AddRange(IEnumerable`1 items) in R:\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 194
   at Avalonia.Styling.Styles.AddRange(IEnumerable`1 items) in R:\Avalonia\src\Avalonia.Styling\Styling\Styles.cs:line 174
   at Avalonia.UnitTests.UnitTestApplication.RegisterServices() in R:\Avalonia\tests\Avalonia.UnitTests\UnitTestApplication.cs:line 73
   at Avalonia.UnitTests.UnitTestApplication..ctor(TestServices services) in R:\Avalonia\tests\Avalonia.UnitTests\UnitTestApplication.cs:line 28
   at Avalonia.UnitTests.UnitTestApplication.Start(TestServices services) in R:\Avalonia\tests\Avalonia.UnitTests\UnitTestApplication.cs:line 38
   at Avalonia.Controls.UnitTests.Primitives.PopupRootTests.PopupRoot_Should_Have_Null_VisualParent() in R:\Avalonia\tests\Avalonia.Controls.UnitTests\Primitives\PopupRootTests.cs:line 99

```

**Comment by grokys** [comment]
Just tried this and seems that you need to do two things: 

1. Make sure the `avares:` URI scheme is registered: `Avalonia.Shared.PlatformSupport.AssetLoader.RegisterResUriParsers();`
2. Pass a `baseUri` to the `FluentTheme` constructor. This would usually be the XAML file that contains the `<FluentTheme>` element but in this case it doesn't seem to be needed so a dummy URL should work, e.g. `new FluentTheme(new Uri("avares://Dummy/App.xaml"))`
