### ISSUE TITLE
NullReferenceException in CompileAvaloniaXamlTask with a ProjectReference

### ISSUE THREAD

**Issue by lostmsu** [AvaloniaUI/Avalonia#4965]
An empty Avalonia app template fails to build when a reference is added to a local project.

> AvaloniaBuildTasks.targets(80,5): error MSB4018: The "CompileAvaloniaXamlTask" task failed unexpectedly.
> AvaloniaBuildTasks.targets(80,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at XamlIl.TypeSystem.XamlIlTypeSystemExtensions.EmitCall(IXamlIlEmitter emitter, IXamlIlMethod method, Boolean swallowResult) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\TypeSystem\TypeSystem.cs:line 476
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at XamlIl.Transform.XamlIlContextDefinition..ctor(IXamlIlTypeBuilder parentBuilder, IXamlIlTypeSystem typeSystem, XamlIlLanguageTypeMappings mappings) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\Transform\XamlIlContext.cs:line 150
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at XamlIl.Transform.XamlIlContextDefinition.GenerateContextClass(IXamlIlTypeBuilder builder, IXamlIlTypeSystem typeSystem, XamlIlLanguageTypeMappings mappings) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\XamlIl\xamlil.github\src\XamlIl\Transform\XamlIlContext.cs:line 110
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.Compile(IBuildEngine engine, String input, String[] references, String projectDirectory, String output, Boolean verifyIl) in D:\a\1\s\src\Avalonia.Build.Tasks\XamlCompilerTaskExecutor.cs:line 62
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute() in D:\a\1\s\src\Avalonia.Build.Tasks\CompileAvaloniaXamlTask.cs:line 35
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
> AvaloniaBuildTasks.targets(80,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by FoggyFinder** [comment]
Is it so complicated to prepare MCVE?

> \src\Bugs.csproj : error NU1102: Unable to find package LostTech.Python.Runtime with version (>= 3.0.3-b1261)

**Comment by lostmsu** [comment]
@FoggyFinder sorry, I was still uploading the packages.

I did a bit of fiddling, and it seems that having a ProjectReference is not necessary.

It fails when this is added: `<PackageReference Include="LostTech.TensorFlow" Version="1.15.0-CI-20201020-001" />`

**Comment by maxkatz6** [comment]
@kekekeks
Still can be reproduced with 0.10.14:
```
Error	MSB4018	The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at XamlX.IL.XamlIlEmitterExtensions.EmitCall(IXamlILEmitter emitter, IXamlMethod method, Boolean swallowResult)
   at XamlX.IL.XamlILContextDefinition..ctor(IXamlTypeBuilder`1 parentBuilder, IXamlTypeSystem typeSystem, XamlLanguageTypeMappings mappings, XamlLanguageEmitMappings`2 emitMappings)
   at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.CompileCore(IBuildEngine engine, CecilTypeSystem typeSystem, String projectDirectory, Boolean verifyIl, MessageImportance logImportance, Boolean debuggerLaunch)
   at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.Compile(IBuildEngine engine, String input, String[] references, String projectDirectory, String output, Boolean verifyIl, MessageImportance logImportance, String strongNameKey, Boolean patchCom, Boolean skipXamlCompilation, Boolean debuggerLaunch)
   at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Bugs	C:\Users\maxka\.nuget\packages\avalonia\0.10.14\buildTransitive\AvaloniaBuildTasks.targets	98	

```
