### ISSUE TITLE
ControlCatalog.NetCore System.AccessViolationException

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#5057]
affected version: 7dcc843

StackTrace
```cli
fatal error. 0xC0000005
   at System.Runtime.InteropServices.GCHandle.get_Target()
   at Avalonia.MicroCom.Ccw.GetShadow()
   at Avalonia.MicroCom.MicroComVtblBase.QueryInterface(Avalonia.MicroCom.Ccw*, System.Guid*, Void**)
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositorProxy.CreateEffectFactory(Avalonia.Win32.WinRT.IGraphicsEffect)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection.CreateBlurBrush()
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection..ctor(Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface, System.Object)
   at Avalonia.Win32.WinRT.Composition.WinUICompositorConnection+<>c__DisplayClass15_0.<TryCreateAndRegisterCore>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

ControlCatalog.Desktop is working correctly.

**Comment by kekekeks** [comment]
Which windows version?

**Comment by workgroupengineering** [comment]
Windows 10 64-bit build 2004 19041.630

NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

**Comment by kekekeks** [comment]
Fixed in master
