### ISSUE TITLE
textLine.GetNextCaretCharacterHit fails for certain input

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/Avalonia#5130]
Getting the next caret hit fails for certain inputs. The expected behaviour is to just return the right most trailing character hit of the cursor can't move further to the right/ the left most leading char hit if the cursor can't move further to the left.

This works as expected mostly but throws for certain inputs.

Test that reproduces the issue on `0.10.999-cibuild0011450-beta`.

in `TextLineTests.cs`
```csharp
        [InlineData("𐐷𐐷𐐷𐐷𐐷")] // works
        [InlineData("01234567🎉\n")] // fails
        [Theory]
        public void Should_Get_Next_Caret_CharacterHits_And_Stop_At_Last_One(string text)
        {
            using (Start())
            {
                var defaultProperties = new GenericTextRunProperties(Typeface.Default);

                var textSource = new SingleBufferTextSource(text, defaultProperties);

                var textLine =
                    TextFormatter.Current.FormatLine(textSource, 0, double.PositiveInfinity,
                        new GenericTextParagraphProperties(defaultProperties, lineHeight: double.NaN));

                var currentHit = new CharacterHit(0, 0);

                foreach (var _ in Enumerable.Range(0, 20))
                {
                    var input = new CharacterHit(currentHit.FirstCharacterIndex, 0);

                    var nextHit = textLine.GetNextCaretCharacterHit(input);

                    currentHit = nextHit;

                    Console.WriteLine($"input char hit ({input.FirstCharacterIndex}, {input.TrailingLength}) -> output char hit ({nextHit.FirstCharacterIndex}, {nextHit.TrailingLength})");
                }

            }
        }
```

fails with 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.

System.IndexOutOfRangeException
Index was outside the bounds of the array.
   at Avalonia.Utilities.ReadOnlySlice`1.get_Item(Int32 index)
   at Avalonia.Media.TextFormatting.Unicode.Codepoint.ReadAt(ReadOnlySlice`1 text, Int32 index, Int32& count)
   at Avalonia.Media.TextFormatting.TextLineImpl.TryFindNextCharacterHit(CharacterHit characterHit, CharacterHit& nextCharacterHit)
   at Avalonia.Media.TextFormatting.TextLineImpl.GetNextCaretCharacterHit(CharacterHit characterHit)
```

**Comment by Gillibald** [comment]
This PR improves the TextLine API to deal with trailing whitespace https://github.com/AvaloniaUI/Avalonia/pull/4893
Trying to fix this for master

**Comment by JaggerJo** [comment]
@Gillibald is it already in master ? 🙂

**Comment by Gillibald** [comment]
Haven't touched master yet

**Comment by JaggerJo** [comment]
@Gillibald ok - is the fix already in the other branch / is it hard to port it to master ? The issue is kind of blocking for me and prevents me from continuing. 🙂

**Comment by Gillibald** [comment]
Yes this is fixed in the FormattedText branch. The moment I have fixed the remaining issues in that branch I will try to merge it into master. All the changes to TextFormatter etc. will improve your ability to write an editor.
