### ISSUE TITLE
KeyNotFoundException during rendering on MacOS

### ISSUE THREAD

**Issue by capdj** [AvaloniaUI/Avalonia#5197]
I'm seeing KeyNotFoundException during rendering on MacOS - not consistently reproducible, but it has happened more than once; I think while scrolling some content within a tab. It's not massively frequent (say, 1 crash per hour of usage?) - often enough to be annoying but not often enough to have an easy reproduction!

May not actually be MacOS specific, but the same program doesn't seem to exhibit the bug on Windows and Linux.

Stack trace from the error (have seen identical stack traces on multiple occasions):
```

 Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.Layoutable.ArrangeOverride(Size finalSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Controls.Primitives.Track.ArrangeOverride(Size arrangeSize)
   at Avalonia.Layout.Layoutable.ArrangeCore(Rect finalRect)
   at Avalonia.Layout.Layoutable.Arrange(Rect rect)
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Boolean priorityContainsMeaningfulValue)

```
Looking at DirtyVisuals, I assume the exception is coming from line 49: _inner[existingDistance].Remove(visual); 

However I can't see any obvious flaw in the logic that would cause an item to be present in _index without also being present in _inner - unless dirty items are being added/cleared from multiple threads at once - DirtyVisuals doesn't look threadsafe, and so that could definitely be an issue, and would explain the unpredictable and fairly infrequent nature of the crash. I don't know enough about the architecture of Avalonia to say whether or not that's the case though!

**Comment by MikeCodesDotNET** [comment]
It'd be interesting to know if you still have the same issue with v11?

**Comment by maxkatz6** [comment]
DirtyVisuals was removed, so it won't happen anymore.
