### ISSUE TITLE
fbdev and drm options are not working

### ISSUE THREAD

**Issue by Eroli** [AvaloniaUI/Avalonia#5230]
Hi everybody and thank you for the effort you put into this project. I decided to write a small PictureFrame application using avalonia for a raspberry pi running the latest raspberry os.

OS Name: raspbian
OS Version: 10
.NET Core Runtime Version: 3.1.10
.NET Core SDK Version: 3.1.404
Avalonia version: Nightlybuild from global nuget repository: v0.10.0-rc1

At the moment i am able to start the application on raspberry and it works already quite fine, but is very slow. The carousel crossfade transition is already struggling with full hd pictures, meaning that the animation is almost not visible and the pictures are just suddenly changing.
Therefore, i wanted to try out the fbdev or drm options, but none of these works. Here are some parts of the relevant code:

Main.cs Main:
`public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
            .With(new X11PlatformOptions
            {
                EnableMultiTouch = true,
                UseDBusMenu = true
            })
            .With(new Win32PlatformOptions
            {
                EnableMultitouch = true,
                AllowEglInitialization = true
            })
            .UseSkia()
                .UseReactiveUI()
            .UseManagedSystemDialogs();

        static void SilenceConsole()
        {
            new Thread(() =>
            {
                Console.CursorVisible = false;
                while (true)
                    Console.ReadKey(true);
            })
            {
                IsBackground = true
            }.Start();
        }
    }`

App.axaml.cs:
`        public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                desktop.MainWindow = new MainWindow
                {
                    DataContext = new MainWindowViewModel(),
                };
            }
            base.OnFrameworkInitializationCompleted();
        }`

However, the following exceptions are raised when starting the application with the fbdev or drm options:

> SmartPictureFrame --fbdev
> Run in Mode: Framebuffer
> Unhandled exception. System.Exception: Unable to set 32-bit display mode
>     at Avalonia.LinuxFrameBuffer.FbdevOutput.Init()
> [...]

> SmartPictureFrame --drm
> Run in Mode: DRM
> Unhandled exception. System.ComponentModel.Win32Exception (95): drmModeGetResources failed
>    at Avalonia.LinuxFrameBuffer.Output.DrmResources..ctor(Int32 fd)
> [...]

Do you have any hints on how to fix those issues? I was also reading carefully through https://github.com/AvaloniaUI/Avalonia/issues/3671
but as i get a different exception i did not try to change the application from Window to UserControl. Also, full KMS is also enabled.

Thanks everybody for you help :-)

**Comment by kekekeks** [comment]
1) you need to stop XOrg and/or switch to another tty
2) `glxinfo`

**Comment by Eroli** [comment]
> 1. you need to stop XOrg and/or switch to another tty
> 2. Please, show `glxinfo` output, it might be possible to get hw-accelerated graphics with XOrg

Thanks for your answer, @kekekeks !
First, you may find the output of glxinfo attached: [glxinfo.txt](https://github.com/AvaloniaUI/Avalonia/files/5750476/glxinfo.txt)

I stopped XOrg using raspi-config and tried it out of the console, but that didnt work either. I found out that also the kmscube demo application was not starting. It is required to specify the correct driver for this to work:
`kmscube -D /dev/dri/card1`

Therefore, i changed the application builder in the program.cs to
`return builder.StartLinuxDrm(args, "/dev/dri/card1", scaling: GetScaling());`

Now, if i start the application in a ClassicDesktopApplicationLifetime-environment, i get the already known IWindowingPlatform is not registered error. If i change my App.axaml.cs to

```
 public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is ISingleViewApplicationLifetime single)
            {
                single.MainView = new MainWindow()
                {
                    DataContext = new MainWindowViewModel()
                };
            }

            base.OnFrameworkInitializationCompleted();
        }
```
where "MainWindow" is just a UserControl, i get the following error:

> gbm_surface_lock_front_buffer failed

How is this workaround mentioned in #3671 meant to work? Just the way i did it by changing all occurences from Window to UserControl (Start- and end-tag in xaml file as well as the inheritance in the code-behind file?)? If i do so, starting the application using VisualStudio results in no window being showed. _Something_ seams to be running though, but not visible for me.

**Comment by kekekeks** [comment]
Your setup has desktop OpenGL profile enabled for X11, so issues are probably not related to X11, so it's better to try get the app working properly with X11.

Since you are experiencing frame drop with HD images try increasing Skia texture budget in Skia options to 512MB.

**Comment by Eroli** [comment]
I tried it once again using X11. Therefore, i increased the memory as you suggested like this (in the AppBuilder)

```
            .UseSkia()
            .With(new SkiaOptions
            {
                MaxGpuResourceSizeBytes = 512 * 1024 * 1024
            })
```
(Or should i set the SkiaOptions before UseSkia?)

Furthermore, i added a delay of 3 seconds between loading of the pictures and doing the transition in order to make sure that the loading times are not causing the frame drop. However, nothing changed: In the transition are still frames lost, causing an abrupt change of the pictures instead of a smooth transition. Once again, for FullHD pictures it works fine, but not for 4K resolution. Nevertheless i assume, that the raspberry pi 4B (4GB RAM) should have more than enough computing power for such an easy task? Or am i wrong?
