### ISSUE TITLE
CompileAvaloniaXamlTask bug

### ISSUE THREAD

**Issue by WenjunHuang** [AvaloniaUI/Avalonia#5236]
**Describe the bug**
When defining a custom   Transition<IBrush> subclass and then use ‘Property’ and ‘Duration’ in a style XAML file, the compiler logged  the following error:
  AvaloniaBuildTasks.targets(84, 5): [MSB4018] “CompileAvaloniaXamlTask”任务意外失败。
System.ArgumentException: Member 'Avalonia.AvaloniaProperty' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.SignatureWriter.MakeTypeDefOrRefCodedRID(TypeReference type)
   at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.SignatureWriter.WriteMethodSignature(IMethodSignature method)
   at Mono.Cecil.MetadataBuilder.GetMethodSignature(IMethodSignature method)
   at Mono.Cecil.MetadataBuilder.GetMemberRefSignature(MemberReference member)
   at Mono.Cecil.MetadataBuilder.CreateMemberRefRow(MemberReference member)
   at Mono.Cecil.MetadataBuilder.GetMemberRefToken(MemberReference member)
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.Compile(IBuildEngine engine, String input, String[] references, String projectDirectory, String output, Boolean verifyIl, MessageImportance logImportance, String strongNameKey, Boolean patchCom, Boolean skipXamlCompilation)
   at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**To Reproduce**
my custom Transition
`
public class ColorTransition : Transition<IBrush>
    {
        
        public override IObservable<IBrush> DoTransition(IObservable<double> progress, IBrush oldValue, IBrush newValue)
        {
            if (oldValue is SolidColorBrush sold)
            {
                if (newValue is SolidColorBrush snew)
                {
                    var oldColor = sold.Color;
                    var newColor = snew.Color;
                    return progress.Select(p =>
                    {
                        var r = Easing.Ease(p) * (newColor.R - oldColor.R) + oldColor.R;
                        var g = Easing.Ease(p) * (newColor.G - oldColor.G) + oldColor.G;
                        var b = Easing.Ease(p) * (newColor.B - oldColor.B) + oldColor.B;
                        var a = Easing.Ease(p) * (newColor.A - oldColor.A) + oldColor.A;

                        var c = Color.FromArgb(Convert.ToByte(a),
                            Convert.ToByte(r),
                            Convert.ToByte(g),
                            Convert.ToByte(b)
                        );
                        return new SolidColorBrush(c);
                    });
                }
            }

            return progress.Select(_ => newValue);
        }
    }
`

and use it in xaml

`    
<Styles xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="CustomStyleForTextBox.Styles.TextBox"
        xmlns:sys="clr-namespace:System"
        xmlns:local="clr-namespace:CustomStyleForTextBox">
...
<Style Selector="TextBox.CustomStyle /template/ Border#PART_BorderElement">
        <Setter Property="Transitions">
            <Transitions>
                <local:ColorTransition Property="BorderBrush" Duration="0:0:0.2"></local:ColorTransition>
            </Transitions>
        </Setter>
    </Style>
`

version: 0.10.0-rc1
os:windows 10

**Comment by maxkatz6** [comment]
Seems to not be an issue anymore. We have custom transition sample in RenderDemo.
If it's still reproducible, please ask to reopen and add a project to build and test.
