### ISSUE TITLE
macos clipboard GetDataAsync

### ISSUE THREAD

**Issue by zhenggr520** [AvaloniaUI/Avalonia#5380]
In macos, I need to get the file name, but the clipboard contains text data. Calling the GetDataAsync method will cause the program to crash. What should I do?

object data = await Application.Current.Clipboard.GetDataAsync(DataFormats.FileNames);

 at Avalonia.MicroCom.MicroComProxyBase.get_NativePointer() in /_/src/Avalonia.MicroCom/MicroComProxyBase.cs:line 20
   at Avalonia.MicroCom.MicroComProxyBase.get_PPV() in /_/src/Avalonia.MicroCom/MicroComProxyBase.cs:line 24
   at Avalonia.MicroCom.MicroComProxyBase.Release() in /_/src/Avalonia.MicroCom/MicroComProxyBase.cs:line 44
   at Avalonia.MicroCom.MicroComProxyBase.Dispose(Boolean disposing) in /_/src/Avalonia.MicroCom/MicroComProxyBase.cs:line 73
   at Avalonia.MicroCom.MicroComProxyBase.Dispose() in /_/src/Avalonia.MicroCom/MicroComProxyBase.cs:line 79
   at Avalonia.Native.ClipboardImpl.GetFileNames() in /_/src/Avalonia.Native/ClipboardImpl.cs:line 78
   at Avalonia.Native.ClipboardImpl.<GetDataAsync>d__13.MoveNext() in /_/src/Avalonia.Native/ClipboardImpl.cs:line 107
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AvaloniaApplication1.Views.MainWindow.<MainWindow_KeyDown>d__1.MoveNext() in /Users/zheng/Desktop/Code/AvaloniaApplication1/AvaloniaApplication1/Views/MainWindow.axaml.cs:line 28

**Comment by pr8x** [comment]
Please use the proper issue templates in the future.

**Comment by IngvarX** [comment]
Same issue in my project on macos. I use Avalonia v0.10.0
