### ISSUE TITLE
Using $parent with xmlns and using throws ArgumentNullException

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#5382]
**Describe the bug**
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'assemblyName')
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.XamlTypeResolver.Resolve(String qualifiedTypeName) in /_/src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs:line 135
   at Avalonia.Markup.Xaml.Extensions.ResolveType(IServiceProvider ctx, String namespacePrefix, String type) in /_/src/Markup/Avalonia.Markup.Xaml/Extensions.cs:line 33
   at Avalonia.Markup.Parsers.ExpressionParser.ParseFindAncestor(AncestorNode node) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionParser.cs:line 92
   at Avalonia.Markup.Parsers.ExpressionParser.Parse(CharacterReader& r) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionParser.cs:line 54
   at Avalonia.Markup.Parsers.ExpressionObserverBuilder.Parse(String expression, Boolean enableValidation, Func`3 typeResolver, INameScope nameScope) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionObserverBuilder.cs:line 21
   at Avalonia.Data.Binding.CreateExpressionObserver(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/Binding.cs:line 74
   at Avalonia.Data.BindingBase.Initiate(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/BindingBase.cs:line 95
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 365
   at AvaloniaDemo.Views.MenuView.!XamlIlPopulate(IServiceProvider , MenuView ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MenuView.axaml:line 5
   at AvaloniaDemo.Views.MenuView.!XamlIlPopulateTrampoline(MenuView )
   at AvaloniaDemo.Views.MenuView.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MenuView.axaml.cs:line 25
   at AvaloniaDemo.Views.MenuView..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MenuView.axaml.cs:line 20
   at AvaloniaDemo.Views.MainView.!XamlIlPopulate(IServiceProvider , MainView ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MainView.axaml:line 13
   at AvaloniaDemo.Views.MainView.!XamlIlPopulateTrampoline(MainView )
   at AvaloniaDemo.Views.MainView.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainView.axaml.cs:line 15
   at AvaloniaDemo.Views.MainView..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainView.axaml.cs:line 10
   at AvaloniaDemo.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MainWindow.axaml:line 17
   at AvaloniaDemo.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at AvaloniaDemo.Views.MainWindow.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainWindow.axaml.cs:line 17
   at AvaloniaDemo.Views.MainWindow..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainWindow.axaml.cs:line 11
   at AvaloniaDemo.App.OnFrameworkInitializationCompleted() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\App.axaml.cs:line 30
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 133
   at AvaloniaDemo.Program.Main(String[] args) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Program.cs:line 11

```
**To Reproduce**
```xaml
<UserControl x:Class="AvaloniaDemo.Views.MenuView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:v="using:AvaloniaDemo.Views">
    <CheckBox IsChecked="{Binding $parent[v:MenuView].Test}"/>
</UserControl>
````

```C#
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaloniaDemo.Views
{
    public class MenuView : UserControl
    {
        public static readonly StyledProperty<bool> TestProperty =
            AvaloniaProperty.Register<MenuView, bool>(nameof(Test));

        public bool Test
        {
            get => GetValue(TestProperty);
            set => SetValue(TestProperty, value);
        }
        
        public MenuView()
        {
            this.InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```
**Expected behavior**

No exception.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version0.10.0

**Comment by wieslawsoltes** [comment]
```
Unhandled exception. Avalonia.Data.Core.ExpressionParseException: Expected end of expression.
   at Avalonia.Markup.Parsers.ExpressionObserverBuilder.Parse(String expression, Boolean enableValidation, Func`3 typeResolver, INameScope nameScope) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionObserverBuilder.cs:line 25
   at Avalonia.Data.Binding.CreateExpressionObserver(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/Binding.cs:line 74
   at Avalonia.Data.BindingBase.Initiate(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/BindingBase.cs:line 95
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 365
   at AvaloniaDemo.Views.MenuView.!XamlIlPopulate(IServiceProvider , MenuView ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MenuView.axaml:line 5
   at AvaloniaDemo.Views.MenuView.!XamlIlPopulateTrampoline(MenuView )
   at AvaloniaDemo.Views.MenuView.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MenuView.axaml.cs:line 25
   at AvaloniaDemo.Views.MenuView..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MenuView.axaml.cs:line 20
   at AvaloniaDemo.Views.MainView.!XamlIlPopulate(IServiceProvider , MainView ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MainView.axaml:line 13
   at AvaloniaDemo.Views.MainView.!XamlIlPopulateTrampoline(MainView )
   at AvaloniaDemo.Views.MainView.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainView.axaml.cs:line 15
   at AvaloniaDemo.Views.MainView..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainView.axaml.cs:line 10
   at AvaloniaDemo.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views/MainWindow.axaml:line 17
   at AvaloniaDemo.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at AvaloniaDemo.Views.MainWindow.InitializeComponent() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainWindow.axaml.cs:line 17
   at AvaloniaDemo.Views.MainWindow..ctor() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Views\MainWindow.axaml.cs:line 11
   at AvaloniaDemo.App.OnFrameworkInitializationCompleted() in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\App.axaml.cs:line 30
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 133
   at AvaloniaDemo.Program.Main(String[] args) in C:\DOWNLOADS\GitHub\Dock\samples\AvaloniaDemo\Program.cs:line 11
```

```xaml
<UserControl x:Class="AvaloniaDemo.Views.MenuView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:v="clr-namespace:AvaloniaDemo.Views">
    <CheckBox IsChecked="{Binding $parent[v:MenuView].Test)}"/>
</UserControl>
``

**Comment by wieslawsoltes** [comment]
Using `clr-namespace` works:
```xaml
<UserControl x:Class="AvaloniaDemo.Views.MenuView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:v="clr-namespace:AvaloniaDemo.Views">
    <CheckBox IsChecked="{Binding $parent[v:MenuView].Test}"/>
</UserControl>
```

**Comment by maxkatz6** [comment]
Sounds similar to https://github.com/AvaloniaUI/Avalonia/issues/7200
