### ISSUE TITLE
Blank boilerplate project throws error when trying to open the MainWindow.axaml

### ISSUE THREAD

**Issue by OnlyOnePro** [AvaloniaUI/Avalonia#5474]
**Describe the bug**
When created a blank project using the Avalonia Extension it generates a boilerplate with minimal configurations. Trying to open the MainWindow.axaml file throws an error in Visual Studio due to an invalid method from Serilog as a dependency.

**To Reproduce**

1- On Visual Studio 2019 16.8.5 install the Avalonia Extension via the VS Marketplace
2- Create a new Avalonia Project (not the MVVM one).
3- Compile and build the project. Run the project. The app displays successfully.
4- Try to open the MainWindow.axaml. The app throws the following error:

```
An error occurred while initializing the frame's content
System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.Configuration.LoggerDestructuringConfiguration.ToMaximumStringLength(Int32)'.
   at AvaloniaVS.Services.PreviewerProcess..ctor()
   at AvaloniaVS.Views.AvaloniaDesigner..ctor() in D:\a\1\s\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 110
   at AvaloniaVS.Views.DesignerPane.Initialize() in D:\a\1\s\AvaloniaVS\Views\DesignerPane.cs:line 73
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsWindowPane.SetSite(IServiceProvider psp)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.SetUIElementSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)

```

**Expected behavior**
It should open the Avalonia XAML editor.

**Desktop (please complete the following information):**

- OS: Windows
- Version : 20H2 19024.804

**Comment by danwalmsley** [comment]
Issue related to https://github.com/AvaloniaUI/AvaloniaVS
