### ISSUE TITLE
bug: UI Theme Changing is Broken if there is a <Carousel />

### ISSUE THREAD

**Issue by worldbeater** [AvaloniaUI/Avalonia#5530]
**Describe the bug**

After bumping Avalonia version from 0.9.12 to 0.10.0 theme changing via `window.Styles[0] = new StyleInclude` is no longer working properly. E.g. every _second_ time I change the theme, the theme is applied correctly but then someone is _resetting_ the styles, see the GIF below:

![ezgif-7-caa9cbcc48e9](https://user-images.githubusercontent.com/6759207/108681600-6501d200-7500-11eb-8464-783e53912e05.gif)

**Update (28.02.2021)**

The errors seem to be coming from the `<Carousel />` control.
Theme changing works perfectly if I remove the `<Carousel />`, see https://github.com/AvaloniaUI/Avalonia/issues/5530#issuecomment-787417903
Also a `<Carousel />` occasionally throws a `KeyNotFoundException`, see https://github.com/AvaloniaUI/Avalonia/issues/5530#issuecomment-787050397

**To Reproduce**

Here is the [repro](https://github.com/worldbeater/Camelotia/tree/updates). Steps to reproduce the behavior:

1. `git clone https://github.com/worldbeater/Camelotia.git`
2. `git checkout updates` (a branch with Avalonia 0.10.0)
3. Launch `src/Camelotia.Avalonia.sln` or do `cd src/Camelotia.Presentation.Avalonia && dotnet run`
4. Press `Switch Theme` multiple times

On `master` (Avalonia 0.9.12) theme changing works fine, on [`updates`](https://github.com/worldbeater/Camelotia/tree/updates) (Avalonia 0.10.0) theme changing is broken.

**Expected behavior**

Theme changing at runtime worked perfectly on Avalonia 0.9.12, so I guess it should work on Avalonia 0.10.0? Or, probably there is a workaround that could help prevent the style resetting after doing `_window.Styles[0] = new StyleInclude`? Currently using [this class](https://github.com/worldbeater/Camelotia/blob/updates/src/Camelotia.Presentation.Avalonia/Services/AvaloniaStyleManager.cs#L36) and `avares` for theme loading. Possibly related https://github.com/AvaloniaUI/Avalonia/issues/5509

**Desktop (please complete the following information):**

- OS: Ubuntu KDE
- Version 18.04 LTS

**Comment by kekekeks** [comment]
@grokys

**Comment by worldbeater** [comment]
Hmm, if I click the "Switch theme" button two fast (just a double-click via a mouse), the software just crashes.

`Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary2.get_Item(TKey key)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Dematerialize(Int32 startingIndex, Int32 count) in /_/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs:line 69
   at Avalonia.Controls.Presenters.CarouselPresenter.MoveToPage(Int32 fromIndex, Int32 toIndex) in /_/src/Avalonia.Controls/Presenters/CarouselPresenter.cs:line 201
   at Avalonia.Controls.Presenters.CarouselPresenter.SelectedIndexChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/Presenters/CarouselPresenter.cs:line 256
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 108
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at Camelotia.Presentation.Avalonia.Program.Main(String[] args) in C:\Users\prizr\Documents\GitHub\Camelotia\src\Camelotia.Presentation.Avalonia\Program.cs:line 8`

According to the stack trace, the issue is definitely not on the Camelotia side.

**Comment by worldbeater** [comment]
The `KeyNotFoundException` error seems to be coming from this line:
https://github.com/AvaloniaUI/Avalonia/blob/554aaec5e5cc96c0b4318b6ed1fbf8159f442889/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs#L71
If I remove the `<Carousel />` control and replace it with a `<TransitioningContentControl />`, the error goes away.

Also, without the `<Carousel />` control theme changing works perfectly! ✨

**Comment by Shidesu** [comment]
@worldbeater as I have a similar issue with Carousel crashing I would like to ask you if you had a PageTransition set in your Carousel.
From what I tested, it might be the root of the problem.

**Comment by worldbeater** [comment]
@Shidesu yeah there is a page transition inside the carousel control in the related repro https://github.com/worldbeater/Camelotia/blob/updates/src/Camelotia.Presentation.Avalonia/Views/MainView.xaml#L129
So probably the crash might be caused by some kind of a delay or a concurrent update.

**Comment by Shidesu** [comment]
Yeah that's what I think.
I removed my PageSlide transition and can't make it crash now. 
I suppose this should also fix it for you.

**Comment by worldbeater** [comment]
Ideally we should somehow debug and fix this on Avalonia side. The issue seems to arise due to a missing key in the dict https://github.com/AvaloniaUI/Avalonia/blob/554aaec5e5cc96c0b4318b6ed1fbf8159f442889/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs#L65-L78

**Comment by Takoooooo** [comment]
Seem to be fixed in 11.0,used this repro. In 0.10.18 i get the exception and visully controls look broken,but can't repro in 11.0
Thats the repro i was using.
[AvaloniaApplication33.zip](https://github.com/AvaloniaUI/Avalonia/files/10203133/AvaloniaApplication33.zip)
