### ISSUE TITLE
Exception thrown: 'System.IndexOutOfRangeException' in Avalonia.Interactivity.dll

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#565]
To reproduce the issue run `Core2D`.
* File -> New
* In `Styles` tab add styles using `+` button so scrollbar is visible
* Selected last item in the list
* Add one more style using `+` button
* Scroll using mouse wheel
* Exception is thrown

Also you can notice strange resizing of scrollbar itself (it shrinking and enlarging while adding new items to `ListBox`).

```
Exception thrown: 'System.IndexOutOfRangeException' in Avalonia.Interactivity.dll
Core2D.Avalonia.Direct2D.vshost.exe Error: 0 : Indeks wykraczał poza granice tablicy.
   w System.Collections.Immutable.ImmutableArray`1.System.Collections.IList.get_Item(Int32 index)
   w Avalonia.Controls.Utils.IEnumerableUtils.ElementAt(IEnumerable items, Int32 index)
   w Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta)
   w Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value)
   w Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value)
   w Avalonia.Controls.Presenters.ItemsPresenter.Avalonia.Controls.Primitives.IScrollable.set_Offset(Vector value)
   w Avalonia.Controls.Presenters.ScrollContentPresenter.<>c__DisplayClass28_0.<UpdateScrollableSubscription>b__1(Vector x)
   w System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   w System.Reactive.Linq.ObservableImpl.Skip`1._.OnNext(TSource value)
   w System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   w System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   w System.Reactive.ObserverBase`1.OnNext(T value)
   w Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass0_1.<GetObservable>b__1(Object s, AvaloniaPropertyChangedEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   w Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   w Avalonia.Controls.Presenters.ScrollContentPresenter.OnPointerWheelChanged(PointerWheelEventArgs e)
   w Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass1_0`1.<AddClassHandler>b__0(Object sender, RoutedEventArgs e)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   w System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   w System.Reactive.ObserverBase`1.OnNext(T value)
   w Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   w Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   w Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   w Avalonia.Input.MouseDevice.MouseWheel(IMouseDevice device, IInputRoot root, Point p, Vector delta, InputModifiers inputModifiers)
   w Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   w System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   w System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   w System.Reactive.Linq.ObservableImpl.OfType`2._.OnNext(TSource value)
   w System.Reactive.Observer`1.OnNext(T value)
   w Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   w Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   w Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   w Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   w Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   w Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   w Avalonia.Application.Run(ICloseable closable)
   w Core2D.Avalonia.App.Start(IFileSystem fileIO, ILog log, ImmutableArray`1 writers) w C:\DOWNLOADS\GitHub-Core2D\Core2D\src\Core2D.Avalonia\App.xaml.cs:wiersz 181
```

**Comment by donandren** [comment]
Same exception occasionally happening in Window close:

> An unhandled exception of type 'System.IndexOutOfRangeException' occurred in Avalonia.Controls.dll
> 
> Additional information: Could not recycle container: not materialized.


`
   at Avalonia.Controls.Generators.ItemContainerGenerator`1.TryRecycle(Int32 oldIndex, Int32 newIndex, Object item, IMemberSelector selector) in Avalonia\src\Avalonia.Controls\Generators\ItemContainerGenerator`1.cs:line 91
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta) in Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 356
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value) in Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 67
   at Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value) in Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizer.cs:line 109
   at Avalonia.Controls.Presenters.ItemsPresenter.Avalonia.Controls.Primitives.IScrollable.set_Offset(Vector value) in Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 62
   at Avalonia.Controls.Presenters.ScrollContentPresenter.<>c__DisplayClass28_0.<UpdateScrollableSubscription>b__1(Vector x) in Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 307
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Skip`1._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass0_1.<GetObservable>b__1(Object s, AvaloniaPropertyChangedEventArgs e) in Avalonia\src\Avalonia.Base\AvaloniaObjectExtensions.cs:line 40
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 631
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 663
   at Avalonia.Controls.Presenters.ScrollContentPresenter.set_Offset(Vector value) in Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 91
   at Avalonia.Controls.Presenters.ScrollContentPresenter.<>c.<.cctor>b__9_4(ScrollContentPresenter o, Vector v) in Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 34
   at Avalonia.DirectProperty`2.Avalonia.IDirectPropertyAccessor.SetValue(IAvaloniaObject instance, Object value) in Avalonia\src\Avalonia.Base\DirectProperty.cs:line 120
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 336
   at Avalonia.AvaloniaObject.DirectBindingSet(AvaloniaProperty property, Object value) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 729
   at Avalonia.AvaloniaObject.<>c__DisplayClass35_0.<Bind>b__4(Object x) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 433
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.SafeObserver`1.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.T.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Markup.Data.ExpressionNode.set_CurrentValue(WeakReference value) in Avalonia\src\Markup\Avalonia.Markup\Data\ExpressionNode.cs:line 76
   at Avalonia.Markup.Data.ExpressionNode.set_Target(WeakReference value) in Avalonia\src\Markup\Avalonia.Markup\Data\ExpressionNode.cs:line 49
   at Avalonia.Markup.Data.ExpressionObserver.<IncrementCount>b__27_0(Unit x) in Avalonia\src\Markup\Avalonia.Markup\Data\ExpressionObserver.cs:line 270
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Skip`1._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass0_1.<GetObservable>b__1(Object s, AvaloniaPropertyChangedEventArgs e) in Avalonia\src\Avalonia.Base\AvaloniaObjectExtensions.cs:line 40
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 631
   at Avalonia.AvaloniaObject.ParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 810
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 631
   at Avalonia.AvaloniaObject.Avalonia.IPriorityValueOwner.Changed(PriorityValue sender, Object oldValue, Object newValue) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 524
   at Avalonia.PriorityValue.UpdateValue(Object value, Int32 priority) in Avalonia\src\Avalonia.Base\PriorityValue.cs:line 264
   at Avalonia.PriorityValue.LevelValueChanged(PriorityLevel level) in Avalonia\src\Avalonia.Base\PriorityValue.cs:line 164
   at Avalonia.PriorityLevel.set_DirectValue(Object value) in Avalonia\src\Avalonia.Base\PriorityLevel.cs:line 76
   at Avalonia.PriorityValue.SetValue(Object value, Int32 priority) in Avalonia\src\Avalonia.Base\PriorityValue.cs:line 96
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 369
   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority) in Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 387
   at Avalonia.Controls.Control.set_TemplatedParent(ITemplatedControl value) in Avalonia\src\Avalonia.Controls\Control.cs:line 302
   at Avalonia.Controls.Control.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in Avalonia\src\Avalonia.Controls\Control.cs:line 732
   at Avalonia.Controls.Control.Avalonia....
`

**Comment by donandren** [comment]
A change in ItemVirtualizerSimple.cs like that is fixing the problem at my side:

`
--- a/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs
+++ b/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs
@@ -234,6 +234,8 @@ private void CreateAndRemoveContainers()
             var generator = Owner.ItemContainerGenerator;
             var panel = VirtualizingPanel;
 
+            if (panel.IsAttachedToLogicalTree == false) return;
+
             if (!panel.IsFull && Items != null)
             {
                 var memberSelector = Owner.MemberSelector;
@@ -339,6 +341,10 @@ private void RecycleContainersForMove(int delta)
         {
             var panel = VirtualizingPanel;
             var generator = Owner.ItemContainerGenerator;
+
+            if (!panel.IsAttachedToLogicalTree) return;
+
             var selector = Owner.MemberSelector;
             var sign = delta < 0 ? -1 : 1;
             var count = Math.Min(Math.Abs(delta), panel.Children.Count);
`
