### ISSUE TITLE
OpenFileDialog crashes on Windows when adding filters

### ISSUE THREAD

**Issue by vadd98** [AvaloniaUI/Avalonia#5705]
**Describe the bug**

I'm trying to open an OpenFileDialog on Windows but I get this exception when I add filetype filters:

```
System.ArgumentException: Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IFileDialog.SetFileTypes(UInt32 cFileTypes, COMDLG_FILTERSPEC[] rgFilterSpec)
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass1_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

If I remove the filters the Dialog opens without any problem.

This is my code:

```
            var fileDialog = new OpenFileDialog();
            fileDialog.AllowMultiple = true;
            var extensions = new FileDialogFilter();
            extensions.Extensions = new List<string>()
            {
                "aac"
            };
            fileDialog.Filters = new List<FileDialogFilter>(){extensions};
            
            string[] fileList = await fileDialog.ShowAsync(MyWindow);
```

I underline that the exact same code works flawlessly on Mac.

**To Reproduce**

1. Create a OpenFileDialog on Windows
2. Add filetype filters
3. Open the Dialog

**Expected behavior**
Being able to set filters to OpenFileDialog on Windows

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10 20H2]
- Version [0.10.0]

**Additional context**

**Comment by FoggyFinder** [comment]
Try to set `Name` property as well.
At least this code works fine for me

```fs
        let openFileDialog = OpenFileDialog(AllowMultiple=false)
        let filters'=
            filters
            |> Seq.map(fun (name, ext) ->
                FileDialogFilter(Name = name, Extensions = List([ext]))
            )
        openFileDialog.Filters <- List(filters')
```

**Comment by vadd98** [comment]
Thanks, adding the name Property solved the issue
