### ISSUE TITLE
Carousel KeyNotFoundException when changing Items source.

### ISSUE THREAD

**Issue by Shidesu** [AvaloniaUI/Avalonia#5731]
**Describe the bug**
Using the carousel control with an Items source that can change leads to a KeyNotFoundException when replacing the old source with one that has less items.

**To Reproduce**

1. Create a carousel control
2. Bind an items source to it
3. go to the third or fourth item
4. Change the items source to one that have less items
5. Crash

**Expected behavior**
The carousel should not crash the app with a KeyNotFoundException when the ItemsSource is replaced.

**Desktop :**

- OS: Windows 10
- Version 0.10.0

**Additional context**
I also tried to clear and fill an AvaloniaList instead of replacing it, it's also crashing.
Seems to be related to #1639 so i'm not sure to understand why it's happening as it should be fixed according to that PR.

**Comment by FoggyFinder** [comment]
Probably it is the same as #5530

**Comment by Shidesu** [comment]
That is definitely throwing the same error:
```Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '3' was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Dematerialize(Int32 startingIndex, Int32 count) in /_/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs:line 69
   at Avalonia.Controls.Presenters.CarouselPresenter.MoveToPage(Int32 fromIndex, Int32 toIndex) in /_/src/Avalonia.Controls/Presenters/CarouselPresenter.cs:line 201
   at Avalonia.Controls.Presenters.CarouselPresenter.SelectedIndexChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/Presenters/CarouselPresenter.cs:line 254
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
```

**Comment by Shidesu** [comment]
Okay I tested a bit more. It **looks like** it's not crashing without page transition.

**Comment by sumitgaurin** [comment]
Facing the same issue.
1. I have a user control having a Carousel
2. In MainWindow I have a TabControl in which i am dynamically adding tabs and loading an instance of the user control (based on click of a button)
3. The moment i add a new tab or close a tab or close application, i get the same error.
4. When i removed the "PageSlide" styling from the Carousel, everything is working fine

`<ScrollViewer Name="wizardScrollViewer" Grid.Row="1">
        <Border HorizontalAlignment="Stretch"
                            VerticalAlignment="Stretch">
          <Carousel Name="wizardCarousel" HorizontalAlignment="Stretch"
                            VerticalAlignment="Stretch" Items="{Binding StepItems}"
                    SelectedIndex="{Binding CurrentPage}" >
            
          </Carousel>
        </Border>
      </ScrollViewer>`
