### ISSUE TITLE
Avalonia crash on Linux

### ISSUE THREAD

**Issue by IngvarX** [AvaloniaUI/Avalonia#5837]
**Describe the bug**
Avalonia sometimes crashes on Linux with following stacktrace:
```
Unhandled application error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.TextBox.MoveVertical(Int32 count) in /_/src/Avalonia.Controls/TextBox.cs:line 1024
   at Avalonia.Controls.TextBox.OnKeyDown(KeyEventArgs e) in /_/src/Avalonia.Controls/TextBox.cs:line 727
   at Avalonia.Input.InputElement.<>c.<.cctor>b__30_2(InputElement x, KeyEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 202
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 229
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.X11.X11Window.<ScheduleInput>b__120_0() in /_/src/Avalonia.X11/X11Window.cs:line 718
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169                                        
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245                                          
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61                                             
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107                                                                     
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134                      
   at Camelot.Program.Main(String[] args) in /home/runner/work/Camelot/Camelot/src/Camelot/Program.cs:line 33                                                                         
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Controls.TextBox.MoveVertical(Int32 count) in /_/src/Avalonia.Controls/TextBox.cs:line 1024
   at Avalonia.Controls.TextBox.OnKeyDown(KeyEventArgs e) in /_/src/Avalonia.Controls/TextBox.cs:line 727
   at Avalonia.Input.InputElement.<>c.<.cctor>b__30_2(InputElement x, KeyEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 202
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 229
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.X11.X11Window.<ScheduleInput>b__120_0() in /_/src/Avalonia.X11/X11Window.cs:line 718
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at Camelot.Program.Main(String[] args) in /home/runner/work/Camelot/Camelot/src/Camelot/Program.cs:line 33
```

**To Reproduce**
1) Open avalonia app, go to datagrid
2) Focus another app (but don't close/hide avalonia app)
3) click on avalonia app top bar to focus it
4) click arrow and observe app crashed

**Expected behavior**
App doesn't crash

**Desktop (please complete the following information):**

- OS: Linux
- Version: 0.10.0 from Nuget

**Comment by kekekeks** [comment]
@Gillibald
