### ISSUE TITLE
Closing a windows with ESC crash the application on v0.10.0.2

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#5841]
**Describe the bug**
Closing a window using a button with the `IsCancel` attribute set and press ESC crash the application.
Clicking the close [X] or button don't crash the application, only when press ESC does.
Press ENTER to submit a window with `IsDefault` attribute set works as expected.
I'm with fluent theme

```XML
<Button 
            Padding="10"
            IsCancel="True"
            Command="{Binding Close}"
            HotKey="Escape">
            <StackPanel 
              Orientation="Horizontal"
              Spacing="10">
              <Image Source="/Assets/Icons/exit-16x16.png"/>
              <TextBlock Text="Cancel"/>
            </StackPanel>
          </Button>
```

**Stack**

```
(Fatal Non-UI Error) @ 04/27/2021 18:53:41: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 224
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 468
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 26
```

**Desktop (please complete the following information):**

- OS: Windows 10 v20H2
- Version: 0.10.0.2

**Comment by sn4k3** [comment]
I able to fix by remove the `HotKey="Escape"` from control and it works as expected now.
