### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by Toemsel** [AvaloniaUI/Avalonia#5850]
**Describe the bug**

While filling a collection with thousands of entries, the DataGrid causes an unhandled exception when re-assigning the collection to a new object.

**To Reproduce**

1. Bind a collection to the DataGrid
2. Fill the collection (as fast as possible) with entries
3. While filling the collection, re-assign the collection to a new instance and raise 'PropertyChanged'

ViewModel

```
            NetworkPackets = new ObservableCollection<NetworkPacket>(relevantPackets);
            this.RaisePropertyChanged(nameof(NetworkPackets));
```

View

`    <DataGrid Items="{Binding NetworkPackets, Mode=OneWay}" />`

**Edit: Problem does** ~~not~~ **occur less when executing on the UI thread:**
 
```
            Avalognia.UIThread....(() => 
            {
                     NetworkPackets = new ObservableCollection<NetworkPacket>(relevantPackets);
                     this.RaisePropertyChanged(nameof(NetworkPackets));
           }
```

**Expected behavior**
The DataGrid should display the collection's new data.

**Screenshots**
[![Avalognia-Bug.gif](https://i.postimg.cc/xTd8pMx9/Avalognia-Bug.gif)](https://postimg.cc/QVRjH9Zz)

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.2
- DataGrid: 0.10.2

**Additional context**
I tried not to assign a new object to the collection in first place. With the help of this [observablecollection](https://stackoverflow.com/a/45364074/2934290) one can add/remove a range of objects. But removing + adding more than one entry won't be reflected within the Grid. The DataGrid will (e.g.: after collection.Clear(); collection.AddRange()) only show one entry, even thought the collection has more than 1 entry. (I guess this would be another bug, similar to this [issue](https://github.com/AvaloniaUI/Avalonia/issues/3510))

Here might be issue located

https://github.com/AvaloniaUI/Avalonia/blob/ef39b9487897fe5a7ae9c4502f0e8ce05c8f4612/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs#L2683

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Avalonia.Collections.DataGridCollectionView.CopySourceToInternalList() in /_/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs:line 2683
   at Avalonia.Collections.DataGridCollectionView..ctor(IEnumerable source, Boolean isDataSorted, Boolean isDataInGroupOrder) in /_/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs:line 225
   at Avalonia.Collections.DataGridCollectionView..ctor(IEnumerable source) in /_/src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs:line 204
   at Avalonia.Controls.DataGridDataConnection.CreateView(IEnumerable source) in /_/src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs:line 466
   at Avalonia.Controls.DataGrid.OnItemsPropertyChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 811
   at Avalonia.Controls.DataGrid.<>c.<.cctor>b__223_0(DataGrid x, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 669
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 149
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 758
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
   at Avalonia.Controls.DataGrid.set_Items(IEnumerable value) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 622
   at Avalonia.Controls.DataGrid.<>c.<.cctor>b__223_29(DataGrid o, IEnumerable v) in /_/src/Avalonia.Controls.DataGrid/DataGrid.cs:line 614
   at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, BindingValue`1 value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 835
   at Avalonia.AvaloniaObject.DirectBindingSubscription`1.<>c__DisplayClass7_0.<OnNext>b__0() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 936
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 117
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at Dji.UI.Program.Main(String[] args) in C:\NAS\Personal\JKU\SS21\Master's Thesis\Software\Dji-Network\Dji.UI\Program.cs:line 13

**Comment by grokys** [comment]
It sounds like from your description, that you using `AddRange` from the `ObservableRangeCollection` class you linked to, is this correct?

If so, I suspect this is because the `DataGrid` was ported from the Silverlight Toolkit - WPF and Silverlight do _not_ work well with adding/removing more than one item from an `ObservableCollection` (in fact there was pushback on even adding those methods to `ObservableCollection` for .NET because WPF doesn't like it: https://github.com/dotnet/runtime/issues/18087)

**Comment by grokys** [comment]
Oh wait, you're saying that using `AddRange` was how you tried to work around the problem, and not the actual problem, right?

**Comment by Toemsel** [comment]
Sorry for the vague description in first place. I do use a custom (not the in the link provided ObservableRangeCollection, but similar) implementation for adding and removing bulk items. With that said, the DataGrid has its own characteristic and doesn't quite like adding or removing ranges.

1. Adding more than 1 item with .AddRange will sometimes result in no UI update at all. This especially happens if you try to add more than 10k items at once. There is a magic boundary while adding bulk items. More than X items won't result in an UI update
2. .Clear or .RemoveRange followed by a .AddRange will result in a completely strange behaviour. Most of the time the DataGrid end ups only showing one item.

With that said, when dealing with huge data updates (adding or removing more than 10k items) I ended up with re-defining the observablecollection and call notifyproperty changed. See my original post:

>       NetworkPackets = new ObservableCollection<NetworkPacket>(relevantPackets);
>             this.RaisePropertyChanged(nameof(NetworkPackets));

This does work (the DataGrid updates as it should, even thought with some side-effects like losing sorting) but sometimes Avalonia throws an exception. My personal guess is, that I do re-assign the (in my case NetworckPackets) collection in a timeframe whereas avalonia tries to build up its internal UI tree.

**Comment by maxkatz6** [comment]
Problem with AddRange was fixed, so it supposed to work properly without replacing whole collection which is suboptimal 
https://github.com/AvaloniaUI/Avalonia/pull/9135
