### ISSUE TITLE
libskiasharp.so is missing

### ISSUE THREAD

**Issue by dragonDScript** [AvaloniaUI/Avalonia#5862]
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 27
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 304
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 133
   at Fetchman.Program.Main(String[] args) in /mnt/sda1/Projects/Fetchman/Program.cs:line 13

Process finished with exit code 134.
[Minimal repro](https://github.com/dragonDScript/fetchman)
platform: Linux, Ubuntu, 20.04

**Comment by PieroCastillo** [comment]
trying reinstall dotnet sdk, for me that was enough

**Comment by dragonDScript** [comment]
> trying reinstall dotnet sdk, for me that was enough

Have you gotten it from Snap? That may be related.

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/5190#issuecomment-748724948

Also
https://github.com/AvaloniaUI/Avalonia/issues/3679

**Comment by kekekeks** [comment]
.NET SDK installed from Snap **is fundamentally incompatible** with running UI apps

**Comment by dragonDScript** [comment]
> .NET SDK installed from Snap **is fundamentally incompatible** with running UI apps

Alright, I will try to install from source and tell you if it worked.

**Comment by kekekeks** [comment]
Just follow [package manager instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux) for your distro

**Comment by dragonDScript** [comment]
Closing issue. I can't access my main computer right now, so if I have this problem again, I will open it up again.
