### ISSUE TITLE
ArgumentOutOfRangeException in ListBox with Right alignment and Horizontal items

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#589]
An exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll but was not handled in user code

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ReactiveUI.ReactiveList`1.get_Item(Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.ReactiveUI\src\ReactiveUI\ReactiveList.cs:line 775
   at ReactiveUI.ReactiveList`1.System.Collections.IList.get_Item(Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.ReactiveUI\src\ReactiveUI\ReactiveList.cs:line 809
   at Avalonia.Controls.Utils.IEnumerableUtils.ElementAt(IEnumerable items, Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Utils\IEnumerableUtils.cs:line 75
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.CreateAndRemoveContainers() in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 274
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.UpdateControls() in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 100
   at Avalonia.Controls.VirtualizingStackPanel.MeasureOverride(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\VirtualizingStackPanel.cs:line 69
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 456
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 313
   at Avalonia.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 110
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 456
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 313
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ScrollContentPresenter.cs:line 191
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 456
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 313
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Grid.cs:line 424
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 456
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\Layoutable.cs:line 313
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 141
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 112
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in C:\Development\Perspex\Avalonia\src\Avalonia.Layout\LayoutManager.cs:line 73
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 480
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ScrollIntoView(Object item) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 236
   at Avalonia.Controls.Presenters.ItemsPresenter.ScrollIntoView(Object item) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 91
   at Avalonia.Controls.Primitives.SelectingItemsControl.ScrollIntoView(Object item) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 287
   at Avalonia.Controls.Primitives.SelectingItemsControl.SelectedItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\Development\Perspex\Avalonia\src\Avalonia.Controls\Primitives\SelectingItemsControl.cs:line 735
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index) in C:\Development\Perspex\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 504
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in C:\Development\Perspex\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 191
   at VirtualizationTest.ViewModels.MainWindowViewModel.Recreate() in C:\Development\Perspex\Avalonia\samples\VirtualizationTest\ViewModels\MainWindowViewModel.cs:line 133
   at VirtualizationTest.ViewModels.MainWindowViewModel.<.ctor>b__7_0(Object _) in C:\Development\Perspex\Avalonia\samples\VirtualizationTest\ViewModels\MainWindowViewModel.cs:line 27
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnNext(TSource value)

**Comment by donandren** [comment]
Issue can be reacreated from https://github.com/donandren/Avalonia/tree/issue589

- Start VitualizationTest app
- Press Recreate
- Press Remove Item
- Press Recreate
- Exception ArgumentOutOfRangeException  will be raised
