### ISSUE TITLE
Call from invalid thread

### ISSUE THREAD

**Issue by omerhijazi404** [AvaloniaUI/Avalonia#6004]
**Describe the bug**
In my code I am doing this, in an async void called Connect, which is the function to be called for a button:

```csharp
this.FindControl<ImageControl>("Screen").Source = new Bitmap("screen.png");
```

But it gives me an error:

```csharp
System.InvalidOperationException
  HResult=0x80131509
  Message=Call from invalid thread
  Source=Avalonia.Base
  StackTrace:
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.GetValue[T](StyledPropertyBase`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 252
   at Avalonia.Controls.NameScope.GetNameScope(StyledElement styled) in /_/src/Avalonia.Styling/Controls/NameScope.cs:line 37
   at Avalonia.Controls.NameScopeExtensions.<>c.<FindNameScope>b__4_0(StyledElement x) in /_/src/Avalonia.Styling/Controls/NameScopeExtensions.cs:line 114
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Avalonia.Controls.NameScopeExtensions.FindNameScope(ILogical control) in /_/src/Avalonia.Styling/Controls/NameScopeExtensions.cs:line 116
   at Avalonia.Controls.ControlExtensions.FindControl[T](IControl control, String name) in /_/src/Avalonia.Controls/ControlExtensions.cs:line 59
   at ScreenShareClient.MainWindow.<Connect>b__2_1(SocketIOResponse data) in C:\Users\HP\Desktop\Socket.IO Screen Share\Client\MainWindow.axaml.cs:line 46
   at SocketIOClient.Packgers.MessageEventPackger.Unpack(SocketIO client, String text)
   at SocketIOClient.Packgers.MessagePackger.Unpack(SocketIO client, String text)
   at SocketIOClient.Packgers.PackgeManager.Unpack(String msg)
   at SocketIOClient.WebSocketClient.ClientWebSocket.<ListenAsync>d__16.MoveNext()
```

**Expected behavior**
For the image source to change

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.4

**Comment by omerhijazi404** [comment]
^Please help anyone

**Comment by Gillibald** [comment]
You need to wrap your code inside `Dispatcher.UIThread.InvokeAsync` Your socket is most likely calling into your method from a different thread.

**Comment by omerhijazi404** [comment]
ok @Gillibald this is my function with your suggestion:
```csharp
async void Connect() {
    try {
      string url = this.FindControl < TextBox > ("URL").Text;

      await Dispatcher.UIThread.InvokeAsync(async () => {
        var client = new SocketIO(url, new SocketIOOptions() {
          ConnectionTimeout = new TimeSpan(0, 0, 10), AllowedRetryFirstConnection = true, Reconnection = true, EIO = 4
        });

        // Event Handling
        client.OnConnected += async (sender, e) => {
          await client.EmitAsync("hello", "Client connected");
        };

        client.On("screen", data => {
          LoadBase64(data.GetValue < string > ()).Save("screen.png");
```
```csharp
          this.FindControl < ImageControl > ("Screen").Source = new Bitmap("screen.png");
```
```csharp
        });

        await client.ConnectAsync();
      });
    } catch (Exception ex) {
      var window = new Window {
        Width = 400, Height = 200, Background = new SolidColorBrush(new Color(255, 37, 37, 38))
      };
      window.Content = new TextBlock {
        Text = "An exception occured: " + ex.Message, FontFamily = "Cascadia Code, Segoe UI, Tahoma", Foreground = new SolidColorBrush(new Color(255, 241, 241, 241)), VerticalAlignment = VerticalAlignment.Center, HorizontalAlignment = HorizontalAlignment.Center
      };
      window.WindowStartupLocation = WindowStartupLocation.CenterOwner;
      await window.ShowDialog((Window) VisualRoot);
    }
```
But i still get the same error at the separate line above.

**Comment by Gillibald** [comment]
`client.On` isn't executed on the UIThread thats the place where you want to use the dispatcher

**Comment by omerhijazi404** [comment]
@Gillibald ohhh ok
so normal code but at that line:
```csharp
Dispatcher.UIThread.InvokeAsync(async () => {
     this.FindControl < ImageControl > ("Screen").Source = new Bitmap("screen.png");
})
```

**Comment by omerhijazi404** [comment]
Thank you it works
