### ISSUE TITLE
KeyNotFoundException in TreeContainerIndex.cs:line 76

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#604]
Occurs sometime when development tools are open controls in logical tree are expanded and usually when closing the window that devtolls are attached.
line of the exception:
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Generators/TreeContainerIndex.cs#L59

Exception details:

An exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll but was not handled in user code

Additional information: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Avalonia.Controls.Generators.TreeContainerIndex.Remove(IEnumerable`1 containers) in C:\Development\SynergyBaseballGit\External\Avalonia\src\Avalonia.Controls\Generators\TreeContainerIndex.cs:line 76
   at Avalonia.Controls.Generators.TreeItemContainerGenerator`1.RemoveRange(Int32 startingIndex, Int32 count) in C:\Development\SynergyBaseballGit\External\Avalonia\src\Avalonia.Controls\Generators\TreeItemContainerGenerator.cs:line 117
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e) in C:\Development\SynergyBaseballGit\External\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerNone.cs:line 79
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e) in C:\Development\SynergyBaseballGit\External\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 134
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\Development\SynergyBaseballGit\External\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 257

**Comment by danwalmsley** [comment]
I also get this quite a lot in treeview. Any clues on an exact repro?

**Comment by donandren** [comment]
no idea how to make stable repro, only from time to time

**Comment by danwalmsley** [comment]
I get it quite often when I remove items from TreeView.

**Comment by danwalmsley** [comment]
Ok guys solid repro coming up!!!

**Comment by danwalmsley** [comment]
Steps to reproduce:

1) Clone Avalon studio at this commit: https://github.com/VitalElement/AvalonStudio/commit/ad60123a16d247a22d74e0e8e72e2e96f0bc06f4

2) Clean and build the entire solution.

3) Replace the nugget assemblies with Avalonia assemblies built on your machine.

4) Compile and Run.

5) Open STM32SampleProject from the base dir where you cloned to.
![image](https://cloud.githubusercontent.com/assets/4672627/17105340/ba3384c0-527e-11e6-92b3-4e23b101e1a8.png)

6) Click File -> New Solution and select C++ Console Application.

7) Click OK

8) From the solution explorer, right click on ConsoleApplication1 and select remove.
![image](https://cloud.githubusercontent.com/assets/4672627/17105380/e81a3f32-527e-11e6-8a41-211b5fdbf1f8.png)

9) Click File -> Close Solution
Hopefully you will see this!
![image](https://cloud.githubusercontent.com/assets/4672627/17105397/fb244ff0-527e-11e6-9edd-9c62031b55e5.png)
