### ISSUE TITLE
ArgumentOutOfRangeException in AutocompleteBox on SelectItem if ItemsSource was dynamically changed

### ISSUE THREAD

**Issue by sentaniel** [AvaloniaUI/Avalonia#6128]
**Describe the bug**
Hello.
So I have this simpe XAML:
 
` <AutoCompleteBox Width="300" Margin="4" Text="{Binding SearchText}"  
                         Items="{Binding FoundItems}" SelectedItem="{Binding SelectedItem}" FilterMode="ContainsOrdinal"/>`

and ViewModel:

`        
        public ObservableCollection<TModel> FoundItems
        {
            get => _foundItems;
            private set => this.RaiseAndSetIfChanged(ref _foundItems, value);
        }

        public string SearchText
        {
            get => _searchText;
            set
            {
                this.RaiseAndSetIfChanged(ref _searchText, value);
                SearchCommand();
            }
        }
        
        public async Task SearchCommand()
        {
            IList<TModel> items;
            if(string.IsNullOrEmpty(_searchText))
                items = await _repository.FetchAsync<TModel>();
            else
                items = await _repository.FetchAsync<TModel>(x=>x.Name.ToLower().Contains(_searchText.ToLower()));

            FoundItems.Clear();
            FoundItems.AddRange(items);
        }`

So all works fine until I try to change ItemSource. If the commented call of SearchCommand and preload some data on the Initialization of ViewModel all works. If I changed ItemSource in my case bounded to this property FoundItems. I have got ArgumentOutOfRangeException.

See the stack trace:

`
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 150
   at Avalonia.Collections.AvaloniaList`1.System.Collections.IList.get_Item(Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 183
   at Avalonia.Controls.ItemsSourceView`1.GetAt(Int32 index) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 219
   at Avalonia.Controls.ItemsSourceView`1.get_Item(Int32 index) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 210
   at Avalonia.Controls.Selection.SelectedItems`1.GetEnumerator()+MoveNext() in /_/src/Avalonia.Controls/Selection/SelectedItems.cs:line 89
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnSelectionModelSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e) in /_/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 766
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(Operation operation, Boolean raisePropertyChanged) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 706
   at Avalonia.Controls.Selection.SelectionModel`1.EndBatchUpdate() in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 214
   at Avalonia.Controls.Selection.SelectionModel`1.BatchUpdateOperation.Dispose() in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 764
   at Avalonia.Controls.Selection.SelectionModel`1.set_SelectedIndex(Int32 value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 76
   at Avalonia.Controls.Selection.SelectionModel`1.Avalonia.Controls.Selection.ISelectionModel.set_SelectedItem(Object value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 170
   at Avalonia.Controls.Primitives.SelectingItemsControl.set_SelectedItem(Object value) in /_/src/Avalonia.Controls/Primitives/SelectingItemsControl.cs:line 195
   at Avalonia.Controls.Utils.SelectingItemsControlSelectionAdapter.set_SelectedItem(Object value) in /_/src/Avalonia.Controls/Utils/SelectingItemsControlSelectionAdapter.cs:line 124
   at Avalonia.Controls.AutoCompleteBox.CloseDropDown() in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 1863
   at Avalonia.Controls.AutoCompleteBox.ClosingDropDown(Boolean oldValue) in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 1707
   at Avalonia.Controls.AutoCompleteBox.OnIsDropDownOpenChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 707
   at Avalonia.Controls.AutoCompleteBox.<>c.<.cctor>b__67_1(AutoCompleteBox x, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 846
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass23_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 583
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.AvaloniaProperty`1.NotifyChanged(AvaloniaPropertyChangedEventArgs`1 e) in /_/src/Avalonia.Base/AvaloniaProperty`1.cs:line 80
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 762
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 674
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 704
   at Avalonia.Controls.AutoCompleteBox.set_IsDropDownOpen(Boolean value) in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 966
   at Avalonia.Controls.AutoCompleteBox.OnAdapterSelectionComplete(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Controls/AutoCompleteBox.cs:line 2463
   at Avalonia.Controls.Utils.SelectingItemsControlSelectionAdapter.OnCommit(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Controls/Utils/SelectingItemsControlSelectionAdapter.cs:line 298
   at Avalonia.Controls.Utils.SelectingItemsControlSelectionAdapter.OnCommit() in /_/src/Avalonia.Controls/Utils/SelectingItemsControlSelectionAdapter.cs:line 288
   at Avalonia.Controls.Utils.SelectingItemsControlSelectionAdapter.OnSelectorPointerReleased(Object sender, PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Utils/SelectingItemsControlSelectionAdapter.cs:line 183
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 306
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 173
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 86
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 476
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 470
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.PopupImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/PopupImpl.cs:line 110
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at BrokenArrow.UnitSpecificationsEditor.Program.Main(String[] args) in P:\Projects\BrokenArrow\Tools\source\BrokenArrow.UnitSpecificationsEditor\BrokenArrow.UnitSpecificationsEditor\Program.cs:line 11
`

**Expected behavior**
No exception occurs.

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.6

**Comment by maxkatz6** [comment]
While it is a bug indeed, I believe there is already defined property AsyncPopulator, which you can use to populate list on text changed. You need to assign value of type ```Func<string, CancellationToken, Task<IEnumerable<object>>>``` to it

**Comment by berkansasmaz** [comment]
Is there any progress on this issue, we have encountered a similar problem.

Here is the stack trace:

```csharp
[FTL] Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.System.Collections.IList.get_Item(Int32 index)
   at Avalonia.Controls.ItemsSourceView`1.GetAt(Int32 index) in /_/src/Avalonia.Controls/ItemsSourceView.cs:line 239
   at Avalonia.Controls.Selection.SelectedItems`1.GetEnumerator()+MoveNext() in /_/src/Avalonia.Controls/Selection/SelectedItems.cs:line 92
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e) in /_/src/Avalonia.Controls/Selection/InternalSelectionModel.cs:line 204
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(Operation operation, Boolean raisePropertyChanged) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 739
   at Avalonia.Controls.Selection.SelectionModel`1.BatchUpdateOperation.Dispose() in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 762
   at Avalonia.Controls.Selection.SelectionModel`1.set_SelectedIndex(Int32 value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 74
   at Avalonia.Controls.Selection.SelectionModel`1.set_SelectedItem(T value) in /_/src/Avalonia.Controls/Selection/SelectionModel.cs:line 98
   at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, BindingValue`1 value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 839
   at Avalonia.AvaloniaObject.DirectBindingSubscription`1.<>c__DisplayClass7_0.<OnNext>b__0() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 959
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 276
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at MyProjectName.UI.Program.Main(String[] args) in D:\Github\MyProjectName\src\MyProjectName.UI.Host\Program.cs:line 80
```

**Comment by stepangovorko** [comment]
the problem also occurs on 11.0.5 (but there is no stable repro)
https://youtrack.jetbrains.com/issue/DTRC-30252

**Comment by DamirLisak** [comment]
This issue is still reproducible on current versions (the code in SelectedItems.cs is unchanged since it was reported). We hit the exact same crash in a production application: an AutoCompleteBox whose ItemsSource is filtered/replaced while the drop-down still holds a selection raises ArgumentOutOfRangeException from SelectedItems<T> because the selection ranges reference indices that no longer exist in the (cleared/shrunk) source collection.

Stack trace (essentially identical to the original report):

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index)
   at Avalonia.Controls.ItemsSourceView`1.get_Item(Int32 index)
   at Avalonia.Controls.Selection.SelectedItems`1.GetEnumerator()+MoveNext()
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSelectionChanged(...)
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(...)
```


Root cause: SelectedItems<T> (src/Avalonia.Controls/Selection/SelectedItems.cs) indexes into Items using the stored IndexRanges without validating that the indices are still valid. When the source collection is cleared or shrunk between the selection being made and the SelectionChanged event being raised, Items[index] throws.

Suggested fix — guard both accessors against stale indices:

```csharp
public override T? this[int index]
{
    get
    {
        if (index >= Count)
        {
            throw new IndexOutOfRangeException("The index was out of range.");
        }

        if (_owner?.SingleSelect == true)
        {
            return _owner.SelectedItem;
        }
        else if (Items is not null && Ranges is not null)
        {
            var itemIndex = IndexRange.GetAt(Ranges, index);

            // The source collection may have shrunk or been cleared since the
            // selection ranges were computed (e.g. AutoCompleteBox clearing its
            // filtered view while the drop-down still has a selection). Don't
            // throw in that case - return the default value instead.
            if (itemIndex < 0 || itemIndex >= Items.Count)
            {
                return default;
            }

            return Items[itemIndex];
        }
        else
        {
            return default;
        }
    }
}
```

```csharp
public override IEnumerator<T?> GetEnumerator()
{
    if (_owner?.SingleSelect == true)
    {
        if (_owner.SelectedIndex >= 0)
        {
            yield return _owner.SelectedItem;
        }
    }
    else
    {
        var items = Items;

        foreach (var range in Ranges!)
        {
            for (var i = range.Begin; i <= range.End; ++i)
            {
                // Skip indices that no longer exist in the source collection
                // (it may have been cleared or shrunk after the selection was
                // made - see this[int] above).
                if (items is object)
                {
                    if (i >= 0 && i < items.Count)
                    {
                        yield return items[i];
                    }
                }
                else
                {
                    yield return default;
                }
            }
        }
    }
}
```

We have applied exactly this change in a local fork and the crash is gone, with no observable behavioral regressions — the deselection event simply reports fewer/no items, which is the correct semantic when the underlying items no longer exist.

Could the maintainers please consider fixing this? The issue has been open since 2021 and it crashes applications in a fairly common scenario (dynamically filtered AutoCompleteBox / ListBox sources). We'd be happy to submit a PR with this change plus a regression test if that helps.
