### ISSUE TITLE
ArgumentException: An item with the same key has already been added. in ItemContainerGenerator

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#615]
System.ArgumentException : An item with the same key has already been added.
at
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Generators/ItemContainerGenerator.cs#L125

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Avalonia.Controls.Generators.ItemContainerGenerator.RemoveRange(Int32 startingIndex, Int32 count) in Avalonia\src\Avalonia.Controls\Generators\ItemContainerGenerator.cs:line 125
   at Avalonia.Controls.Presenters.ItemVirtualizerNone.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e) in Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerNone.cs:line 79
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e) in Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 134
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 257

**Comment by grokys** [comment]
Could you give information on what you were doing to get this exception? The stack track doesn't really tell me anything about what exactly happened.

Closing in the meantime, please reopen when you have a repro.
