### ISSUE TITLE
ListBox in StackPanel has wrong size

### ISSUE THREAD

**Issue by hlewin** [AvaloniaUI/Avalonia#6356]
When putting a ListBox into a StackPanel, the ListBox does not honor the vertical size restriction.
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TopologyEditor.MainWindow"
        Title="MainWindow">
    <StackPanel VerticalAlignment="Stretch">
        <ListBox HorizontalAlignment="Left"
                 ScrollViewer.VerticalScrollBarVisibility="Visible" Items="{Binding Items}">
            <ListBox.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Name}" />
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
    </StackPanel>
</Window>
```

In the example above the bottom part of the vertical scrollbar lies outside the window. I tried numerous VerticalAlignments and/or Components - I cannot manage to put a ListBox below any dynamically sized element.

This example produces an exception:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TopologyEditor.MainWindow"
        Title="MainWindow">
    <StackPanel VerticalAlignment="Stretch">
        <RelativePanel VerticalAlignment="Stretch">
            <ListBox RelativePanel.AlignBottomWithPanel="True" VerticalAlignment="Stretch" HorizontalAlignment="Left"
                     ScrollViewer.VerticalScrollBarVisibility="Visible" Items="{Binding Items}">
                <ListBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock Text="{Binding Name}" />
                    </DataTemplate>
                </ListBox.ItemTemplate>
            </ListBox>
        </RelativePanel>
    </StackPanel>
</Window>

Unhandled exception. System.InvalidOperationException: Invalid size returned for Measure.
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 373
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/StackPanel.cs:line 207
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 362
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 133
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Window.cs:line 859
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /_/src/Avalonia.Controls/WindowBase.cs:line 246
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 287
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 174
   at Avalonia.Controls.Window.ShowCore(Window parent) in /_/src/Avalonia.Controls/Window.cs:line 660
   at Avalonia.Controls.Window.Show() in /_/src/Avalonia.Controls/Window.cs:line 611
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 115
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
```

Avolonia 0.10.6

**Comment by maxkatz6** [comment]
> In the example above the bottom part of the vertical scrollbar lies outside the window.

Expected. Stack Panel does not constraints child size, but allows to take as much space as it needs. Otherwise it wouldn't be possible to "stack" elements after each other. Depending on your task you might need Grid or UniformGrid or DockPanel or else.
Or you can remove scroll bar from ListBox by disabling it, and put ScrollViewer as parent of your StackPanel. It will work, but it will disable virtualization (if you have a lot of items there).


About second example, having ListBox inside of RelativePanel inside of StackPanel does not sounds as expected scenario... But exception also isn't something that I might expect there.

**Comment by hlewin** [comment]
Actually I tried a lot of combinations - even with RelativePanel the bottom part of the scrollbar is cut
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignWidth="800" d:DesignHeight="450"
        x:Class="TopologyEditor.MainWindow"
        Title="MainWindow">

    <RelativePanel VerticalAlignment="Stretch">
        <TextBlock x:Name="test" Text="Test" />
        <ListBox RelativePanel.Below="test" RelativePanel.AlignBottomWithPanel="True"
                 ScrollViewer.VerticalScrollBarVisibility="Visible" Items="{Binding Items}">
            <ListBox.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Name}" />
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
    </RelativePanel>
</Window>
```

**Comment by maxkatz6** [comment]
I am not sure how exactly it should work with RelativePanel, but I expect it to be similar to StackPanel in this scenario.
Have you tried more common (for this scenario) Grid or DockPanel?
```xaml
    <DockPanel VerticalAlignment="Stretch">
        <TextBlock DockPanel.Dock="Top" x:Name="test" Text="Test" />
        <ListBox ScrollViewer.VerticalScrollBarVisibility="Visible" Items="{Binding Items}">
            <ListBox.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Name}" />
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>
    </DockPanel>
```

**Comment by hlewin** [comment]
Thank you. This seems to work good enough for the time being.
But there still is a measuring issue, it seems. There now is some additional whitespace at the bottom of the list content.
![Screenshot_2021-08-03_00-55-08](https://user-images.githubusercontent.com/25082820/127933714-0238b3b6-f57d-47d9-a7c7-7af3fada61d8.png)
When compared to only putting the listbox in the window:
![Screenshot_2021-08-03_00-59-57](https://user-images.githubusercontent.com/25082820/127933996-966cfdaf-c3f5-4016-bb3b-7a5fe45530c7.png)
The difference could well be the height of the "Test"-text.

**Comment by maxkatz6** [comment]
I believe this issue can be closed. And for flickering you already created another one - https://github.com/AvaloniaUI/Avalonia/issues/6360
