### ISSUE TITLE
Designer process throws "Collection was modified" in XamlXmlnsMappings.Resolve

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/Avalonia#6423]
On loading of certain projects, Avalonia Designer process throws an exception:
```
InvalidOperationException: Collection was modified; enumeration operation may not execute. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
 at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
 at System.Collections.Generic.List`1.Enumerator.MoveNext()
 at XamlX.Transform.XamlXmlnsMappings.Resolve(IXamlTypeSystem typeSystem, XamlLanguageTypeMappings typeMappings) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/XamlXmlnsMappings.cs:line 22
 at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.InitializeSre() in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 92
 at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 173
 at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 158
 at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 258
 at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) in /_/src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs:line 13
 at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) in /_/src/Avalonia.DesignerSupport/DesignWindowLoader.cs:line 33
 at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0() in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 233
```

### Steps to reproduce

1. Open [this solution](https://github.com/VMelnalksnis/AvaloniaRiderExceptionExample) in either Rider or Visual Studio with Avalonia plugin installed.
2. Open `Avalonia.NETCoreApp/Views/MainWindow.axaml` in the editor.
3. Observe the exception.

### Screenshots

![AvaloniaVS](https://user-images.githubusercontent.com/92793/129471415-a3118014-6ca5-4d3c-a778-8e6f061a64d1.png)
![AvaloniaRider](https://user-images.githubusercontent.com/92793/129471420-b36b463d-5250-4ece-81da-1b618788b8b6.png)

### Additional information

It is interesting that the project in question references an ASP.NET Core web application. The user who reported the issue also reports that

> if I change `CompileBindings` for that view to a different value, it previewer works without issues until next build/restart, even if I change `CompileBindings` back to the original value.

Also,

> The exception appears when referencing a ASP.NET Core project with `<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0"/>`.

**Desktop (please complete the following information):**

- **OS:** Windows
- **Avalonia version:** 0.10.6

**Comment by Takoooooo** [comment]
Should be fixed by https://github.com/kekekeks/XamlX/pull/46
May you verify?

**Comment by kekekeks** [comment]
@Takoooooo you need to actually update submodule reference in Avalonia repository via a separate PR.

**Comment by Takoooooo** [comment]
> @Takoooooo you need to actually update submodule reference in Avalonia repository via a separate PR.

done
