### ISSUE TITLE
Occasional Crash in Skia backend on Windows

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#689]
nhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Skia.WindowRenderTarget.CreateDrawingContext()
   at Avalonia.Rendering.RendererMixin.Render(IRenderTarget renderTarget, IVisual visual)
   at Avalonia.Controls.Platform.DefaultTopLevelRenderer.<>c__DisplayClass0_0.<Attach>b__2(Rect rect)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

**Comment by grokys** [comment]
Are you still encountering this?

**Comment by grokys** [comment]
Closing this as I assume the lack of response means no ;) Please re-open if you're still seeing this.
