### ISSUE TITLE
Crash when closing the application

### ISSUE THREAD

**Issue by scout719** [AvaloniaUI/Avalonia#7231]
**Describe the bug**
When the application's window is closed on MacOS, a LayoutPass is called that causes the application to crash since there is no longer an opened window.

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowBaseImpl.Resize(Size clientSize, PlatformResizeReason reason) in /_/src/Avalonia.Native/WindowImplBase.cs:line 326
   at Avalonia.Controls.Window.ArrangeSetBounds(Size size) in /_/src/Avalonia.Controls/Window.cs:line 934
   at Avalonia.Controls.WindowBase.ArrangeCore(Rect finalRect) in /_/src/Avalonia.Controls/WindowBase.cs:line 254
   at Avalonia.Layout.Layoutable.Arrange(Rect rect) in /_/src/Avalonia.Layout/Layoutable.cs:line 396
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.Arrange(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 298
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 264
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 234
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 135
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(IntPtr this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 3702
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at ServiceStudio.Hybrid.Program.Start(String[] args, Boolean showSplash)
   at ServiceStudio.Hybrid.Program.Main(String[] args)
```

**To Reproduce**
Unfortunately, these are reports from our users and I didn't manage to replicate it

**Expected behavior**
There should be no crash, ignoring any event after the window is closed.

**Desktop (please complete the following information):**

- OS: Mac 10.14 or newer
- Version 0.10.7-cibuild0015649-beta

**Additional context**
I found this issue that has a similar behavior and was fixed on Feb 2020: https://github.com/AvaloniaUI/Avalonia/issues/3544

**Comment by grokys** [comment]
Looks like the the job queue is pumped during window close, causing a layout to be run when the window is actually closed.
