### ISSUE TITLE
Regression from 0.10.10 to 0.10.11: Main window not rendered

### ISSUE THREAD

**Issue by fubar-coder** [AvaloniaUI/Avalonia#7262]
**Describe the bug**

I see a black main window:

![grafik](https://user-images.githubusercontent.com/4739844/147332924-c86c3a71-7439-47c4-afc0-796eba4ecf24.png)

**To Reproduce**

Prerequisite: Installed Avalonia templates (`dotnet new -i Avalonia.Templates`)

1. mkdir TestAvaloniaApp && cd TestAvaloniaApp
2. dotnet new avalonia.mvvm
3. Upgrade Avalonia packages from version `0.10.10` to `0.10.11`
   - With dotnet-oudated:
     - dotnet tool install -g dotnet-outdated-tool
     - dotnet outdated -u
   - Manually
     - Open the TestAvaloniaApp.csproj and change all references from version `0.10.10` to `0.10.11`
4. `dotnet run`
5. Window isn't rendered

**Expected behavior**

A rendered window showing the following:

![grafik](https://user-images.githubusercontent.com/4739844/147334155-c51854e1-bd45-4e94-8b54-4e59da5f5413.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 21.10, Wayland, NVidia
- Version 0.10.11

**Additional context**

It seems that it's a regression in `0.10.11`, because rendering works in `0.10.10`.

The debug output shows:

```log
[Visual] Exception in render loop: 'System.ArgumentException: Invalid create info - no Canvas provided (Parameter 'createInfo')
   at Avalonia.Skia.DrawingContextImpl..ctor(CreateInfo createInfo, IDisposable[] disposables) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 108
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in /_/src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs:line 40
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 617
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 374
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 323
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 275
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Visuals/Rendering/RenderLoop.cs:line 147' (RenderLoop #52307948)
```

**Comment by kekekeks** [comment]
@danwalmsley it looks like that Skia 2.88 is not that stable after all.

**Comment by kekekeks** [comment]
@fubar-coder which nvidia driver are you using?

**Comment by fubar-coder** [comment]
I'm using nvidia-driver-495

**Comment by kekekeks** [comment]
Unfortunately I can't repro with Xorg+Bumblebee-based setup. Setting up 21.10 with Wayland will take some time.

**Comment by fubar-coder** [comment]
@kekekeks It's not critical (yet), because 0.10.10 works well enough for my use case.

**Comment by ThadHouse** [comment]
I can reproduce this on Fedora 36. This still happens all the way on 0.10.18

**Comment by MTRNord** [comment]
I have the same issue on Fedora Silverblue/kinoite with a wayland session. See https://github.com/Revolutionary-Games/Thrive-Launcher/issues/180 :)

I am using the proprietary nvidia drivers here from the rpm fusion repos.

**Comment by timunie** [comment]
We have a PR for wayland support open. Probably you want to test it out and give some feedback if you find anything not working as expected. See #8352

**Comment by gacalves** [comment]
I was same problem in OpenSuse Tumbleweed 15.4, coincidentally I notice some glitchs on VS Code and Chrome.
Then I decided to install proprietary NVIDIA graphical driver folowing this tuto https://www.if-not-true-then-false.com/2022/opensuse-nvidia-guide, this **solved** the problem.
Avalonia: 0.10.14
OS: OpenSuse Tumbleweed 15.4 Gnome

I left this comment to help others in future.

**Comment by iMonZ** [comment]
> not

Hey,
any news here?
