### ISSUE TITLE
System.NullReferenceException at Window.Close() from Opened or Activated handler

### ISSUE THREAD

**Issue by Maikelsoft** [AvaloniaUI/Avalonia#7265]
When calling Close() from inside an event handler for Opened or Activated, an uncaught System.NullReferenceException occurs in the Main() function of the program.

**Expected behavior**
Window closes (and application terminates when using default shutdown mode).

**Steps to reproduce**
Create an Avalonia Application and change the code in MainWindow.cs as follows:

```csharp
  public class MainWindow : Window
  {
      public MainWindow()
      {
          Opened += OnOpened;
          // Uncomment the line above and comment the line above
          //Activated += OnActivated;
          InitializeComponent();
      }
  
      private void OnActivated(object? sender, EventArgs e)
      {
          Close(); // <= Causes an exception
      }
  
      private void OnOpened(object? sender, EventArgs e)
      {
          Close(); // <= Causes an exception
      }
  
      private void InitializeComponent()
      {
          AvaloniaXamlLoader.Load(this);
      }
  }
```

The exception occurs in Main():

```csharp
  [STAThread]
  public static void Main(string[] args) => BuildAvaloniaApp()
           .StartWithClassicDesktopLifetime(args); // <= Uncaught System.NullReferenceException
```
**Desktop**

- OS: Windows 10
- Version 0.10.10 and 0.10.11

**Additional context**
If you show a dialog window **before** calling Close(), the behavior is as expected:
```csharp
  public class MainWindow : Window
  {
      public MainWindow()
      {
          Opened += OnOpened;
          InitializeComponent();
      }
  
      private async void OnOpened(object? sender, EventArgs e)
      {
          Window dialogWindow = new VersionUpgradeWindow();
          await dialogWindow.ShowDialog(this);
          Close(); // <== No exception, window and application closes
      }
  
      private void InitializeComponent()
      {
          AvaloniaXamlLoader.Load(this);
      }
  }
```

**Comment by maxkatz6** [comment]
Stacktrace?

**Comment by Maikelsoft** [comment]
Oh yeah...the stack trace :-)

```
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 132
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 187
   at Maikelsoft.PhotoTool.AvaloniaUI.Program.Main(String[] args) in ************************\Program.cs:line 15
```
Exception source: Avalonia.Controls

**Comment by FG-rgb** [comment]
I got the same Problem, this is really annoying.

**Comment by workgroupengineering** [comment]
I think this is correct behavior, because you call close before the windows object is fully initialized.

To be sure that everything is initialized you have to call it in the following way:

```csharp
      public MainWindow()
      {       
          InitializeComponent();
          Dispatcher.UIThread.Post(()=>Close(),DispatcherPriority.Background);
      }
```

**Comment by FG-rgb** [comment]
Ok, my scenario is a bit different, and for me it is not clear what's the cause of the problem.
I only see a NullReferenceExcetion with a Stacktrace of Avalonia Source.

Therefore this kind of Exception is not helpful, and definately a bug.

**Comment by Maikelsoft** [comment]
> I think this is correct behavior, because you call close before the windows object is fully initialized.
> 
> To be sure that everything is initialized you have to call it in the following way:
> 
> ```cs
>       public MainWindow()
>       {       
>           InitializeComponent();
>           Dispatcher.UIThread.Post(()=>Close(),DispatcherPriority.Background);
>       }
> ```

Thanks for your help.
I don't agree that this is correct behavior because a method of the base class should not depend on the implementation of the inherited class in order to work as expected.

**Comment by Gillibald** [comment]
`OnActivated` and `OnOpened` should only be raised when the Window is initialized so this is a bug

**Comment by FG-rgb** [comment]
In my case  the bug occurs, too, when awaiting until window IsInitialized = true.
