### ISSUE TITLE
EntryPointNotFoundException: Unable to find an entry point named 'GetDpiForMonitor' in DLL 'shcore.dll'.

### ISSUE THREAD

**Issue by telikey** [AvaloniaUI/Avalonia#7284]
**Describe the bug**
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException: Unable to find an entry point named 'GetDpiForMonitor' in DLL 'shcore.dll'.
StackStrace: 
 at Avalonia.Win32.Interop.UnmanagedMethods.GetDpiForMonitor(IntPtr hmonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at Avalonia.Win32.WindowImpl.CreateWindow() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 773
   at Avalonia.Win32.WindowImpl..ctor() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 123
   at Avalonia.Win32.Win32Platform.CreateWindow() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 316
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 48
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 231
   at Avalonia.ReactiveUI.ReactiveWindow'1..ctor() in /_/src/Avalonia.ReactiveUI/ReactiveWindow.cs:line 26
   at Client_App.Views.MainWindow..ctor() in C:\Users\Admin\Desktop\RAO_Project\Client_App\Views\MainWindow.axaml.cs:line 34
   at Client_App.App.OnFrameworkInitializationCompleted() in C:\Users\Admin\Desktop\RAO_Project\Client_App\App.axaml.cs:line 19
   at Avalonia.Controls.AppBuilderBase'1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase'1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 174

**Desktop (please complete the following information):**
- OS: Windows 8
- Version 6.2.9200
- Build 9200

**Additional context**
Updated Avalonia 0.10.10 from 0.10.0

**Comment by Symbai** [comment]
`GetDpiForMonitor` requires Windows 8.1 or later. I couldn't find any system requirements for Avalonia but Windows 8(.0) is pretty much out of support anywhere. If you don't want to run into more issue you should consider upgrading.

**Comment by kekekeks** [comment]
CreateWindow does check the windows version to be >8.0:
https://github.com/AvaloniaUI/Avalonia/blob/28a2a2fc8eeacf5f68a7bb40526b76f3a407a2e9/src/Windows/Avalonia.Win32/WindowImpl.cs#L774
The same check is done in https://github.com/AvaloniaUI/Avalonia/blob/a77b8aa1f644c628dce2a277695937d710b2bd8d/src/Windows/Avalonia.Win32/FramebufferManager.cs#L90

ScreenImpl, however, checks using GetProcAddress: https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Windows/Avalonia.Win32/ScreenImpl.cs#L34

**Comment by stepangovorko** [comment]
There is an issue with this check `Win32Platform.WindowsVersion > PlatformConstants.Windows8` 
It returns true i.e. for Windows Server 2012, because Win32Platform.WindowsVersion=**6.2.9200**, but PlatformConstants.Windows8=**6.2.0**
