### ISSUE TITLE
TrimMode=link issue on Windows

### ISSUE THREAD

**Issue by amerkoleci** [AvaloniaUI/Avalonia#7293]
**Describe the bug**
Built-in COM has been disabled via a feature switch.

**To Reproduce**
- On Windows create new project using Avalonia MVVM template
- Switch to .net6.0 in csproj
- Run debug and you'll get:

System.NotSupportedException: 'Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.'

**Expected behavior**
Shoulw work without issues

**Stack Trace**
```
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Avalonia.Win32.Interop.UnmanagedMethods.RegisterDragDrop(IntPtr hwnd, IDropTarget target)
   at Avalonia.Win32.OleContext.RegisterDragDrop(IPlatformHandle hwnd, IDropTarget target) in /_/src/Windows/Avalonia.Win32/OleContext.cs:line 49
   at Avalonia.Win32.WindowImpl.CreateDropTarget() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 795
   at Avalonia.Win32.WindowImpl.SetInputRoot(IInputRoot inputRoot) in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 589
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 153
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 62
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl) in /_/src/Avalonia.Controls/WindowBase.cs:line 58
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 242
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 233
   at Alimer.Studio.Views.MainWindow..ctor() in C:\test\AlimerPrivate\src\Alimer.Studio\Views\MainWindow.axaml.cs:line 8
   at Alimer.Studio.App.OnFrameworkInitializationCompleted() in C:\test\AlimerPrivate\src\Alimer.Studio\App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 313
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 187
   at Alimer.Studio.Program.Main(String[] args) in C:\test\AlimerPrivate\src\Alimer.Studio\Program.cs:line 14
```

**Additional context**
Workaround by adding <BuiltInComInteropSupport>true</BuiltInComInteropSupport> in csproj, as described here: 
https://stackoverflow.com/questions/68110207/system-notsupportedexception-in-taskscheduler-when-using-publishtrimmed-net6-0

**Comment by kekekeks** [comment]
We are gradually switching to MicroCom. e. g. dialogs were migrated last month - https://github.com/AvaloniaUI/Avalonia/pull/7028

**Comment by amerkoleci** [comment]
> We are gradually switching to MicroCom. e. g. dialogs were migrated last month - #7028

Yes I saw that! I just opened issue to keep track :) thanks again.

**Comment by maxkatz6** [comment]
Dup of https://github.com/AvaloniaUI/Avalonia/issues/6892
