### ISSUE TITLE
DataGrid and app crash

### ISSUE THREAD

**Issue by dalekseev-monokot** [AvaloniaUI/Avalonia#7609]
**Describe the bug**
The application crashes in an unpredictable way and the bug does not reproduce and has occurred only a few times. Occurs if the view models presented in the data grid are periodically updated (approximately once per second) from a task unrelated to the GUI thread of the application. 

**To Reproduce**
I don't have clear instructions for reproducing the bug.

**Expected behavior**
The application should not crash.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 21H1
- Version 0.10.10

**Additional context**

Here is the stack trace:
```
at DynamicData.ChangeAwareList`1.Insert(Int32 index, T item) in
D:\a\DynamicData\DynamicData\src\DynamicData\List\ChangeAwareList.cs:line 295
at
DynamicData.Binding.ObservableCollectionEx.<>c__DisplayClass5_0`2.<ToObservableChangeSet>b__1(Chan
geAwareList`1 list, EventPattern`1 args) in
D:\a\DynamicData\DynamicData\src\DynamicData\Binding\ObservableCollectionEx.cs:line 197
at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in
/_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Scan.cs:line 49
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in
/_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
at System.Reactive.ExceptionHelpers.Throw(Exception exception) in
/_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in
/_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in
/_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
at System.Reactive.Sink`1.ForwardOnError(Exception error) in
/_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 61
at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in
/_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in
/_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 509
at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in
/_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in
/_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 261
at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in
/_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in
/_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]
args) in
/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
at
Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T
builder, String[] args, ShutdownMode shutdownMode) in
/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
at Monokot.Mos.Administrator.Program.Main(String[] args) in
C:\rep\MosSolution\Mos_AdminAvalonia\Program.cs:line 11
System.ArgumentException: "index cannot be greater than the size of the collection"
```

**Comment by Takoooooo** [comment]
Seems to be related to DynamicData but not Avalonia therefore closing.
