### ISSUE TITLE
Crash due to `Avalonia.Diagnostics` loading non-existance `Avalonia.Controls.DataGrid`

### ISSUE THREAD

**Issue by colejohnson66** [AvaloniaUI/Avalonia#7825]
**Describe the bug**
Building in debug mode is fine, but when built in release mode (where `Avalonia.Diagnostics` is not needed), we get a `FileNotFound` exception attempting to load the `Avalonia.Controls.DataGrid` assembly. I have not been able to deduce an MRE, but removing the `Condition` attribute in my `csproj` file allows me to run my program in Release mode.

**To Reproduce**
not yet found

**Expected behavior**
My program doesn't crash when building in release mode.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 and 11
- Version 0.10.13

**Exception:**

```
System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Controls/DataGrid, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.XamlTypeResolver.Resolve(String qualifiedTypeName) in /_/src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs:line 147
   at Avalonia.Markup.Xaml.Extensions.ResolveType(IServiceProvider ctx, String namespacePrefix, String type) in /_/src/Markup/Avalonia.Markup.Xaml/Extensions.cs:line 35
   at Avalonia.Markup.Parsers.ExpressionParser.ParseFindAncestor(AncestorNode node) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionParser.cs:line 95
   at Avalonia.Markup.Parsers.ExpressionParser.Parse(CharacterReader& r) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionParser.cs:line 57
   at Avalonia.Markup.Parsers.ExpressionObserverBuilder.Parse(String expression, Boolean enableValidation, Func`3 typeResolver, INameScope nameScope) in /_/src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionObserverBuilder.cs:line 21
   at Avalonia.Data.Binding.CreateExpressionObserver(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/Binding.cs:line 74
   at Avalonia.Data.BindingBase.Initiate(IAvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation) in /_/src/Markup/Avalonia.Markup/Data/BindingBase.cs:line 96
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 361
   at Avalonia.Animation.AnimatorKeyFrame.BindSetter(IAnimationSetter setter, Animatable targetControl) in /_/src/Avalonia.Animation/AnimatorKeyFrame.cs:line 58
   at Avalonia.Animation.Animation.InterpretKeyframes(Animatable control) in /_/src/Avalonia.Animation/Animation.cs:line 298
   at Avalonia.Animation.Animation.Apply(Animatable control, IClock clock, IObservable`1 match, Action onComplete) in /_/src/Avalonia.Animation/Animation.cs:line 326
   at Avalonia.Styling.StyleInstance..ctor(IStyle source, IStyleable target, IReadOnlyList`1 setters, IReadOnlyList`1 animations, IStyleActivator activator) in /_/src/Avalonia.Styling/Styling/StyleInstance.cs:line 54
   at Avalonia.Styling.Style.TryAttach(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Style.cs:line 106
   at Avalonia.Styling.Styles.TryAttach(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 122
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryAttach(IStyleable target, IStyleHost host) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 85
   at Avalonia.Styling.Styles.TryAttach(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 122
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryAttach(IStyleable target, IStyleHost host) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 85
   at Avalonia.Styling.Styles.TryAttach(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 122
   at Avalonia.Markup.Xaml.Styling.StyleInclude.TryAttach(IStyleable target, IStyleHost host) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 85
   at Avalonia.Styling.Styles.TryAttach(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 122
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 30
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target, IStyleHost host) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 25
   at Avalonia.Styling.Styler.ApplyStyles(IStyleable target) in /_/src/Avalonia.Styling/Styling/Styler.cs:line 15
   at Avalonia.StyledElement.ApplyStyling() in /_/src/Avalonia.Styling/StyledElement.cs:line 340
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 670
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 684
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 684
   at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 684
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Styling/StyledElement.cs:line 439
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate() in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 275
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 554
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/StackPanel.cs:line 207
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 291
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 277
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 277
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 277
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 277
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 251
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 233
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 135
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 258
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at MyProgram.Program.Main(String[] args) in C:\...\Program.cs:line 15
```

**Comment by colejohnson66** [comment]
This seems to be caused by building one DLL without the conditional (so it references the DataGrid) (caused by NuGet updater deleting it), and building an EXE referencing the *DLL* (not project), but without the conditional. The EXE will crash when loading the DataGrid

**Comment by timunie** [comment]
There is a separate package for DataGrid which you have to install via nuget. It is included in the diagnostic package, but as this is missing in release mode, the DataGrid is also. 

https://www.nuget.org/packages/Avalonia.Controls.DataGrid/

Happy coding
Tim

**Comment by maxkatz6** [comment]
If you use DataGrid or add style DataGrid in your project, you need to reference this control.
