### ISSUE TITLE
Frequent tab switching can crash the app

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#7922]
**Describe the bug**
Fastly switching between tabs can crash ControlCatalog.

**To Reproduce**

1. Build and run CC.NetCore
2. Switch among tabs fast and frequently (especially Text related tabs such as TextBox and TextBlock)
3. See the crash

```
Unhandled exception. Avalonia.AvaloniaInternalException: Visual is atached to visual tree but root could not be found.
   at Avalonia.Visual.SetVisualParent(Visual value) in D:\source\repos\Avalonia\src\Avalonia.Visuals\Visual.cs:line 602
   at Avalonia.Visual.SetVisualParent(IList children, Visual parent) in D:\source\repos\Avalonia\src\Avalonia.Visuals\Visual.cs:line 643
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in D:\source\repos\Avalonia\src\Avalonia.Base\Collections\AvaloniaList.cs:line 698
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content) in D:\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 321
   at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e) in D:\source\repos\Avalonia\src\Avalonia.Controls\Presenters\ContentPresenter.cs:line 492
   at Avalonia.Animation.Animatable.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in D:\source\repos\Avalonia\src\Avalonia.Animation\Animatable.cs:line 169
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in D:\source\repos\Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in D:\source\repos\Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 544
   at Avalonia.ValueStore.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in D:\source\repos\Avalonia\src\Avalonia.Base\ValueStore.cs:line 238
   at Avalonia.PropertyStore.BindingEntry`1.OnNext(BindingValue`1 value) in D:\source\repos\Avalonia\src\Avalonia.Base\PropertyStore\BindingEntry.cs:line 98
   at Avalonia.Reactive.BindingValueAdapter`1.OnNext(T value) in D:\source\repos\Avalonia\src\Avalonia.Base\Reactive\BindingValueAdapter.cs:line 16
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in D:\source\repos\Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 761
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in D:\source\repos\Avalonia\src\Avalonia.Base\AvaloniaObject.cs:line 703
   at Avalonia.Controls.TransitioningContentControl.set_CurrentContent(Object value) in D:\source\repos\Avalonia\src\Avalonia.Controls\TransitioningContentControl.cs:line 47
   at Avalonia.Controls.TransitioningContentControl.UpdateContentWithTransition(Object content) in D:\source\repos\Avalonia\src\Avalonia.Controls\TransitioningContentControl.cs:line 91
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in D:\source\repos\Avalonia\src\Avalonia.Base\Threading\AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\source\repos\Avalonia\src\Avalonia.Base\Threading\JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\source\repos\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\source\repos\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\source\repos\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in D:\source\repos\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 120
   at ControlCatalog.NetCore.Program.Main(String[] args) in D:\source\repos\Avalonia\samples\ControlCatalog.NetCore\Program.cs:line 100
```

**Expected behavior**
No crash happen.

**Desktop (please complete the following information):**

- OS: Windows 11 22581
- Version: master

**Comment by robloo** [comment]
I noticed this one too a while ago.

**Comment by grokys** [comment]
I notice a `TransitioningContentControl` in the call stack there - I suspect this control is the root of the problem? Looks to me like changing the content while a transition is under way is getting us into an invalid state.

**Comment by hez2010** [comment]
> I suspect this control is the root of the problem?

I think so. I've replied in that PR about getting a repro.
