### ISSUE TITLE
Android app crashes on startup when run without debugger

### ISSUE THREAD

**Issue by AzuxirenLeadGuy** [AvaloniaUI/Avalonia#8150]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/8133

<div type='discussions-op-text'>

<sup>Originally posted by **AzuxirenLeadGuy** May 15, 2022</sup>
I am building the `avalonia.xplat` application for android. When I run it on the `Debug` configuration in Visual Studio, It runs fine. However, if I close the debugging session and run the app again on the android emulator, it crashes on startup. Similarly, if I build and deploy it on the `Release` configuration, the app is deployed but it crashes on startup. 

EDIT: 

This video [shows](https://user-images.githubusercontent.com/40014666/168531872-2589e621-1da2-41d8-a843-da1ae0ac4890.mp4) what I see while I run it: 

Thanks to @timunie , The exception message is now known. It is as shown

```
System.InvalidOperationException: Invalid size returned for Measure.
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Embedding.EmbeddableControlRoot.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Controls.TopLevel.HandleResized(Size clientSize, PlatformResizeReason reason)
   at Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.OnResized(Size size)
   at Avalonia.Android.AvaloniaView.ViewImpl.OnResized(Size size)
   at Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl.ViewImpl.Android.Views.ISurfaceHolderCallback.SurfaceChanged(ISurfaceHolder holder, Format format, Int32 width, Int32 height)
   at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceChanged_Landroid_view_SurfaceHolder_III(IntPtr jnienv, IntPtr native__this, IntPtr native_holder, Int32 native_format, Int32 width, Int32 height)
```

Please let me know how to solve this. Thanks in advance.</div>

It goes without saying that the problem was present even when no modification was made to the program from the template. I had tried the android build on the pixel 5 emulator and also tested it on [waydroid](https://waydro.id/), but the issue persists.

**Comment by timunie** [comment]
@AzuxirenLeadGuy can you share the Avalonia version you use? Also as Android is under heavy development atm, please try to update to the latest preview package and double-check this issue again. 

Thank you.

**Comment by AzuxirenLeadGuy** [comment]
> @AzuxirenLeadGuy can you share the Avalonia version you use? 

I had not configured the `csproj` file after generating from the template. I have deleted that earlier project so I can't say for sure, but I suppose it should have been whatever version was latest about a week ago.

> Also as Android is under heavy development atm, please try to update to the latest preview package and double-check this issue again.

I created a new project from scratch, updated all the NuGet packages and now the application is working fine in debug configuration. I can close the debug session in Visual Studio and re-open the application and it is now working. 🤷‍♂️

However, the issue persists for the Release configuration.

I have modified the program to write the error message of all unhandled exceptions to be written to the file. The exception message is still the same as in the problem title.

The emulator I am working on is pixel 5 with API 25. I tried increasing the Target API in the android csproj file, but to no avail. 

The current version of Avalonia package is 0.10.999-cibuild0019213-beta. I can't update the packages to the current latest prerelease as the following error is shown

> NU1108	Cycle detected.
> Gambit.Android -> Avalonia.Android 0.10.999-cibuild0020448-beta -> Avalonia 0.10.999-cibuild0020448-beta -> Avalonia.Themes.Default 0.10.999-cibuild0020448-beta -> Avalonia (>= 0.10.999-cibuild0020448-beta).	Gambit.Android

**Comment by AzuxirenLeadGuy** [comment]
@timunie Thank you once again. I am able to update the app. The issue is still there, but the error description is changed slightly. It is now

```
Message: Cannot call Measure using a size with NaN values.

Inner Exception: null 

StackTrace:    at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Android.AndroidThreadingInterface.<Signal>b__5_0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr ) 

HResult: -2146233079 

HelpLink: null
```

I used string formatting in the text file, so it appears a bit different now.

@maxkatz6 
> I wonder if it would possible to get SurfaceChanged size or any root view sizes from the app on your device.

Please point out where this property `SurfaceChanged` is so that the details of it can be logged.

**Comment by maxkatz6** [comment]
@AzuxirenLeadGuy interesting.
What I tried:
1. Created simple project from xplat template without any additional changes.
2. Created Pixel 5 with 25 SDK
3. Run project in DEBUG on it, successfully, and closed
4. Opened app again without a debugger, still works fine.

https://user-images.githubusercontent.com/3163374/169953837-984e0586-c298-401e-8091-424f99d56e10.mp4

**Comment by maxkatz6** [comment]
@AzuxirenLeadGuy since you can reproduce this problem. Can you subscribe on SurfaceChanged event?
It is located here https://github.com/AvaloniaUI/Avalonia/blob/82c7d7d64f91a485fb05ab0396d53caf9556f72a/src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs#L173
And as you can see it invokes Resized event, which we can listen. To do so, inside of MainView:
```csharp
protected override void OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e)
{
    base.OnAttachedToVisualTree(e);

    ((TopLevel)e.Root).PlatformImpl!.Resized += (size, reason) =>
    {
        // log size and reason here
    };
}
```

It won't help if app crashes before any control was attached to the visual tree. But let's see.

**Comment by AzuxirenLeadGuy** [comment]
> @AzuxirenLeadGuy interesting. What I tried:
> 
> 1. Created simple project from xplat template without any additional changes.
> 2. Created Pixel 5 with 25 SDK
> 3. Run project in DEBUG on it, successfully, and closed
> 4. Opened app again without a debugger, still works fine.

Thanks for the reponse. I also mentioned in my [previous reply](https://github.com/AvaloniaUI/Avalonia/issues/8150#issuecomment-1129210448) that the project running on debug is now running successfully with the nightly build. However, the problem is still there in the Release configuration. Can you check if you can reproduce the problem?

> @AzuxirenLeadGuy since you can reproduce this problem. Can you subscribe on SurfaceChanged event?
It is located here

I'll try it out and let you know in some time.

**Comment by davidbuckleyni** [comment]
Why sdk 25 that seems a very old version to go back to

**Comment by maxkatz6** [comment]
Please let me know if this issue is still reproducible

**Comment by AzuxirenLeadGuy** [comment]
Sorry for the late reply. I had stopped working on app development with Avalonia at that time. 

I created a new project on the new version, and the bug is no longer there. So I guess this issue can be closed. Thank you all for your responses.
