### ISSUE TITLE
NullReferenceException when Observables change too frequently

### ISSUE THREAD

**Issue by ADIX7** [AvaloniaUI/Avalonia#8155]
I'm getting a NullReferenceException from Avalonia. I use the latest Avalonia nuget packages. My project heavily uses Rx.NET and DynamicData, so a lot of Observables. I guess this exception is thrown because observables are changing too frequently.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 116
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 97
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.Propagate(UInt64 currentid) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs:line 77
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.<>c.<OnNext>b__9_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs:line 68
   at System.Reactive.Concurrency.Scheduler.Invoke[TState](ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 259
   at System.Reactive.Concurrency.Scheduler.<>c__78`1.<ScheduleAction>b__78_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 137
   at System.Reactive.Concurrency.UserWorkItem`1.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs:line 29
   at System.Reactive.Concurrency.DefaultScheduler.<>c__6`1.<Schedule>b__6_0(Object closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 76
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.Timer.Tick() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 176
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.Timer.<>c.<.ctor>b__4_0(Object this) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 166
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

Relevant part of ExpressionNode.cs:
```csharp
        private Action<object?>? _subscriber;

        private void ValueChanged(object? value, bool notify)
        {
            if (_subscriber is null)
                return;

            var notification = value as BindingNotification;

            if (notification == null)
            {
                LastValue = value != null ? new WeakReference<object?>(value) : NullReference;

                if (Next != null)
                {
                    Next.Target = LastValue;
                }
                else if (notify)
                {
                    _subscriber(value);
                }
            }
            else
            {
                LastValue = notification.Value != null ? new WeakReference<object?>(notification.Value) : NullReference;

                if (Next != null)
                {
                    Next.Target = LastValue;
                }

                if (Next == null || notification.Error != null)
                {
                    _subscriber(value);
                }
            }
        }
```

Looking at the code, ValueChanged is checking if _subscriber is null, but later uses the same field but that time it can be null. So it should be cached or checked again, possibly in a lock statement.

**To Reproduce**
I didn't put together a sample app. This is my project, if you go around some folders it will sure throw that exception:
https://github.com/ADIX7/FileTime

**Expected behavior**
Avalonia should not throw an exception even when observables are changing rapidly.

**Desktop (please complete the following information):**

- OS: Windows 10, Fedora Linux 36
- Version 0.10.14
- Dotnet 6.0.202

**Comment by workgroupengineering** [comment]
When you have time try this PR #8167

**Comment by ADIX7** [comment]
Works great! I couldn't reproduce the exception with this version.
