### ISSUE TITLE
CompiledBinding with "Path=" syntax throws exception

### ISSUE THREAD

**Issue by martinzding** [AvaloniaUI/Avalonia#8202]
**Describe the bug**
Xaml compiler failed when using `{Binding Path=xxx}` on ItemsControl.Items. Strangely, the equivalent syntax `{Binding xxx}` worked.

```
Internal compiler error while transforming node XamlX.Ast.XamlAstConstructableObjectNode:
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.XamlIlBindingPathHelper.UpdateCompiledBindingExtension(AstTransformationContext context, XamlAstConstructableObjectNode binding, Func`1 startTypeResolver, IXamlType selfType) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs:line 25
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlBindingPathTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/AstTransformationContext.cs:line 62 Line 17, position 16.	AvaloniaTest	D:\Projects\AvaloniaTest\Views\MainWindow.axaml	17	

```

**To Reproduce**
Avalonia 0.10.14 , VS 2022
Create a new Avalonia MVVM project, and set the content to this in the main window. Enable CompiledBinding, and create a simple ViewModel with Numbers as a `ObservableCollection<int>`.
```
<ItemsControl Items="{Binding Path=Numbers}">
	<ItemsControl.ItemTemplate>
		<DataTemplate>
			<TextBlock />
		</DataTemplate>
	</ItemsControl.ItemTemplate>
</ItemsControl>
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: Windows 10

**Additional context**

**Comment by rabbitism** [comment]
Issue reproduced, and throws when setting ItemTemplate as described above.
