### ISSUE TITLE
No line number / descriptive error message when creating a style with an empty ControlTemplate

### ISSUE THREAD

**Issue by sam-wheat** [AvaloniaUI/Avalonia#8360]
**Describe the bug**
Error message has no line number or meaningful description of what the problem is.

**To Reproduce**
Create a style with an empty ControlTemplate.

**Expected behavior**
Error message contains line number of invalid XAML or some indication, however vague, of what the problem is.

**Desktop (please complete the following information):**

- OS: Windows 10 19044.1766
Avalonia 0.10.15

**Additional context**

	  System.NullReferenceException
	  HResult=0x80004003
	  Message=Object reference not set to an instance of an object.
	  Source=Avalonia.Controls
	  StackTrace:
	   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
	   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
	   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
	   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
	   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
	   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
	   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
	   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
	   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
	   at Avalonia.Controls.Window.ShowCore(Window parent)
	   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
	   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
	   at AvaloniaApp2.Program.Main(String[] args) in C:\Projects\AvaloniaApp2\AvaloniaApp2\Program.cs:line 13

**Comment by sam-wheat** [comment]
TypeConverter cannot convert from System.String.


    
       at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
       at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
       at Avalonia.Xaml.Interactions.Core.TypeConverterHelper.Convert(String value, Type destinationType)
       at Avalonia.Xaml.Interactions.Core.ChangePropertyAction.UpdateAvaloniaPropertyValue(IAvaloniaObject avaloniaObject, AvaloniaProperty property)
       at Avalonia.Xaml.Interactions.Core.ChangePropertyAction.Execute(Object sender, Object parameter)
       at Avalonia.Xaml.Interactivity.Interaction.ExecuteActions(Object sender, ActionCollection actions, Object parameter)
       at Avalonia.Xaml.Interactions.Core.DataTriggerBehavior.OnValueChanged(AvaloniaPropertyChangedEventArgs args)
       at System.Reactive.Subjects.Subject`1.OnNext(T value)
       at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.ValueStore.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.PropertyStore.BindingEntry`1.OnNext(BindingValue`1 value)
       at Avalonia.Reactive.BindingValueAdapter`1.OnNext(T value)
       at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
       at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
       at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer)
       at Avalonia.Data.Core.Plugins.AvaloniaPropertyAccessorPlugin.Accessor.SubscribeCore()
       at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference)
       at Avalonia.Data.Core.ExpressionNode.StartListening()
       at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
       at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
       at Avalonia.Data.BindingBase.UpdateSignal.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
       at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.ValueStore.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
       at Avalonia.PropertyStore.BindingEntry`1.OnNext(BindingValue`1 value)
       at Avalonia.Reactive.BindingValueAdapter`1.OnNext(T value)
       at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
       at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
       at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference)
       at Avalonia.Data.Core.ExpressionNode.StartListening()
       at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
       at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
       at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
       at Avalonia.Visual.SetVisualParent(Visual value)
       at Avalonia.Visual.SetVisualParent(IList children, Visual parent)
       at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
       at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
       at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
       at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
       at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
       at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
       at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
       at Avalonia.Layout.Layoutable.Measure(Size availableSize)
       at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
       at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
       at Avalonia.Layout.LayoutManager.InnerLayoutPass()
       at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
       at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
       at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
       at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
       at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
       at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
       at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
       at LeaderAnalytics.LeaderPivot.XAML.Avalonia.Host.Program.Main(String[] args) in C:\Git\LeaderPivot.XAML.Avalonia\LeaderPivot.XAML.Avalonia.Host\Program.cs:line 13
