### ISSUE TITLE
Cannot publish self-contained on Linux

### ISSUE THREAD

**Issue by kant2002** [AvaloniaUI/Avalonia#8395]
**Describe the bug**
Publishing self-contained apps produce incorrect executable. Even if regular app works

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Avalonia.Controls.Window' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Avalonia.Controls.Primitives.TemplatedControl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Avalonia.Controls.Border' threw an exception.
 ---> System.TypeLoadException: Method 'get_SyncRoot' in type 'Avalonia.Collections.AvaloniaList`1' from assembly 'Avalonia.Base, Version=0.10.15.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation.
   --- End of inner exception stack trace ---
   at Avalonia.Controls.Primitives.TemplatedControl..cctor() in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 21
   --- End of inner exception stack trace ---
   at Avalonia.Controls.Window..cctor() in /_/src/Avalonia.Controls/Window.cs:line 195
   --- End of inner exception stack trace ---
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..cctor() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 25
   --- End of inner exception stack trace ---
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..ctor() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 20
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T , String[] , ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 203
   at AvaloniaAotBench.Program.Main(String[] args) in /home/kant/d/github/avaotbench/AvaloniaAotBench/Program.cs:line 15
Aborted (core dumped)
```

**To Reproduce**

```
git clone https://github.com/kant2002/AvAotBench -b kant/scritp
cd AvAotBench
dotnet publish AvaloniaAotBench/AvaloniaAotBench.csproj -c Release -r linux-x64 --self-contained
AvaloniaAotBench/bin/Release/net6.0/linux-x64/publish/AvaloniaAotBench
```

**Expected behavior**
Screen with data should be shown

**Desktop (please complete the following information):**

- OS: Linux Gentoo
- Version 0.10.15

**Comment by kant2002** [comment]
On windows there similar problem, but with different stack trace 
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException: Method not found: 'System.Object Avalonia.Markup.Xaml.IRootObjectProvider.get_IntermediateRootObject()'.
   at AvaloniaAotBench.App.!XamlIlPopulate(IServiceProvider , App )
   at AvaloniaAotBench.App.!XamlIlPopulateTrampoline(App ) in D:\AvAotBench\AvaloniaAotBench\App.axaml:line 0
   at AvaloniaAotBench.App.Initialize() in D:\AvAotBench\AvaloniaAotBench\App.axaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T , String[] , ShutdownMode )
   at AvaloniaAotBench.Program.Main(String[] args) in D:\AvAotBench\AvaloniaAotBench\Program.cs:line 15
```

**Comment by kant2002** [comment]
Problem was with me! thanks for your help in chat
