### ISSUE TITLE
Web projects now fail with "DllNotFoundException: libSkiaSharp"

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#8486]
**Describe the bug**
We had started working in Avalonia and had used the `dotnet new` command to create "avalonia.xplat" using the v0.10.14 of the AvaloniaTemplates.  This all worked several weeks ago and I hadn't ran the web project since then.  But now when I run web project, the bottom of the browser eventually shows "An unhandled error has occurred." notification and no Avalonia UI loads (other than the "Powered by Avalonia" splash).

**To Reproduce**

1. `dotnet new -i Avalonia.Templates`
2. `dotnet new avalonia.xplat -o AvaloniaHelloWorld`
3. Open the solution in VS 2022 and set the Web project as startup.
4. Run the solution (using latest Microsoft Edge) and see the unhandled error notification a few seconds later.

**Expected behavior**
The Web version of the app should run ok like it used to.

**Desktop (please complete the following information):**

- OS: Windows 11 desktop.
- Avalonia Version: 0.10.999-cibuild0019213-beta

**Additional context**
I also tested the above repro steps above a few minutes ago again with a new solution and still see the issue.  And a colleague could reproduce it too.

This is the exception I see in the VS 2022 debug output:

```
Unhandled Exception:
System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKFont..ctor()
   at Avalonia.Skia.PlatformRenderInterface..cctor() in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 185
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Avalonia.Skia.PlatformRenderInterface' threw an exception.
System.TypeInitializationException: The type initializer for 'Avalonia.Skia.PlatformRenderInterface' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
   at SkiaSharp.SKFont..ctor()
   at Avalonia.Skia.PlatformRenderInterface..cctor() in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 185
   --- End of inner exception stack trace ---
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 21
   at Avalonia.SkiaApplicationExtensions.<>c__0`1[[Avalonia.Web.Blazor.AvaloniaBlazorAppBuilder, Avalonia.Web.Blazor, Version=0.10.999.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1[[Avalonia.Web.Blazor.AvaloniaBlazorAppBuilder, Avalonia.Web.Blazor, Version=0.10.999.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 309
   at Avalonia.Controls.AppBuilderBase`1[[Avalonia.Web.Blazor.AvaloniaBlazorAppBuilder, Avalonia.Web.Blazor, Version=0.10.999.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]].SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.Web.Blazor.WebAppBuilder.SetupWithSingleViewLifetime[AvaloniaBlazorAppBuilder](AvaloniaBlazorAppBuilder builder) in /_/src/Web/Avalonia.Web.Blazor/BlazorSingleViewLifetime.cs:line 18
   at AvaloniaHelloWorld.Web.App.OnParametersSet() in S:\Code\Test\Actipro\AvaloniaHelloWorld\AvaloniaHelloWorld.Web\App.razor.cs:line 11
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by kekekeks** [comment]
`dotnet workload install wasm-tools`

**Comment by billhenn** [comment]
Thank you, that fixed it.  There must have been a SDK update since I last ran the Web project.
