### ISSUE TITLE
LibInputBackend failed to initialise when minimal linux boot with no input 

### ISSUE THREAD

**Issue by OmidID** [AvaloniaUI/Avalonia#8530]
**Describe the bug**
I created a minimal Linux using Buildroot and I have no input devices. LibInputBackend tries to iterate all the input and get failed because `/dev/input` does not exist.

**To Reproduce**

1. Config minimal linux
2. Do not connect any input device such as Keyboard, Mouse or touchscreen
3. Setup application in init.d directory
4. Don't forget to use `SkiaSharp.NativeAssets.Linux.NoDependencies`. 

**Expected behavior**
LibInputBackend should skip iterating input devices

**Desktop (please complete the following information):**

- OS: Linux
- Version Minimal ARM using DRM

**Additional context**
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/dev/input'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Avalonia.LinuxFramebuffer.Input.LibInput.LibInputBackend.InputThread(IntPtr ctx) in /_/src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs:line 41
   at Avalonia.LinuxFramebuffer.Input.LibInput.LibInputBackend.<>c__DisplayClass9_0.<.ctor>b__1() in /_/src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs:line 29
   at System.Threading.Thread.StartCallback()
```

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs#L41

Maybe if check the directory exists, we can solve the issue.

**Comment by timunie** [comment]
If you have an idea to solve it, you can file a PR. They are very welcome as far as I can tell. 

Happy coding, 
Tim
