### ISSUE TITLE
DBus file dialogs crash the application if 

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#8537]
```
Unhandled exception. Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at Avalonia.FreeDesktop.DBusSystemDialog.OpenFilePickerAsync(FilePickerOpenOptions options) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.FreeDesktop/DBusSystemDialog.cs:line 69
   at Avalonia.Controls.Platform.SystemDialogImpl.ShowFileDialogAsync(FileDialog dialog, Window parent) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs:line 27
   at ControlCatalog.Pages.DialogsPage.<>c__DisplayClass0_0.<<-ctor>b__2>d.MoveNext() in /home/kekekeks/Projects/AvaloniaMaster/samples/ControlCatalog/Pages/DialogsPage.xaml.cs:line 71
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Threading.Dispatcher.RunJobs() in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Base/Threading/Dispatcher.cs:line 69
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /home/kekekeks/Projects/AvaloniaMaster/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at ControlCatalog.NetCore.Program.Main(String[] args) in /home/kekekeks/Projects/AvaloniaMaster/samples/ControlCatalog.NetCore/Program.cs:line 103
   ```
   
   
   Also for some reason DBus file dialogs are enabled by the option that enables the global menu support.

**Comment by kekekeks** [comment]
Broken by https://github.com/AvaloniaUI/Avalonia/pull/8217
cc: @maxkatz6 @affederaffe

**Comment by affederaffe** [comment]
`Avalonia.X11Platform.Initialize()` is synchronous and I had to test if the DBus interface is available first to be able to provide the managed fallback before binding it to the locator, see https://github.com/affederaffe/Avalonia/blob/90a81a954846936692324f4af32308f06e9ba539/src/Avalonia.X11/X11Platform.cs#L83=

**Comment by affederaffe** [comment]
This was actually the case in an earlier [commit](https://github.com/AvaloniaUI/Avalonia/pull/8217/commits/8026fb1047e9ce309056787d7277aa36ff631c70), but got removed based on this discussion:
> It would be better to keep DBusSystemDialog only for dbus dialog, and instead add a static factory method "TryCreate" here. And if it fails, then register ManagedSystemDialogImpl. New helper methods won't be needed too.

**Comment by maxkatz6** [comment]
I will take a look tomorrow, how it can be redo
