### ISSUE TITLE
CompileAvaloniaXamlTask task failed unexpectedly when x:TypeArguments is referenced to type in another module

### ISSUE THREAD

**Issue by egortech** [AvaloniaUI/Avalonia#8789]
**Describe the bug**
When ``x:TypeArguments`` markup extensions is used to create instance of generic type with generic type parameters from another module in XAML markup follow exception is occurs:
```
Error	MSB4018	The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.ArgumentException: Member '<TypeName>' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.SignatureWriter.WriteGenericInstanceSignature(IGenericInstance instance)
   at Mono.Cecil.MetadataBuilder.GetTypeSpecToken(TypeReference type)
   at Mono.Cecil.MetadataBuilder.CreateMemberRefRow(MemberReference member)
   at Mono.Cecil.MetadataBuilder.GetMemberRefToken(MemberReference member)
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.Compile(IBuildEngine engine, String input, String[] references, String projectDirectory, String output, Boolean verifyIl, MessageImportance logImportance, String strongNameKey, Boolean patchCom, Boolean skipXamlCompilation, Boolean debuggerLaunch)
   at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()E:\.nuget\avalonia\0.10.18\buildTransitive\AvaloniaBuildTasks.targets	98	
```

I can reproduce this when generic type is defined in application assembly.

**To Reproduce**

Let's define some generic type:
```cs
public class Test<T>
{

}
```

And trying to create instance of this type with any generic type defined outside of current assembly:
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:AvaloniaApplication2"
             x:Class="AvaloniaApplication2.App">
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    <Application.Resources>
        <ResourceDictionary>
          <local:Test x:TypeArguments="ListBox" x:Key="Test"/>
        </ResourceDictionary>
    </Application.Resources>

    <Application.Styles>
        <FluentTheme Mode="Light"/>
    </Application.Styles>
</Application>
```

And bang ``CompileAvaloniaXamlTask`` is failed.

**Expected behavior**
XAML complier should compile this markup without error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.18

**Additional context**

**Comment by Dryadxon** [comment]
Maybe #8809 is related in some way to the issue?
I can reproduce the same error with this [View](https://github.com/Dryadxon/AvaloniaCompileBindingsIssue/blob/main/Views/MainWindow.axaml) and [ViewModel](https://github.com/Dryadxon/AvaloniaCompileBindingsIssue/blob/main/ViewModels/MainWindowViewModel.cs) using `IDictionary` or `Dictionary`, but not when using [`IFoo`](https://github.com/Dryadxon/AvaloniaCompileBindingsIssue/blob/main/Models/IFoo.cs), which is just an `IDictionary` copy, and [`Foo`](https://github.com/Dryadxon/AvaloniaCompileBindingsIssue/blob/main/Models/Foo.cs) a `Dictionary` wrapper.

**Comment by busitech** [comment]
Adding on a couple of other open issues which discuss the same exception:

#9090  
#9355
