### ISSUE TITLE
WeakHashList Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#8810]
**Describe the bug**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakHashList`1.GetAlive(Func`1 factory) in /_/src/Avalonia.Base/Utilities/WeakHashList.cs:line 210
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 157
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object _, PropertyChangedEventArgs e) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[T](T& field, T newValue, String propertyName)
   at SvgToXaml.ViewModels.FileItemViewModel.set_Svg(SvgViewModel value) in /Users/wieslawsoltes/Documents/GitHub/SvgToXaml/src/SvgToXaml.Base/ViewModels/FileItemViewModel.cs:line 37
   at SvgToXaml.ViewModels.FileItemViewModel.<>c__DisplayClass28_0.<Load>b__0() in /Users/wieslawsoltes/Documents/GitHub/SvgToXaml/src/SvgToXaml.Base/ViewModels/FileItemViewModel.cs:line 86
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SvgToXaml.ViewModels.FileItemViewModel.Load(DrawAttributes ignoreAttribute) in /Users/wieslawsoltes/Documents/GitHub/SvgToXaml/src/SvgToXaml.Base/ViewModels/FileItemViewModel.cs:line 84
   at SvgToXaml.ViewModels.MainWindowViewModel.<.ctor>b__31_9(FileItemViewModel x) in /Users/wieslawsoltes/Documents/GitHub/SvgToXaml/src/SvgToXaml.Base/ViewModels/MainWindowViewModel.cs:line 93
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4502
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at SvgToXaml.Program.Main(String[] args) in /Users/wieslawsoltes/Documents/GitHub/SvgToXaml/src/SvgToXaml.Desktop/Program.cs:line 14

```

**To Reproduce**

Run SvgToXaml.Desktop app and add some items, change selections in left ListBox, exception sometimes happens.

**Expected behavior**

No exception

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS M1
- Version 11.0.0-preview1

**Additional context**

**Comment by AJSoft** [comment]
I digged into this exception, the NullReferencedException is in the file 
Avalonia/src/Avalonia.Base/Utilities/WeakHashList.cs 
when Line 212
`s_listPool.Pop()`
returns a null value, it causes the NRE.

I guess the reason is the Hash is not thread-safe. While viewmodel updating property in multi-thread concurrently, this exception will be fired occasionally

**Comment by chyyran** [comment]
This is occurring for me as well on 11 preview2, Windows 10. My particular edge case is [updating a download percentage value](https://github.com/chyyran/skyinstaller/blob/master/src/TrailsHelper/ViewModels/InstallViewModel.cs#L273), updating the property frequently from an async Task causes this issue to pop up. This bug wasn't present in 0.10.x.

**Comment by christian289** [comment]
Hello.

I'd like to share an issue.
Currently, I am using Avalonia UI 11.0.0-Preview2.
And I'm using ReactiveUI with the same version.
In my case, there is a phenomenon like this.

When I subscribe to a particular property with WhenAnyValue in ViewModel

```
ObserveOn(RxApp.MainThreadScheduler)
```

This happens when you use it with .

However, this does not happen if you remove the ObserveOn method.

I don't know if it's related, but RxApp.If you check the MainThreadScheduler, the DefaultScheduler is applied.

**Comment by Unreal852** [comment]
I got the same error when updating a ProgressBar frequently 

```
System.NullReferenceException: Object reference not set to an instance of an object.
  File "/_/src/Avalonia.Base/Utilities/WeakHashList.cs", line 229, col 21, in PooledList<T> WeakHashList<T>.GetAlive(Func<PooledList<T>> factory)
  File "/_/src/Avalonia.Base/Utilities/WeakEvent.cs", line 157, col 13, in void Subscription.OnEvent(object sender, TEventArgs eventArgs)
  File "/_/src/Avalonia.Base/AvaloniaObject.cs", line 785, col 25, in void AvaloniaObject.RaisePropertyChanged<T>(AvaloniaPropertyChangedEventArgs<T> change)
  File "/_/src/Avalonia.Controls/ProgressBar.cs", line 279, col 9, in void ProgressBar.UpdateIndicator()
  File "/_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs", line 145, col 22, in void Subject<T>.OnNext(T value)
  File "/_/src/Avalonia.Base/AvaloniaObject.cs", line 775, col 17, in void AvaloniaObject.RaisePropertyChanged<T>(AvaloniaPropertyChangedEventArgs<T> change)
  File "/_/src/Avalonia.Controls/Primitives/RangeBase.cs", line 149, col 13, in void RangeBase.set_Value(double value)
  File "/_/src/Avalonia.Base/DirectProperty.cs", line 164, col 17, in void DirectProperty<TOwner, TValue>.InvokeSetter(IAvaloniaObject instance, BindingValue<TValue> value)
  File "/_/src/Avalonia.Base/AvaloniaObject.cs", line 839, col 17, in void AvaloniaObject.SetDirectValueUnchecked<T>(DirectPropertyBase<T> property, BindingValue<T> value)
  File "/_/src/Avalonia.Base/AvaloniaObject.cs", line 959, col 52, in void DirectBindingSubscription<T>.OnNext(BindingValue<T> value)+() => { }
  File "/_/src/Avalonia.Base/Threading/JobRunner.cs", line 38, col 17, in void JobRunner.RunJobs(DispatcherPriority? priority)
  File "/_/src/Windows/Avalonia.Win32/Win32Platform.cs", line 287, col 13, in IntPtr Win32Platform.WndProc(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam)
  ?, in IntPtr UnmanagedMethods.DispatchMessage(ref MSG lpmsg)
  File "/_/src/Windows/Avalonia.Win32/Win32Platform.cs", line 214, col 17, in void Win32Platform.RunLoop(CancellationToken cancellationToken)
  File "/_/src/Avalonia.Base/Threading/Dispatcher.cs", line 61, col 13, in void Dispatcher.MainLoop(CancellationToken cancellationToken)
  File "/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs", line 120, col 13, in int ClassicDesktopStyleApplicationLifetime.Start(string[] args)
  File "/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs", line 209, col 13, in int ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime<T>(T builder, string[] args, ShutdownMode shutdownMode)
  File "Program.cs", line 49, col 17, in void Program.Main(string[] args)
```

**Comment by batzen** [comment]
This also happens in my application.
In my case i have instances of `ObservableCollection` which are updated on background threads, but those updates are protected by locks so it's in fact thread safe.
With Avalonia 10 this wasn't an issue, but with 11 it just throws an NRE.

The exception is not thrown in `WeakHashList` but in `Subscription.OnEvent` and then in `foreach(var item in alive.Span)` where `alive` is from `WeakHashList.GetAlive()`.

**Comment by grokys** [comment]
Does anyone have a minimal repro for this? Not quite sure what's happening here. It looks like a binding isn't being marshaled to the UI thread, but I'm not sure why.

**Comment by batzen** [comment]
Will try to build one and post it here.

**Comment by sdijoseph** [comment]
> Does anyone have a minimal repro for this? Not quite sure what's happening here. It looks like a binding isn't being marshaled to the UI thread, but I'm not sure why.

I think this should demonstrate the issue: [AvaloniaWeakHashList](https://github.com/sdijoseph/AvaloniaWeakHashList)

It constructs 30 view models, each with a string that outputs each second from an Observable.Interval. On Avalonia 0.10 this runs fine, but it throws an exception almost immediately on 11.

**Comment by grokys** [comment]
Thanks @sdijoseph !

**Comment by grokys** [comment]
Ok I've taken a look and the problem isn't that the binding isn't being marshaled to the UI thread.

The problem seems to be that `InpcPropertyAccessorPlugin` uses [weak events](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/Plugins/InpcPropertyAccessorPlugin.cs#L188) and do indeed support listening to INPC events on threads other than the UI thread, but `WeakHashTable` isn't thread-safe it seems.

Pinging @kekekeks for input on this.

**Comment by 11v1** [comment]
Hi guys, I'm not sure this has been entirely fixed. Avalonia 11.3.0. I get the same exception occasionally.
StackTrace:
```
System.NullReferenceException: Arg_NullReferenceException
   at Avalonia.Utilities.WeakHashList`1.GetAlive(Func`1 factory)
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs)
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_0.<.cctor>b__5(Object _, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Foundation.Common.Collections.ObservableList`1.Insert(Int32 index, T item)
   at Foundation.Common.Collections.TransformingObservableList`2.AddItem(NotifyCollectionChangedEventArgs e)
   at Foundation.Common.Collections.TransformingObservableList`2.HandleSourceCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Foundation.Common.Collections.ObservableList`1.Reset(IEnumerable`1 items)
...
```
The observable collection is modified thread-safely not on the UI thread

**Comment by IAmRainMaker** [comment]
Hi everyone! We experience the same random error with INotifyDataErrorInfo (ErrorsChanged may be invoked in a non-UI thread, similar to previous comments). It looks like the [fix](https://github.com/AvaloniaUI/Avalonia/pull/10362/files) only corrects the way to process INotifyPropertyChanged.PropertyChanged at the binding level, whereas you still can see the issue in many different usage scenarios
