### ISSUE TITLE
Application crash when hotkey is press or button is pressed

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#8835]
**Describe the bug**
https://github.com/sn4k3/UVtools/issues/543
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method129(Closure , Object )
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter) in /_/src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs:line 82
   at Avalonia.Controls.HotKeyManager.HotkeyCommandWrapper.Execute(Object parameter) in /_/src/Avalonia.Controls/HotkeyManager.cs:line 29
   at Avalonia.Input.KeyBinding.TryHandle(KeyEventArgs args) in /_/src/Avalonia.Input/KeyBinding.cs:line 40
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 241
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 541
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 70
```

My application cash most of the times when specific hotkey (ctrl + z) or button is pressed. However it did not happen when i manually select the item on the list view.

Both button and hotkey is binded to `ClipboardUndo`

```xml
<Button IsEnabled="{Binding Clipboard.CanUndo}"
									Command="{Binding ClipboardUndo}"
									HotKey="Ctrl + Z"
									ToolTip.Tip="Undo [Ctrl + Z]
&#x0a;Shift + Click to Undo and edit last operation [Ctrl + Shift + Z]"
									i:Attached.Icon="fa-solid fa-undo-alt"/>
```

```C#
    public void ClipboardUndo()
    {
        CanSave = true;
        if ((_globalModifiers & KeyModifiers.Shift) != 0)
        {
            ClipboardUndo(true);
            return;
        }
        Clipboard.Undo();
    } 
```

```C#
public void Clipboard.Undo()
    {
        if (!CanUndo) return;
        CurrentIndex++;
    }
```

So click on button does what change index on list does, it increments the value of `CurrentIndex`.
However it never crash when change index from list

I placed a breakpoint on `ClipboardUndo` which is what button calls and the breakpoint is never hit, causing the exception above.

![devenv_2022-08-27_16-21-03](https://user-images.githubusercontent.com/113281/187036569-49b443f6-c682-40a5-b3b4-9679f3323d86.png)

**Screenshots**

https://user-images.githubusercontent.com/113281/187036639-c8ab3c52-4926-4114-b396-57a8b2d5fde2.mp4

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.18

**Additional context**
I have an idea that this start happen after upgrading from 0.10.17 to 0.10.18
Also it only happens with this button, for example, the redo button does not produce this problem

**Comment by timunie** [comment]
Tip: I personally like to use Commands over binding to void. See: https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src%2FAvalonia.Samples%2FMVVM%2FCommandSample

**Comment by timunie** [comment]
Also you may want to set a break point there and try to figure out where it is `null`

**Comment by rabbitism** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/f95dde85fd4c2b4e1e3421fc052cddfbbc8723b0/src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs#L80-L82

I think at least we can change these lines to 
```csharp
public bool CanExecute(object? parameter) => canExecute?.Invoke(parameter);
public void Execute(object? parameter) => execute?.Invoke(parameter);
```

**Comment by jp2masa** [comment]
I don't think that would help, because the NRE occurs inside the lambda:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method129(Closure , Object )
```

**Comment by timunie** [comment]
If I use an ICommand, the issue can't be reproduced. So I think this should be the way to go tbh.

**Comment by timunie** [comment]
https://github.com/sn4k3/UVtools/pull/544

**Comment by sn4k3** [comment]
I found the problem... In fact it was obvious where the issue is since that didn't happen with previous version and all others buttons works fine.

I have two functions with same name beside one have a required argument:

```C#
public void ClipboardUndo()
    {
        CanSave = true;
        if ((_globalModifiers & KeyModifiers.Shift) != 0)
        {
            ClipboardUndoAndRerun(true);
            return;
        }
        Clipboard.Undo();
    } 

    public async void ClipboardUndo(bool rerun)
    {
        CanSave = true;
        var clip = Clipboard.CurrentClip;
        Clipboard.Undo();
        if (!rerun)
        {
            return;
        }
        if (clip?.Operation is null) return;
        /*if (clip.Operation.HaveROI)
        {
            ROI = GetTransposedRectangle(clip.Operation.ROI);
        }

        if (clip.Operation.HaveMask)
        {
            AddMaskPoints(clip.Operation.MaskPoints);
        }*/

        var operation = await ShowRunOperation(clip.Operation.GetType(), clip.Operation);
        if (operation is null)
        {
            Clipboard.Redo();
            CanSave = false;
        }
    }
```

Something should changed regarding that with Avalonia on the last release?
By simply rename the second function to: `ClipboardUndoAndRerun` solves the problem since theres no duplicate name

**Comment by rabbitism** [comment]
I think the default behavior evaluates the binding method parameter length instead of binding parameter. 
https://github.com/AvaloniaUI/Avalonia/blob/f95dde85fd4c2b4e1e3421fc052cddfbbc8723b0/src/Avalonia.Base/Data/Converters/DefaultValueConverter.cs#L34-L39

Then the default command converter take the parameter count to determine how to create delegate.
https://github.com/AvaloniaUI/Avalonia/blob/f95dde85fd4c2b4e1e3421fc052cddfbbc8723b0/src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs#L30-L40

**Comment by sn4k3** [comment]
Humm something is strange here, i just tested with the previous release of my program and it was working fine on 0.10.18 without crashing, but i change nothing regards this undo

[v3.6.1](https://github.com/sn4k3/UVtools/releases/tag/v3.6.2)
[v3.6.2](https://github.com/sn4k3/UVtools/releases/tag/v3.6.1)
[v3.6.1 vs v3.6.2](https://github.com/sn4k3/UVtools/compare/v3.6.1...v3.6.2)

**Comment by timunie** [comment]
I think this issue is probably related to https://github.com/AvaloniaUI/Avalonia/issues/5076 ?
