### ISSUE TITLE
[WebAssembly] .NET 7 RC1 -  Unhandled exception rendering component: GL is not defined

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#8965]
**Describe the bug**

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: GL is not defined
      ReferenceError: GL is not defined
          at SKHtmlCanvas.createWebGLContext (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:174:19)
          at new SKHtmlCanvas (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:8:38)
          at SKHtmlCanvas.init (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:47:22)
          at SKHtmlCanvas.initGL (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:27:33)
          at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3219)
          at Object.Dt [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:60823)
          at Object.Ii (https://localhost:5001/_framework/dotnet..1g6d4ircqv.js:5:70880)
          at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet..1g6d4ircqv.js:7683:71)
          at do_icall (wasm://wasm/053a4952:wasm-function[15936]:0x5b6634)
          at do_icall_wrapper (wasm://wasm/053a4952:wasm-function[15883]:0x5b550e)
Microsoft.JSInterop.JSException: GL is not defined
ReferenceError: GL is not defined
    at SKHtmlCanvas.createWebGLContext (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:174:19)
    at new SKHtmlCanvas (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:8:38)
    at SKHtmlCanvas.init (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:47:22)
    at SKHtmlCanvas.initGL (https://localhost:5001/_content/Avalonia.Web.Blazor/SKHtmlCanvas.js:27:33)
    at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3219)
    at Object.Dt [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:60823)
    at Object.Ii (https://localhost:5001/_framework/dotnet..1g6d4ircqv.js:5:70880)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet..1g6d4ircqv.js:7683:71)
    at do_icall (wasm://wasm/053a4952:wasm-function[15936]:0x5b6634)
    at do_icall_wrapper (wasm://wasm/053a4952:wasm-function[15883]:0x5b550e)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[GLInfo](String identifier, Int64 targetInstanceId, Object[] args)
   at Microsoft.JSInterop.Implementation.JSInProcessObjectReference.Invoke[GLInfo](String identifier, Object[] args)
   at Avalonia.Web.Blazor.Interop.JSModuleInterop.Invoke[GLInfo](String identifier, Object[] args) in /_/src/Web/Avalonia.Web.Blazor/Interop/JSModuleInterop.cs:line 38
   at Avalonia.Web.Blazor.Interop.SKHtmlCanvasInterop.InitGL() in /_/src/Web/Avalonia.Web.Blazor/Interop/SKHtmlCanvasInterop.cs:line 49
   at Avalonia.Web.Blazor.AvaloniaView.OnAfterRenderAsync(Boolean firstRender) in /_/src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs:line 268
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by ShadowMarker789** [comment]
Possibly related dotnet-runtime issue

https://github.com/dotnet/runtime/issues/76077

**Comment by mattleibow** [comment]
I know the Avalonia team did it first, but this is my PR that seems to work on net6 and net7 - without using any copied values from runtime source: https://github.com/mono/SkiaSharp/pull/2268

**Comment by maxkatz6** [comment]
Closing as it seems to not be an issue with new SkiaSharp
