### ISSUE TITLE
Native blob disposal from finalizer thread

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#9051]
**Describe the bug**

``` bash
Native blob disposal from finalizer thread
Backtrace:    at System.Environment.get_StackTrace()
   at Avalonia.Platform.Internal.UnmanagedBlob.Dispose() in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Platform/Internal/UnmanagedBlob.cs:line 87
   at Avalonia.Skia.WriteableBitmapImpl.ReleaseProc(IntPtr address, Object ctx) in /home/spaccabit/GitHub/Avalonia/src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs:line 177
   at SkiaSharp.SKBitmap.<>c__DisplayClass108_0.<InstallPixels>b__0(IntPtr addr, Object _)
   at SkiaSharp.DelegateProxies.SKBitmapReleaseDelegateProxyImplementation(Void* address, Void* context)
   at SkiaSharp.SkiaApi.sk_bitmap_destructor(IntPtr cbitmap)
   at SkiaSharp.SkiaApi.sk_bitmap_destructor(IntPtr cbitmap)
   at SkiaSharp.SKBitmap.DisposeNative()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKBitmap.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()

Blob created by    at System.Environment.get_StackTrace()
   at Avalonia.Platform.Internal.UnmanagedBlob..ctor(Int32 size) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Platform/Internal/UnmanagedBlob.cs:line 53
   at Avalonia.Platform.StandardRuntimePlatform.AllocBlob(Int32 size) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Platform/StandardRuntimePlatform.cs:line 15
   at Avalonia.Skia.WriteableBitmapImpl..ctor(PixelSize size, Vector dpi, PixelFormat format, AlphaFormat alphaFormat) in /home/spaccabit/GitHub/Avalonia/src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs:line 107
   at Avalonia.Skia.PlatformRenderInterface.CreateWriteableBitmap(PixelSize size, Vector dpi, PixelFormat format, AlphaFormat alphaFormat) in /home/spaccabit/GitHub/Avalonia/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 228
   at Avalonia.Media.Imaging.WriteableBitmap.CreatePlatformImpl(PixelSize size, Vector& dpi, Nullable`1 format, Nullable`1 alphaFormat) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Media/Imaging/WriteableBitmap.cs:line 77
   at Avalonia.Media.Imaging.WriteableBitmap..ctor(PixelSize size, Vector dpi, Nullable`1 format, Nullable`1 alphaFormat) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Media/Imaging/WriteableBitmap.cs:line 22
   at Avalonia.Controls.Primitives.ColorPickerHelpers.CreateBitmapFromPixelData(IList`1 bgraPixelData, Int32 pixelWidth, Int32 pixelHeight) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Controls.ColorPicker/Helpers/ColorPickerHelpers.cs:line 614
   at Avalonia.Controls.Primitives.ColorSlider.UpdateBackground() in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Controls.ColorPicker/ColorSlider/ColorSlider.cs:line 113
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Avalonia.Controls.Primitives.ColorPickerHelpers.CreateComponentBitmapAsync(Int32 width, Int32 height, Orientation orientation, ColorModel colorModel, ColorComponent component, HsvColor baseHsvColor, Boolean isAlphaMaxForced, Boolean isSaturationValueMaxForced) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Controls.ColorPicker/Helpers/ColorPickerHelpers.cs:line 307
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Controls.Platform.InternalPlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Controls/Platform/InternalPlatformThreadingInterface.cs:line 27
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token) in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 55
   at LinuxFramebufferPlatformExtensions.StartLinuxDirect[T](T builder, String[] args, IOutputBackend outputBackend, IInputBackend inputBackend) in /home/spaccabit/GitHub/Avalonia/src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs:line 162
   at LinuxFramebufferPlatformExtensions.StartLinuxFbDev[T](T builder, String[] args, String fbdev, Double scaling, IInputBackend inputBackend) in /home/spaccabit/GitHub/Avalonia/src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs:line 146
   at ControlCatalog.NetCore.Program.Main(String[] args) in /home/spaccabit/GitHub/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 47
Native blob disposal from finalizer thread
Backtrace:    at System.Environment.get_StackTrace()
   at Avalonia.Platform.Internal.UnmanagedBlob.Dispose() in /home/spaccabit/GitHub/Avalonia/src/Avalonia.Base/Platform/Internal/UnmanagedBlob.cs:line 87
   at Avalonia.Skia.WriteableBitmapImpl.ReleaseProc(IntPtr address, Object ctx) in /home/spaccabit/GitHub/Avalonia/src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs:line 177
   at SkiaSharp.SKBitmap.<>c__DisplayClass108_0.<InstallPixels>b__0(IntPtr addr, Object _)
   at SkiaSharp.DelegateProxies.SKBitmapReleaseDelegateProxyImplementation(Void* address, Void* context)
   at SkiaSharp.SkiaApi.sk_bitmap_destructor(IntPtr cbitmap)
   at SkiaSharp.SkiaApi.sk_bitmap_destructor(IntPtr cbitmap)
   at SkiaSharp.SKBitmap.DisposeNative()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKBitmap.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```
**To Reproduce**

1. Build Avalonia 
1. Go to Linux Terminal
2. Go to samples/ControlCatalog.NetCore/bin/Debug/net6.0
3. Write `dotnet ControlCatalog.NetCore.dll`
4. Go ColorPicker example
5. See error in console

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 22.04.1 64bit 
- Version: 84791dbf2e772cad889d575ef64000b5ba3d637a 

**Additional context**

**Comment by maxkatz6** [comment]
There are couple of places where writeable bitmap should be reused in ColorPicker code. But the most of these finalizer thread disposal comes from this slider part
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.ColorPicker/ColorSlider/ColorSlider.cs#L113

**Comment by kekekeks** [comment]
Controls should dispose their bitmaps either when they no longer used or when such control is detached from the visual tree. If there are undisposed bitmaps being finalized it's a bug in the control code.

**Comment by robloo** [comment]
Note that releasing `WriteableBitmap`s when detaching from the visual tree negatively affects performance especially on the `ColorSpectrum`. This is because those bitmaps take some time to build and now have to be re-built every single time the control comes in and out of view. @kekekeks If there is a better way to do this without a performance impact using `OnDetachedFromVisualTree()` I would like to pursue it.

**Comment by kekekeks** [comment]
>This is because those bitmaps take some time to build and now have to be re-built every single time the control comes in and out of view

Could you just reuse the same bitmap for all ColorSpectrum instances?

> should be responsible for it's own lifecycle management as in WinUI

Yes, we have the same "lifecycle management" as WinUI which is "automatically release memory when GC collects WritableBitmap". We just print a warning in debug build when that happens.

**Comment by robloo** [comment]
>> This is because those bitmaps take some time to build and now have to be re-built every single time the control comes in and out of view
>
>Could you just reuse the same bitmap for all ColorSpectrum instances?

Interesting idea but:
 1. It would be a pretty annoying tear-up to the code
 2. Would probably be limited benefit because the majority of the delay is calculating the actual bytes of the spectrum bitmap itself -- not instantiating the writeable bitmap and copying in the bytes. The bitmaps also do change between controls depending on selected color and certain parameters. Only the default spectrum bitmap which varies Hue and Saturation appears the same on all controls. It's possible to vary other parameters.

> Yes, we have the same "lifecycle management" as WinUI which is "automatically release memory when GC collects WritableBitmap". We just print a warning in debug build when that happens.

If so that seems to contradict "Controls should dispose their bitmaps either when they no longer used or when such control is detached from the visual tree. If there are undisposed bitmaps being finalized it's a bug in the control code." In that if controls don't release these resources it's not an actual bug and the GC will handle it correctly freeing memory and resources.

With that in mind, it might be better to NEVER dispose when detached from the visual tree and only dispose instances when a new bitmap needs to be generated.

**Comment by robloo** [comment]
Calling .Dispose() on WriteableBitmap or attempting to re-use it causes intermittent crashes that usually don't throw exceptions. It's a hard, silent crash. Therefore, I'm probably not going to really fix this one for now... It sounds like it wasn't really a bug to begin with and is just a warning in debug mode.

**Comment by kekekeks** [comment]
> .Dispose() on WriteableBitmap or attempting to re-use it causes intermittent crashes

Please, file a bug report. We have reference tracking code specifically to prevent the actual bitmap from being disposed while it's still in use by the renderer.

**Comment by robloo** [comment]
@kekekeks Created a bug report #9092
