### ISSUE TITLE
InvalidOperationException in RichTextBlock when changing text in Run, followed by InlineUIContainer

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#9072]
**Describe the bug**
When i use RichTextBlock with inlines, changing value of Run (via binding), followed by InlineUIContainer (or just a control itself) causes this exception. 

**To Reproduce**

1. Create RichTextBlock with inlines, for example this:
```xaml
<RichTextBlock>
    <Run Text="START"></Run>
    <Run Text="{Binding Greeting}"></Run>
    <InlineUIContainer>
        <Rectangle Height="10" Width="10" Fill="Red"></Rectangle>
    </InlineUIContainer>
</RichTextBlock>
```
2. Change value of second Run (is my case via binding)
3. See error

**Desktop (please complete the following information):**

- OS: Windows, but i think what reproduceable everywhere
- Version: 11.0.0-preview1

**Additional context**
Exception:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Avalonia.Rendering.Composition.CompositingRenderer.Update() in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 197
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 267
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 214
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Avalonia.NETCoreMVVMApp1.Program.Main(String[] args) in C:\Users\SKProCH\RiderProjects\Temp\AvaloniaApplication1\Avalonia.NETCoreMVVMApp1\Program.cs:line 11
```

**Comment by Gillibald** [comment]
Fixed by: https://github.com/AvaloniaUI/Avalonia/pull/8849
