### ISSUE TITLE
Error on startup when using custom controls in Linux

### ISSUE THREAD

**Issue by cemelo** [AvaloniaUI/Avalonia#9152]
**Describe the bug**
Avalonia fails to startup on Linux due to a missing method implementation when a specific custom control is added.

**To Reproduce**

1. Create a clean project.
2. Add the [Dock](https://github.com/wieslawsoltes/Dock) custom control.
3. Try to start the application.

**Expected behavior**
The application starts.

**Desktop (please complete the following information):**

- OS: Linux (Ubuntu 20.04)
- Version 0.10.12

**Additional context**
Exception thrown:

```Unhandled exception. System.TypeLoadException: Method 'ScreenFromWindow' in type 'Avalonia.X11.X11Screens' from assembly 'Avalonia.X11, Version=0.10.12.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation.
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /_/src/Avalonia.X11/X11Platform.cs:line 279
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Aurora.Program.main(String[] args) in /home/carlos/Projects/Aurora/Program.fs:line 44```

**Comment by cemelo** [comment]
My apologies. This is not a bug with Avalonia.
