### ISSUE TITLE
[mac] Random crash on M1 macs on VerifyAccess

### ISSUE THREAD

**Issue by ltetak** [AvaloniaUI/Avalonia#9351]
**Describe the bug**
The application randomly crashes on an M1 mac machine in the middle of the session. The reason is the main thread check.

`System.InvalidOperationException: Call from invalid thread`

I saw several discussions about the main thread check that is different in the mac implementation. I am not sure though why this basic feature would return suddenly that the main thread is not the main thread.

**To Reproduce**
In our case, it is opening a second window and then clicking on the system dock panel.

**Desktop:**
- OS: any Mac OS version. So far only M1 machines crashed (tested on at least 5 different machines).
- Avalonia version: 0.10.18

**Additional context**

This is the stack trace below (I would say definitely on the main thread). It was running for a while so it had checked for this a thousand times before.

https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/platformthreading.mm#L104

```
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.GetValue[T](StyledPropertyBase`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 249
   at Avalonia.Input.FocusManager.GetFocusScopeAncestors(IInputElement control)+MoveNext() in /_/src/Avalonia.Input/FocusManager.cs:line 203
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Input/FocusManager.cs:line 64
   at Avalonia.Input.FocusManager.SetFocusScope(IFocusScope scope) in /_/src/Avalonia.Input/FocusManager.cs:line 162
   at Avalonia.Controls.WindowBase.HandleActivated() in /_/src/Avalonia.Controls/WindowBase.cs:line 294
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Activated() in /_/src/Avalonia.Native/WindowImplBase.cs:line 188
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Activated(Void* this) in /_/src/Avalonia.Native/Interop.Generated.cs:line 3689
   --- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at MyApp.Main(String[] args) in /Users/administrator/buildagent/buildAgent/work/ded0ac7a4578263e/MyApp/Program.cs:line 43
```

**Comment by ltetak** [comment]
I am not exactly sure what happened here. I managed to catch this with debug and realized that it was indeed running on a non-UI thread. I guess thats because the main loop on mac is implemented natively so it is not clear from the managed stack trace if it runs on the main thread or not.
The check in the VerifyAccess method is correct just the stack trace is a bit hard to read. I am closing this issue.
