### ISSUE TITLE
InvalidCastException :Unable to cast object of type *ViewModel to AvaloniaObject (11.0-preview4)

### ISSUE THREAD

**Issue by huaxing-yuan** [AvaloniaUI/Avalonia#9508]
I was trying to upgrade to Avalonia 11.0 preview 4 and able to handle most of breaking change. But I had a weird exception when load a view (with ViewModel) into Window: When I set DataContext to an object of type MyViewModel, An exception is thrown:

System.InvalidCastException: 'Unable to cast object of type 'MyViewModel' to type 'Avalonia.AvaloniaObject'.'

I use `FluentAvalonia`'s NavigationView as container and changes it's content according to selection.
- The exception is not thrown immediately after the assignment of DataContext. It throws later, before the event "Loaded".
- The exception is not thrown immediately after the assignment of NavigationView.Content 
- When I assign DataContext to null, the UI can be shown (with no content of course)
- When I remove the assignment to change NavigationView.Content, there is no exception.

For some simple ViewModels (not inherited from AvaloniaObject) there is no issue.
Here is the stack trace when exception occurs, happened from 11.0-preview1 to 11.0-preview4. no issue on 0.10.18

Thanks in advance for any hints.
```
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorFactory.CreateAvaloniaPropertyAccessor(WeakReference`1 target, IPropertyInfo property)
   at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference)
   at Avalonia.Data.Core.ExpressionNode.StartListening()
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference)
   at Avalonia.Data.Core.ExpressionNode.StartListening()
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference)
   at Avalonia.Data.Core.ExpressionNode.StartListening()
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at Avalonia.Data.BindingBase.UpdateSignal.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.InheritanceParentChanged[T](StyledPropertyBase`1 property, AvaloniaObject oldParent)
   at Avalonia.AvaloniaObject.set_InheritanceParent(AvaloniaObject value)
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token)
   at Program.AppMain(Application app, String[] args) in D:\Projets\Program.cs:line 78
   at Program.Main(String[] args) in D:\Projets\Program.cs:line 28
```

**Comment by maxkatz6** [comment]
This issue was fixed with this PR https://github.com/AvaloniaUI/Avalonia/pull/9460
You can try nightly or wait for preview5
