### ISSUE TITLE
TrayIcon NullReferenceException during AvaloniaXamlLoader.Load

### ISSUE THREAD

**Issue by petedavis** [AvaloniaUI/Avalonia#9530]
**Describe the bug**
Putting together the most minimal example of a tray icon application has caused a null reference exception in the parsing of the Xaml.

**To Reproduce**

1. In the Sandbox project, paste the following code under the `Application.Styles`
```
  <TrayIcon.Icons>
    <TrayIcon Icon="/Assets/test_icon.ico" ToolTipText="Avalonia Tray Icon ToolTip">
      <TrayIcon.Menu>
        <NativeMenu>
          <NativeMenuItem Header="Settings">
            <NativeMenu>
              <NativeMenuItem Header="Option 1" ToggleType="Radio" IsChecked="True" />
              <NativeMenuItem Header="Option 2" ToggleType="Radio" IsChecked="True" />
              <NativeMenuItemSeparator />
              <NativeMenuItem Header="Option 3" ToggleType="CheckBox" IsChecked="True" />
              <NativeMenuItem Icon="/Assets/test_icon.ico" Header="Restore Defaults" />
              <NativeMenuItem Header="Disabled option" IsEnabled="False" />
            </NativeMenu>
          </NativeMenuItem>
        </NativeMenu>
      </TrayIcon.Menu>
    </TrayIcon>
  </TrayIcon.Icons>
```
3. Create an Assets folder
4. Copy the test_icon.ico file from the ControlCatalog project into the Assets folder.
5. Run the Sandbox project.
6. See error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.App.!XamlIlPopulate(IServiceProvider , App ) in _\Avalonia\samples\Sandbox\App.axaml:line 19
   at Sandbox.App.!XamlIlPopulateTrampoline(App ) in _\Avalonia\samples\Sandbox\App.axaml:line 0
   at Sandbox.App.Initialize() in _\Avalonia\samples\Sandbox\App.axaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup() in _\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 287
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in _\Avalonia\src\Avalonia.Controls\AppBuilderBase.cs:line 148
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in _\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Sandbox.Program.Main(String[] args) in _\Avalonia\samples\Sandbox\Program.cs:line 7
```

**Expected behavior**
I expected the basic sandbox app to start with a tray icon in the system tray.

**Desktop**

- OS: Windows 11
- Version 0.10.18 & current master branch

**Comment by maxkatz6** [comment]
I suspect you are missing `<TrayIcons>` node https://github.com/AvaloniaUI/Avalonia/blob/ed2a4a3d00ddc02bd86d06e15a9f1c7b757f9b45/samples/ControlCatalog/App.xaml#L48-L50

**Comment by maxkatz6** [comment]
And answering why we need TrayIcons node:
Compiler looks for "Add" method on the target property value. And if property value is null, it will fail with NRE.
So, collection initialization node can be skipped, if collection is initalised by default. But `<TrayIcon.Icons>` is an attached property, which cannot have a default value per each target control (it's possible to set shared default value tho, but that would break many things here).
For more details: https://github.com/AvaloniaUI/Avalonia/issues/4464

**Comment by petedavis** [comment]
Thanks that was my issue. Sorry, I don't know how I missed that.
