### ISSUE TITLE
OpenGL Exception shows on application startup using Avalonia 11.0 Preview-4

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9531]
**Describe the bug**

An OpenGL error shows on startup.

```


[OpenGL]Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Unable to load DLL 'av_libGLESv2.dll' or one of its dependencies: Could not find the corresponding module. (0x8007007E)
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<InitializeCore>b__1_0() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 33
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 36' 	0.55 seconds	


```

**Expected behavior**
The module should be found and loaded.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 22H2 22621.819 Windows Feature Experience Pack 1000.22636.1000.0

**Comment by maxkatz6** [comment]
You need to build avalonia with "win7-x64" runtime identifier on windows.

**Comment by llfab** [comment]
Build or publish with that runtime identifier?

**Comment by hez2010** [comment]
> You need to build avalonia with "win7-x64" runtime identifier on windows.

Can we just fix the package to put the dll under win-x64 instead?

**Comment by timunie** [comment]
@hez2010 we agree that this is counter intuitive. If we find a way to change this, we will do for 11.0. If you have an idea what to do in order to solve this issue, a PR is very welcome I think.
