### ISSUE TITLE
UI fails to run when launched with sudo in Linux enviroment

### ISSUE THREAD

**Issue by BlakePeavy** [AvaloniaUI/Avalonia#9601]
When launching a UI with the sudo command (ex. "sudo dotnet myapp.dll" or "sudo -s" "dotnet myapp.dll") the build seemingly fails.

This can be reproduced with any basic application, in my particular case it requires superuser access. Running as a user runs as expected (aside from permission issues from my client dll which isn't related to any UI issues). 

**Desktop (please complete the following information):**

- Ubuntu 62 bit
- Ubuntu 22.04.1 LTS

```
Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in /_/src/Avalonia.X11/X11Platform.cs:line 57
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /_/src/Avalonia.X11/X11Platform.cs:line 280
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at myapp.Program.Main(String[] args) in C:\git\myapp\Program.cs:line 14
```

**Comment by kekekeks** [comment]
Check if `xterm` works with sudo on your Linux machine.

**Comment by kekekeks** [comment]
XOpenDisplay means a failure to connect to X11, so it's an environment issue
