### ISSUE TITLE
Can't set visible status of control when click button

### ISSUE THREAD

**Issue by Duy-Thanh** [AvaloniaUI/Avalonia#9790]
Hello. First time asking here. I currently have a project that is expected to run on three platforms Linux, Windows and macOS. I also had prior C# experience, but that experience was with Windows Forms Application using the proprietary .NET Framework for Windows. Therefore, I came to AvaloniaUI because of its ease and many similarities with WPF.

However, I am having a problem:

I want to display the `ProgressBar` that I already have set in the XAML file from before. I want that after the button is pressed, this `ProgressBar` will be demolished the `IsVisible` state and once done, the `ProgressBar` will automatically change the `IsVisible` state to `false`.

I tried the following, this code is in the button click event:

`progressStatus.IsVisible = true;`

And an Unhandled Exception is thrown as soon as I click that button:

```
/home/duythanh/RiderProjects/AvaloniaFinalTest/AvaloniaFinalTest/bin/Debug/net7.0/AvaloniaFinalTest
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaFinalTest.MainWindowControl.BtnLogin_OnClick(Object sender, RoutedEventArgs e) in /home/duythanh/RiderProjects/AvaloniaFinalTest/AvaloniaFinalTest/MainWindowControl.axaml.cs:line 26
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 319
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 364
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 223
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 313
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 179
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 90
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 508
   at Avalonia.X11.X11Window.<.ctor>b__26_0(RawInputEventArgs e) in /_/src/Avalonia.X11/X11Window.cs:line 187
   at Avalonia.RawEventGrouper.DispatchFromQueue() in /_/src/Shared/RawEventGrouping.cs:line 54
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at AvaloniaFinalTest.Program.Main(String[] args) in /home/duythanh/RiderProjects/AvaloniaFinalTest/AvaloniaFinalTest/Program.cs:line 12

Process finished with exit code 134.
```

It said that the object reference was not set to the instance of the object.

I learned that in AvaloniaUI, to set the element properties, I would have to use the sender as that component. Here is what I tried, the code is located:

`(sender as Button)!.Content = "Test";`

And when I clicked the button, the displayed content of that button changed to "Test" as desired.

I tried this again, but got the same error as above:

`(sender as ProgressBar)!.IsVisible = true;`

But apparently I have put a `ProgressBar` with such name in XAML!

For a clearer view of the problem, see my full code

**Please note that I create different UserControls, in the main Window I will create a panel and that Panel will contain the UserControls.**

MainWindow.axaml

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="900" d:DesignHeight="630"
        x:Class="AvaloniaFinalTest.MainWindow"
        WindowStartupLocation="CenterScreen"
        CanResize="False"
        Title="AvaloniaFinalTest"
        Width="900" Height="630">
        
        <!-- Panel -->
        <Panel
                x:Name="panelControls"
                Width="900" Height="630"></Panel>
</Window>

```

MainWindow.axaml.cs

```
using Avalonia.Controls;

namespace AvaloniaFinalTest;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        // The first user control will be show is login activity
        MainWindowControl loginControl = new MainWindowControl();
        panelControls.Children.Add(loginControl);
    }
}
```

MainWindowControl.axaml

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="900" d:DesignHeight="630"
             x:Class="AvaloniaFinalTest.MainWindowControl"
             Width="900" Height="630">
        <!-- Row Definitions -->
        <Grid ShowGridLines="False">
                <Grid.RowDefinitions>
                        <!-- Blank (Row 0)-->
                        <RowDefinition Height="45"></RowDefinition>
                        
                        <!-- Title -->
                        <RowDefinition Height="100"></RowDefinition>
                        
                        <!-- Username (Label and textbox)-->
                        <RowDefinition Height="*"></RowDefinition>
                        
                        <!-- Class (Label and textbox) -->
                        <RowDefinition Height="*"></RowDefinition>
                        
                        <!-- Students Code (Label and textbox) -->
                        <RowDefinition Height="*"></RowDefinition>
                        
                        <!-- Confirm checkbox-->
                        <RowDefinition Height="*"></RowDefinition>
                        
                        <!-- Button Login -->
                        <RowDefinition Height="*"></RowDefinition>
                        
                        <!-- Button Exit -->
                        <RowDefinition Height="*"></RowDefinition>

                        <!-- Status Text And Progress Bar -->
                        <RowDefinition Height="38"></RowDefinition>
                </Grid.RowDefinitions>
                
                <Label Grid.Row="1"
                       x:Name="lblTitle"
                       FontSize="36"
                       FontWeight="Bold"
                       HorizontalContentAlignment="Center"
                       VerticalAlignment="Center"
                       Margin="50, 10, 0, 0">FinalTest
                </Label>
                
                <Label Grid.Row="2"
                       x:Name="lblUsername"
                       FontSize="18"
                       VerticalAlignment="Center"
                       HorizontalAlignment="Center"
                       Margin="-120, 0, 560, 0">Username: </Label>
                
                <TextBox Grid.Row="2"
                         x:Name="txtUsername"
                         FontSize="18"
                         HorizontalAlignment="Center"
                         VerticalAlignment="Center"
                         Margin="100, 0, 0, 0"
                         Width="620">
                </TextBox>
            <Label Grid.Row="3"
                   x:Name="lblClass"
                   FontSize="18"
                   VerticalAlignment="Center"
                   HorizontalAlignment="Center"
                   Margin="-158, 0, 560, 0">Class: </Label>
                
            <TextBox Grid.Row="3"
                     x:Name="txtClass"
                     FontSize="18"
                     HorizontalAlignment="Center"
                     VerticalAlignment="Center"
                     Margin="100, 0, 0, 0"
                     Width="620">
            </TextBox>
            <Label Grid.Row="4"
                   x:Name="lblStudentCode"
                   FontSize="16"
                   VerticalAlignment="Center"
                   HorizontalAlignment="Center"
                   Margin="-100, 0, 560, 0">Student Code: </Label>
                
            <TextBox Grid.Row="4"
                     x:Name="txtStudentCode"
                     FontSize="18"
                     HorizontalAlignment="Center"
                     VerticalAlignment="Center"
                     Margin="100, 0, 0, 0"
                     Width="620">
            </TextBox>

            <CheckBox Grid.Row="5"
                      x:Name="chkConfirm"
                      FontSize="16"
                      HorizontalAlignment="Center"
                      VerticalAlignment="Center"
                      Margin="0, 0, 0, 0">
                My information are correct and let me continue using this application
            </CheckBox>

            <Button Grid.Row="6"
                    x:Name="BtnLogin"
                    FontSize="20"
                    HorizontalAlignment="Center"
                    VerticalAlignment="Center"
                    HorizontalContentAlignment="Center"
                    Width="760"
                    Background="#FF0000"
                    Foreground="White"
                    Margin="0, 0, 0, 20"
                    Click="BtnLogin_OnClick"
                    Content="Login"></Button>

            <Button Grid.Row="7"
                    x:Name="BtnExit"
                    FontSize="20"
                    HorizontalAlignment="Center"
                    VerticalAlignment="Center"
                    HorizontalContentAlignment="Center"
                    Width="760"
                    Background="#808080"
                    Foreground="White"
                    Margin="0, 0, 0, 36"
                    Click="BtnExit_OnClick"
                    Content="Exit"></Button>

            <ProgressBar Grid.Row="8"
                         IsVisible="False"
                         x:Name="progressStatus"
                         ShowProgressText="True"
                         FontSize="18"
                         Minimum="0"
                         Maximum="100"
                         Margin="0, 0, 0, -15"
                         Value="0"></ProgressBar>

            <Label Grid.Row="8"
                   IsVisible="False"
                   x:Name="lblStatus"
                   Foreground="#FF0000"
                   FontSize="22"
                   FontStyle="Normal"
                   FontWeight="Heavy"
                   HorizontalAlignment="Center"
                   VerticalAlignment="Center"
                   HorizontalContentAlignment="Center"
                   VerticalContentAlignment="Center"
                   Margin="0, 0, 0, 2">An error occured!</Label>
        </Grid>
</UserControl>

```

MainWindowControl.axaml.cs

```
using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Avalonia.Media;

namespace AvaloniaFinalTest;

public partial class MainWindowControl : UserControl
{
    public MainWindowControl()
    {
        InitializeComponent();
    }

    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
    }

    private void BtnLogin_OnClick(object sender, RoutedEventArgs e)
    {
        // (sender as Button)!.Content = "Test";
        progressStatus.IsVisible = true;
    }

    private void BtnExit_OnClick(object? sender, RoutedEventArgs e)
    {
        Process.Start("killall", Process.GetCurrentProcess().ProcessName);
    }
}
```

So what should I do in this case? Any help would be very helpful and much appreciated. Thank you so much for your help and who created this project.

**Comment by ahopper** [comment]
Do you have XamlNameReferenceGenerator included in your .csproj? This is needed for named controls to be automatically visible to code, otherwise you need to use FindControl .  

I highly recommend reading up on MVVM if you are planning to do much with Avalonia.

**Comment by Duy-Thanh** [comment]
@ahopper Thank you for your help. Sorry for the slow response.

I have not added `XamlNameReferenceGenerator` to my project file. What do I have to do to add that to my project file?

**Comment by Duy-Thanh** [comment]
@ahopper Thank you for your help. Sorry for the slow response.

I checked and found that `XamlNameReferenceGenerator` was added to the project file.

Here is the full content of .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>
    <ItemGroup>
        <None Remove=".gitignore" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="0.10.18" />
        <PackageReference Include="Avalonia.Desktop" Version="0.10.18" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.18" />
        <PackageReference Include="XamlNameReferenceGenerator" Version="1.5.1" />
    </ItemGroup>
</Project>
```

And the following line shows it:

` <PackageReference Include="XamlNameReferenceGenerator" Version="1.5.1" />`

I also tried again with the command `dotnet add package XamlNameReferenceGenerator` as mentioned in the `README.md` file at [https://github.com/AvaloniaUI/Avalonia.NameGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) and recompiled but the problem persisted.

What do I need to do next?

**Comment by timunie** [comment]
Honestly, best and easiest approach would be to use the MVVM pattern. In there you can bind to a bool called IsProgessVisible. Set this property inside a Command which your button binds to. See the MVVM samples https://github.com/AvaloniaUI/Avalonia.Samples

**Comment by Duy-Thanh** [comment]
I will try switching to MVVM. Thanks for all your help :3
