### ISSUE TITLE
System.InvalidOperationException: Call from invalid thread when using binding to Observable.Interval

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#9801]
**Describe the bug**

```
Unhandled exception. System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.VerifyAccess() in /_/src/Avalonia.Base/AvaloniaObject.cs:line 111
   at Avalonia.AvaloniaObject.GetValue[T](StyledPropertyBase`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 226
   at Avalonia.Xaml.Interactions.Custom.ValueChangedTriggerBehavior.get_Binding() in /Users/wieslawsoltes/Documents/GitHub/AvaloniaBehaviors/src/Avalonia.Xaml.Interactions/Custom/ValueChangedTriggerBehavior.cs:line 24
   at Avalonia.Xaml.Interactions.Custom.ValueChangedTriggerBehavior.OnValueChanged(AvaloniaPropertyChangedEventArgs args) in /Users/wieslawsoltes/Documents/GitHub/AvaloniaBehaviors/src/Avalonia.Xaml.Interactions/Custom/ValueChangedTriggerBehavior.cs:line 35
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.AvaloniaProperty`1.NotifyChanged(AvaloniaPropertyChangedEventArgs`1 e) in /_/src/Avalonia.Base/AvaloniaProperty`1.cs:line 65
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 662
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 194
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledPropertyBase`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 68
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 205
   at Avalonia.PropertyStore.LocalValueUntypedBindingObserver`1.OnNext(Object value) in /_/src/Avalonia.Base/PropertyStore/LocalValueUntypedBindingObserver.cs:line 53
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 118
   at Avalonia.Data.Core.BindingExpression.InnerListener.OnNext(Object value) in /_/src/Avalonia.Base/Data/Core/BindingExpression.cs:line 368
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 118
   at Avalonia.Data.Core.ExpressionObserver.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionObserver.cs:line 311
   at Avalonia.Data.Core.ExpressionNode.NextValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 94
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 115
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 97
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.Tick() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 168
   at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.<>c.<Run>b__4_0(_ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 141
   at System.Reactive.Concurrency.Scheduler.<>c__67`1.<SchedulePeriodic>b__67_0(ValueTuple`2 t) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs:line 79
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.<>c.<Tick>b__5_0(PeriodicallyScheduledWorkItem`1 closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 127
   at System.Reactive.Concurrency.AsyncLock.<>c__5`1.<Wait>b__5_0(Delegate actionObject, Object stateObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 53
   at System.Reactive.Concurrency.AsyncLock.Wait(Object state, Delegate delegate, Action`2 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 93
   at System.Reactive.Concurrency.AsyncLock.Wait[TState](TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 53
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.Tick() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 125
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 210
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.<>c.<.ctor>b__2_0(Object this) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 207
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**To Reproduce**

```xaml
Binding="{Binding Values^}"
```

```C#
Values = Observable.Interval(TimeSpan.FromSeconds(1)).Select(_ => _value++);
```

**Expected behavior**
No Exception

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Version master, 11.0.999-cibuild0026718-beta

**Additional context**

**Comment by BAndysc** [comment]
`Observable.Interval` may run on a separate thread, so this example shouldn't be expected to work. You can run the timer using `AvaloniaScheduler` tho: 
```Observable.Interval(TimeSpan.FromSeconds(1), AvaloniaScheduler.Instance)```
In this case everything will work fine, as the callback will run on the main thread.

**Comment by wieslawsoltes** [comment]
> `Observable.Interval` may run on a separate thread, so this example shouldn't be expected to work. You can run the timer using `AvaloniaScheduler` tho: `Observable.Interval(TimeSpan.FromSeconds(1), AvaloniaScheduler.Instance)` In this case everything will work fine, as the callback will run on the main thread.

It was working before.

**Comment by maxkatz6** [comment]
@wieslawsoltes I assume more thread checks were added in the recent PRs, but generally users need to make sure their observables are running on the correct thread.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes I assume more thread checks were added in the recent PRs, but generally users need to make sure their observables are running on the correct thread.

I was working before value store refactoring.

**Comment by BAndysc** [comment]
Multithreaded code with invalid thread access might _look like it works_, but it doesn't change the fact that it is invalid and may lead to multiple weird and serious bugs. So it might have been working back then (it might work now if the check was commented), but there was (nor is) no guarantee that it would work.

**Comment by maxkatz6** [comment]
Streaming bindings might require same fix as this PR https://github.com/AvaloniaUI/Avalonia/pull/9722
I will leave it up to @grokys if we want to support implicit "observeon".
