### ISSUE TITLE
IOS - App crashes after updating a TextBox and changing focus.

### ISSUE THREAD

**Issue by mike-franz** [AvaloniaUI/Avalonia#9956]
**Describe the bug**
When deployed to iOS 16.2, the app crashes when the Text is updated in the UI and the TextBox loses focus. The app only crashes when the length of the Text property is longer than it was original set with. 

**To Reproduce**

1. Create a page with two TextBox controls
2. Run application
3. Update the text in the first TextBox from Hello World to Hello World1
4. Click on the second TextBox to change the focus

**Expected behavior**

The user should be able to change the focus of a TextBox without the application crashing

** TextInputInspector.cs **

SurroundingText.Text is null and the exception is thrown.

private int DocumentLength => _client.SurroundingText.Text.Length + (_markedText?.Length ?? 0);

** Stack Trace **

System.NullReferenceException: Object reference not set to an instance of an object
   at Avalonia.iOS.AvaloniaView.TextInputResponder.get_DocumentLength() in /_/src/iOS/Avalonia.iOS/TextInputResponder.cs:line 448
   at Avalonia.iOS.AvaloniaView.TextInputResponder.GetPositionCore(AvaloniaTextPosition pos, IntPtr offset) in /_/src/iOS/Avalonia.iOS/TextInputResponder.cs:line 254
   at Avalonia.iOS.AvaloniaView.TextInputResponder.UIKit.IUITextInput.GetPosition(UITextPosition fromPosition, IntPtr offset) in /_/src/iOS/Avalonia.iOS/TextInputResponder.cs:line 242
   at UIKit.UIResponder.ResignFirstResponder()
   at Avalonia.iOS.AvaloniaView.TextInputResponder.ResignFirstResponder() in /_/src/iOS/Avalonia.iOS/TextInputResponder.cs:line 478
   at UIKit.UIResponder.BecomeFirstResponder()
   at Avalonia.iOS.AvaloniaView.BecomeFirstResponder() in /_/src/iOS/Avalonia.iOS/AvaloniaView.Text.cs:line 17
   at Avalonia.iOS.AvaloniaView.Avalonia.Input.TextInput.ITextInputMethodImpl.Reset() in /_/src/iOS/Avalonia.iOS/AvaloniaView.Text.cs:line 52
   at Avalonia.Input.TextInput.TextInputMethodManager.set_Client(ITextInputMethodClient value) in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 39
   at Avalonia.Input.TextInput.TextInputMethodManager.TryFindAndApplyClient() in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 126
   at Avalonia.Input.TextInput.TextInputMethodManager.SetFocusedElement(IInputElement element) in /_/src/Avalonia.Base/Input/TextInput/InputMethodManager.cs:line 107
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/KeyboardDevice.cs:line 159
   at Avalonia.Input.FocusManager.SetFocusedElement(IFocusScope scope, IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 140
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 70
   at Avalonia.Input.FocusManager.OnPreviewPointerPressed(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 234
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Base/Interactivity/RoutedEvent.cs:line 92
   at System.Reactive.AnonymousObserver`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNextCore(ValueTuple`2 value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(ValueTuple`2 value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1[[System.ValueTuple`2[[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Avalonia.Interactivity.RoutedEventArgs, Avalonia.Base, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(ValueTuple`2 value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/RoutedEvent.cs:line 99
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 94
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 125
   at Avalonia.Input.TouchDevice.ProcessRawEvent(RawInputEventArgs ev) in /_/src/Avalonia.Base/Input/TouchDevice.cs:line 77
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Base/Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 535
   at Avalonia.iOS.TouchHandler.Handle(NSSet touches, UIEvent evt) in /_/src/iOS/Avalonia.iOS/TouchHandler.cs:line 44
   at Avalonia.iOS.AvaloniaView.TouchesBegan(NSSet touches, UIEvent evt) in /_/src/iOS/Avalonia.iOS/AvaloniaView.cs:line 137
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS
- Version 16.2

**Comment by mike-franz** [comment]
<img width="439" alt="Screenshot 2023-01-11 at 11 20 11 AM" src="https://user-images.githubusercontent.com/4064899/211899521-531f7b47-6980-4176-b20b-7b5234859c9e.png">

**Comment by kerams** [comment]
I've just had this happen on a user's phone with `12.0.999-cibuild0057525-alpha`

```
System.NullReferenceException: Object reference not set to an instance of an object
   at Avalonia.iOS.AvaloniaView.TextInputResponder.GetPositionCore(AvaloniaTextPosition pos, IntPtr offset)
   at Avalonia.iOS.AvaloniaView.TextInputResponder.UIKit.IUITextInput.GetPosition(UITextPosition fromPosition, IntPtr offset)
```

but I don't know how to reproduce.

```csharp
private AvaloniaTextPosition? GetPositionCore(AvaloniaTextPosition pos, nint offset)
{

    var end = pos.Index + (int)offset;
    if (end < 0)
        return null!;
    if (end > DocumentLength)
        return null;
    return new AvaloniaTextPosition(end);
}
```

Not sure what could be failing here. Is it possible that iOS passes `nil` to `GetPosition`?
